const section=(heading,body,bullets=[])=>({heading,body,bullets})

export const CONSTRUCTION_GUIDES=[
  {
    slug:'best-steel-for-house-construction',
    type:'construction-guide',
    category:'Materials',
    title:'Best Steel for House Construction | TMT Bar Selection Guide | ProPulse',
    description:'Learn how to choose reinforcement steel for house construction, what IS 1786 means, how Fe grades differ and what to verify before buying TMT bars.',
    heading:'What is the best steel for house construction?',
    summary:'There is no single steel brand or grade that is best for every house. Start with the structural engineer’s design, verify BIS-conforming reinforcement and compare grade, ductility, test certificates, source and storage before purchase.',
    searchTerms:['best steel for house construction','best TMT bar for home construction','Fe500 vs Fe500D for house','steel for RCC house construction','IS 1786 steel for construction'],
    ctaLabel:'Get Construction Quote',
    cta:'/quote?package=standard#construction',
    note:'Structural reinforcement must follow the project’s structural design. Do not substitute bar grade, diameter or reinforcement quantity based only on an online guide.',
    sections:[
      section('Start with the structural design, not a brand ranking','The structural engineer should specify reinforcement grade, bar diameters, spacing, laps, anchorage and detailing for the actual building. A commonly marketed grade is not automatically correct for every footing, column, beam or slab.'),
      section('Check the applicable Indian reinforcement standard','For high-strength deformed bars used as reinforcement, BIS lists IS 1786:2008. The standard covers multiple Fe grades and requirements for reinforcement steel. IS 456:2000 remains a key code of practice for plain and reinforced concrete.',['Ask for BIS-conforming material from a traceable source','Match the grade to the structural drawings','Keep manufacturer test certificates and invoices','Do not accept unidentified re-rolled bars with uncertain origin']),
      section('Understand grade and ductility','Higher yield strength alone does not make a bar universally better. Ductility, elongation, bend performance, weldability where relevant and the structural design all matter. “D” variants are associated with enhanced ductility requirements within the standard.'),
      section('What to verify before steel reaches the site','Material control matters as much as the name printed on the bar.',['Correct grade and diameter against drawings','Bar markings and source traceability','Mill or manufacturer test certificate where applicable','Weight/diameter checks when required','Rust, contamination and poor storage conditions','Proper stacking above ground and protection from mud/standing water']),
      section('Questions to ask your contractor','Ask which grade is specified by the structural engineer, how steel quantity is measured, whether cutting/bending wastage is included, how substitutions are approved and who signs off reinforcement before concreting.')
    ],
  },
  {
    slug:'prevent-cracks-in-house',
    type:'construction-guide',
    category:'Construction Quality',
    title:'How to Reduce Cracks in a New House | Construction Precautions | ProPulse',
    description:'Construction precautions that can reduce the risk of cracks in a new house, including design, concrete quality, curing, joints, masonry, waterproofing and site supervision.',
    heading:'Precautions to reduce cracks in a new house',
    summary:'No practical building can be promised to remain completely crack-free. The goal is to reduce avoidable cracking through correct structural design, material control, workmanship, curing, movement detailing and timely inspection.',
    searchTerms:['how to avoid cracks in house construction','precautions to avoid cracks in home','wall cracks after construction','concrete crack prevention house','curing to prevent cracks'],
    ctaLabel:'Create Construction Requirement',
    cta:'/quote?package=standard#construction',
    note:'Wide, growing, diagonal or structural cracks should be assessed by a qualified structural professional. Cosmetic crack advice should not be used to diagnose structural safety.',
    sections:[
      section('Get the structure and foundation designed for the actual site','Soil conditions, spans, floor count, loads, openings and foundation behaviour affect cracking. Avoid copying reinforcement or footing details from another house.'),
      section('Control concrete quality and water','Uncontrolled water addition, poor batching and weak compaction can increase shrinkage, segregation and defects. Use the specified concrete grade and approved mix/process.',['Do not add water casually at site to improve workability','Compact concrete properly without over-vibration','Protect reinforcement cover and formwork dimensions','Plan pours so avoidable cold joints are reduced']),
      section('Curing is a construction process, not a finishing step','Early moisture loss and hot-weather concreting can increase cracking risk. BIS lists IS 7861 (Part 1) for hot-weather concreting practice and IS 456 for reinforced concrete practice. Follow the project engineer’s curing method and duration.'),
      section('Detail movement between different materials','Cracks often occur where RCC and masonry meet, around openings, long walls, chases and changes in geometry. Proper detailing, suitable mesh/reinforcement where specified, control joints where appropriate and sequencing can reduce recurring cracks.'),
      section('Do not ignore masonry and plaster workmanship','Block/brick quality, mortar consistency, curing, chasing for services and plaster thickness can influence non-structural cracks. Coordinate electrical/plumbing chases before final plaster where possible.'),
      section('Fix water ingress early','Leakage and repeated wetting can damage finishes and reveal or worsen defects. Roofs, toilets, balconies, external walls and plumbing penetrations need planned waterproofing and testing before finishes conceal them.')
    ],
  },
  {
    slug:'2bhk-interiors-hyderabad',
    type:'construction-guide',
    category:'Interiors',
    title:'2BHK Interiors in Hyderabad | Planning, Budget & Checklist | ProPulse',
    description:'Plan 2BHK interiors in Hyderabad with a room-by-room scope, modular kitchen and wardrobe checklist, material decisions, package references and quote comparison tips.',
    heading:'How to plan 2BHK interiors in Hyderabad',
    summary:'A useful 2BHK interior quote starts with the actual rooms, storage needs, kitchen layout, wardrobe sizes, finishes, electrical changes and move-in timeline—not only a generic per-sq-ft number.',
    searchTerms:['2bhk interiors in Hyderabad','2bhk interior design Hyderabad','2bhk interior cost Hyderabad','2bhk modular interiors Hyderabad','2bhk home interiors Hyderabad'],
    ctaLabel:'View Interior Packages',
    cta:'/packages#interior',
    sections:[
      section('Create a room-by-room scope first','Separate must-have work from optional decor so every interior company quotes the same requirement.',['Kitchen base and wall units','Master-bedroom wardrobe and loft','Second-bedroom wardrobe or study','TV/storage unit','False ceiling if required','Electrical and lighting changes','Curtains, loose furniture and decor as separate items']),
      section('Measure actual cabinet areas','Carpet area alone does not define modular-interior cost. Wardrobe width/height, kitchen running length, lofts, internal accessories and finish choices matter much more for cabinetry.'),
      section('Compare material specifications, not package names','Ask for the actual board/ply grade, laminate thickness/brand allowance, hardware range, edge treatment, internal finish, basket/accessory allowance and warranty terms.'),
      section('Keep civil and modular scope separate','Painting, electrical relocation, plumbing changes, tile work, false ceiling and masonry alterations may sit outside modular cabinetry. Make exclusions explicit before comparing quotations.'),
      section('Use one final drawing set','After design freeze, approve dimensions, internal layouts, finish codes, appliance sizes and electrical points before production. Changes after production can create delays and variation costs.')
    ],
  },
  {
    slug:'choose-construction-contractor-hyderabad',
    type:'construction-guide',
    category:'Contractor Selection',
    title:'How to Choose the Best Construction Contractor in Hyderabad | ProPulse',
    description:'Searching for the best contractor in Hyderabad? Use a practical contractor-comparison checklist covering scope, projects, materials, exclusions, milestones, warranty and contract terms.',
    heading:'How to choose the right construction contractor in Hyderabad',
    summary:'“Best contractor” depends on project fit. Compare every construction company against the same drawings, scope, materials, budget, timeline and written commercial terms before deciding.',
    searchTerms:['best contractor in Hyderabad','best construction company in Hyderabad','home construction contractor Hyderabad','house construction contractors Hyderabad','how to choose builder in Hyderabad'],
    ctaLabel:'Find ProPulse Professionals',
    cta:'/experts',
    sections:[
      section('Shortlist for project fit, not only brand visibility','A contractor experienced in a similar house type, plot condition, specification level and project size may be more relevant than the most visible name online.'),
      section('Send the same scope to every bidder','Use the same drawings, built-up area, floor count, material schedule and expected finish level. Otherwise two headline prices may represent different work.'),
      section('Check completed work and references','Review completed and in-progress projects where possible. Ask what the contractor directly manages, how supervision works and how material substitutions are approved.'),
      section('Compare exclusions line by line','Clarify approvals, architectural/structural design, soil tests, utility connections, compound walls, borewell, sump, external works, lifts, solar, interiors, taxes and escalation terms.'),
      section('Review payment and variation rules','Milestone payments should map to measurable progress. Understand how extra items, design changes and quantity variations are priced before signing.'),
      section('Prefer a written contract and handover checklist','The agreement should capture scope, specifications, timeline assumptions, payment stages, change control, warranty/defect obligations and handover deliverables.')
    ],
  },
  {
    slug:'home-construction-checklist',
    type:'construction-guide',
    category:'Planning',
    title:'Home Construction Checklist | Plot to Handover | ProPulse',
    description:'A practical home construction checklist covering site inputs, design, soil and structure, quotations, materials, execution, waterproofing, quality checks and handover.',
    heading:'Home construction checklist: plot to handover',
    summary:'Use a stage-by-stage checklist so important decisions are made before work begins rather than during expensive site changes.',
    searchTerms:['home construction checklist','house construction steps India','new home construction checklist','construction checklist for owner','house building planning checklist'],
    ctaLabel:'Get Construction Quote',
    cta:'/quote?package=standard#construction',
    sections:[
      section('Before design','Collect plot dimensions, survey information, access constraints, ownership/approval inputs, utility information and your family’s room/parking/future-floor requirements.'),
      section('Design and engineering','Freeze architectural layouts, structural design, service routes and major elevations before comparing execution quotations.'),
      section('Quotation comparison','Check scope, quantities/measurement method, material allowances, exclusions, taxes, milestones, timeline assumptions and variation rules.'),
      section('Structure and masonry','Use approved drawings and stage inspections for reinforcement, formwork, concrete, masonry openings and service sleeves before work is concealed.'),
      section('Waterproofing and services','Plan wet areas, roofs, balconies, plumbing pressure tests, electrical conduits and drainage before finishes.'),
      section('Finishes and handover','Approve samples, snag rooms systematically, test services, collect warranties/manuals, document changes and close pending items before final payment.')
    ],
  },
  {
    slug:'waterproofing-precautions-new-house',
    type:'construction-guide',
    category:'Construction Quality',
    title:'Waterproofing Precautions for a New House | ProPulse',
    description:'Plan waterproofing for roofs, toilets, balconies, external walls, basements and service penetrations with substrate preparation, detailing, testing and protection checks.',
    heading:'Waterproofing precautions for a new house',
    summary:'Waterproofing works best as a coordinated construction system. Good detailing, substrate preparation, slopes, penetrations, testing and protection matter as much as the selected product.',
    searchTerms:['waterproofing precautions new house','toilet waterproofing checklist','terrace waterproofing new construction','how to prevent leakage in new house','waterproofing during house construction'],
    ctaLabel:'Create Construction Requirement',
    cta:'/quote?package=standard#construction',
    sections:[
      section('Identify every water-risk zone before finishing','Roofs, toilets, balconies, utility areas, sunken slabs, retaining/below-grade areas and pipe penetrations need a planned detail rather than a late repair.'),
      section('Prepare the substrate correctly','Weak, dusty, uneven or contaminated surfaces can undermine many waterproofing systems. Follow the approved system requirements before application.'),
      section('Detail corners, drains and penetrations','Changes in plane, pipe sleeves, floor traps, parapet junctions and thresholds are common leakage points. Use the project detail and compatible accessories/system components.'),
      section('Get slopes and drainage right','Waterproofing should not be expected to compensate for standing water caused by poor slopes or blocked drainage. Verify falls before final finishes.'),
      section('Test before covering the system','Where appropriate for the system and area, carry out the specified pond/flood or water test before tiles/screeds conceal the waterproofing. Document defects and repairs.'),
      section('Protect completed waterproofing','Subsequent trades can puncture or damage finished layers. Control access and use the specified protective screed/board/detail before continuing.')
    ],
  },,
  {
    slug:'best-cement-for-house-construction',
    type:'construction-guide',
    category:'Materials',
    title:'Best Cement for House Construction | OPC, PPC & PSC Guide | ProPulse',
    description:'Understand how to choose cement for house construction, including OPC, PPC and PSC, relevant BIS standards, storage, freshness and project-specific selection.',
    heading:'What is the best cement for house construction?',
    summary:'There is no single cement type that is best for every structural and masonry application. Match the cement to the structural design, exposure conditions, concrete mix and project specification rather than choosing only by brand.',
    searchTerms:['best cement for house construction','OPC vs PPC for house construction','PPC cement for home construction','PSC cement for house','cement for RCC house construction'],
    ctaLabel:'Get Construction Quote',
    cta:'/quote?package=standard#construction',
    note:'Cement selection for structural concrete should follow the engineer-approved specification and concrete mix. Do not change cement type mid-project without technical review.',
    sections:[
      section('Start with the specified concrete and exposure conditions','The correct cement depends on the structural design, exposure, concrete grade, mix design and construction method. Brand popularity alone is not a technical specification.'),
      section('Know the common BIS cement families','BIS lists standards including IS 269:2015 for Ordinary Portland Cement, IS 455:2015 for Portland Slag Cement and IS 1489 for Portland Pozzolana Cement.',['Verify the bag carries the appropriate conformity marking','Check the cement type against the approved specification','Keep purchase invoices and batch/source records','Avoid mixing different cement types casually in one structural pour']),
      section('Store cement correctly','Keep bags dry, raised above the floor, protected from walls/moisture and arranged so older stock can be consumed first. Lumpy or moisture-damaged cement should not be accepted casually.'),
      section('Freshness and consistency matter','Long or poor storage can affect handling and performance. Control supply so site teams are not forced to use uncertain material simply because it is already delivered.'),
      section('Ask what the quotation includes','Clarify cement type/allowance, approved brands or equivalent criteria, whether concrete is site-mixed or ready-mixed and how substitutions are approved.')
    ],
  },
  {
    slug:'m-sand-vs-river-sand-house-construction',
    type:'construction-guide',
    category:'Materials',
    title:'M-Sand vs River Sand for House Construction | ProPulse',
    description:'Compare manufactured sand and river sand for house construction, including grading, cleanliness, source quality, concrete/masonry use and what to verify before purchase.',
    heading:'M-sand vs river sand: what should you use for a house?',
    summary:'Source quality, grading and suitability for the intended work matter more than the label alone. Fine aggregates used for concrete should meet the project specification and applicable aggregate requirements.',
    searchTerms:['m sand vs river sand for house construction','best sand for concrete house','M sand for plastering','manufactured sand for RCC','IS 383 sand for concrete'],
    ctaLabel:'Get Construction Quote',
    cta:'/quote?package=standard#construction',
    note:'Concrete aggregate selection should follow the approved mix/design and material testing requirements. Plastering and masonry sands may need different grading/finish characteristics.',
    sections:[
      section('Do not compare only by price','The useful comparison is grading, cleanliness, particle shape, fines, source consistency and suitability for concrete, masonry or plastering.'),
      section('Concrete aggregate has specification requirements','BIS lists IS 383:2016 for coarse and fine aggregates for concrete. Use approved sources and test material where required by the project quality plan.'),
      section('Manufactured sand can be consistent when properly produced','A controlled crushing and screening process can provide consistent grading, but poor-quality manufactured sand can still have excess fines or unsuitable characteristics.'),
      section('River sand quality varies by source','Natural sand is not automatically superior. Silt, organic contamination, grading and legality/source traceability need attention.'),
      section('Separate concrete, masonry and plaster needs','A sand suitable for structural concrete may not automatically give the desired plaster finish. Define each use in the material schedule and quotation.')
    ],
  },
  {
    slug:'red-brick-vs-aac-block-house',
    type:'construction-guide',
    category:'Materials',
    title:'Red Brick vs AAC Block for House Construction | ProPulse',
    description:'Compare red clay brick and AAC block for house construction by weight, workmanship, services, plastering, moisture detailing and project-specific suitability.',
    heading:'Red brick vs AAC block: how should you compare them?',
    summary:'Walling choice affects dead load, labour, chasing, plaster, fixing details, thermal behaviour and execution. The right option depends on the structural and architectural design, local workmanship and project priorities.',
    searchTerms:['red brick vs AAC block','AAC blocks for house construction','red bricks for house','best blocks for house construction','AAC block vs brick cost'],
    ctaLabel:'Create Construction Requirement',
    cta:'/quote?package=standard#construction',
    sections:[
      section('Compare the complete wall system','Unit price alone misses mortar/adhesive, plaster thickness, wastage, labour productivity, chasing, lintels, fixings and waterproofing details.'),
      section('Weight can influence the structural system','AAC is generally lighter than conventional clay masonry units, but wall type and load assumptions must be coordinated with the structural design.'),
      section('Workmanship changes the outcome','Poor jointing, improper curing where required, careless chasing and weak junction detailing can create cracking or finishing problems with any walling system.'),
      section('Plan service chases and heavy fixings','Electrical/plumbing routes and wall-mounted loads should be planned early. Use appropriate anchors/fixing systems for the selected substrate.'),
      section('Ask for one written wall specification','Define unit type, dimensions, mortar/adhesive, reinforcement/mesh at junctions where specified, plaster system and external-water protection before comparing quotes.')
    ],
  },
  {
    slug:'concrete-curing-house-construction',
    type:'construction-guide',
    category:'Construction Quality',
    title:'Concrete Curing for House Construction | Why It Matters | ProPulse',
    description:'Understand why concrete curing matters, how early moisture and temperature control affect concrete and what owners should verify on a house-construction site.',
    heading:'Concrete curing: what should a homeowner check?',
    summary:'Curing helps concrete retain the moisture and temperature conditions needed for cement hydration and strength development. The project engineer should define the curing method and duration for the actual concrete and weather conditions.',
    searchTerms:['concrete curing house construction','how many days curing for concrete','slab curing house','curing to avoid cracks','concrete curing in hot weather India'],
    ctaLabel:'View Construction Checklist',
    cta:'/guides/home-construction-checklist',
    note:'Do not use a generic online curing duration as a substitute for the engineer/specification for your concrete, cement type, member and weather conditions.',
    sections:[
      section('Start curing at the correct stage','Concrete should be protected from damaging early moisture loss while avoiding disturbance of fresh surfaces. Site teams should follow the approved method for slabs, columns, beams and other members.'),
      section('Hot and windy weather increases risk','Higher temperature, low humidity and wind can accelerate surface drying. BIS guidance includes IS 7861 (Part 1) for hot-weather concreting alongside IS 456 concrete practice.'),
      section('Keep curing continuous','Intermittent wetting that allows repeated drying is not the same as maintaining suitable curing conditions. Use the approved water, membrane or covering method for the member.'),
      section('Do not confuse formwork retention with curing','Keeping formwork in place may reduce exposed surface area, but exposed faces and subsequent surfaces still need the specified curing/protection.'),
      section('Document site quality','Record pour date, concrete grade/source, cube/test references where applicable, weather concerns and curing start/inspection notes for important structural pours.')
    ],
  },
  {
    slug:'soil-test-before-house-construction',
    type:'construction-guide',
    category:'Planning',
    title:'Soil Test Before House Construction | Foundation Planning Guide | ProPulse',
    description:'Learn why soil investigation matters before house construction, what information a structural engineer may need and why copying a neighbour’s foundation can be risky.',
    heading:'Do you need a soil test before building a house?',
    summary:'Foundation design depends on site conditions, building loads and geotechnical information. A neighbour’s footing size is not a reliable substitute for investigation and structural design.',
    searchTerms:['soil test before house construction','soil testing for home construction','foundation soil test cost Hyderabad','SBC soil test house','geotechnical investigation house'],
    ctaLabel:'Get Construction Quote',
    cta:'/quote?package=standard#construction',
    note:'Foundation decisions are structural and site-specific. Use a qualified geotechnical/structural professional for investigation interpretation and foundation design.',
    sections:[
      section('Soil conditions can change over short distances','Fill, expansive soils, groundwater, rock depth and past site use can vary even within the same neighbourhood.'),
      section('The investigation should match the project','The required scope depends on building size, loads, site history and local conditions. The structural/geotechnical team should decide the appropriate investigation.'),
      section('Use results in foundation design','Bearing conditions, settlement risk and groundwater information should feed into foundation selection and structural calculations.'),
      section('Do not use “safe bearing capacity” as the only decision','Foundation performance also involves settlement, variability, groundwater, excavation conditions and structural interaction.'),
      section('Include site investigation in pre-construction planning','Ask who arranges investigation, who reviews the report and whether foundation changes are treated as a variation before construction starts.')
    ],
  },
  {
    slug:'rcc-slab-before-concrete-checklist',
    type:'construction-guide',
    category:'Construction Quality',
    title:'RCC Slab Checklist Before Concreting | Home Construction | ProPulse',
    description:'A homeowner-friendly pre-pour checklist for RCC slabs covering approved drawings, reinforcement inspection, cover, formwork, service sleeves, cleanliness and concrete planning.',
    heading:'RCC slab checklist before concrete is poured',
    summary:'The most important slab checks happen before concrete hides the reinforcement and services. Use an engineer-led pre-pour inspection rather than relying only on a visual homeowner check.',
    searchTerms:['RCC slab checklist before concrete','slab reinforcement checklist house','before slab concreting checklist','RCC slab quality checks','house slab concrete precautions'],
    ctaLabel:'View Home Construction Checklist',
    cta:'/guides/home-construction-checklist',
    note:'Reinforcement size, spacing, laps, anchorage, cover and structural details must be checked against approved drawings by qualified project personnel. This guide is not a structural inspection substitute.',
    sections:[
      section('Confirm the latest approved drawings are on site','Avoid pouring against superseded structural or service drawings. Resolve architectural openings and structural details before the pour.'),
      section('Complete the reinforcement inspection','Engineer/site quality checks should cover bar grade/diameter, spacing, laps, anchorage, extra bars, openings and supports against drawings.'),
      section('Verify cover and supports','Cover blocks/chairs should be appropriate and stable so reinforcement position does not collapse during concreting.'),
      section('Coordinate electrical and plumbing sleeves','Sleeves, conduits, drain openings and reserved penetrations should be agreed before concrete. Unplanned post-cutting can damage finished work.'),
      section('Check formwork, access and pour plan','Formwork stability, levels, cleanliness, release agent, construction joints, pump/access route, manpower, backup equipment and curing preparation should be ready before concrete arrives.')
    ],
  },
  {
    slug:'electrical-planning-new-house',
    type:'construction-guide',
    category:'MEP Planning',
    title:'Electrical Planning Checklist for a New House | ProPulse',
    description:'Plan electrical points, loads, circuits, lighting, ACs, kitchen appliances, EV/solar readiness, earthing and future needs before walls and ceilings are finished.',
    heading:'Electrical planning checklist for a new house',
    summary:'Electrical changes become expensive once masonry, plaster and ceilings are finished. Plan room functions, appliance loads, circuiting and future needs before chasing and wiring begins.',
    searchTerms:['electrical planning new house','electrical points checklist home','new house wiring checklist','electrical layout for 2bhk 3bhk','home electrical planning India'],
    ctaLabel:'Create Construction Requirement',
    cta:'/quote?package=standard#construction',
    note:'Electrical design, protection devices, conductor sizing, earthing and code compliance should be handled by qualified electrical professionals.',
    sections:[
      section('Plan room use before counting switches','Furniture, bed positions, TV walls, study desks, kitchen appliances and outdoor equipment determine useful point locations.'),
      section('List major loads separately','ACs, geysers, ovens, induction hobs, pumps, lifts, EV charging and other large loads need early planning rather than spare sockets added later.'),
      section('Coordinate lighting with ceiling design','False ceilings, profile lights, fans, sensors and feature lighting need coordinated electrical and interior drawings.'),
      section('Plan data, security and automation conduits','Internet access points, cameras, doorbells, intercom, access control and future automation can be easier to provision during construction.'),
      section('Leave a documented as-built record','Panel schedules, circuit labels, conduit routes and test records are useful for maintenance and future renovation.')
    ],
  },
  {
    slug:'plumbing-checklist-new-house',
    type:'construction-guide',
    category:'MEP Planning',
    title:'Plumbing Checklist for a New House | Water & Drainage Planning | ProPulse',
    description:'Plan water supply, drainage, toilets, kitchen, utility, tank/pump systems, sleeves, testing and maintenance access before finishes close the walls and floors.',
    heading:'Plumbing checklist for a new house',
    summary:'Good plumbing planning starts before slab sleeves, wall chases and toilet levels are fixed. Coordinate water, drainage, waterproofing and maintenance access as one system.',
    searchTerms:['plumbing checklist new house','house plumbing planning','toilet plumbing checklist','water pipe planning home','drainage planning house construction'],
    ctaLabel:'Create Construction Requirement',
    cta:'/quote?package=standard#construction',
    sections:[
      section('Freeze fixture locations early','WC, basin, shower, kitchen sink, washing machine, dishwasher and outdoor taps affect pipe routes and drainage levels.'),
      section('Coordinate sleeves and vertical shafts','Plan service shafts and slab/wall penetrations before structural and masonry work is closed.'),
      section('Separate water and drainage decisions','Supply pressure/storage, hot water, rainwater and soil/waste drainage each need coordinated sizing, routing and access.'),
      section('Test before concealment','Pressure/leak testing and drainage checks should happen before tiles, ceilings or boxing make repairs difficult.'),
      section('Keep valves and cleanouts accessible','Future maintenance should not require unnecessary demolition. Mark concealed routes and retain as-built information.')
    ],
  },
  {
    slug:'wall-putty-primer-paint-sequence',
    type:'construction-guide',
    category:'Finishes',
    title:'Wall Putty, Primer & Paint Sequence for a New House | ProPulse',
    description:'Understand the typical wall-finish workflow from plaster/drying and surface preparation through putty, primer and paint, plus common causes of peeling and patchiness.',
    heading:'Putty, primer and paint: what sequence should a new house follow?',
    summary:'A good paint finish depends heavily on substrate dryness, plaster quality and surface preparation. Product sequence should follow the selected paint system and manufacturer instructions.',
    searchTerms:['wall putty primer paint sequence','painting process new house','putty before primer or after','new plaster painting checklist','how to avoid paint peeling new house'],
    ctaLabel:'View Home Construction Checklist',
    cta:'/guides/home-construction-checklist',
    sections:[
      section('Do not rush a wet wall into finishing','Moisture, active leakage or insufficiently dried plaster can contribute to blistering, efflorescence, peeling and colour variation.'),
      section('Repair the substrate before decorative coats','Remove loose material, repair cracks appropriately, address dampness and achieve the required surface flatness before the selected finishing system.'),
      section('Follow one compatible manufacturer system','Putty, primer and topcoat compatibility, dilution, drying intervals and number of coats should follow product instructions rather than a generic universal sequence.'),
      section('Use sample approvals for colour and sheen','Lighting, wall texture and batch variation affect appearance. Approve representative samples before completing large areas.'),
      section('Protect finished paint from later trades','Carpentry, electrical, plumbing and moving work can damage final coats. Sequence final touch-ups close to handover.')
    ],
  },
  {
    slug:'modular-kitchen-planning-hyderabad',
    type:'construction-guide',
    category:'Interiors',
    title:'Modular Kitchen Planning in Hyderabad | Layout & Material Checklist | ProPulse',
    description:'Plan a modular kitchen in Hyderabad by layout, appliance sizes, storage, countertop, shutters, hardware, electrical/plumbing points and installation sequence.',
    heading:'How to plan a modular kitchen in Hyderabad',
    summary:'The best kitchen quotation starts after appliance sizes, plumbing/electrical points, cabinet modules, storage needs and finish level are clear.',
    searchTerms:['modular kitchen Hyderabad','modular kitchen planning Hyderabad','kitchen interior cost Hyderabad','best modular kitchen layout','modular kitchen checklist'],
    ctaLabel:'View Interior Packages',
    cta:'/packages#interior',
    sections:[
      section('Fix appliance sizes before cabinet production','Refrigerator, hob, chimney, oven, microwave, dishwasher and sink sizes affect module widths and service points.'),
      section('Choose layout from room geometry and workflow','Straight, L-shaped, parallel, U-shaped and island layouts each have different aisle and service implications.'),
      section('Define cabinet material and finish separately','Internal board/ply, shutter material, laminate/acrylic/PU finish, edge treatment and moisture exposure should be explicit in the quote.'),
      section('Specify hardware and accessories','Hinges, channels, baskets, corner units, tall units and lift-up systems can materially change cost and usability.'),
      section('Coordinate countertop, dado and services','Counter level, backsplash/dado, sink cutout, gas line, RO, sockets and under-cabinet lighting should be coordinated before installation.')
    ],
  },
  {
    slug:'wardrobe-materials-plywood-mdf-hdhmr',
    type:'construction-guide',
    category:'Interiors',
    title:'Plywood vs MDF vs HDHMR for Wardrobes | Interior Material Guide | ProPulse',
    description:'Compare common wardrobe substrate choices such as plywood, MDF and HDHMR by moisture exposure, finish, screw holding, machining and project-specific use.',
    heading:'Plywood vs MDF vs HDHMR: what should you use for wardrobes?',
    summary:'There is no universal “best board” for every wardrobe. Select the substrate based on moisture exposure, finish type, hardware, machining requirements, budget and the interior specification.',
    searchTerms:['plywood vs MDF wardrobe','HDHMR vs plywood wardrobe','best wood for wardrobe','wardrobe material Hyderabad','best board for modular wardrobe'],
    ctaLabel:'View Interior Packages',
    cta:'/packages#interior',
    sections:[
      section('Separate substrate from surface finish','The internal board and the visible finish are different decisions. A laminate, veneer, acrylic or painted finish can be applied over different suitable substrates.'),
      section('Consider moisture exposure','Wardrobes near damp external walls, wet areas or poor ventilation need more attention to moisture-resistant detailing and building dampness.'),
      section('Check screw holding and hardware use','Heavy shutters, pull-outs and repeated hardware loads can make edge quality, density and fixing method important.'),
      section('Match the board to the finish process','Painted routed shutters, laminate shutters and veneer work can favour different substrates and fabrication methods.'),
      section('Ask for exact brand/grade/thickness in the quotation','Avoid generic words like “premium board.” Write substrate type, grade, thickness, finish, edge treatment and hardware range into the scope.')
    ],
  },
]

export function guideBySlug(slug){
  return CONSTRUCTION_GUIDES.find(item=>item.slug===String(slug||'').toLowerCase())||null
}

export const CONSTRUCTION_GUIDE_ROUTES=CONSTRUCTION_GUIDES.map(item=>({
  path:'/guides/'+item.slug,
  type:'construction-guide',
  guideSlug:item.slug,
  title:item.title,
  description:item.description,
  heading:item.heading,
  summary:item.summary,
  searchTerms:item.searchTerms,
}))


export const CONSTRUCTION_GUIDE_HUB_ROUTE={
  path:'/guides',
  type:'guide-hub',
  title:'Home Construction & Interior Guides | ProPulse',
  description:'Practical guides for home construction, materials, concrete quality, contractor selection, waterproofing, electrical, plumbing and interiors.',
  heading:'Home construction and interior planning guides',
  summary:'Research common construction and interior decisions, then turn the useful details into a project-specific requirement.',
}
