const pool=require('../config/database');

function fail(message,code='COUPON_INVALID'){throw Object.assign(new Error(message),{code})}
function ids(values){return [...new Set((Array.isArray(values)?values:[]).map(Number).filter(Number.isInteger).filter(x=>x>0))]}
function normalizeCode(code){return String(code||'').trim().toUpperCase()}
function discountFor(coupon,subtotal){const amount=Number(subtotal);let discount=coupon.discount_type==='percent'?amount*Number(coupon.discount_value)/100:Number(coupon.discount_value);if(coupon.max_discount!=null)discount=Math.min(discount,Number(coupon.max_discount));return Number(Math.min(Math.max(discount,0),amount).toFixed(2))}

async function getAdminCoupons({search='',status='all'}={}){
  const values=[],where=[];if(search.trim()){values.push(`%${search.trim()}%`);where.push(`(c.code ILIKE $${values.length} OR COALESCE(c.description,'') ILIKE $${values.length})`)}
  if(status==='active'){where.push('c.is_active=TRUE')}else if(status==='inactive'){where.push('c.is_active=FALSE')}
  const base=where.length?`WHERE ${where.join(' AND ')}`:'';
  const rows=(await pool.query(`SELECT c.*,COALESCE((SELECT COUNT(*) FROM coupon_users cu WHERE cu.coupon_id=c.id),0)::int target_user_count,COALESCE((SELECT COUNT(*) FROM coupon_industries ci WHERE ci.coupon_id=c.id),0)::int target_industry_count,COALESCE((SELECT COUNT(*) FROM coupon_redemptions cr WHERE cr.coupon_id=c.id AND cr.status='redeemed'),0)::int redeemed_count,COALESCE((SELECT string_agg(i.name,', ' ORDER BY i.name) FROM coupon_industries ci JOIN industries i ON i.id=ci.industry_id WHERE ci.coupon_id=c.id),'') target_industries FROM coupons c ${base} ORDER BY c.created_at DESC,c.id DESC`,values)).rows;
  return rows
}

async function getAdminCoupon(id){
  const coupon=(await pool.query('SELECT * FROM coupons WHERE id=$1',[id])).rows[0];if(!coupon)return null;
  const users=(await pool.query(`SELECT u.id,u.name,u.email FROM coupon_users cu JOIN users u ON u.id=cu.user_id WHERE cu.coupon_id=$1 ORDER BY u.name,u.id`,[id])).rows;
  const industries=(await pool.query(`SELECT i.id,i.name,i.slug FROM coupon_industries ci JOIN industries i ON i.id=ci.industry_id WHERE ci.coupon_id=$1 ORDER BY i.name,i.id`,[id])).rows;
  return {...coupon,users,industries}
}

async function createCoupon(input,adminId){
  const code=normalizeCode(input.code);if(!/^[A-Z0-9_-]{3,50}$/.test(code))fail('Coupon code must be 3-50 characters using letters, numbers, _ or -','INVALID_COUPON');
  const type=input.discount_type==='fixed'?'fixed':'percent';const value=Number(input.discount_value);if(!Number.isFinite(value)||value<=0||(type==='percent'&&value>100))fail('Invalid discount value','INVALID_COUPON');
  const min=Math.max(0,Number(input.min_order_amount||0));const max=input.max_discount===''||input.max_discount==null?null:Number(input.max_discount);const usage=input.usage_limit===''||input.usage_limit==null?null:Number(input.usage_limit);const perUser=input.per_user_limit===''||input.per_user_limit==null?null:Number(input.per_user_limit);if(max!=null&&(!Number.isFinite(max)||max<=0))fail('Invalid maximum discount','INVALID_COUPON');if(usage!=null&&(!Number.isInteger(usage)||usage<=0))fail('Invalid usage limit','INVALID_COUPON');if(perUser!=null&&(!Number.isInteger(perUser)||perUser<=0))fail('Invalid per-user limit','INVALID_COUPON');
  const purchaseTypes=[...new Set((Array.isArray(input.purchase_types)?input.purchase_types:['membership','lead','booster']).filter(x=>['membership','lead','booster'].includes(x)))];if(!purchaseTypes.length)fail('Select at least one purchase type','INVALID_COUPON');
  const userIds=ids(input.user_ids),industryIds=ids(input.industry_ids),planIds=ids(input.membership_plan_ids);const client=await pool.connect();try{await client.query('BEGIN');const row=(await client.query(`INSERT INTO coupons(code,description,discount_type,discount_value,max_discount,min_order_amount,usage_limit,per_user_limit,starts_at,expires_at,is_active,created_by,purchase_types,membership_plan_ids) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13::jsonb,$14::jsonb) RETURNING *`,[code,input.description||null,type,value,max,min,usage,perUser,input.starts_at||null,input.expires_at||null,input.is_active!==false,adminId,JSON.stringify(purchaseTypes),JSON.stringify(planIds)] )).rows[0];for(const userId of userIds)await client.query('INSERT INTO coupon_users(coupon_id,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[row.id,userId]);for(const industryId of industryIds)await client.query('INSERT INTO coupon_industries(coupon_id,industry_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[row.id,industryId]);await client.query('COMMIT');return getAdminCoupon(row.id)}catch(e){await client.query('ROLLBACK');if(e.code==='23505')fail('A coupon with this code already exists','DUPLICATE_COUPON');throw e}finally{client.release()}}

async function updateCoupon(id,input){const existing=await getAdminCoupon(id);if(!existing)fail('Coupon not found','NOT_FOUND');const code=normalizeCode(input.code||existing.code);const type=input.discount_type==='fixed'||input.discount_type==='percent'?input.discount_type:existing.discount_type;const value=input.discount_value==null?Number(existing.discount_value):Number(input.discount_value);if(!Number.isFinite(value)||value<=0||(type==='percent'&&value>100))fail('Invalid discount value','INVALID_COUPON');const userIds=ids(input.user_ids),industryIds=ids(input.industry_ids),planIds=ids(input.membership_plan_ids);const purchaseTypes=Array.isArray(input.purchase_types)?input.purchase_types.filter(x=>['membership','lead','booster'].includes(x)):existing.purchase_types;const client=await pool.connect();try{await client.query('BEGIN');await client.query(`UPDATE coupons SET code=$1,description=$2,discount_type=$3,discount_value=$4,max_discount=$5,min_order_amount=$6,usage_limit=$7,per_user_limit=$8,starts_at=$9,expires_at=$10,is_active=$11,purchase_types=$12::jsonb,membership_plan_ids=$13::jsonb,updated_at=CURRENT_TIMESTAMP WHERE id=$14`,[code,input.description??existing.description,type,value,input.max_discount===''?null:(input.max_discount??existing.max_discount),input.min_order_amount===''?0:(input.min_order_amount??existing.min_order_amount),input.usage_limit===''?null:(input.usage_limit??existing.usage_limit),input.per_user_limit===''?null:(input.per_user_limit??existing.per_user_limit),input.starts_at??existing.starts_at,input.expires_at??existing.expires_at,input.is_active!==undefined?Boolean(input.is_active):existing.is_active,JSON.stringify(purchaseTypes),JSON.stringify(planIds),id]);if(input.user_ids!==undefined){await client.query('DELETE FROM coupon_users WHERE coupon_id=$1',[id]);for(const userId of userIds)await client.query('INSERT INTO coupon_users(coupon_id,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[id,userId])}if(input.industry_ids!==undefined){await client.query('DELETE FROM coupon_industries WHERE coupon_id=$1',[id]);for(const industryId of industryIds)await client.query('INSERT INTO coupon_industries(coupon_id,industry_id) VALUES($1,$2) ON CONFLICT DO NOTHING',[id,industryId])}await client.query('COMMIT');return getAdminCoupon(id)}catch(e){await client.query('ROLLBACK');if(e.code==='23505')fail('A coupon with this code already exists','DUPLICATE_COUPON');throw e}finally{client.release()}}

async function setCouponActive(id,isActive){const r=await pool.query('UPDATE coupons SET is_active=$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2 RETURNING *',[Boolean(isActive),id]);if(!r.rows[0])fail('Coupon not found','NOT_FOUND');return r.rows[0]}

async function validateForUser({userId,code,subtotal,purchaseType,industryId=null,membershipPlanId=null}){
  const normalized=normalizeCode(code);if(!normalized)return null;const amount=Number(subtotal);if(!Number.isFinite(amount)||amount<0)fail('Invalid purchase amount','INVALID_AMOUNT');const coupon=(await pool.query('SELECT * FROM coupons WHERE UPPER(code)=UPPER($1) FOR UPDATE',[normalized])).rows[0];if(!coupon)fail('Coupon code not found','COUPON_NOT_FOUND');const now=new Date();if(!coupon.is_active)fail('This coupon is inactive','COUPON_INACTIVE');if(coupon.starts_at&&new Date(coupon.starts_at)>now)fail('This coupon is not active yet','COUPON_NOT_STARTED');if(coupon.expires_at&&new Date(coupon.expires_at)<=now)fail('This coupon has expired','COUPON_EXPIRED');if(Number(coupon.min_order_amount)>amount)fail(`Minimum order amount is ₹${Number(coupon.min_order_amount).toFixed(2)}`,'MIN_ORDER');const purchaseTypes=Array.isArray(coupon.purchase_types)?coupon.purchase_types:JSON.parse(coupon.purchase_types||'[]');if(purchaseType&&!purchaseTypes.includes(purchaseType))fail('This coupon does not apply to this purchase','PURCHASE_NOT_ELIGIBLE');const planIds=Array.isArray(coupon.membership_plan_ids)?coupon.membership_plan_ids:JSON.parse(coupon.membership_plan_ids||'[]');if(membershipPlanId&&planIds.length&&!planIds.includes(Number(membershipPlanId)))fail('This coupon does not apply to this membership plan','PLAN_NOT_ELIGIBLE');const targetUser=(await pool.query('SELECT 1 FROM coupon_users WHERE coupon_id=$1 AND user_id=$2',[coupon.id,userId])).rowCount;const targetUserCount=(await pool.query('SELECT COUNT(*)::int count FROM coupon_users WHERE coupon_id=$1',[coupon.id])).rows[0].count;if(Number(targetUserCount)>0&&!targetUser)fail('This coupon is restricted to specified users','USER_NOT_ELIGIBLE');const targetIndustry=(await pool.query('SELECT 1 FROM coupon_industries WHERE coupon_id=$1 AND industry_id=$2',[coupon.id,industryId])).rowCount;const targetIndustryCount=(await pool.query('SELECT COUNT(*)::int count FROM coupon_industries WHERE coupon_id=$1',[coupon.id])).rows[0].count;if(Number(targetIndustryCount)>0&&!targetIndustry)fail('This coupon is restricted to specified industries','INDUSTRY_NOT_ELIGIBLE');if(coupon.usage_limit!=null&&Number(coupon.used_count)>=Number(coupon.usage_limit))fail('This coupon has reached its usage limit','USAGE_LIMIT');const userUses=(await pool.query(`SELECT COUNT(*)::int count FROM coupon_redemptions WHERE coupon_id=$1 AND user_id=$2 AND status IN ('reserved','redeemed')`,[coupon.id,userId])).rows[0].count;if(coupon.per_user_limit!=null&&Number(userUses)>=Number(coupon.per_user_limit))fail('You have reached this coupon usage limit','USER_USAGE_LIMIT');const discount=discountFor(coupon,amount);return{coupon,discountAmount:discount,finalAmount:Number((amount-discount).toFixed(2))}}

module.exports={getAdminCoupons,getAdminCoupon,createCoupon,updateCoupon,setCouponActive,validateForUser};
