const pool=require('../config/database');const walletService=require('./walletService');const {isProMember}=require('./membershipAccessService');
function priceFor(pricing,shares,tier){const row=(pricing?.shares||[]).find(x=>Number(x.shares)===shares);if(!row)throw Object.assign(new Error('Selected share package is unavailable'),{code:'INVALID_SHARES'});const value=Number(row[tier]);if(!Number.isFinite(value)||value<0)throw Object.assign(new Error('Lead price is invalid'),{code:'INVALID_PRICE'});return value}
async function matchesBusinessProfile(client,lead,userId){const serviceMatch=await client.query(`SELECT 1 FROM business_profiles bp JOIN business_profile_services bps ON bps.business_profile_id=bp.id WHERE bp.user_id=$1 AND bps.is_active=TRUE AND bps.industry_id=$2 AND bps.service_id=$3 AND ($4::int IS NULL OR bps.subservice_id IS NULL OR bps.subservice_id=$4) LIMIT 1`,[userId,lead.industry_id,lead.service_id,lead.subservice_id]);if(!serviceMatch.rows.length)throw Object.assign(new Error('Complete your business services before purchasing this lead'),{code:'PROFILE_MISMATCH'});const locationMatch=await client.query(`SELECT 1 FROM business_profiles bp JOIN business_profile_locations bpl ON bpl.business_profile_id=bp.id WHERE bp.user_id=$1 AND bpl.is_active=TRUE AND bpl.state_id=$2 AND bpl.city_id=$3 LIMIT 1`,[userId,lead.state_id,lead.city_id]);if(!locationMatch.rows.length)throw Object.assign(new Error('Add this lead location to your business profile before purchasing'),{code:'PROFILE_MISMATCH'})}
async function allocateInvestmentRevenue(client,{leadPurchaseId,industryId,grossAmount}){
  if(!industryId||grossAmount<=0)return;
  const settings=(await client.query('SELECT investor_revenue_share_percent FROM investor_settings WHERE id=1 FOR UPDATE')).rows[0];
  const globalShare=Math.max(0,Math.min(100,Number(settings?.investor_revenue_share_percent??100)));
  if(globalShare<=0)return;
  const investors=(await client.query(`SELECT id,amount FROM investments WHERE industry_id=$1 AND status='active' AND starts_at<=CURRENT_TIMESTAMP AND matures_at>CURRENT_TIMESTAMP ORDER BY id FOR UPDATE`,[industryId])).rows;
  if(!investors.length)return;
  const total=investors.reduce((sum,x)=>sum+Number(x.amount),0);if(total<=0)return;
  const distributable=grossAmount*globalShare/100;
  for(const inv of investors){
    const allocated=distributable*(Number(inv.amount)/total);
    if(allocated<=0)continue;
    await client.query(`INSERT INTO investment_revenue_allocations(investment_id,lead_purchase_id,industry_id,gross_sale_amount,investor_share_percent,allocated_amount) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(investment_id,lead_purchase_id) DO NOTHING`,[inv.id,leadPurchaseId,industryId,grossAmount,globalShare,allocated]);
  }
}
async function purchaseLead({leadId,userId,shares}){const requested=Number(shares);if(!Number.isInteger(requested)||requested<=0)throw Object.assign(new Error('Shares must be a positive integer'),{code:'INVALID_SHARES'});const client=await pool.connect();try{await client.query('BEGIN');const leadResult=await client.query(`SELECT l.*,CASE WHEN l.is_exclusive THEN l.created_at+make_interval(days=>l.exclusive_delay_days) ELSE NULL END AS exclusive_available_at FROM leads l WHERE l.id=$1 FOR UPDATE`,[leadId]);const lead=leadResult.rows[0];if(!lead)throw Object.assign(new Error('Lead not found'),{code:'NOT_FOUND'});if(lead.status!=='available')throw Object.assign(new Error('Lead is no longer available'),{code:'NOT_AVAILABLE'});const existing=await client.query(`SELECT id,shares,amount,pricing_tier,status FROM lead_purchases WHERE lead_id=$1 AND user_id=$2 AND status='paid' FOR UPDATE`,[leadId,userId]);if(existing.rows[0]){await client.query('COMMIT');return existing.rows[0]}const capacity=Math.max(1,Number(lead.buyer_capacity)||1);const capacityResult=await client.query(`SELECT COUNT(*)::int AS paid_buyers FROM lead_purchases WHERE lead_id=$1 AND status='paid'`,[leadId]);const paidBuyers=Number(capacityResult.rows[0].paid_buyers)||0;if(paidBuyers>=capacity)throw Object.assign(new Error('This lead has reached its buyer capacity'),{code:'CAPACITY_REACHED'});await matchesBusinessProfile(client,lead,userId);const pro=await isProMember(userId,client);const expired=!lead.is_exclusive||!lead.exclusive_available_at||new Date(lead.exclusive_available_at)<=new Date();if(lead.is_exclusive&&!pro&&!expired)throw Object.assign(new Error('This exclusive lead is currently reserved for Pro members'),{code:'PRO_REQUIRED'});const tier=pro?'pro':'normal';const amount=priceFor(lead.pricing,requested,tier);const result=await client.query(`INSERT INTO lead_purchases(lead_id,user_id,shares,amount,pricing_tier,status) VALUES($1,$2,$3,$4,$5,'paid') RETURNING *`,[leadId,userId,requested,amount,tier]);await walletService.debitForLead(client,{userId,amount,leadPurchaseId:result.rows[0].id});await allocateInvestmentRevenue(client,{leadPurchaseId:result.rows[0].id,industryId:lead.industry_id,grossAmount:amount});await client.query('COMMIT');return result.rows[0]}catch(e){try{await client.query('ROLLBACK')}catch{}throw e}finally{client.release()}}
async function getPurchases(userId){return(await pool.query(`SELECT p.*,l.industry_id,l.service_id,l.subservice_id,l.state_id,l.city_id,l.customer_name,l.customer_phone,l.customer_email,l.requirement,l.property_type,l.budget,l.source,l.notes,i.name AS industry_name,s.name AS service_name,ss.name AS subservice_name,st.name AS state_name,c.name AS city_name FROM lead_purchases p JOIN leads l ON l.id=p.lead_id LEFT JOIN industries i ON i.id=l.industry_id LEFT JOIN services s ON s.id=l.service_id LEFT JOIN subservices ss ON ss.id=l.subservice_id LEFT JOIN states st ON st.id=l.state_id LEFT JOIN cities c ON c.id=l.city_id WHERE p.user_id=$1 AND p.status='paid' ORDER BY p.created_at DESC`,[userId])).rows}
module.exports={purchaseLead,getPurchases};
