const pool=require('../config/database');
const leadEntitlementService=require('./leadEntitlementService');
const {leadSelect,maskLead,normalizeLeadType,isProMember}=require('./leadReadService');

async function getMarketplacePage({industryId,serviceId,subserviceId,stateId,cityId,status='available',leadType,search,userId,role,page=1,limit=20}){
 const safePage=Math.max(1,Number.parseInt(page,10)||1);const safeLimit=Math.min(50,Math.max(1,Number.parseInt(limit,10)||20));const values=[];const conditions=[];const add=(value,sql)=>{values.push(value);conditions.push(sql.replace('?',`$${values.length}`))};
 if(status&&status!=='all')add(status,'l.status=?');const type=normalizeLeadType(leadType);if(type)add(type,'l.lead_type=?');if(industryId)add(industryId,'l.industry_id=?');if(serviceId)add(serviceId,'l.service_id=?');if(subserviceId)add(subserviceId,'l.subservice_id=?');if(stateId)add(stateId,'l.state_id=?');if(cityId)add(cityId,'l.city_id=?');
 const q=String(search||'').trim().toLowerCase();if(q){values.push(`%${q}%`);const p=`$${values.length}`;conditions.push(`(LOWER(COALESCE(i.name,'')) LIKE ${p} OR LOWER(COALESCE(s.name,'')) LIKE ${p} OR LOWER(COALESCE(ss.name,'')) LIKE ${p} OR LOWER(COALESCE(c.name,'')) LIKE ${p} OR LOWER(COALESCE(st.name,'')) LIKE ${p} OR LOWER(COALESCE(l.requirement,'')) LIKE ${p})`)}
 if(role!=='admin'&&userId){values.push(userId);const p=`$${values.length}`;conditions.push(`EXISTS (SELECT 1 FROM business_profiles bp JOIN business_profile_services bps ON bps.business_profile_id=bp.id WHERE bp.user_id=${p} AND bps.is_active=TRUE AND (l.industry_id IS NULL OR bps.industry_id=l.industry_id) AND (l.service_id IS NULL OR bps.service_id=l.service_id) AND (l.subservice_id IS NULL OR bps.subservice_id IS NULL OR bps.subservice_id=l.subservice_id))`);values.push(userId);const p2=`$${values.length}`;conditions.push(`EXISTS (SELECT 1 FROM business_profiles bp JOIN business_profile_locations bpl ON bpl.business_profile_id=bp.id WHERE bp.user_id=${p2} AND bpl.is_active=TRUE AND (l.state_id IS NULL OR bpl.state_id=l.state_id) AND (l.city_id IS NULL OR bpl.city_id=l.city_id))`)}
 const where=conditions.length?`WHERE ${conditions.join(' AND ')}`:'';const count=await pool.query(`SELECT COUNT(*)::int AS total FROM leads l LEFT JOIN industries i ON i.id=l.industry_id LEFT JOIN services s ON s.id=l.service_id LEFT JOIN subservices ss ON ss.id=l.subservice_id LEFT JOIN states st ON st.id=l.state_id LEFT JOIN cities c ON c.id=l.city_id ${where}`,values);const total=Number(count.rows[0]?.total||0);const offset=(safePage-1)*safeLimit;const pageValues=[...values,safeLimit,offset];
 const rows=(await pool.query(`${leadSelect} ${where} ORDER BY l.created_at DESC,l.id DESC LIMIT $${pageValues.length-1} OFFSET $${pageValues.length}`,pageValues)).rows;if(role==='admin')return rows;
 const pro=await isProMember(userId);const accessMap=await leadEntitlementService.getLeadAccessMap(userId,rows.map(x=>x.id));const items=rows.map(row=>{const access=accessMap[row.id]||{authenticated:Boolean(userId),claimed:false,canClaim:false};const owned=Boolean(access.claimed);const exclusive=Boolean(row.is_exclusive);const expired=!exclusive||!row.exclusive_available_at||new Date(row.exclusive_available_at)<=new Date();const base=owned?row:maskLead(row);return{...base,is_purchased:owned,is_accessible:owned,is_pro_member:pro,has_exclusive_option:exclusive,exclusive_available:exclusive&&(pro||expired),exclusive_can_buy:!owned&&exclusive&&(pro||expired),exclusive_action:owned?'access_granted':(!exclusive?'buy':(pro||expired?'buy':'upgrade_to_pro')),access};});return{items,pagination:{page:safePage,limit:safeLimit,total,hasNext:offset+rows.length<total,hasPrevious:safePage>1}};
}
module.exports={getMarketplacePage};
