const pool=require('../config/database');
const DEFAULT_PRICING={shares:[{shares:1,normal:0,pro:0},{shares:3,normal:0,pro:0},{shares:5,normal:0,pro:0}],exclusive:{normal:0,pro:0}};
const VALID_TYPES=['basic','premium'];const cleanJson=(v,fallback={})=>v&&typeof v==='object'&&!Array.isArray(v)?v:fallback;const normalizeType=v=>VALID_TYPES.includes(String(v||'').toLowerCase())?String(v).toLowerCase():'basic';
function mergePricing(base,sheet){if(!sheet||(!Array.isArray(sheet.shares)&&!sheet.exclusive))return base;const source=new Map((sheet.shares||[]).map(x=>[Number(x.shares),x]));const shares=(base?.shares||DEFAULT_PRICING.shares).map(x=>{const s=source.get(Number(x.shares));return{shares:Number(x.shares),normal:s?.normal!==null&&s?.normal!==undefined&&s?.normal!==''?Number(s.normal):Number(x.normal||0),pro:s?.pro!==null&&s?.pro!==undefined&&s?.pro!==''?Number(s.pro):Number(x.pro||0)}});const b=base?.exclusive||DEFAULT_PRICING.exclusive;const e=sheet.exclusive||{};return{shares,exclusive:{normal:e.normal!==null&&e.normal!==undefined&&e.normal!==''?Number(e.normal):Number(b.normal||0),pro:e.pro!==null&&e.pro!==undefined&&e.pro!==''?Number(e.pro):Number(b.pro||0)}}}
async function getConfiguredRule(industryId,cityId,leadType='basic'){const type=normalizeType(leadType);const r=await pool.query(`SELECT pricing,exclusive_delay_hours FROM lead_pricing_rules WHERE is_active=TRUE AND lead_type=$3 AND (industry_id=$1 OR industry_id IS NULL) AND (city_id=$2 OR city_id IS NULL) ORDER BY CASE WHEN industry_id IS NOT NULL AND city_id IS NOT NULL THEN 3 WHEN industry_id IS NOT NULL THEN 2 WHEN city_id IS NOT NULL THEN 1 ELSE 0 END DESC LIMIT 1`,[industryId||null,cityId||null,type]);return{pricing:r.rows[0]?.pricing||DEFAULT_PRICING,exclusiveDelayHours:Number(r.rows[0]?.exclusive_delay_hours??24)}}
async function getConfiguredPricing(industryId,cityId,leadType='basic'){return(await getConfiguredRule(industryId,cityId,leadType)).pricing}
async function createLead({industryId,serviceId,subserviceId,stateId,cityId,customerName,customerPhone,customerEmail,requirement,propertyType,budget,source,notes,customFields,pricing,pricingSource,leadType='basic',exclusiveDelayHours,createdBy}){const type=normalizeType(leadType);const configured=await getConfiguredRule(industryId,cityId,type);const effectivePricing=pricingSource==='sheet'?mergePricing(configured.pricing,pricing):configured.pricing;const rawDelay=exclusiveDelayHours===undefined||exclusiveDelayHours===null||exclusiveDelayHours===''?configured.exclusiveDelayHours:exclusiveDelayHours;const delay=Math.max(0,Math.min(8760,Number(rawDelay)));return(await pool.query(`INSERT INTO leads (industry_id,service_id,subservice_id,state_id,city_id,customer_name,customer_phone,customer_email,requirement,property_type,budget,source,notes,custom_fields,pricing,lead_type,exclusive_delay_hours,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15::jsonb,$16::jsonb,$17,$18,$19) RETURNING *`,[industryId||null,serviceId||null,subserviceId||null,stateId||null,cityId||null,customerName||null,customerPhone||null,customerEmail||null,requirement||null,propertyType||null,budget??null,source||'upload',notes||null,JSON.stringify(cleanJson(customFields)),JSON.stringify(cleanJson(effectivePricing,DEFAULT_PRICING)),type,delay,createdBy||null])).rows[0]}
const leadSelect=`SELECT l.*,i.name AS industry_name,s.name AS service_name,ss.name AS subservice_name,st.name AS state_name,c.name AS city_name,(l.created_at + make_interval(hours => l.exclusive_delay_hours)) AS exclusive_available_at FROM leads l LEFT JOIN industries i ON i.id=l.industry_id LEFT JOIN services s ON s.id=l.service_id LEFT JOIN subservices ss ON ss.id=l.subservice_id LEFT JOIN states st ON st.id=l.state_id LEFT JOIN cities c ON c.id=l.city_id`;
async function getLeadById(id){return(await pool.query(`${leadSelect} WHERE l.id=$1`,[id])).rows[0]||null}
async function isProMember(userId){if(!userId)return false;const r=await pool.query(`SELECT 1 FROM memberships m JOIN membership_plans mp ON mp.id=m.membership_plan_id WHERE m.user_id=$1 AND m.status='active' AND m.starts_at<=CURRENT_TIMESTAMP AND m.ends_at>=CURRENT_TIMESTAMP AND LOWER(COALESCE(mp.plan_type,'')) IN ('pro','premium_pro') AND mp.is_active=TRUE LIMIT 1`,[userId]);return r.rows.length>0}
async function getLeads({industryId,serviceId,subserviceId,stateId,cityId,status='available',leadType,userId,role}){const v=[],c=[];if(status&&status!=='all'){v.push(status);c.push(`l.status=$${v.length}`)}if(leadType){v.push(normalizeType(leadType));c.push(`l.lead_type=$${v.length}`)}if(industryId){v.push(industryId);c.push(`l.industry_id=$${v.length}`)}if(serviceId){v.push(serviceId);c.push(`l.service_id=$${v.length}`)}if(subserviceId){v.push(subserviceId);c.push(`l.subservice_id=$${v.length}`)}if(stateId){v.push(stateId);c.push(`l.state_id=$${v.length}`)}if(cityId){v.push(cityId);c.push(`l.city_id=$${v.length}`)}let pro=false;if(role!=='admin'){pro=await isProMember(userId);v.push(userId);c.push(`EXISTS (SELECT 1 FROM business_profiles bp JOIN business_profile_services bps ON bps.business_profile_id=bp.id WHERE bp.user_id=$${v.length} AND bps.is_active=TRUE AND bps.industry_id=l.industry_id AND bps.service_id=l.service_id AND (bps.subservice_id IS NULL OR bps.subservice_id=l.subservice_id))`);v.push(userId);c.push(`EXISTS (SELECT 1 FROM business_profiles bp JOIN business_profile_locations bpl ON bpl.business_profile_id=bp.id WHERE bp.user_id=$${v.length} AND bpl.is_active=TRUE AND bpl.state_id=l.state_id AND bpl.city_id=l.city_id)`)}const rows=(await pool.query(`${leadSelect} ${c.length?`WHERE ${c.join(' AND ')}`:''} ORDER BY l.created_at DESC`,v)).rows;if(role==='admin')return rows;return rows.map(row=>{const e=row.pricing?.exclusive;const has=Boolean(e&&(e.normal!==undefined&&e.normal!==null||e.pro!==undefined&&e.pro!==null));const expired=row.exclusive_available_at?new Date(row.exclusive_available_at)<=new Date():true;return{...row,is_pro_member:pro,has_exclusive_option:has,exclusive_available:Boolean(has&&(pro||expired)),exclusive_can_buy:Boolean(has&&(pro||expired)),exclusive_action:!has?'none':pro||expired?'buy':'upgrade_to_pro'}})}
async function updateLead(id,data){const {industryId,serviceId,subserviceId,stateId,cityId,customerName,customerPhone,customerEmail,requirement,propertyType,budget,source,status,notes,customFields,pricing,leadType,exclusiveDelayHours}=data;const type=normalizeType(leadType);const rawDelay=exclusiveDelayHours===undefined||exclusiveDelayHours===null||exclusiveDelayHours===''?24:exclusiveDelayHours;const delay=Math.max(0,Math.min(8760,Number(rawDelay)));return(await pool.query(`UPDATE leads SET industry_id=$1,service_id=$2,subservice_id=$3,state_id=$4,city_id=$5,customer_name=$6,customer_phone=$7,customer_email=$8,requirement=$9,property_type=$10,budget=$11,source=$12,status=$13,notes=$14,custom_fields=$15::jsonb,pricing=$16::jsonb,lead_type=$17,exclusive_delay_hours=$18,updated_at=CURRENT_TIMESTAMP WHERE id=$19 RETURNING *`,[industryId||null,serviceId||null,subserviceId||null,stateId||null,cityId||null,customerName||null,customerPhone||null,customerEmail||null,requirement||null,propertyType||null,budget??null,source||'upload',status||'available',notes||null,JSON.stringify(cleanJson(customFields)),JSON.stringify(cleanJson(pricing,DEFAULT_PRICING)),type,delay,id])).rows[0]||null}
async function updateLeadStatus(id,status){return(await pool.query('UPDATE leads SET status=$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2 RETURNING *',[status,id])).rows[0]||null}
async function deleteLead(id){return(await pool.query('DELETE FROM leads WHERE id=$1 RETURNING *',[id])).rows[0]||null}
async function getLeadPricing(){return(await pool.query('SELECT * FROM lead_pricing WHERE id=1')).rows[0]||null}
async function updateLeadPricing(data){const values=[Number(data.normal?.oneShare||0),Number(data.normal?.threeShares||0),Number(data.normal?.fiveShares||0),Number(data.pro?.oneShare||0),Number(data.pro?.threeShares||0),Number(data.pro?.fiveShares||0)];if(values.some(v=>!Number.isFinite(v)||v<0))throw Error('Pricing values must be non-negative numbers');return(await pool.query(`INSERT INTO lead_pricing (id,normal_one_share,normal_three_shares,normal_five_shares,pro_one_share,pro_three_shares,pro_five_shares,updated_at) VALUES (1,$1,$2,$3,$4,$5,$6,CURRENT_TIMESTAMP) ON CONFLICT (id) DO UPDATE SET normal_one_share=EXCLUDED.normal_one_share,normal_three_shares=EXCLUDED.normal_three_shares,normal_five_shares=EXCLUDED.normal_five_shares,pro_one_share=EXCLUDED.pro_one_share,pro_three_shares=EXCLUDED.pro_three_shares,pro_five_shares=EXCLUDED.pro_five_shares,updated_at=CURRENT_TIMESTAMP RETURNING *`,values)).rows[0]}
async function getPricingRules(){return(await pool.query(`SELECT r.id,r.industry_id,r.city_id,r.lead_type,r.pricing,r.exclusive_delay_hours,r.is_active,i.name AS industry_name,c.name AS city_name FROM lead_pricing_rules r LEFT JOIN industries i ON i.id=r.industry_id LEFT JOIN cities c ON c.id=r.city_id ORDER BY r.industry_id NULLS FIRST,r.city_id NULLS FIRST,r.lead_type`)).rows}
async function savePricingRule({id,industryId,cityId,pricing,isActive=true,leadType='basic',exclusiveDelayHours=24}){const type=normalizeType(leadType);const rawDelay=exclusiveDelayHours===undefined||exclusiveDelayHours===null||exclusiveDelayHours===''?24:exclusiveDelayHours;const delay=Math.max(0,Math.min(8760,Number(rawDelay)));const params=[industryId||null,cityId||null,type,JSON.stringify(cleanJson(pricing,DEFAULT_PRICING)),delay,Boolean(isActive)];if(id)return(await pool.query(`UPDATE lead_pricing_rules SET industry_id=$1,city_id=$2,lead_type=$3,pricing=$4::jsonb,exclusive_delay_hours=$5,is_active=$6,updated_at=CURRENT_TIMESTAMP WHERE id=$7 RETURNING *`,[...params,id])).rows[0]||null;return(await pool.query(`INSERT INTO lead_pricing_rules (industry_id,city_id,lead_type,pricing,exclusive_delay_hours,is_active,updated_at) VALUES ($1,$2,$3,$4::jsonb,$5,$6,CURRENT_TIMESTAMP) RETURNING *`,params)).rows[0]}
async function deletePricingRule(id){return(await pool.query('DELETE FROM lead_pricing_rules WHERE id=$1 RETURNING id',[id])).rows[0]||null}
module.exports={createLead,getLeadById,getLeads,updateLead,updateLeadStatus,deleteLead,getLeadPricing,updateLeadPricing,getPricingRules,savePricingRule,deletePricingRule,isProMember};
