const pool = require('../config/database');

async function ensureWallet(client, userId) {
  const r = await client.query(`INSERT INTO wallets(user_id) VALUES($1) ON CONFLICT(user_id) DO UPDATE SET user_id=EXCLUDED.user_id RETURNING *`, [userId]);
  return r.rows[0];
}
function money(value, code='INVALID_AMOUNT') { const n=Number(value); if(!Number.isFinite(n)||n<=0) throw Object.assign(new Error('Amount must be greater than zero'),{code}); return Number(n.toFixed(2)); }
async function getWallet(userId) {
  const client=await pool.connect(); try { await client.query('BEGIN'); const w=await ensureWallet(client,userId); const tx=await client.query(`SELECT id,type,amount,balance_after,reference_type,reference_id,payment_id,status,description,created_at FROM wallet_transactions WHERE user_id=$1 ORDER BY created_at DESC,id DESC LIMIT 100`,[userId]); await client.query('COMMIT'); return {id:w.id,balance:Number(w.balance),transactions:tx.rows.map(x=>({...x,amount:Number(x.amount),balance_after:Number(x.balance_after)}))}; } catch(e){await client.query('ROLLBACK');throw e} finally{client.release()}
}
async function createTopup({userId,amount,reference,proofUrl}) {
  const value=money(amount), normalizedReference=reference==null?null:String(reference).trim()||null, client=await pool.connect();
  try { await client.query('BEGIN'); if(normalizedReference) await client.query('SELECT pg_advisory_xact_lock(hashtext($1))',[`wallet-topup-reference:${normalizedReference.toLowerCase()}`]); const r=await client.query(`INSERT INTO wallet_topups(user_id,amount,reference,proof_url) VALUES($1,$2,$3,$4) RETURNING *`,[userId,value,normalizedReference,proofUrl||null]); await client.query('COMMIT'); return r.rows[0]; } catch(e){await client.query('ROLLBACK');if(e.code==='23505')throw Object.assign(new Error('This payment reference / UTR has already been submitted'),{code:'DUPLICATE_REFERENCE'});throw e} finally{client.release()}
}
async function getTopups(userId) { const r=await pool.query(`SELECT id,amount,payment_method,reference,proof_url,status,reviewed_at,created_at,updated_at FROM wallet_topups WHERE user_id=$1 ORDER BY created_at DESC,id DESC LIMIT 100`,[userId]); return r.rows.map(x=>({...x,amount:Number(x.amount)})); }
async function getAdminTopups({status='all',search='',page=1,limit=50}) {
  const params=[],where=[]; if(status&&status!=='all'){if(!['pending','approved','rejected'].includes(status))throw Object.assign(new Error('Invalid top-up status filter'),{code:'INVALID_STATUS'});params.push(status);where.push(`wt.status=$${params.length}`)}
  if(search&&search.trim()){params.push(`%${search.trim()}%`);where.push(`(u.name ILIKE $${params.length} OR u.email ILIKE $${params.length} OR COALESCE(bp.business_name,'') ILIKE $${params.length} OR COALESCE(wt.reference,'') ILIKE $${params.length})`)}
  const safeLimit=Math.min(Math.max(Number(limit)||50,1),100),safePage=Math.max(Number(page)||1,1),offset=(safePage-1)*safeLimit,baseWhere=where.length?`WHERE ${where.join(' AND ')}`:'';
  const from=`wallet_topups wt JOIN users u ON u.id=wt.user_id LEFT JOIN business_profiles bp ON bp.user_id=wt.user_id`;
  const count=(await pool.query(`SELECT COUNT(*)::int total FROM ${from} ${baseWhere}`,params)).rows[0].total;
  const stats=(await pool.query(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE wt.status='pending')::int pending,COUNT(*) FILTER(WHERE wt.status='approved')::int approved,COUNT(*) FILTER(WHERE wt.status='rejected')::int rejected,SUM(wt.amount) FILTER(WHERE wt.status='approved')::numeric approved_amount FROM ${from} ${baseWhere}`,params)).rows[0];
  const dataParams=[...params,safeLimit,offset],rows=(await pool.query(`SELECT wt.id,wt.user_id,wt.amount,wt.payment_method,wt.reference,wt.proof_url,wt.status,wt.reviewed_by,wt.reviewed_at,wt.created_at,wt.updated_at,u.name user_name,u.email user_email,bp.business_name,ru.name reviewer_name,COALESCE(w.balance,0)::numeric wallet_balance FROM ${from} LEFT JOIN wallets w ON w.user_id=wt.user_id LEFT JOIN users ru ON ru.id=wt.reviewed_by ${baseWhere} ORDER BY wt.created_at DESC,wt.id DESC LIMIT $${dataParams.length-1} OFFSET $${dataParams.length}`,dataParams)).rows.map(x=>({...x,amount:Number(x.amount),wallet_balance:Number(x.wallet_balance||0)}));
  return {items:rows,total:count,page:safePage,limit:safeLimit,pages:Math.ceil(count/safeLimit),stats:{...stats,approved_amount:Number(stats.approved_amount||0)}};
}
async function approveTopup({topupId,adminId}) { const client=await pool.connect(); try {await client.query('BEGIN');const t=(await client.query(`SELECT * FROM wallet_topups WHERE id=$1 FOR UPDATE`,[topupId])).rows[0];if(!t)throw Object.assign(new Error('Top-up not found'),{code:'NOT_FOUND'});if(t.status!=='pending')throw Object.assign(new Error('Top-up is already reviewed'),{code:'ALREADY_REVIEWED'});const w=await ensureWallet(client,t.user_id),locked=(await client.query(`SELECT id,balance FROM wallets WHERE id=$1 FOR UPDATE`,[w.id])).rows[0],next=Number(locked.balance)+Number(t.amount);await client.query(`UPDATE wallets SET balance=$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2`,[next,locked.id]);await client.query(`INSERT INTO wallet_transactions(wallet_id,user_id,type,amount,balance_after,reference_type,reference_id,description) VALUES($1,$2,'credit',$3,$4,'wallet_topup',$5,'Wallet top-up approved')`,[locked.id,t.user_id,t.amount,next,t.id]);const updated=(await client.query(`UPDATE wallet_topups SET status='approved',reviewed_by=$1,reviewed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=$2 AND status='pending' RETURNING *`,[adminId,topupId])).rows[0];if(!updated)throw Object.assign(new Error('Top-up was reviewed concurrently'),{code:'ALREADY_REVIEWED'});await client.query('COMMIT');return updated}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()} }
async function rejectTopup({topupId,adminId}) {const r=await pool.query(`UPDATE wallet_topups SET status='rejected',reviewed_by=$1,reviewed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=$2 AND status='pending' RETURNING *`,[adminId,topupId]);if(!r.rows[0])throw Object.assign(new Error('Pending top-up not found'),{code:'NOT_FOUND'});return r.rows[0]}
async function debitForPayment(client,{userId,amount,paymentId,referenceType,referenceId,description}) {
  const total=money(amount); if(!Number.isInteger(Number(paymentId))||Number(paymentId)<=0)throw Object.assign(new Error('Invalid payment reference'),{code:'INVALID_REFERENCE'});
  const w=await ensureWallet(client,userId); const locked=(await client.query(`SELECT id,balance FROM wallets WHERE id=$1 FOR UPDATE`,[w.id])).rows[0];
  const balance=Math.max(0,Number(locked.balance)||0), walletAmount=Number(Math.min(balance,total).toFixed(2));
  if(walletAmount<=0)return {walletAmount:0,externalAmount:total,walletTransactionId:null,balanceAfter:balance};
  const next=Number((balance-walletAmount).toFixed(2));
  const tx=(await client.query(`UPDATE wallets SET balance=$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2 RETURNING balance`,[next,locked.id])).rows[0];
  const inserted=(await client.query(`INSERT INTO wallet_transactions(wallet_id,user_id,type,amount,balance_after,reference_type,reference_id,payment_id,description) VALUES($1,$2,'debit',$3,$4,$5,$6,$7,$8) RETURNING id`,[locked.id,userId,walletAmount,next,referenceType||null,referenceId||null,paymentId,description||'Purchase paid from wallet'])).rows[0];
  return {walletAmount,externalAmount:Number((total-walletAmount).toFixed(2)),walletTransactionId:inserted.id,balanceAfter:Number(tx.balance)};
}
async function refundForPayment(client,{userId,paymentId,description}) {
  const debit=(await client.query(`SELECT wt.id,wt.wallet_id,wt.amount,wt.balance_after FROM wallet_transactions wt WHERE wt.payment_id=$1 AND wt.type='debit' FOR UPDATE`,[paymentId])).rows[0];
  if(!debit)return {refundedAmount:0,balanceAfter:null,walletTransactionId:null};
  const existing=(await client.query(`SELECT id,balance_after FROM wallet_transactions WHERE payment_id=$1 AND type='refund' LIMIT 1`,[paymentId])).rows[0];
  if(existing)return {refundedAmount:0,balanceAfter:Number(existing.balance_after),walletTransactionId:existing.id};
  const wallet=(await client.query(`SELECT id,balance FROM wallets WHERE id=$1 FOR UPDATE`,[debit.wallet_id])).rows[0]; if(!wallet)throw Object.assign(new Error('Wallet not found'),{code:'WALLET_NOT_FOUND'});
  const next=Number((Number(wallet.balance)+Number(debit.amount)).toFixed(2)); await client.query(`UPDATE wallets SET balance=$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2`,[next,wallet.id]);
  const tx=(await client.query(`INSERT INTO wallet_transactions(wallet_id,user_id,type,amount,balance_after,reference_type,reference_id,payment_id,description) VALUES($1,$2,'refund',$3,$4,'payment',$5,$6,$7) RETURNING id`,[wallet.id,userId,debit.amount,next,paymentId,paymentId,description||'Wallet payment refunded'])).rows[0];
  return {refundedAmount:Number(debit.amount),balanceAfter:next,walletTransactionId:tx.id};
}
async function debitForLead(client,{userId,amount,leadPurchaseId}) { const value=money(amount); if(!Number.isInteger(Number(leadPurchaseId))||Number(leadPurchaseId)<=0)throw Object.assign(new Error('Invalid lead purchase reference'),{code:'INVALID_REFERENCE'}); const w=await ensureWallet(client,userId),locked=(await client.query(`SELECT id,balance FROM wallets WHERE id=$1 FOR UPDATE`,[w.id])).rows[0],balance=Number(locked.balance); if(!Number.isFinite(balance)||balance<value)throw Object.assign(new Error('Insufficient wallet balance'),{code:'INSUFFICIENT_BALANCE'}); const next=balance-value; await client.query(`UPDATE wallets SET balance=$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2`,[next,locked.id]); await client.query(`INSERT INTO wallet_transactions(wallet_id,user_id,type,amount,balance_after,reference_type,reference_id,description) VALUES($1,$2,'debit',$3,$4,'lead_purchase',$5,'Lead purchase')`,[locked.id,userId,value,next,leadPurchaseId]); return next; }
module.exports={ensureWallet,getWallet,createTopup,getTopups,getAdminTopups,approveTopup,rejectTopup,debitForLead,debitForPayment,refundForPayment};