const pool=require('../config/database');

async function ensureWallet(client,userId){
  const r=await client.query(`INSERT INTO wallets(user_id) VALUES($1) ON CONFLICT(user_id) DO UPDATE SET user_id=EXCLUDED.user_id RETURNING *`,[userId]);
  return r.rows[0];
}
async function getWallet(userId){
  const client=await pool.connect();try{await client.query('BEGIN');const w=await ensureWallet(client,userId);const tx=await client.query(`SELECT id,type,amount,balance_after,reference_type,reference_id,status,description,created_at FROM wallet_transactions WHERE user_id=$1 ORDER BY created_at DESC,id DESC LIMIT 100`,[userId]);await client.query('COMMIT');return {id:w.id,balance:Number(w.balance),transactions:tx.rows.map(x=>({...x,amount:Number(x.amount),balance_after:Number(x.balance_after)}))};}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}
async function createTopup({userId,amount,reference,proofUrl}){const value=Number(amount);if(!Number.isFinite(value)||value<=0)throw Object.assign(new Error('Top-up amount must be greater than zero'),{code:'INVALID_AMOUNT'});const r=await pool.query(`INSERT INTO wallet_topups(user_id,amount,reference,proof_url) VALUES($1,$2,$3,$4) RETURNING *`,[userId,value,reference||null,proofUrl||null]);return r.rows[0]}
async function approveTopup({topupId,adminId}){const client=await pool.connect();try{await client.query('BEGIN');const t=(await client.query(`SELECT * FROM wallet_topups WHERE id=$1 FOR UPDATE`,[topupId])).rows[0];if(!t)throw Object.assign(new Error('Top-up not found'),{code:'NOT_FOUND'});if(t.status!=='pending')throw Object.assign(new Error('Top-up is already reviewed'),{code:'ALREADY_REVIEWED'});const w=await ensureWallet(client,t.user_id);const next=Number(w.balance)+Number(t.amount);await client.query(`UPDATE wallets SET balance=$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2`,[next,w.id]);await client.query(`INSERT INTO wallet_transactions(wallet_id,user_id,type,amount,balance_after,reference_type,reference_id,description) VALUES($1,$2,'credit',$3,$4,'wallet_topup',$5,'Wallet top-up approved')`,[w.id,t.user_id,t.amount,next,t.id]);const updated=(await client.query(`UPDATE wallet_topups SET status='approved',reviewed_by=$1,reviewed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=$2 RETURNING *`,[adminId,topupId])).rows[0];await client.query('COMMIT');return updated;}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}
async function rejectTopup({topupId,adminId}){const r=await pool.query(`UPDATE wallet_topups SET status='rejected',reviewed_by=$1,reviewed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=$2 AND status='pending' RETURNING *`,[adminId,topupId]);if(!r.rows[0])throw Object.assign(new Error('Pending top-up not found'),{code:'NOT_FOUND'});return r.rows[0]}
async function debitForLead(client,{userId,amount,leadPurchaseId}){const w=await ensureWallet(client,userId);const balance=Number(w.balance),value=Number(amount);if(balance<value)throw Object.assign(new Error('Insufficient wallet balance'),{code:'INSUFFICIENT_BALANCE'});const next=balance-value;await client.query(`UPDATE wallets SET balance=$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2`,[next,w.id]);await client.query(`INSERT INTO wallet_transactions(wallet_id,user_id,type,amount,balance_after,reference_type,reference_id,description) VALUES($1,$2,'debit',$3,$4,'lead_purchase',$5,'Lead purchase')`,[w.id,userId,value,next,leadPurchaseId]);return next}
module.exports={ensureWallet,getWallet,createTopup,approveTopup,rejectTopup,debitForLead};
