require('dotenv').config();
const express=require('express');
const cors=require('cors');
const pool=require('./config/database');
const industryRoutes=require('./routes/industryRoutes');
const serviceRoutes=require('./routes/serviceRoutes');
const subserviceRoutes=require('./routes/subserviceRoutes');
const stateRoutes=require('./routes/stateRoutes');
const cityRoutes=require('./routes/cityRoutes');
const subcityRoutes=require('./routes/subcityRoutes');
const pincodeRoutes=require('./routes/pincodeRoutes');
const cityService=require('./services/cityService');
const pincodeService=require('./services/pincodeService');
const authRoutes=require('./routes/authRoutes');
const profileRoutes=require('./routes/profileRoutes');
const adminRoutes=require('./routes/adminRoutes');
const leadRoutes=require('./routes/leadRoutes');
const paymentRoutes=require('./routes/paymentRoutes');
const membershipPlanRoutes=require('./routes/membershipPlanRoutes');
const adminCommercialRoutes=require('./routes/adminCommercialRoutes');
const walletRoutes=require('./routes/walletRoutes');
const investmentRoutes=require('./routes/investmentRoutes');
const boosterOrderRoutes=require('./routes/boosterOrderRoutes');
const app=express();
const PORT=process.env.PORT||5000;
const configuredOrigins=String(process.env.CORS_ORIGIN||'http://localhost:5173').split(',').map(x=>x.trim()).filter(Boolean);
const indiaPincodeSyncInterval=Number(process.env.INDIA_PINCODE_SYNC_INTERVAL_MS)||7*24*60*60*1000;
app.use(cors({origin(origin,callback){if(!origin||configuredOrigins.includes(origin))return callback(null,true);return callback(new Error('CORS origin not allowed'));}}));
app.use(express.json({limit:'10mb'}));
app.get('/health',async(req,res)=>{try{await pool.query('SELECT 1');res.json({status:'ok',database:'connected'});}catch(e){console.error(e.message);res.status(500).json({status:'error',database:'disconnected'});}});
app.use('/api/auth',authRoutes);
app.use('/api/profile',profileRoutes);
app.use('/api/admin',adminRoutes);
app.use('/api/leads',leadRoutes);
app.use('/api/payments',paymentRoutes);
app.use('/api/membership-plans',membershipPlanRoutes);
app.use('/api/admin/commercial',adminCommercialRoutes);
app.use('/api/wallet',walletRoutes);
app.use('/api/investments',investmentRoutes);
app.use('/api/booster-orders',boosterOrderRoutes);
app.use('/api/industries',industryRoutes);
app.use('/api/services',serviceRoutes);
app.use('/api/subservices',subserviceRoutes);
app.use('/api/states',stateRoutes);
app.use('/api/cities',cityRoutes);
app.use('/api/subcities',subcityRoutes);
app.use('/api/pincodes',pincodeRoutes);
app.use((req,res)=>res.status(404).json({error:'Not found'}));
app.use((err,req,res,next)=>{if(err.message==='CORS origin not allowed')return res.status(403).json({error:'Origin not allowed'});console.error('Unhandled server error:',err.message);return res.status(500).json({error:'Internal server error'});});
app.listen(PORT,'0.0.0.0',()=>{
  console.log(`Server running on port ${PORT}`);
  setTimeout(()=>cityService.syncPincodesBatch(20).catch(e=>console.error('Automatic pincode sync failed:',e.message)),10*60*1000);
  setInterval(()=>cityService.syncPincodesBatch(20).catch(e=>console.error('Automatic pincode sync failed:',e.message)),60*60*1000);
  setTimeout(()=>cityService.syncCoverageBatch(1).catch(e=>console.error('Automatic location coverage sync failed:',e.message)),30*60*1000);
  setInterval(()=>cityService.syncCoverageBatch(1).catch(e=>console.error('Automatic location coverage sync failed:',e.message)),6*60*60*1000);
  setTimeout(()=>pincodeService.syncAllIndiaPincodes().catch(e=>console.error('Automatic India pincode directory sync failed:',e.message)),20*60*1000);
  setInterval(()=>pincodeService.syncAllIndiaPincodes().catch(e=>console.error('Automatic India pincode directory sync failed:',e.message)),indiaPincodeSyncInterval);
});