const svc=require('../services/adminCommercialService');
async function investorSettings(req,res){try{res.json(await svc.getInvestorSettings())}catch(e){console.error(e);res.status(500).json({error:'Failed to load investor settings'})}}
async function updateInvestor(req,res){try{res.json(await svc.updateInvestorSettings(req.body))}catch(e){console.error(e);const status=e.code==='INVALID_LOCATION_CONFIG'||e.code==='INVALID_INVESTMENT_CONFIG'?400:500;res.status(status).json({error:e.message||'Failed to save investor settings',code:e.code})}}
async function coupons(req,res){try{res.json(await svc.getCoupons())}catch(e){res.status(500).json({error:'Failed to load coupons'})}}
async function createCoupon(req,res){try{res.status(201).json(await svc.createCoupon(req.body))}catch(e){console.error(e);res.status(500).json({error:e.code==='23505'?'Coupon code already exists':'Failed to create coupon'})}}
async function updateCoupon(id,d){return (await pool.query(`UPDATE coupons SET code=$1,discount_type=$2,discount_value=$3,max_discount=$4,min_order_amount=$5,usage_limit=$6,starts_at=$7,expires_at=$8,is_active=$9,updated_at=CURRENT_TIMESTAMP WHERE id=$10 RETURNING *`,[String(d.code).trim().toUpperCase(),d.discountType,Number(d.discountValue),d.maxDiscount===''?null:Number(d.maxDiscount),Number(d.minOrderAmount)||0,d.usageLimit===''||d.usageLimit==null?null:Number(d.usageLimit),d.startsAt||null,d.expiresAt||null,Boolean(d.isActive),id])).rows[0]||null;}
async function updateCoupon(req,res){try{const x=await svc.updateCoupon(req.params.id,req.body);if(!x)return res.status(404).json({error:'Coupon not found'});res.json(x)}catch(e){res.status(500).json({error:'Failed to update coupon'})}}
async function couponStatus(req,res){try{const x=await svc.setCouponStatus(req.params.id,Boolean(req.body.isActive));if(!x)return res.status(404).json({error:'Coupon not found'});res.json(x)}catch(e){res.status(500).json({error:'Failed to update coupon'})}}
async function deleteCoupon(req,res){try{const x=await svc.deleteCoupon(req.params.id);if(!x)return res.status(404).json({error:'Coupon not found'});res.json({message:'Coupon deleted'})}catch(e){res.status(500).json({error:'Failed to delete coupon'})}}
module.exports={investorSettings,updateInvestor,coupons,createCoupon,updateCoupon,couponStatus,deleteCoupon};
