const couponService=require('../services/couponService');
const {sendError}=require('../utils/errorResponse');

async function list(req,res){try{return res.json(await couponService.getAdminCoupons({search:req.query.search||'',status:req.query.status||'all'}))}catch(e){console.error('Coupon list failed:',e.message);return sendError(res,500,e,'Failed to fetch coupons')}}
async function details(req,res){try{const row=await couponService.getAdminCoupon(req.params.id);if(!row)return res.status(404).json({error:'Coupon not found'});return res.json(row)}catch(e){console.error('Coupon details failed:',e.message);return sendError(res,500,e,'Failed to fetch coupon')}}
async function create(req,res){try{return res.status(201).json(await couponService.createCoupon(req.body||{},req.user.id))}catch(e){const status=e.code==='DUPLICATE_COUPON'?409:e.code==='INVALID_COUPON'?400:500;if(status===500)console.error('Coupon create failed:',e.message);return sendError(res,status,e,'Failed to create coupon',{code:e.code})}}
async function update(req,res){try{return res.json(await couponService.updateCoupon(req.params.id,req.body||{}))}catch(e){const status=e.code==='NOT_FOUND'?404:e.code==='DUPLICATE_COUPON'?409:e.code==='INVALID_COUPON'?400:500;if(status===500)console.error('Coupon update failed:',e.message);return sendError(res,status,e,'Failed to update coupon',{code:e.code})}}
async function remove(req,res){try{return res.json(await couponService.deleteCoupon(req.params.id))}catch(e){const status=e.code==='NOT_FOUND'?404:e.code==='COUPON_HAS_REDEMPTIONS'?409:500;if(status===500)console.error('Coupon delete failed:',e.message);return sendError(res,status,e,'Failed to delete coupon',{code:e.code})}}
async function toggle(req,res){try{return res.json(await couponService.setCouponActive(req.params.id,req.body?.isActive))}catch(e){const status=e.code==='NOT_FOUND'?404:500;if(status===500)console.error('Coupon toggle failed:',e.message);return sendError(res,status,e,'Failed to update coupon',{code:e.code})}}
async function validate(req,res){try{return res.json(await couponService.validateForUser({userId:req.user.id,code:req.body?.code,subtotal:req.body?.subtotal,purchaseType:req.body?.purchaseType,industryId:req.body?.industryId,membershipPlanId:req.body?.membershipPlanId}))}catch(e){const clientCodes=['COUPON_NOT_FOUND','COUPON_INACTIVE','COUPON_NOT_STARTED','COUPON_EXPIRED','MIN_ORDER','PURCHASE_NOT_ELIGIBLE','PLAN_NOT_ELIGIBLE','USER_NOT_ELIGIBLE','INDUSTRY_NOT_ELIGIBLE','USAGE_LIMIT','USER_USAGE_LIMIT','INVALID_AMOUNT'];const status=clientCodes.includes(e.code)?400:500;if(status===500)console.error('Coupon validation failed:',e.message);return sendError(res,status,e,'Coupon validation failed',{code:e.code})}}
async function offers(req,res){try{return res.json(await couponService.getPublicOffersForUser({userId:req.user.id,purchaseType:String(req.query.purchaseType||''),subtotal:req.query.subtotal==null?null:req.query.subtotal,membershipPlanId:req.query.membershipPlanId||null,industryId:req.query.industryId||null}))}catch(e){console.error('Coupon offer list failed:',e.message);return sendError(res,500,e,'Failed to fetch available offers')}}
module.exports={list,details,create,update,remove,toggle,validate,offers};
