const pool = require('../config/database');
const cycleService = require('../services/investmentCycleService');
const cycleStatement = require('../services/investmentCycleStatementService');
const payoutRequests = require('../services/investorPayoutRequestService');
const investorCycleHistory = require('../services/investorCycleHistoryService');

async function current(req,res){try{const cycleData=await cycleService.getCycleSummary(Number(req.user.id),req.query.cycleId?Number(req.query.cycleId):null);if(!cycleData)return res.json({cycle:null});const cycleId=Number(cycleData.id);const [statement,funds]=await Promise.all([cycleStatement.getCycleStatement(Number(req.user.id),cycleId),payoutRequests.getInvestorFunds(Number(req.user.id),cycleId)]);return res.json({cycle:{...cycleData,...statement.cycle,principal:Number(statement.investment?.principal||cycleData.principal||0),investment_count:Number(statement.investment?.count||cycleData.investment_count||0),ad_spent:Number(statement.ads?.spent||0),gross_revenue:Number(statement.revenue?.gross_sales||0),investor_earnings:Number(statement.revenue?.investor_earnings||0),payout_transferred:Number(funds?.payout_transferred||0),payout_reserved:Number(funds?.payout_reserved||0),available_for_ads:Number(funds?.available_for_ads||0),withdrawable_earnings:Number(funds?.withdrawable_earnings||0),transferable:Number(funds?.transferable||0),total_invested:Number(funds?.total_invested||statement.investment?.principal||0),generated:Number(funds?.generated||statement.revenue?.investor_earnings||0),single_share_sales:Number(statement.leads?.single_share_sales||0),shared_sales:Number(statement.leads?.shared_sales||0),shares_sold:Number(statement.leads?.shares_sold||0),sold_leads:Number(statement.leads?.sold||0),pending_leads:Number(statement.leads?.pending||0)}});}catch(e){console.error('Investment cycle load failed:',e.message);return res.status(500).json({error:'Failed to load investment cycle'});}}
async function investorList(req,res){try{return res.json(await investorCycleHistory.list(Number(req.user.id)));}catch(e){console.error('Investor cycle history load failed:',e);return res.status(500).json({error:'Failed to load investment cycles'});}}
async function investorStatement(req,res){try{const cycleId=Number(req.params.cycleId);if(!Number.isInteger(cycleId)||cycleId<=0)return res.status(400).json({error:'Invalid cycle'});return res.json(await investorCycleHistory.getCycleHistory(Number(req.user.id),cycleId));}catch(e){const map={INVALID_CYCLE:400,CYCLE_NOT_FOUND:404};return res.status(map[e.code]||500).json({error:e.message||'Failed to load cycle history',code:e.code});}}
async function requestFinalExit(req,res){try{return res.json(await cycleService.requestFinalExit({userId:Number(req.user.id),cycleId:req.body?.cycleId?Number(req.body.cycleId):null}));}catch(e){const map={CYCLE_NOT_FOUND:404,CYCLE_ALREADY_CLOSED:409,CYCLE_NOT_MATURED:400,CYCLE_CLOSING:409};return res.status(map[e.code]||400).json({error:e.message||'Failed to request cycle exit',code:e.code});}}
async function adminList(req,res){try{return res.json(await cycleService.adminList());}catch(e){console.error('Admin investment cycles load failed:',e);return res.status(500).json({error:'Failed to load investment cycles'});}}
async function adminStatement(req,res){try{const userId=Number(req.params.userId),cycleId=Number(req.params.cycleId);if(!Number.isInteger(userId)||userId<=0||!Number.isInteger(cycleId)||cycleId<=0)return res.status(400).json({error:'Invalid investor or cycle'});return res.json(await cycleService.adminCycleStatement({userId,cycleId}));}catch(e){return res.status(e.code==='CYCLE_NOT_FOUND'?404:500).json({error:e.message||'Failed to load cycle statement',code:e.code});}}
async function adminFinish(req,res){try{return res.json(await cycleService.adminFinishCycle({cycleId:Number(req.params.id),adminId:Number(req.user.id),reason:req.body?.reason}));}catch(e){const map={CYCLE_NOT_FOUND:404,CYCLE_ALREADY_CLOSED:409,REASON_REQUIRED:400,REASON_TOO_LONG:400,LEADS_NOT_FINAL:409};return res.status(map[e.code]||500).json({error:e.message||'Failed to finish investment cycle',code:e.code});}}
async function adminClose(req,res){try{return res.json(await cycleService.adminCloseCycle({cycleId:Number(req.params.id)}));}catch(e){const map={CYCLE_NOT_FOUND:404,CYCLE_ALREADY_CLOSED:409,CYCLE_NOT_ELIGIBLE:409};return res.status(map[e.code]||500).json({error:e.message||'Failed to close investment cycle',code:e.code});}}
module.exports={current,investorList,investorStatement,requestFinalExit,adminList,adminStatement,adminFinish,adminClose};
