const { sendError } = require('../utils/errorResponse');
const {sendProofDescriptor}=require('../utils/proofResponse');
const pool = require('../config/database');
const service = require('../services/investmentService');
const adminOps = require('../services/investorAdminOperationsService');
const managedAdSpend = require('../services/managedInvestorAdSpendService');
const investorLinkedLeads = require('../services/investorLinkedLeadService');
const payoutRequests = require('../services/investorPayoutRequestService');
const adminInvestorTransfer = require('../services/adminInvestorTransferService');
const cycleStatement = require('../services/investmentCycleStatementService');
const investorCycleHistory = require('../services/investorCycleHistoryService');
function booleanValue(value){return value===true||['true','1','on','yes'].includes(String(value??'').trim().toLowerCase())}
async function setPreference(investmentId,userId,enabled){if(!investmentId)return;await pool.query('UPDATE investments SET reinvestment_enabled=$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2 AND user_id=$3',[booleanValue(enabled),Number(investmentId),Number(userId)])}
async function access(req,res){try{return res.json(await service.getInvestmentAccess(req.user.id))}catch(e){console.error('Investment access failed:',e.message);return res.status(500).json({error:'Failed to load investment access'})}}
async function rules(req,res){try{return res.json(await service.getRules())}catch(e){return res.status(500).json({error:'Failed to load investment rules'})}}
async function locationRules(req,res){try{return res.json(await service.getLocationRules())}catch(e){return res.status(500).json({error:'Failed to load investment location rules'})}}
async function create(req,res){try{const reinvestmentEnabled=booleanValue(req.body.reinvestmentEnabled);const result=await service.createInvestment({userId:req.user.id,industryId:Number(req.body.industryId),stateId:req.body.stateId==null||req.body.stateId===''?null:Number(req.body.stateId),cityId:req.body.cityId==null||req.body.cityId===''?null:Number(req.body.cityId),amount:req.body.amount,reinvestmentEnabled});await setPreference(result.id,req.user.id,reinvestmentEnabled);return res.status(201).json({...result,reinvestment_enabled:reinvestmentEnabled})}catch(e){const map={PRO_REQUIRED:403,INVESTMENT_DISABLED:403,AMOUNT_OUT_OF_RANGE:400,MAXIMUM_CAPITAL_REACHED:400,INDUSTRY_UNAVAILABLE:400,INDUSTRY_LIMIT_REACHED:400,LOCATION_REQUIRED:400,LOCATION_UNAVAILABLE:400,LOCATION_CAPACITY_REACHED:409,INSUFFICIENT_BALANCE:400,ACTIVE_CYCLE_EXISTS:409,CYCLE_CLOSING:409,CYCLE_MODE_MISMATCH:400};return sendError(res,map[e.code]||400,e,'Investment request failed',{code:e.code});}}
async function checkout(req,res){try{const reinvestmentEnabled=booleanValue(req.body.reinvestmentEnabled);const result=await service.createInvestmentCheckout({userId:req.user.id,industryId:Number(req.body.industryId),stateId:req.body.stateId==null||req.body.stateId===''?null:Number(req.body.stateId),cityId:req.body.cityId==null||req.body.cityId===''?null:Number(req.body.cityId),amount:req.body.amount,useWallet:req.body.useWallet!==false,reinvestmentEnabled});await setPreference(result.investment?.id,req.user.id,reinvestmentEnabled);if(result.investment)result.investment.reinvestment_enabled=reinvestmentEnabled;return res.status(201).json({...result,reinvestmentEnabled})}catch(e){const map={PRO_REQUIRED:403,INVESTMENT_DISABLED:403,AMOUNT_OUT_OF_RANGE:400,MAXIMUM_CAPITAL_REACHED:400,INDUSTRY_UNAVAILABLE:400,INDUSTRY_LIMIT_REACHED:400,LOCATION_REQUIRED:400,LOCATION_UNAVAILABLE:400,LOCATION_CAPACITY_REACHED:409,INSUFFICIENT_BALANCE:400,PAYMENT_PENDING:409,INVALID_AMOUNT:400,ACTIVE_CYCLE_EXISTS:409,CYCLE_CLOSING:409,CYCLE_MODE_MISMATCH:400};return sendError(res,map[e.code]||400,e,'Investment request failed',{code:e.code});}}
async function mine(req,res){try{const cycleId=req.query?.cycleId==null||req.query?.cycleId===''?null:Number(req.query.cycleId);const investments=await service.getMyInvestments(req.user.id,{cycleId:Number.isInteger(cycleId)&&cycleId>0?cycleId:null});return res.json(investments.filter(item=>String(item.status).toLowerCase()!=='cancelled'))}catch(e){console.error('Investor investments load failed:',e.message);return sendError(res,500,e,'Failed to load investments')}}
async function linkedInvestorLeads(req,res){try{return res.json(await investorLinkedLeads.getLinkedLeads({investorId:Number(req.user.id),page:req.query?.page||1,limit:req.query?.limit||30,availability:'available'}))}catch(e){console.error('Investor linked leads failed:',e);return res.status(500).json({error:'Failed to load investor leads'})}}
async function soldLeads(req,res){try{return res.json(await investorLinkedLeads.getLinkedLeads({investorId:Number(req.user.id),page:req.query?.page||1,limit:req.query?.limit||30,availability:'sold'}))}catch(e){return res.status(500).json({error:'Failed to load investor sold leads'})}}
async function linkedLeads(req,res){try{return res.json(await investorLinkedLeads.getLinkedLeads({investorId:Number(req.params.userId),page:req.query?.page||1,limit:req.query?.limit||50}))}catch(e){console.error('Admin investor linked leads failed:',e.message);return sendError(res,500,e,'Failed to load linked leads')}}
async function reinvest(req,res){try{return res.status(201).json(await service.reinvestInvestment({userId:req.user.id,investmentId:Number(req.params.id)}))}catch(e){const map={NOT_FOUND:404,NOT_SETTLED:400,CYCLE_NOT_CLOSED:409,REINVESTMENT_DISABLED:400,NO_REALIZED_AMOUNT:400,REINVESTMENT_EXISTS:409,INDUSTRY_UNAVAILABLE:400,LOCATION_UNAVAILABLE:400,LOCATION_CAPACITY_REACHED:409,REINVESTMENT_ABOVE_MAXIMUM:400};return sendError(res,map[e.code]||400,e,'Investment request failed',{code:e.code});}}
async function adminList(req,res){try{return res.json(await service.adminList())}catch(e){return res.status(500).json({error:'Failed to load investments'})}}
async function updateAdAmount(req,res){try{return res.json(await adminOps.updateAdAmount({investmentId:Number(req.params.id),amount:req.body.amount,adminId:req.user.id}))}catch(e){const map={NOT_FOUND:404,CANCELLED:400,INVALID_AMOUNT:400,AMOUNT_EXCEEDS_INVESTMENT:400,ALLOCATION_BELOW_SPEND:400,AMOUNT_EXCEEDS_AVAILABLE_AD_FUNDS:400};return sendError(res,map[e.code]||500,e,'Failed to update amount in ads',{code:e.code});}}
async function getAdSpend(req,res){try{return res.json(await adminOps.getAdSpend({investmentId:Number(req.params.id)}))}catch(e){return sendError(res,e.code==='NOT_FOUND'?404:500,e,'Failed to load ad spending',{code:e.code});}}
async function getPayoutProof(req,res){try{return res.json(await adminOps.getPayoutProof({investmentId:Number(req.params.id)}))}catch(e){return sendError(res,e.code==='NOT_FOUND'?404:500,e,'Failed to load payout proof',{code:e.code});}}
async function recordAdSpend(req,res){try{return res.status(201).json(await managedAdSpend.recordSpendForInvestment({investmentId:Number(req.params.id),amount:req.body.amount,platform:req.body.platform,campaign:req.body.campaign,spendDate:req.body.spendDate,reference:req.body.reference,notes:req.body.notes,adminId:req.user.id}))}catch(e){const map={NOT_FOUND:404,CANCELLED:400,INVALID_SPEND_AMOUNT:400,NO_ACTIVE_INVESTMENT:400,NO_AD_ALLOCATION:400,SPEND_EXCEEDS_ALLOCATION:400,SPEND_EXCEEDS_AVAILABLE_AD_FUNDS:400};return sendError(res,map[e.code]||500,e,'Failed to record ad spending',{code:e.code});}}
async function payout(req,res){try{if(booleanValue(req.body.transferAll))return res.json(await adminInvestorTransfer.transferInvestorEarnings({userId:Number(req.params.id),adminId:req.user.id,transferReference:req.body.transferReference,proofUrl:req.body.proofUrl}));return res.json(await adminOps.payout({investmentId:Number(req.params.id),adminId:req.user.id,transferReference:req.body.transferReference,proofUrl:req.body.proofUrl,forceTransfer:booleanValue(req.body.forceTransfer)}))}catch(e){const map={NOT_FOUND:404,ALREADY_PAID:409,CANCELLED:400,NOT_MATURED:400,NO_REALIZED_AMOUNT:400,NO_TRANSFERABLE_EARNINGS:400,INDUSTRY_UNAVAILABLE:400,LOCATION_REQUIRED:400,LOCATION_UNAVAILABLE:400,LOCATION_CAPACITY_REACHED:409,TRANSFER_REFERENCE_REQUIRED:400,TRANSFER_PROOF_REQUIRED:400,DUPLICATE_TRANSFER_REFERENCE:409,DUPLICATE_REFERENCE:409,PAYOUT_ACCOUNT_REQUIRED:400,REINVESTMENT_EXISTS:409,REINVESTMENT_ABOVE_MAXIMUM:400};return sendError(res,map[e.code]||500,e,'Failed to settle investor return',{code:e.code});}}
async function adminTransferInvestorEarnings(req,res){try{return res.json(await adminInvestorTransfer.transferInvestorEarnings({userId:Number(req.params.userId),adminId:req.user.id,transferReference:req.body.transferReference,proofUrl:req.body.proofUrl}))}catch(e){const map={TRANSFER_REFERENCE_REQUIRED:400,TRANSFER_PROOF_REQUIRED:400,PAYOUT_ACCOUNT_REQUIRED:400,DUPLICATE_TRANSFER_REFERENCE:409,NO_TRANSFERABLE_EARNINGS:400};return sendError(res,map[e.code]||500,e,'Failed to transfer investor earnings',{code:e.code});}}
async function investorFunds(req,res){try{const cycleId=req.query.cycleId==null||req.query.cycleId===''?null:Number(req.query.cycleId);return res.json(await payoutRequests.getInvestorFunds(req.user.id,Number.isInteger(cycleId)&&cycleId>0?cycleId:null))}catch(e){console.error('Investor funds failed:',e.message);return res.status(500).json({error:'Failed to load investor funds'})}}
async function requestInvestorTransfer(req,res){try{return res.status(201).json(await payoutRequests.requestTransfer({userId:req.user.id,amount:req.body.amount,notes:req.body.notes,withdrawalType:req.body.withdrawalType||'PARTIAL'}))}catch(e){const map={INVALID_AMOUNT:400,INSUFFICIENT_GENERATED_FUNDS:400,PAYOUT_ACCOUNT_REQUIRED:400,CYCLE_NOT_FOUND:409,INVALID_WITHDRAWAL_TYPE:400,CYCLE_CLOSING:409};return sendError(res,map[e.code]||500,e,'Failed to create withdrawal request',{code:e.code});}}
async function adminInvestorTransferRequests(req,res){try{return res.json(await payoutRequests.adminList({status:req.query.status||'all',search:req.query.search||'',page:req.query.page,limit:req.query.limit}))}catch(e){return sendError(res,e.code==='INVALID_STATUS'?400:500,e,'Failed to load investor transfer requests',{code:e.code})}}
async function adminInvestorTransferProof(req,res){try{return res.json(await payoutRequests.getAdminProof(Number(req.params.id)))}catch(e){return sendError(res,e.code==='NOT_FOUND'?404:500,e,'Failed to load transfer proof',{code:e.code})}}
async function adminInvestorTransferProofFile(req,res){try{return sendProofDescriptor(res,await payoutRequests.getAdminProofDescriptor(Number(req.params.id)))}catch(e){return sendError(res,e.code==='NOT_FOUND'?404:500,e,'Failed to stream transfer proof',{code:e.code})}}
async function adminProcessInvestorTransfer(req,res){try{return res.json(await payoutRequests.adminProcess({requestId:req.params.id,adminId:req.user.id,action:req.body.action,transferReference:req.body.transferReference,proofUrl:req.body.proofUrl,notes:req.body.notes}))}catch(e){const map={NOT_FOUND:404,ALREADY_PROCESSED:409,INVALID_ACTION:400,TRANSFER_REFERENCE_REQUIRED:400,TRANSFER_PROOF_REQUIRED:400,TRANSFER_PROOF_TOO_LARGE:400,INVALID_TRANSFER_PROOF:400,DUPLICATE_REFERENCE:409,INSUFFICIENT_GENERATED_FUNDS:400};return sendError(res,map[e.code]||500,e,'Failed to process investor transfer',{code:e.code});}}
async function adminCycleStatement(req,res){try{return res.json(await cycleStatement.getCycleStatement(Number(req.params.userId),Number(req.params.cycleId)))}catch(e){const map={INVALID_CYCLE:400,CYCLE_NOT_FOUND:404};return sendError(res,map[e.code]||500,e,'Failed to load cycle statement',{code:e.code});}}
async function adminCycleHistory(req,res){try{return res.json(await investorCycleHistory.getCycleHistory(Number(req.params.userId),Number(req.params.cycleId)))}catch(e){console.error('Admin cycle history failed:',e);const map={INVALID_CYCLE:400,CYCLE_NOT_FOUND:404};return sendError(res,map[e.code]||500,e,'Failed to load cycle history',{code:e.code})}}
module.exports={access,rules,locationRules,create,checkout,mine,linkedInvestorLeads,soldLeads,linkedLeads,reinvest,adminList,updateAdAmount,getAdSpend,getPayoutProof,recordAdSpend,payout,adminTransferInvestorEarnings,investorFunds,requestInvestorTransfer,adminInvestorTransferRequests,adminInvestorTransferProof,adminInvestorTransferProofFile,adminProcessInvestorTransfer,adminCycleStatement,adminCycleHistory};