const pool = require('../config/database');
const service = require('../services/investmentService');
const adminOps = require('../services/investorAdminOperationsService');
const investorLinkedLeads = require('../services/investorLinkedLeadService');
const payoutRequests = require('../services/investorPayoutRequestService');

async function setPreference(investmentId,userId,enabled){if(!investmentId)return;await pool.query(`UPDATE investments SET reinvestment_enabled=$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2 AND user_id=$3`,[Boolean(enabled),Number(investmentId),Number(userId)])}
async function access(req,res){try{return res.json(await service.getInvestmentAccess(req.user.id))}catch(e){console.error('Investment access failed:',e.message);return res.status(500).json({error:'Failed to load investment access'})}}
async function rules(req,res){try{return res.json(await service.getRules())}catch(e){return res.status(500).json({error:'Failed to load investment rules'})}}
async function locationRules(req,res){try{return res.json(await service.getLocationRules())}catch(e){return res.status(500).json({error:'Failed to load investment location rules'})}}
async function create(req,res){try{const result=await service.createInvestment({userId:req.user.id,industryId:Number(req.body.industryId),stateId:req.body.stateId==null||req.body.stateId===''?null:Number(req.body.stateId),cityId:req.body.cityId==null||req.body.cityId===''?null:Number(req.body.cityId),amount:req.body.amount});await setPreference(result.id,req.user.id,req.body.reinvestmentEnabled===true);return res.status(201).json({...result,reinvestment_enabled:req.body.reinvestmentEnabled===true})}catch(e){const map={PRO_REQUIRED:403,INVESTMENT_DISABLED:403,AMOUNT_OUT_OF_RANGE:400,INDUSTRY_UNAVAILABLE:400,INDUSTRY_LIMIT_REACHED:400,LOCATION_REQUIRED:400,LOCATION_UNAVAILABLE:400,LOCATION_CAPACITY_REACHED:409,INSUFFICIENT_BALANCE:400};return res.status(map[e.code]||400).json({error:e.message,code:e.code})}}
async function checkout(req,res){try{const result=await service.createInvestmentCheckout({userId:req.user.id,industryId:Number(req.body.industryId),stateId:req.body.stateId==null||req.body.stateId===''?null:Number(req.body.stateId),cityId:req.body.cityId==null||req.body.cityId===''?null:Number(req.body.cityId),amount:req.body.amount,useWallet:req.body.useWallet!==false});await setPreference(result.investment?.id,req.user.id,req.body.reinvestmentEnabled===true);if(result.investment)result.investment.reinvestment_enabled=req.body.reinvestmentEnabled===true;return res.status(201).json({...result,reinvestmentEnabled:req.body.reinvestmentEnabled===true})}catch(e){const map={PRO_REQUIRED:403,INVESTMENT_DISABLED:403,AMOUNT_OUT_OF_RANGE:400,INDUSTRY_UNAVAILABLE:400,INDUSTRY_LIMIT_REACHED:400,LOCATION_REQUIRED:400,LOCATION_UNAVAILABLE:400,LOCATION_CAPACITY_REACHED:409,INSUFFICIENT_BALANCE:400,PAYMENT_PENDING:409,INVALID_AMOUNT:400};return res.status(map[e.code]||400).json({error:e.message,code:e.code})}}
async function mine(req,res){try{const investments=await service.getMyInvestments(req.user.id);return res.json(investments.filter(item=>String(item.status).toLowerCase()!=='cancelled'))}catch(e){return res.status(500).json({error:'Failed to load investments'})}}
async function linkedInvestorLeads(req,res){try{return res.json(await investorLinkedLeads.getLinkedLeads({investorId:Number(req.user.id)}))}catch(e){console.error('Investor linked leads failed:',e);return res.status(500).json({error:'Failed to load investor leads'})}}
async function soldLeads(req,res){try{const leads=await investorLinkedLeads.getLinkedLeads({investorId:Number(req.user.id)});return res.json(leads.filter(lead=>Number(lead.purchased_buyer_count||0)>=Number(lead.buyer_capacity||1)))}catch(e){return res.status(500).json({error:'Failed to load investor sold leads'})}}
async function linkedLeads(req,res){try{return res.json(await investorLinkedLeads.getLinkedLeads({investorId:Number(req.params.userId)}))}catch(e){return res.status(500).json({error:'Failed to load linked leads'})}}
async function reinvest(req,res){try{return res.status(201).json(await service.reinvestInvestment({userId:req.user.id,investmentId:Number(req.params.id)}))}catch(e){const map={NOT_FOUND:404,NOT_SETTLED:400,REINVESTMENT_DISABLED:400,NO_REALIZED_AMOUNT:400,REINVESTMENT_EXISTS:409,INDUSTRY_UNAVAILABLE:400,REINVESTMENT_ABOVE_MAXIMUM:400,LOCATION_UNAVAILABLE:400,LOCATION_CAPACITY_REACHED:409};return res.status(map[e.code]||400).json({error:e.message,code:e.code})}}
async function adminList(req,res){try{return res.json(await service.adminList())}catch(e){return res.status(500).json({error:'Failed to load investments'})}}
async function updateAdAmount(req,res){try{return res.json(await adminOps.updateAdAmount({investmentId:Number(req.params.id),amount:req.body.amount,adminId:req.user.id}))}catch(e){const map={NOT_FOUND:404,CANCELLED:400,INVALID_AMOUNT:400,AMOUNT_EXCEEDS_INVESTMENT:400,ALLOCATION_BELOW_SPEND:400,AMOUNT_EXCEEDS_AVAILABLE_AD_FUNDS:400};return res.status(map[e.code]||500).json({error:e.message||'Failed to update amount in ads',code:e.code})}}
async function getAdSpend(req,res){try{return res.json(await adminOps.getAdSpend({investmentId:Number(req.params.id)}))}catch(e){return res.status(e.code==='NOT_FOUND'?404:500).json({error:e.message||'Failed to load ad spending'})}}
async function recordAdSpend(req,res){try{return res.status(201).json(await adminOps.recordAdSpend({investmentId:Number(req.params.id),amount:req.body.amount,platform:req.body.platform,campaign:req.body.campaign,spendDate:req.body.spendDate,reference:req.body.reference,notes:req.body.notes,adminId:req.user.id}))}catch(e){const map={NOT_FOUND:404,CANCELLED:400,INVALID_SPEND_AMOUNT:400,NO_AD_ALLOCATION:400,SPEND_EXCEEDS_ALLOCATION:400};return res.status(map[e.code]||500).json({error:e.message||'Failed to record ad spend',code:e.code})}}
async function payout(req,res){try{return res.json(await adminOps.payout({investmentId:Number(req.params.id),adminId:req.user.id,transferReference:req.body.transferReference,proofUrl:req.body.proofUrl}))}catch(e){const map={NOT_FOUND:404,ALREADY_PAID:409,CANCELLED:400,NOT_MATURED:400,NO_REALIZED_AMOUNT:400,INDUSTRY_UNAVAILABLE:400,LOCATION_REQUIRED:400,LOCATION_UNAVAILABLE:400,LOCATION_CAPACITY_REACHED:409,TRANSFER_REFERENCE_REQUIRED:400,TRANSFER_PROOF_REQUIRED:400,DUPLICATE_TRANSFER_REFERENCE:409,REINVESTMENT_EXISTS:409,REINVESTMENT_ABOVE_MAXIMUM:400};return res.status(map[e.code]||500).json({error:e.message||'Failed to settle investor return',code:e.code})}}
async function investorFunds(req,res){try{return res.json(await payoutRequests.getInvestorFunds(req.user.id))}catch(e){console.error('Investor funds failed:',e.message);return res.status(500).json({error:'Failed to load investor funds'})}}
async function requestInvestorTransfer(req,res){try{return res.status(201).json(await payoutRequests.requestTransfer({userId:req.user.id,amount:req.body.amount,notes:req.body.notes}))}catch(e){const map={INVALID_AMOUNT:400,INSUFFICIENT_GENERATED_FUNDS:400};return res.status(map[e.code]||500).json({error:e.message||'Failed to create transfer request',code:e.code})}}
async function adminInvestorTransferRequests(req,res){try{return res.json(await payoutRequests.adminList({status:req.query.status||'all',search:req.query.search||''}))}catch(e){return res.status(500).json({error:e.message||'Failed to load investor transfer requests'})}}
async function adminProcessInvestorTransfer(req,res){try{return res.json(await payoutRequests.adminProcess({requestId:req.params.id,adminId:req.user.id,action:req.body.action,transferReference:req.body.transferReference,proofUrl:req.body.proofUrl,notes:req.body.notes}))}catch(e){const map={NOT_FOUND:404,ALREADY_PROCESSED:409,TRANSFER_REFERENCE_REQUIRED:400,TRANSFER_PROOF_REQUIRED:400,DUPLICATE_REFERENCE:409,INSUFFICIENT_GENERATED_FUNDS:400};return res.status(map[e.code]||500).json({error:e.message||'Failed to process investor transfer'})}}
module.exports={access,rules,locationRules,create,checkout,mine,linkedInvestorLeads,soldLeads,linkedLeads,reinvest,adminList,updateAdAmount,getAdSpend,recordAdSpend,payout,investorFunds,requestInvestorTransfer,adminInvestorTransferRequests,adminProcessInvestorTransfer};
