const { sendError } = require('../utils/errorResponse');
const leadPartnerService = require('../services/leadPartnerService');
const pricingService = require('../services/leadPartnerPricingService');
const payoutAccountService = require('../services/leadPartnerPayoutAccountService');
const earningsService = require('../services/leadPartnerEarningsService');
const payoutService = require('../services/leadPartnerPayoutService');
const leadReportService = require('../services/leadReportService');
async function dashboard(req,res){try{return res.json(await leadPartnerService.getDashboard(req.user.id,req.query?.period));}catch(e){return res.status(500).json({error:'Failed to load Lead Partner dashboard'});}}
async function apply(req,res){try{return res.status(201).json(await leadPartnerService.apply(req.user.id));}catch(e){return sendError(res,500,e,'Failed to process Lead Partner request');}}
async function me(req,res){try{return res.json(await leadPartnerService.getPartnerByUserId(req.user.id));}catch(e){return res.status(500).json({error:'Failed to load Lead Partner profile'});}}
async function createLead(req,res){try{return res.status(201).json(await leadPartnerService.createLead({userId:req.user.id,...(req.body||{})}));}catch(e){const s=['PARTNER_NOT_FOUND','PARTNER_NOT_ACTIVE'].includes(e.code)?403:400;return sendError(res,s,e,'Lead Partner request failed',{code:e.code});}}
async function myLeads(req,res){try{return res.json(await leadPartnerService.getMyLeads(req.user.id,req.query||{}));}catch(e){const s=['PARTNER_NOT_FOUND','PARTNER_NOT_ACTIVE'].includes(e.code)?403:500;return sendError(res,s,e,'Lead Partner request failed',{code:e.code});}}
async function adminPartners(req,res){try{return res.json(await leadPartnerService.getAdminPartners(req.query||{}));}catch(e){return res.status(500).json({error:'Failed to load Lead Partners'});}}
async function adminPartnerFinancials(req,res){try{return res.json(await earningsService.getAdminPartnerFinancials(req.params.partnerId));}catch(e){return sendError(res,e.code==='PARTNER_NOT_FOUND'?404:500,e,'Failed to load Lead Partner financials',{code:e.code});}}
async function adminUpdateStatus(req,res){try{return res.json(await leadPartnerService.updateStatus(req.params.partnerId,req.body?.status));}catch(e){return sendError(res,e.code==='PARTNER_NOT_FOUND'?404:400,e,'Failed to update Lead Partner status',{code:e.code});}}
async function pricing(req,res){try{return res.json(await pricingService.list(req.user.id,req.query||{}));}catch(e){return res.status(500).json({error:'Failed to load partner pricing'});}}
async function savePricingRule(req,res){try{return res.json(await pricingService.saveRule(req.user.id,{...(req.body||{}),id:req.params.ruleId}));}catch(e){return sendError(res,500,e,'Failed to process Lead Partner request');}}
async function createPricingRule(req,res){try{return res.status(201).json(await pricingService.saveRule(req.user.id,req.body||{}));}catch(e){return sendError(res,500,e,'Failed to process Lead Partner request');}}
async function deletePricingRule(req,res){try{return res.json(await pricingService.deleteRule(req.user.id,req.params.ruleId));}catch(e){return sendError(res,400,e,'Lead Partner request failed',{code:e.code});}}
async function updatePricing(req,res){try{return res.json(await pricingService.update(req.user.id,req.params.leadId,req.body||{}));}catch(e){return sendError(res,500,e,'Failed to process Lead Partner request');}}
async function payoutAccount(req,res){try{return res.json(await payoutAccountService.get(req.user.id));}catch(e){return res.status(500).json({error:'Failed to load payout account'});}}
async function savePayoutAccount(req,res){try{return res.json(await payoutAccountService.save({userId:req.user.id,...(req.body||{}),ifscCode:String(req.body?.ifscCode||'').toUpperCase()}));}catch(e){return res.status(e.code==='INVALID_PARTNER_PAYOUT_ACCOUNT'?400:500).json({error:e.message,code:e.code});}}
async function funds(req,res){try{return res.json(await payoutService.getFunds(req.user.id));}catch(e){const s=['PARTNER_NOT_FOUND','PARTNER_NOT_ACTIVE'].includes(e.code)?403:500;return sendError(res,s,e,'Lead Partner request failed',{code:e.code});}}
async function requestWithdrawal(req,res){try{return res.status(201).json(await payoutService.requestWithdrawal({userId:req.user.id,amount:req.body?.amount,notes:req.body?.notes}));}catch(e){const s=['INVALID_AMOUNT','PAYOUT_ACCOUNT_REQUIRED','INSUFFICIENT_FUNDS'].includes(e.code)?400:['PARTNER_NOT_FOUND','PARTNER_NOT_ACTIVE'].includes(e.code)?403:500;return sendError(res,s,e,'Lead Partner request failed',{code:e.code});}}async function transactions(req,res){try{return res.json(await payoutService.getTransactions(req.user.id));}catch(e){const s=['PARTNER_NOT_FOUND','PARTNER_NOT_ACTIVE'].includes(e.code)?403:500;return res.status(s).json({error:e.message||'Failed to load transaction history',code:e.code});}}
async function reports(req,res){try{return res.json(await leadReportService.getLeadPartnerReports(req.user.id))}catch(e){const s=['PARTNER_NOT_FOUND','PARTNER_NOT_ACTIVE'].includes(e.code)?403:500;return res.status(s).json({error:e.message||'Failed to load Lead Partner reports',code:e.code})}}
async function adminPayouts(req,res){try{return res.json(await payoutService.adminList(req.query||{}));}catch(e){return res.status(500).json({error:'Failed to load Lead Partner payouts'});}}
async function adminProcessPayout(req,res){try{return res.json(await payoutService.adminProcess({requestId:req.params.payoutId,adminId:req.user.id,action:req.body?.action,transferReference:req.body?.transferReference,proofUrl:req.body?.proofUrl,rejectionReason:req.body?.rejectionReason,notes:req.body?.notes}));}catch(e){const bad=['ALREADY_PROCESSED','INVALID_ACTION','TRANSFER_REFERENCE_REQUIRED','INVALID_TRANSFER_PROOF','TRANSFER_PROOF_REQUIRED','TRANSFER_PROOF_TOO_LARGE','DUPLICATE_REFERENCE','PAYOUT_ALLOCATION_MISMATCH'].includes(e.code);return sendError(res,e.code==='NOT_FOUND'?404:bad?400:500,e,'Failed to process Lead Partner payout',{code:e.code});}}
module.exports={dashboard,apply,me,createLead,myLeads,adminPartners,adminPartnerFinancials,adminUpdateStatus,pricing,createPricingRule,savePricingRule,deletePricingRule,updatePricing,payoutAccount,savePayoutAccount,funds,requestWithdrawal,adminPayouts,adminProcessPayout,transactions,reports};
