const pool=require('../config/database');
const leadService=require('../services/leadService');
const leadMarketplaceService=require('../services/leadMarketplaceService');
const leadInvestorService=require('../services/leadInvestorService');
const {fetchGoogleSheetCsv}=require('../services/googleSheetService');
const {appendAdminDynamicDetails}=require('../services/leadReadService');
const {resolvePincode}=require('../services/pincodeService');
const leadPurchaseService=require('../services/leadPurchaseService');
const VALID_STATUSES=['available','paused','sold','closed','invalid'];
const requirePincode=async body=>{const value=String(body?.pincode??body?.zipcode??'').trim();if(/^\d{6}$/.test(value))return value;const custom=body?.customFields&&typeof body.customFields==='object'?body.customFields:{};const location=body?.location??body?.Location??custom.location??custom.Location??custom.area??custom.Area??custom.locality??custom.Locality??custom.postOffice??custom['Post Office']??'';const district=body?.district??body?.District??custom.district??custom.District??'';const resolved=await resolvePincode({stateId:body?.stateId,cityId:body?.cityId,district,location});if(resolved?.pincode)return resolved.pincode;throw new Error('Pincode is required and must be a valid 6-digit Indian PIN, or a matching location must be provided');};
async function createLead(req,res){try{const pincode=await requirePincode(req.body);await leadInvestorService.assertInvestorLink({investorUserId:req.body.investorUserId,industryId:req.body.industryId});const lead=await leadService.createLead({...req.body,pincode,createdBy:req.user?.id});if(req.body.investorUserId!==undefined)await leadInvestorService.setInvestorLink(lead.id,req.body.investorUserId);return res.status(201).json({...lead,investor_user_id:req.body.investorUserId?Number(req.body.investorUserId):null})}catch(error){console.error('Create lead failed:',error.message);const message=String(error?.message||'');if(error.code==='DUPLICATE_LEAD'||error.code==='23505')return res.status(409).json({error:error.message||'Duplicate lead',code:'DUPLICATE_LEAD',leadId:error.leadId});if(message==='Industry is required'||message.startsWith('Pincode is required')||message==='Selected investor has no active investment in this industry')return res.status(400).json({error:error.message});return res.status(500).json({error:'Failed to create lead'})}}
async function getLeads(req,res){try{if(req.user?.role==='admin'){const leads=await leadService.getLeads({...req.query,status:req.query.status||'available',userId:req.user.id,role:req.user.role});return res.json(Array.isArray(leads)?leads.map(appendAdminDynamicDetails):leads)}return res.json(await leadMarketplaceService.getMarketplacePage({...req.query,status:req.query.status||'available',userId:req.user?.id,role:req.user?.role,page:req.query.page,limit:req.query.limit}))}catch(error){console.error('Get leads failed:',error.message);return res.status(500).json({error:'Failed to fetch leads'})}}
async function getInvestors(req,res){try{return res.json(await leadInvestorService.getInvestors())}catch(error){return res.status(500).json({error:'Failed to fetch investors'})}}
async function previewGoogleSheet(req,res){try{if(!req.body?.url)return res.status(400).json({error:'Google Sheets URL is required'});return res.json(await fetchGoogleSheetCsv(req.body.url))}catch(error){const status=/valid|supported|accessible|empty|large|numeric|timed out|CSV data|required/i.test(error.message)?400:502;return res.status(status).json({error:error.message||'Failed to read Google Sheet'})}}
async function getLeadById(req,res){try{const lead=await leadService.getLeadById(req.params.id,req.user?.id,req.user?.role);if(!lead)return res.status(404).json({error:'Lead not found'});return res.json(lead)}catch(error){return res.status(500).json({error:'Failed to fetch lead'})}}
async function updateLead(req,res){try{if(req.body.status&&!VALID_STATUSES.includes(req.body.status))return res.status(400).json({error:'Invalid lead status'});const pincode=await requirePincode(req.body);const current=await leadService.getLeadById(req.params.id,req.user?.id,req.user?.role);if(!current)return res.status(404).json({error:'Lead not found'});await leadInvestorService.assertInvestorLink({investorUserId:req.body.investorUserId,industryId:req.body.industryId});const lead=await leadService.updateLead(req.params.id,{...req.body,pincode});if(!lead)return res.status(404).json({error:'Lead not found'});if(req.body.investorUserId!==undefined)await leadInvestorService.setInvestorLink(req.params.id,req.body.investorUserId);return res.json({...lead,investor_user_id:req.body.investorUserId!==undefined?(req.body.investorUserId?Number(req.body.investorUserId):null):lead.investor_user_id})}catch(error){const message=String(error?.message||'');if(message==='Industry is required'||message.startsWith('Pincode is required')||message==='Selected investor has no active investment in this industry'||message==='Service does not belong to the selected Industry'||message==='Subservice requires a Service'||message==='Subservice does not belong to the selected Service')return res.status(400).json({error:error.message});return res.status(500).json({error:'Failed to update lead'})}}
async function updateLeadStatus(req,res){try{if(!VALID_STATUSES.includes(req.body.status))return res.status(400).json({error:'Invalid lead status'});const lead=await leadService.updateLeadStatus(req.params.id,req.body.status);if(!lead)return res.status(404).json({error:'Lead not found'});return res.json(lead)}catch(error){return res.status(500).json({error:'Failed to update lead status'})}}
async function deleteLead(req,res){try{const lead=await leadService.deleteLead(req.params.id);if(!lead)return res.status(404).json({error:'Lead not found'});return res.json({message:'Lead deleted successfully'})}catch(error){return res.status(500).json({error:'Failed to delete lead'})}}
async function getLeadPricing(req,res){try{return res.json(await leadService.getLeadPricing())}catch(error){return res.status(500).json({error:'Failed to fetch lead pricing'})}}
async function updateLeadPricing(req,res){try{return res.json(await leadService.updateLeadPricing(req.body))}catch(error){return res.status(400).json({error:error.message||'Failed to update pricing'})}}
async function getPricingRules(req,res){try{return res.json(await leadService.getPricingRules())}catch(error){return res.status(500).json({error:'Failed to fetch pricing rules'})}}
async function savePricingRule(req,res){try{return res.json(await leadService.savePricingRule({...req.body,id:req.params.id||req.body.id}))}catch(error){const status=error.code==='PRICING_RULE_NOT_FOUND'?404:400;return res.status(status).json({error:error.message||'Failed to save pricing rule',code:error.code})}}
async function deletePricingRule(req,res){try{const rule=await leadService.deletePricingRule(req.params.id);if(!rule)return res.status(404).json({error:'Pricing rule not found'});return res.json({message:'Pricing rule deleted'})}catch(error){return res.status(400).json({error:error.message||'Failed to delete pricing rule',code:error.code})}}
async function purchase(req,res){try{const userId=req.user.id;const leadId=Number(req.params.id);const pending=(await pool.query(`SELECT p.*,lp.id AS lead_purchase_id,lp.shares,lp.amount AS purchase_amount,lp.status AS purchase_status FROM lead_purchases lp JOIN payments p ON p.id=lp.payment_id WHERE lp.lead_id=$1 AND lp.user_id=$2 AND lp.status='pending_payment' AND p.status='pending' ORDER BY p.id DESC LIMIT 1`,[leadId,userId])).rows[0];if(pending){return res.status(200).json({payment:pending,requires_external_payment:true,walletAmount:Number(pending.wallet_amount||0),externalAmount:Number(pending.external_amount||0),balanceAfter:null,resumed:true})}return res.status(201).json(await leadPurchaseService.purchaseLead({leadId,userId,shares:req.body.shares,useWallet:req.body.useWallet!==false,couponCode:req.body.couponCode}))}catch(error){console.error('Lead purchase failed:',error.message);const bad=['INVALID_SHARES','INVALID_PRICE','INVALID_AMOUNT','PROFILE_MISMATCH','PRO_REQUIRED','NOT_FOUND','NOT_AVAILABLE','CAPACITY_REACHED','PAYMENT_PENDING','COUPON_NOT_FOUND','COUPON_INACTIVE','COUPON_NOT_STARTED','COUPON_EXPIRED','MIN_ORDER','PURCHASE_NOT_ELIGIBLE','PLAN_NOT_ELIGIBLE','USER_NOT_ELIGIBLE','INDUSTRY_NOT_ELIGIBLE','USAGE_LIMIT','USER_USAGE_LIMIT','DUPLICATE_COUPON_REDEMPTION','COUPON_REDEMPTION_INVALID'];const status=error.code==='PAYMENT_PENDING'?409:bad.includes(error.code)?400:500;return res.status(status).json({error:error.message||'Failed to purchase lead',code:error.code,paymentId:error.paymentId})}}
module.exports={createLead,getLeads,getInvestors,previewGoogleSheet,getLeadById,updateLead,updateLeadStatus,deleteLead,updateLeadPricing,getLeadPricing,getPricingRules,savePricingRule,deletePricingRule,purchase};