const leadService=require('../services/leadService');
const leadEntitlementService=require('../services/leadEntitlementService');
const pool=require('../config/database');
const VALID_STATUSES=['available','paused','sold','closed','invalid'];
const maskLead=(lead)=>({...lead,customer_name:null,customer_phone:null,customer_email:null,notes:null,custom_fields:{}});
async function privateLeadIds(userId,leadIds){
  if(!userId||!leadIds.length)return new Set();
  const r=await pool.query(`SELECT lead_id FROM (SELECT lead_id FROM lead_purchases WHERE user_id=$1 AND status='paid' AND lead_id=ANY($2::int[]) UNION SELECT lead_id FROM lead_entitlement_claims WHERE user_id=$1 AND lead_id=ANY($2::int[])) x`,[userId,leadIds]);
  return new Set(r.rows.map(x=>Number(x.lead_id)));
}
async function createLead(req,res){try{return res.status(201).json(await leadService.createLead({...req.body,createdBy:req.user?.id}))}catch(error){console.error('Create lead failed:',error.message);if(error.code==='DUPLICATE_LEAD')return res.status(409).json({error:error.message,code:error.code,leadId:error.leadId});if(error.message==='Industry is required')return res.status(400).json({error:error.message});return res.status(500).json({error:'Failed to create lead'})}}
async function getLeads(req,res){try{const rows=await leadService.getLeads({...req.query,status:req.query.status||'available',userId:req.user?.id,role:req.user?.role});if(req.user?.role==='admin'||!req.user?.id)return res.json(rows);const ids=rows.map(x=>Number(x.id)).filter(Number.isInteger);const privateIds=await privateLeadIds(req.user.id,ids);const accessMap=await leadEntitlementService.getLeadAccessMap(req.user.id,ids);return res.json(rows.map(row=>{const accessible=privateIds.has(Number(row.id));return{...(accessible?row:maskLead(row)),access:accessMap[row.id]||{authenticated:true,claimed:false,canClaim:false}}}))}catch(error){console.error('Get leads failed:',error.message);return res.status(500).json({error:'Failed to fetch leads'})}}
async function getLeadById(req,res){try{const lead=await leadService.getLeadById(req.params.id,req.user?.id,req.user?.role);if(!lead)return res.status(404).json({error:'Lead not found'});if(req.user?.role==='admin')return res.json(lead);const privateIds=await privateLeadIds(req.user?.id,[Number(lead.id)]);return res.json(privateIds.has(Number(lead.id))?lead:maskLead(lead))}catch(error){return res.status(500).json({error:'Failed to fetch lead'})}}
async function updateLead(req,res){try{if(req.body.status&&!VALID_STATUSES.includes(req.body.status))return res.status(400).json({error:'Invalid lead status'});const lead=await leadService.updateLead(req.params.id,req.body);if(!lead)return res.status(404).json({error:'Lead not found'});return res.json(lead)}catch(error){return res.status(500).json({error:'Failed to update lead'})}}
async function updateLeadStatus(req,res){try{if(!VALID_STATUSES.includes(req.body.status))return res.status(400).json({error:'Invalid lead status'});const lead=await leadService.updateLeadStatus(req.params.id,req.body.status);if(!lead)return res.status(404).json({error:'Lead not found'});return res.json(lead)}catch(error){return res.status(500).json({error:'Failed to update lead status'})}}
async function deleteLead(req,res){try{const lead=await leadService.deleteLead(req.params.id);if(!lead)return res.status(404).json({error:'Lead not found'});return res.json({message:'Lead deleted successfully'})}catch(error){return res.status(500).json({error:'Failed to delete lead'})}}
async function getLeadPricing(req,res){try{return res.json(await leadService.getLeadPricing())}catch(error){return res.status(500).json({error:'Failed to fetch lead pricing'})}}
async function updateLeadPricing(req,res){try{return res.json(await leadService.updateLeadPricing(req.body))}catch(error){return res.status(400).json({error:error.message||'Failed to update lead pricing'})}}
async function getPricingRules(req,res){try{return res.json(await leadService.getPricingRules())}catch(error){return res.status(500).json({error:'Failed to fetch pricing rules'})}}
async function savePricingRule(req,res){try{return res.json(await leadService.savePricingRule({...req.body,id:req.params.id||req.body.id}))}catch(error){const status=error.code==='PRICING_RULE_NOT_FOUND'?404:400;return res.status(status).json({error:error.message||'Failed to save pricing rule',code:error.code})}}
async function deletePricingRule(req,res){try{const rule=await leadService.deletePricingRule(req.params.id);if(!rule)return res.status(404).json({error:'Pricing rule not found'});return res.json({message:'Pricing rule deleted'})}catch(error){return res.status(400).json({error:error.message||'Failed to delete pricing rule',code:error.code})}}
module.exports={createLead,getLeads,getLeadById,updateLead,updateLeadStatus,deleteLead,getLeadPricing,updateLeadPricing,getPricingRules,savePricingRule,deletePricingRule};
