const paymentService = require('../services/paymentService');
const { getMembershipAccess, getCurrentProMembership } = require('../services/membershipAccessService');

async function checkoutMembership(req,res){try{const result=await paymentService.createMembershipCheckout({userId:req.user.id,membershipPlanId:req.body.membershipPlanId});res.status(201).json(result)}catch(error){console.error('Membership checkout failed:',error.message);const status=error.code==='PAYMENT_PENDING'?409:['INVALID_PLAN','PLAN_NOT_FOUND','INVALID_AMOUNT','PRO_REQUIRED'].includes(error.code)?400:500;res.status(status).json({error:error.message||'Failed to create membership payment',code:error.code,paymentId:error.paymentId})}}
async function submitPaymentReference(req,res){try{const result=await paymentService.submitPaymentReference({userId:req.user.id,paymentId:req.params.id,manualReference:req.body.manualReference,proofUrl:req.body.proofUrl,notes:req.body.notes});res.json(result)}catch(error){console.error('Submit payment reference failed:',error.message);const status=error.code==='DUPLICATE_REFERENCE'?409:['REFERENCE_REQUIRED','PAYMENT_NOT_PENDING'].includes(error.code)?400:error.code==='NOT_FOUND'?404:500;res.status(status).json({error:error.message||'Failed to submit payment reference',code:error.code})}}
async function getCurrentMembership(req, res) { try { const [membership, access] = await Promise.all([getCurrentProMembership(req.user.id),getMembershipAccess(req.user.id)]); res.json(membership ? { ...membership, ...access } : access); } catch (error) { console.error('Get membership access failed:', error.message); res.status(500).json({ error: 'Failed to fetch membership' }); } }
async function getPayments(req, res) { try { res.json(await paymentService.getPayments({status:req.query.status,search:req.query.search,page:req.query.page,limit:req.query.limit})); } catch (error) { console.error('Get payments failed:', error.message); res.status(500).json({ error: 'Failed to fetch payments' }); } }
async function getMembershipCustomers(req,res){try{res.json(await paymentService.getMembershipCustomers({search:req.query.search,page:req.query.page,limit:req.query.limit}));}catch(error){console.error('Get membership customers failed:',error.message);res.status(500).json({error:'Failed to fetch membership customers'});}}
async function getMembershipCustomerDetails(req,res){try{const result=await paymentService.getMembershipCustomerDetails(req.params.userId);if(!result)return res.status(404).json({error:'User not found'});res.json(result);}catch(error){console.error('Get membership customer details failed:',error.message);res.status(500).json({error:'Failed to fetch membership details'});}}
async function updatePaymentStatus(req, res) { try { const { status } = req.body; if (!['paid', 'rejected', 'failed'].includes(status)) return res.status(400).json({ error: 'Only paid, rejected, or failed are valid admin review outcomes' }); const payment = await paymentService.updatePaymentStatus(req.params.id, status, req.user.id, req.body.notes); if (!payment) return res.status(404).json({ error: 'Payment not found' }); res.json(payment); } catch (error) { console.error('Update payment failed:', error.message); const badRequestCodes=['PAYMENT_NOT_MANUAL','PAYMENT_ALREADY_PAID','PAYMENT_TERMINAL','INVALID_PAYMENT_TRANSITION','PLAN_NOT_FOUND','INVALID_PLAN','PRO_REQUIRED','ANOTHER_PRO_ACTIVE','NOT_AVAILABLE','CAPACITY_REACHED','PURCHASE_NOT_FOUND']; res.status(error.code==='MEMBERSHIP_NOT_FOUND'?404:(badRequestCodes.includes(error.code)||error.code==='23514')?400:500).json({ error: error.message || 'Failed to update payment', code:error.code }); } }
async function updateMembership(req,res){try{const membership=await paymentService.updateMembership({membershipId:req.params.id,action:req.body.action,days:req.body.days,expiresAt:req.body.expiresAt,adminId:req.user.id});res.json(membership);}catch(error){console.error('Update membership from payments failed:',error.message);const bad=['INVALID_MEMBERSHIP_ACTION','INVALID_MEMBERSHIP_DAYS','INVALID_EXPIRY','PRO_REQUIRED','ANOTHER_PRO_ACTIVE'];res.status(error.code==='MEMBERSHIP_NOT_FOUND'?404:(bad.includes(error.code)||error.code==='23514')?400:500).json({error:error.message||'Failed to update membership',code:error.code});}}
module.exports = { checkoutMembership, submitPaymentReference, getCurrentMembership, getPayments, getMembershipCustomers, getMembershipCustomerDetails, updatePaymentStatus, updateMembership };