const pool = require('../config/database');
const paymentService = require('../services/paymentService');
const leadPaymentApprovalService = require('../services/leadPaymentApprovalService');
const investmentService = require('../services/investmentService');
const investmentPaymentDraftService = require('../services/investmentPaymentDraftService');
const { getMembershipAccess, getCurrentProMembership } = require('../services/membershipAccessService');

async function checkoutMembership(req,res){try{const result=await paymentService.createMembershipCheckout({userId:req.user.id,membershipPlanId:req.body.membershipPlanId,couponCode:req.body.couponCode});res.status(201).json(result)}catch(error){console.error('Membership checkout failed:',error.message);const status=error.code==='PAYMENT_PENDING'||error.code==='DUPLICATE_COUPON_REDEMPTION'?409:['INVALID_PLAN','PLAN_NOT_FOUND','INVALID_AMOUNT','PRO_REQUIRED','COUPON_NOT_FOUND','COUPON_INACTIVE','COUPON_NOT_STARTED','COUPON_EXPIRED','MIN_ORDER','PURCHASE_NOT_ELIGIBLE','PLAN_NOT_ELIGIBLE','USER_NOT_ELIGIBLE','INDUSTRY_NOT_ELIGIBLE','USAGE_LIMIT','USER_USAGE_LIMIT','INVALID_AMOUNT','COUPON_REDEMPTION_INVALID'].includes(error.code)?400:500;res.status(status).json({error:error.message||'Failed to create membership payment',code:error.code,paymentId:error.paymentId})}}
async function submitPaymentReference(req,res){
  try {
    const draftId=String(req.params.id||'');
    const manualReference=String(req.body.manualReference||'').trim();
    const proofUrl=req.body.proofUrl;
    if(draftId.startsWith('draft_')){
      if(!manualReference)return res.status(400).json({error:'Payment reference / UTR is required',code:'REFERENCE_REQUIRED'});
      if(!proofUrl)return res.status(400).json({error:'Payment proof is required',code:'PROOF_REQUIRED'});
      const draft=investmentPaymentDraftService.consume(draftId,req.user.id);
      if(!draft)return res.status(404).json({error:'Payment session expired. Please start the direct payment again.',code:'DRAFT_NOT_FOUND'});
      const result=await investmentService.createInvestmentCheckout({...draft,useWallet:false});
      if(result.investment?.id){await pool.query('UPDATE investments SET reinvestment_enabled=$1,updated_at=CURRENT_TIMESTAMP WHERE id=$2 AND user_id=$3',[Boolean(draft.reinvestmentEnabled),Number(result.investment.id),Number(req.user.id)]);}
      const updated=await paymentService.submitPaymentReference({userId:req.user.id,paymentId:result.payment.id,manualReference,proofUrl,notes:req.body.notes||`Investment #${result.investment?.id||result.payment?.purchase_id} direct payment`});
      return res.json(updated);
    }
    const result=await paymentService.submitPaymentReference({userId:req.user.id,paymentId:req.params.id,manualReference,proofUrl,notes:req.body.notes});res.json(result)
  }catch(error){console.error('Submit payment reference failed:',error.message);const status=error.code==='DUPLICATE_REFERENCE'?409:['REFERENCE_REQUIRED','PROOF_REQUIRED','PAYMENT_NOT_PENDING'].includes(error.code)?400:error.code==='NOT_FOUND'||error.code==='DRAFT_NOT_FOUND'?404:error.code==='PAYMENT_PENDING'?409:500;res.status(status).json({error:error.message||'Failed to submit payment reference',code:error.code})}
}
async function getCurrentMembership(req,res){try{const [membership,access]=await Promise.all([getCurrentProMembership(req.user.id),getMembershipAccess(req.user.id)]);res.json(membership?{...membership,...access}:access)}catch(error){console.error('Get membership access failed:',error.message);res.status(500).json({error:'Failed to fetch membership'})}}
async function getUserMembershipPayments(req,res){try{res.json(await paymentService.getUserMembershipPayments(req.user.id));}catch(error){console.error('Get user membership payments failed:',error.message);res.status(500).json({error:'Failed to fetch membership payment history'});}}
async function enrichLeadPayments(items){const leadIds=[...new Set(items.filter(payment=>payment.purchase_type==='lead'&&payment.purchase_id!=null).map(payment=>Number(payment.purchase_id)).filter(Number.isInteger))];let leadMap=new Map();if(leadIds.length){const leadResult=await pool.query(`SELECT l.id,l.customer_name,l.requirement,l.property_type,l.budget,i.name AS industry_name,s.name AS service_name,ss.name AS subservice_name,st.name AS state_name,c.name AS city_name FROM leads l LEFT JOIN industries i ON i.id=l.industry_id LEFT JOIN services s ON s.id=l.service_id LEFT JOIN subservices ss ON ss.id=l.subservice_id LEFT JOIN states st ON st.id=l.state_id LEFT JOIN cities c ON c.id=l.city_id WHERE l.id=ANY($1::int[])`,[leadIds]);leadMap=new Map(leadResult.rows.map(lead=>[Number(lead.id),lead]));}return items.map(payment=>payment.purchase_type==='lead'?{...payment,lead:leadMap.get(Number(payment.purchase_id))||null}:payment)}
async function getPayments(req,res){try{const result=await paymentService.getPayments({status:req.query.status,search:req.query.search,page:req.query.page,limit:req.query.limit});const items=(result.items||[]).filter(payment=>payment.purchase_type!=='lead'&&payment.purchase_type!=='wallet_topup');const visiblePending=items.filter(payment=>payment.status==='pending').length;const visibleTotal=items.length;res.json({...result,items,total:visibleTotal,pages:visibleTotal?Math.ceil(visibleTotal/Math.max(Number(result.limit)||50,1)):0,stats:{...(result.stats||{}),pending:visiblePending,total:visibleTotal}})}catch(error){console.error('Get payments failed:',error.message);res.status(500).json({error:'Failed to fetch payments'})}}
async function getLeadPayments(req,res){try{const result=await paymentService.getPayments({status:req.query.status||'pending',search:req.query.search,page:req.query.page,limit:req.query.limit});const items=(result.items||[]).filter(payment=>payment.purchase_type==='lead'&&!(payment.payment_method==='manual'&&payment.status==='pending'&&!String(payment.manual_reference||'').trim()));const enrichedItems=await enrichLeadPayments(items);const visiblePending=enrichedItems.filter(payment=>payment.status==='pending').length;const visibleTotal=enrichedItems.length;res.json({...result,items:enrichedItems,total:visibleTotal,pages:visibleTotal?Math.ceil(visibleTotal/Math.max(Number(result.limit)||50,1)):0,stats:{...(result.stats||{}),pending:visiblePending,total:visibleTotal}})}catch(error){console.error('Get lead payments failed:',error.message);res.status(500).json({error:'Failed to fetch lead payment approvals'})}}
async function getMembershipCustomers(req,res){try{res.json(await paymentService.getMembershipCustomers({search:req.query.search,page:req.query.page,limit:req.query.limit}));}catch(error){console.error('Get membership customers failed:',error.message);res.status(500).json({error:'Failed to fetch membership customers'});}}
async function getMembershipCustomerDetails(req,res){try{const result=await paymentService.getMembershipCustomerDetails(req.params.userId);if(!result)return res.status(404).json({error:'User not found'});res.json(result)}catch(error){console.error('Get membership customer details failed:',error.message);res.status(500).json({error:'Failed to fetch membership details'})}}
async function updatePaymentStatus(req,res){try{const {status}=req.body;if(!['paid','rejected','failed'].includes(status))return res.status(400).json({error:'Only paid, rejected, or failed are valid admin review outcomes'});const paymentType=(await pool.query(`SELECT purchase_type FROM payments WHERE id=$1`,[req.params.id])).rows[0]?.purchase_type;const payment=paymentType==='lead'?await leadPaymentApprovalService.updateLeadPaymentStatus({paymentId:req.params.id,status,adminId:req.user.id,notes:req.body.notes}):await paymentService.updatePaymentStatus(req.params.id,status,req.user.id,req.body.notes);if(!payment)return res.status(404).json({error:'Payment not found'});res.json(payment)}catch(error){console.error('Update payment failed:',error.message);const badRequestCodes=['PAYMENT_NOT_MANUAL','PAYMENT_ALREADY_PAID','PAYMENT_TERMINAL','INVALID_PAYMENT_TRANSITION','PLAN_NOT_FOUND','INVALID_PLAN','PRO_REQUIRED','ANOTHER_PRO_ACTIVE','NOT_AVAILABLE','CAPACITY_REACHED','PURCHASE_NOT_FOUND','REFERENCE_REQUIRED','PROOF_REQUIRED','INSUFFICIENT_BALANCE'];res.status(error.code==='MEMBERSHIP_NOT_FOUND'||error.code==='NOT_FOUND'?404:(badRequestCodes.includes(error.code)||error.code==='23514')?400:500).json({error:error.message||'Failed to update payment',code:error.code})}}
async function updateMembership(req,res){try{const membership=await paymentService.updateMembership({membershipId:req.params.id,action:req.body.action,days:req.body.days,expiresAt:req.body.expiresAt,adminId:req.user.id});res.json(membership);}catch(error){console.error('Update membership from payments failed:',error.message);const bad=['INVALID_MEMBERSHIP_ACTION','INVALID_MEMBERSHIP_DAYS','INVALID_EXPIRY','PRO_REQUIRED','ANOTHER_PRO_ACTIVE'];res.status(error.code==='MEMBERSHIP_NOT_FOUND'?404:(bad.includes(error.code)||error.code==='23514')?400:500).json({error:error.message||'Failed to update membership',code:error.code});}}
module.exports={checkoutMembership,submitPaymentReference,getCurrentMembership,getUserMembershipPayments,getPayments,getLeadPayments,getMembershipCustomers,getMembershipCustomerDetails,updatePaymentStatus,updateMembership};
