const pool=require('../config/database');
const walletService=require('../services/walletService');
const walletHistoryService=require('../services/walletHistoryService');
const walletCouponService=require('../services/walletCouponService');
async function get(req,res){try{const wallet=await walletService.getWallet(req.user.id);const availability=(await pool.query(`SELECT COALESCE(SUM(wallet_amount),0)::numeric AS reserved_balance,COUNT(*) FILTER (WHERE wallet_amount>0)::int AS reserved_payment_count FROM payments WHERE user_id=$1 AND purchase_type='lead' AND status='pending' AND COALESCE(wallet_amount,0)>0 AND (COALESCE(BTRIM(manual_reference),'')<>'' OR COALESCE(BTRIM(proof_url),'')<>'')`,[req.user.id])).rows[0]||{};const balance=Number(wallet.balance||0);const reservedBalance=Number(availability.reserved_balance||0);res.json({...wallet,availableBalance:Math.max(0,Number((balance-reservedBalance).toFixed(2))),reservedBalance,reservedPaymentCount:Number(availability.reserved_payment_count||0)});}catch(e){console.error('Wallet get failed:',e.message);res.status(500).json({error:'Failed to fetch wallet'})}}
async function history(req,res){try{res.json(await walletHistoryService.getHistory(req.user.id))}catch(e){console.error('Wallet history failed:',e.message);res.status(500).json({error:'Failed to fetch wallet history'})}}
async function topup(req,res){try{const data=String(req.body.couponCode||'').trim()?await walletCouponService.createTopupWithCoupon({userId:req.user.id,amount:req.body.amount,reference:req.body.reference,proofUrl:req.body.proof_url||req.body.proofUrl,couponCode:req.body.couponCode}):await walletService.createTopup({userId:req.user.id,amount:req.body.amount,reference:req.body.reference,proofUrl:req.body.proof_url||req.body.proofUrl});res.status(201).json(data)}catch(e){const status=['INVALID_AMOUNT','DUPLICATE_REFERENCE','REFERENCE_REQUIRED','COUPON_NOT_FOUND','COUPON_INACTIVE','COUPON_NOT_STARTED','COUPON_EXPIRED','MIN_ORDER','PURCHASE_NOT_ELIGIBLE','PLAN_NOT_ELIGIBLE','USER_NOT_ELIGIBLE','USAGE_LIMIT','USER_USAGE_LIMIT'].includes(e.code)?400:500;res.status(status).json({error:e.message||'Failed to create top-up',code:e.code})}}
async function myTopups(req,res){try{res.json(await walletService.getTopups(req.user.id))}catch(e){console.error('Wallet top-up history failed:',e.message);res.status(500).json({error:'Failed to fetch top-up history'})}}
async function listTopups(req,res){try{res.json(await walletService.getAdminTopups({status:req.query.status||'all',search:req.query.search||'',page:req.query.page,limit:req.query.limit}))}catch(e){console.error('Admin wallet top-ups failed:',e.message);res.status(e.code==='INVALID_STATUS'?400:500).json({error:e.message||'Failed to fetch wallet top-ups',code:e.code})}}
async function adminWalletCustomers(req,res){try{res.json(await walletService.getAdminWalletCustomers({search:req.query.search||'',page:req.query.page,limit:req.query.limit}))}catch(e){console.error('Admin wallet history failed:',e.message);res.status(500).json({error:e.message||'Failed to fetch wallet history'})}}
async function adminWalletCustomerDetails(req,res){try{const data=await walletService.getAdminWalletCustomerDetails(req.params.userId);if(!data)return res.status(404).json({error:'Wallet customer not found'});res.json(data)}catch(e){console.error('Admin wallet details failed:',e.message);res.status(500).json({error:e.message||'Failed to fetch wallet details'})}}
async function adjustBalance(req,res){try{const data=await walletService.adjustAdminBalance({userId:req.params.userId,adminId:req.user.id,action:req.body.action,amount:req.body.amount,reason:req.body.reason});res.json(data)}catch(e){const status=['INVALID_AMOUNT','INVALID_ACTION','REASON_REQUIRED','INSUFFICIENT_BALANCE'].includes(e.code)?400:500;res.status(status).json({error:e.message||'Failed to adjust wallet balance',code:e.code})}}
async function approve(req,res){try{const data=await walletService.approveTopup({topupId:req.params.id,adminId:req.user.id,afterReview:(client)=>walletCouponService.syncApprovedTopup({topupId:req.params.id,client})});res.json(data)}catch(e){res.status(e.code==='NOT_FOUND'?404:e.code==='ALREADY_REVIEWED'?409:500).json({error:e.message||'Failed to approve top-up',code:e.code})}}
async function reject(req,res){try{const data=await walletService.rejectTopup({topupId:req.params.id,adminId:req.user.id,afterReview:(client)=>walletCouponService.syncRejectedTopup({topupId:req.params.id,client})});res.json(data)}catch(e){res.status(e.code==='NOT_FOUND'?404:e.code==='ALREADY_REVIEWED'?409:500).json({error:e.message||'Failed to reject top-up',code:e.code})}}
module.exports={get,history,topup,myTopups,listTopups,adminWalletCustomers,adminWalletCustomerDetails,adjustBalance,approve,reject};
