const { sendError } = require('../utils/errorResponse');
const {sendProofDescriptor}=require('../utils/proofResponse');
const walletService=require('../services/walletService');
const walletCouponService=require('../services/walletCouponService');
const walletHistoryService=require('../services/walletHistoryService');
const paymentGatewayService=require('../services/paymentGatewayService');
const telegramPaymentReviewService=require('../services/telegramPaymentReviewService');
async function get(req,res){try{res.json(await walletService.getWallet(req.user.id,{includeTransactions:req.query?.summary!=='1'}))}catch(e){console.error('Wallet get failed:',e.message);res.status(500).json({error:'Failed to fetch wallet'})}}
async function history(req,res){try{res.json(await walletHistoryService.getHistory(req.user.id,{page:req.query?.page,limit:req.query?.limit}))}catch(e){console.error('Wallet history failed:',e.message);res.status(500).json({error:'Failed to fetch wallet history'})}}
async function topup(req,res){try{const data=String(req.body.couponCode||'').trim()?await walletCouponService.createTopupWithCoupon({userId:req.user.id,amount:req.body.amount,reference:req.body.reference,proofUrl:req.body.proof_url||req.body.proofUrl,couponCode:req.body.couponCode}):await walletService.createTopup({userId:req.user.id,amount:req.body.amount,reference:req.body.reference,proofUrl:req.body.proof_url||req.body.proofUrl});if(!data.auto_approved)await telegramPaymentReviewService.notifyWalletTopupReview(data.id).catch(error=>console.error('Telegram wallet top-up review notification failed:',error.message));res.status(201).json(data)}catch(e){const status=['INVALID_AMOUNT','INVALID_PROOF','DUPLICATE_REFERENCE','REFERENCE_REQUIRED','COUPON_NOT_FOUND','COUPON_INACTIVE','COUPON_NOT_STARTED','COUPON_EXPIRED','MIN_ORDER','PURCHASE_NOT_ELIGIBLE','PLAN_NOT_ELIGIBLE','USER_NOT_ELIGIBLE','INDUSTRY_NOT_ELIGIBLE','USAGE_LIMIT','USER_USAGE_LIMIT','OFFLINE_PAYMENT_DISABLED'].includes(e.code)?400:500;sendError(res,status,e,'Failed to create top-up',{code:e.code})}}
async function gatewayTopup(req,res){
  let created=null;
  try{
    created=await walletCouponService.createGatewayTopup({userId:req.user.id,amount:req.body.amount,couponCode:req.body.couponCode});
    if(created.auto_approved||Number(created.payable_amount||0)===0)return res.status(201).json({...created,checkout:null});
    const checkout=await paymentGatewayService.createOrderForPayment({userId:req.user.id,paymentId:created.payment_id});
    return res.status(201).json({...created,checkout});
  }catch(e){
    const map={INVALID_AMOUNT:400,COUPON_NOT_FOUND:400,COUPON_INACTIVE:400,COUPON_NOT_STARTED:400,COUPON_EXPIRED:400,MIN_ORDER:400,PURCHASE_NOT_ELIGIBLE:400,PLAN_NOT_ELIGIBLE:400,USER_NOT_ELIGIBLE:400,INDUSTRY_NOT_ELIGIBLE:400,USAGE_LIMIT:400,USER_USAGE_LIMIT:400,GATEWAY_COMING_SOON:409,GATEWAY_DISABLED:403,GATEWAY_NOT_CONFIGURED:503,GATEWAY_PROVIDER_ERROR:502,GATEWAY_TIMEOUT:504,GATEWAY_AMOUNT_MISMATCH:502,GATEWAY_INVALID_RESPONSE:502,GATEWAY_CONFLICT:409};
    return sendError(res,map[e.code]||500,e,'Failed to create wallet online checkout',{code:e.code,paymentId:created?.payment_id||null});
  }
}
async function myTopups(req,res){try{res.json(await walletService.getTopups(req.user.id,{summary:req.query?.summary==='1'}))}catch(e){console.error('Wallet top-up history failed:',e.message);res.status(500).json({error:'Failed to fetch top-up history'})}}
async function listTopups(req,res){try{res.json(await walletService.getAdminTopups({status:req.query.status||'all',search:req.query.search||'',page:req.query.page,limit:req.query.limit}))}catch(e){console.error('Admin wallet top-ups failed:',e.message);sendError(res,e.code==='INVALID_STATUS'?400:500,e,'Failed to fetch wallet top-ups',{code:e.code})}}
async function topupProof(req,res){try{const data=await walletService.getAdminTopupProof(req.params.id);if(!data)return res.status(404).json({error:'Top-up not found'});return res.json(data)}catch(e){console.error('Admin wallet proof failed:',e.message);return sendError(res,500,e,'Failed to fetch top-up proof')}}
async function streamTopupProof(req,res){try{const data=await walletService.getAdminTopupProofDescriptor(req.params.id);if(!data)return res.status(404).json({error:'Top-up not found'});return sendProofDescriptor(res,data)}catch(e){console.error('Admin wallet proof stream failed:',e.message);return sendError(res,500,e,'Failed to stream top-up proof')}}
async function adminWalletCustomers(req,res){try{res.json(await walletService.getAdminWalletCustomers({search:req.query.search||'',page:req.query.page,limit:req.query.limit}))}catch(e){console.error('Admin wallet history failed:',e.message);sendError(res,500,e,'Failed to fetch wallet history')}}
async function adminWalletCustomerDetails(req,res){try{const data=await walletService.getAdminWalletCustomerDetails(req.params.userId,{rechargePage:req.query?.rechargePage,rechargeLimit:req.query?.rechargeLimit,transactionPage:req.query?.transactionPage,transactionLimit:req.query?.transactionLimit});if(!data)return res.status(404).json({error:'Wallet customer not found'});res.json(data)}catch(e){console.error('Admin wallet details failed:',e.message);sendError(res,500,e,'Failed to fetch wallet details')}}
async function adjustBalance(req,res){try{const data=await walletService.adjustAdminBalance({userId:req.params.userId,adminId:req.user.id,action:req.body.action,amount:req.body.amount,reason:req.body.reason});res.json(data)}catch(e){const status=['INVALID_AMOUNT','INVALID_ACTION','REASON_REQUIRED','INSUFFICIENT_BALANCE'].includes(e.code)?400:500;sendError(res,status,e,'Failed to adjust wallet balance',{code:e.code})}}
async function approve(req,res){try{const data=await walletService.approveTopup({topupId:req.params.id,adminId:req.user.id});res.json(data)}catch(e){sendError(res,e.code==='NOT_FOUND'?404:['ALREADY_REVIEWED','GATEWAY_MANAGED_TOPUP'].includes(e.code)?409:500,e,'Failed to approve top-up',{code:e.code})}}
async function reject(req,res){try{const data=await walletService.rejectTopup({topupId:req.params.id,adminId:req.user.id});res.json(data)}catch(e){sendError(res,e.code==='NOT_FOUND'?404:['ALREADY_REVIEWED','GATEWAY_MANAGED_TOPUP'].includes(e.code)?409:500,e,'Failed to reject top-up',{code:e.code})}}
module.exports={get,history,topup,gatewayTopup,myTopups,listTopups,topupProof,streamTopupProof,adminWalletCustomers,adminWalletCustomerDetails,adjustBalance,approve,reject};
