const express = require('express');
const cityController = require('../controllers/cityController');
const router = express.Router();
router.post('/', cityController.createCity);
router.post('/sync/:stateId', cityController.syncCities);
router.get('/', cityController.getCities);
router.get('/:id', cityController.getCityById);
router.post('/:id/sync-coverage', cityController.syncCoverage);
router.put('/:id', cityController.updateCity);
router.delete('/:id', cityController.deactivateCity);
module.exports = router;
