const express=require('express');
const controller=require('../controllers/couponController');
const requireAuth=require('../middleware/authMiddleware');
const requireAdmin=require('../middleware/adminMiddleware');
const rateLimit=require('../middleware/rateLimitMiddleware');
const router=express.Router();
const couponValidationLimit=rateLimit({windowMs:60*1000,max:30});
router.use(requireAuth);
router.post('/validate',couponValidationLimit,controller.validate);
router.get('/',requireAdmin,controller.list);
router.get('/:id',requireAdmin,controller.details);
router.post('/',requireAdmin,controller.create);
router.patch('/:id',requireAdmin,controller.update);
router.delete('/:id',requireAdmin,controller.remove);
router.patch('/:id/status',requireAdmin,controller.toggle);
module.exports=router;
