const express=require('express');const leadController=require('../controllers/leadController');const leadPurchaseController=require('../controllers/leadPurchaseController');const leadEntitlementController=require('../controllers/leadEntitlementController');const leadCrmController=require('../controllers/leadCrmController');const requireAuth=require('../middleware/authMiddleware');const optionalAuth=require('../middleware/optionalAuthMiddleware');const requireAdmin=require('../middleware/adminMiddleware');const rateLimit=require('../middleware/rateLimitMiddleware');const router=express.Router();
const leadActionLimit=rateLimit({windowMs:60*1000,max:30});
const leadAccessLimit=rateLimit({windowMs:60*1000,max:60});
router.get('/',optionalAuth,leadController.getLeads);
router.get('/investors',requireAdmin,leadController.getInvestors);
router.get('/pricing',requireAdmin,leadController.getLeadPricing);
router.put('/pricing',requireAdmin,leadController.updateLeadPricing);
router.get('/pricing/rules',requireAdmin,leadController.getPricingRules);
router.post('/pricing/rules',requireAdmin,leadController.savePricingRule);
router.put('/pricing/rules/:id',requireAdmin,leadController.savePricingRule);
router.delete('/pricing/rules/:id',requireAdmin,leadController.deletePricingRule);
router.post('/google-sheet/preview',requireAdmin,leadController.previewGoogleSheet);
router.get('/purchased',requireAuth,leadPurchaseController.purchases);
router.get('/purchased/export',requireAuth,leadPurchaseController.exportPurchases);
router.patch('/:id/crm',requireAuth,leadCrmController.update);
router.get('/:id/access',requireAuth,leadAccessLimit,leadEntitlementController.getAccess);
router.post('/:id/claim',requireAuth,leadActionLimit,leadEntitlementController.claim);
router.post('/:id/purchase',requireAuth,leadActionLimit,leadPurchaseController.purchase);
router.get('/:id',requireAuth,leadController.getLeadById);
router.post('/',requireAdmin,leadController.createLead);
router.put('/:id',requireAdmin,leadController.updateLead);
router.patch('/:id/status',requireAdmin,leadController.updateLeadStatus);
router.delete('/:id',requireAdmin,leadController.deleteLead);
module.exports=router;
