ALTER TABLE lead_entitlement_settings
  ADD COLUMN IF NOT EXISTS new_business_allow_single BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS new_business_allow_shared BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS new_business_allow_auto_release BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS new_business_allow_exclusive BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE lead_entitlement_grants
  ADD COLUMN IF NOT EXISTS allow_single BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS allow_shared BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS allow_auto_release BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS allow_exclusive BOOLEAN NOT NULL DEFAULT FALSE;
