-- Add the second homeowner FAQ search-intent expansion.
-- Idempotent by audience + normalized question.

INSERT INTO faq_entries(audience,category,question,answer,sort_order,is_active)
SELECT seed.audience,seed.category,seed.question,seed.answer,seed.sort_order,seed.is_active
FROM (VALUES
  ('homeowner','construction','Why do cracks often appear where a wall meets a beam or column?','RCC and masonry can move, shrink and respond to temperature or moisture differently. Junctions can therefore become crack-prone, especially when detailing or plaster preparation is weak. Project drawings may call for mesh or other junction treatment; the correct detail depends on the wall and structural system.',680,TRUE),
  ('homeowner','construction','Why do cracks form around doors and windows?','Openings create changes in wall geometry and stress concentration. Poor lintel/support detailing, shrinkage, movement at RCC-masonry junctions, weak plaster preparation or settlement can all contribute. Repeated diagonal or widening cracks should be professionally assessed.',690,TRUE),
  ('homeowner','construction','What is a slump test and why is it done?','A slump test is a field check of fresh-concrete consistency or workability. It helps verify whether delivered concrete is reasonably consistent with the specified range, but it does not by itself prove concrete strength or overall quality.',700,TRUE),
  ('homeowner','construction','Why are concrete cubes tested?','Concrete strength specimens are commonly tested to verify compressive-strength performance of sampled concrete at specified ages. Sampling, curing and testing procedures need to follow the project quality plan and applicable standards. Cube results are one part of quality control, not the only check.',710,TRUE),
  ('homeowner','construction','What is lap length in reinforcement?','Lap splices transfer force from one reinforcing bar to another by overlapping them over a designed length. Required lap length depends on bar diameter, concrete and steel properties, stress condition, location and detailing rules. Use structural drawings; do not apply one universal multiple from social media.',720,TRUE),
  ('homeowner','construction','Why are stirrups used in beams and columns?','Stirrups or ties contribute to shear resistance, confinement and holding longitudinal bars in position depending on the structural member. Their diameter, spacing and anchorage are structural-design items and should match approved drawings.',730,TRUE),
  ('homeowner','construction','Can reinforcement bars be bent and straightened repeatedly?','Repeated or uncontrolled bending can damage reinforcement and reduce reliability, especially at tight bends or previously strained locations. Bar bending should follow approved schedules and standards. Do not rework critical reinforcement casually without engineer approval.',740,TRUE),
  ('homeowner','construction','When can shuttering or formwork be removed?','Formwork removal depends on member type, span, concrete strength development, temperature, loading and the approved construction procedure. Do not use one universal number of days for every slab or beam. Follow the structural engineer and project specification.',750,TRUE),
  ('homeowner','construction','Why is masonry curing important?','Curing can help cement-based mortar develop properly and reduce rapid moisture loss. The appropriate method and duration depend on masonry units, mortar and weather. Follow the project specification rather than assuming concrete and masonry require identical curing practice.',760,TRUE),
  ('homeowner','construction','Why is plaster curing important?','Cement plaster can shrink or crack if it loses moisture too quickly or is poorly mixed/applied. Proper substrate preparation, mix consistency, thickness control and curing all influence finish quality. Curing should follow the plaster system and site conditions.',770,TRUE),
  ('homeowner','construction','Why does plaster sometimes sound hollow when tapped?','A hollow sound can indicate loss of bond between plaster and the substrate, although tap testing alone cannot identify every defect. Causes can include poor surface preparation, dust, very smooth concrete, incorrect bonding treatment, improper mix or workmanship.',780,TRUE),
  ('homeowner','construction','What causes white powder or salt marks on walls?','Efflorescence occurs when moisture dissolves soluble salts and carries them to a surface where they crystallize as water evaporates. Treating only the visible salt without resolving the moisture path can lead to recurrence.',790,TRUE),
  ('homeowner','construction','Why do floor or wall tiles crack in a new house?','Tile cracks can result from substrate movement, voids, poor adhesive coverage, structural or screed cracks, thermal movement, impact or inappropriate joint detailing. The crack pattern and whether the substrate is also cracked should be checked before simply replacing the tile.',800,TRUE),
  ('homeowner','construction','Why do tiles sound hollow after installation?','Hollow sound can come from incomplete adhesive or mortar contact, debonding or local voids. Not every hollow area fails immediately, but widespread hollow tiles can indicate installation-quality issues. Evaluate location, movement and actual bond before deciding on repair.',810,TRUE),
  ('homeowner','construction','Why are expansion or movement joints needed in buildings?','Long building elements and finishes move with temperature, shrinkage and other effects. Planned movement joints allow movement to occur at controlled locations instead of forcing random cracking. Joint location and detailing are design decisions, not a decorative choice.',820,TRUE),
  ('homeowner','construction','Should anti-termite treatment be done before construction?','Where termite risk and project specifications call for it, pre-construction termite-control measures can form part of the building protection strategy. Treatment should use legally permitted products and trained applicators, with attention to soil, foundations, service entries and later disturbance of treated zones.',830,TRUE),
  ('homeowner','construction','Why does a terrace become very hot and what can reduce heat gain?','Roofs receive strong solar radiation and can transfer heat into rooms below. Reflective finishes, insulation, ventilated roof systems, shading and appropriate roof build-ups can reduce heat gain. The right solution depends on waterproofing, roof use, climate and construction details.',840,TRUE),
  ('homeowner','construction','Can waterproofing chemical be mixed into concrete and solve all leakage problems?','No single admixture can compensate for cracks, poor joints, bad slopes, leaking penetrations or failed detailing. Integral waterproofing products may be one part of a specified system, but roofs, toilets, basements and joints still need coordinated design, workmanship and testing.',850,TRUE),
  ('homeowner','construction','Why should construction materials be approved before purchase?','Approving material type, grade, brand range or performance criteria before purchase reduces substitution disputes and helps ensure compatibility with drawings and specifications. Keep approvals, invoices and test documents for critical structural and waterproofing materials.',860,TRUE),
  ('homeowner','construction','What should I check when cement bags arrive at site?','Check the specified cement type, manufacturer/source, bag condition, markings, obvious moisture or lumping, storage arrangement and purchase records. Cement should be stored dry and protected from ground and wall moisture.',870,TRUE),
  ('homeowner','interiors','Marine plywood and BWP plywood: are they the same?','“Marine plywood” is often used casually in the market, while BWP refers to a water-resistance performance category. Do not rely on marketing names alone. Check the actual product standard, grade, manufacturer documentation, thickness and intended application.',880,TRUE),
  ('homeowner','interiors','What plywood thickness should be used for wardrobes?','There is no single thickness that is right for every wardrobe component. Side panels, shelves, shutters, backs and lofts may use different substrates and thicknesses based on span, load, hardware and design. Ask for a component-wise material schedule in the quotation.',890,TRUE),
  ('homeowner','interiors','Why do wardrobe shutters bend or warp?','Warping can be influenced by substrate choice, very tall or wide shutter dimensions, uneven finishing, moisture, heat, poor storage, hinge quantity/position or fabrication quality. Large shutters should be designed with suitable material, thickness and hardware rather than treated like small doors.',900,TRUE),
  ('homeowner','interiors','What is soft-close hardware and is it worth it?','Soft-close hinges and drawer systems damp the final part of closing, reducing slamming and improving feel. Value depends on hardware quality, load rating, installation and service support. A low-quality soft-close fitting is not automatically better than a good standard fitting.',910,TRUE),
  ('homeowner','interiors','Gypsum ceiling or POP ceiling: which is better?','Gypsum-board systems can offer fast, controlled dry construction, while POP is a wet-applied material useful for certain profiles and detailing. Selection depends on design, moisture conditions, workmanship, access, repairability and local execution quality.',920,TRUE),
  ('homeowner','interiors','Why do false ceilings develop cracks?','Cracks can occur at board joints, perimeter junctions, movement points or poorly supported framing, and can be influenced by moisture, structural movement or workmanship. Correct framing, joint treatment, movement detailing and dry conditions are important.',930,TRUE),
  ('homeowner','interiors','Wallpaper or paint: which is better for bedroom walls?','Paint is versatile and relatively easy to refresh, while wallpaper can provide texture and pattern but needs a sound, dry substrate and careful joint/detailing work. In damp-prone walls, fix the moisture problem before choosing either finish.',940,TRUE),
  ('homeowner','interiors','What is the best colour temperature for home lighting?','There is no single best colour temperature for every room. Warmer light is often used for relaxed living and bedrooms, while neutral or cooler light may suit task areas. More important is a coordinated lighting plan using brightness, glare control, colour rendering and layered light.',950,TRUE),
  ('homeowner','interiors','Why should kitchen chimney ducting be planned early?','Duct route, outlet location, cabinet height, chimney size and false-ceiling conditions can affect kitchen design. Planning the duct before cabinets are made avoids awkward bends, visible pipes and later cutting through finished work.',960,TRUE),
  ('homeowner','interiors','Ducted or recirculating kitchen chimney: which is better?','A ducted chimney exhausts air outside and is generally better at removing heat, moisture and cooking contaminants when a proper duct route is available. Recirculating units filter and return air indoors and may suit locations where external ducting is impractical.',970,TRUE),
  ('homeowner','interiors','Should wardrobes have ventilation?','Closed storage in humid or damp conditions can develop odour, moisture and fungal problems. Good room ventilation, dry walls and appropriate wardrobe detailing matter more than decorative vents alone. Do not install wardrobes against an unresolved damp wall.',980,TRUE),
  ('homeowner','interiors','What is the correct sequence for interior work after civil construction?','A typical sequence coordinates waterproofing and wet work first, then ceilings/services, wall preparation, fixed carpentry, countertop/glass work, painting/touch-ups, electrical fixtures and final cleaning. The exact sequence changes by project, but avoiding repeated rework between trades is the goal.',990,TRUE),
  ('homeowner','interiors','Why should appliances be selected before kitchen design is frozen?','Built-in and freestanding appliance dimensions affect cabinet widths, ventilation gaps, electrical load, plumbing and countertop cut-outs. Choosing appliances late can force expensive changes to finished cabinets and services.',1000,TRUE),
  ('homeowner','interiors','What should I check in a wardrobe quotation?','Check actual width and height, internal divisions, substrate and thickness, back panel, loft, shutter finish, edge treatment, hinges, drawers, handles, accessories, installation, taxes and warranty. A rate per square foot alone can hide major scope differences.',1010,TRUE),
  ('homeowner','interiors','Why do laminate edges peel or chip?','Edge failure can result from poor edge-banding or adhesive, moisture exposure, impact, weak substrate edges or fabrication quality. Good edge preparation, compatible adhesive/banding and careful installation reduce the risk.',1020,TRUE),
  ('homeowner','interiors','Is wooden flooring suitable for every room?','No. Flooring selection should consider moisture exposure, subfloor flatness, maintenance, pets, sunlight, acoustic needs and manufacturer limitations. Wet areas and damp-prone rooms need particularly careful product selection and detailing.',1030,TRUE),
  ('homeowner','interiors','How can I reduce interior cost without making the home look cheap?','Prioritize storage and high-use zones, simplify decorative elements, standardize modules, use durable mid-range finishes, limit unnecessary false ceilings and feature walls, and spend more on hardware or surfaces that receive heavy daily use.',1040,TRUE),
  ('homeowner','property','What is undivided share of land in an apartment?','Undivided share, often called UDS, represents a proportionate interest in the land associated with an apartment ownership structure. The exact legal treatment and calculation depend on project documents and local law. Verify the sale deed, approved project documents and legal opinion.',1050,TRUE),
  ('homeowner','property','Is bank loan approval proof that a property is legally safe?','No. A lender’s technical or legal review is performed for its own lending decision and should not replace the buyer’s independent legal due diligence. A buyer should still verify title, approvals, encumbrances, project documents and the actual property through qualified professionals.',1060,TRUE),
  ('homeowner','property','What is mutation of property records?','Mutation generally updates ownership or revenue/municipal records after a transfer. It is an important administrative step but does not by itself replace a valid registered conveyance or cure title defects. Procedures vary by jurisdiction.',1070,TRUE),
  ('homeowner','property','Why should property-tax receipts be checked before buying?','Tax records can help identify the property account and whether dues are outstanding, but payment of tax alone does not prove clear ownership. Review tax status together with title deeds, approvals, encumbrances and other transaction documents.',1080,TRUE),
  ('homeowner','property','What should I verify before buying an open plot?','Check title and title chain, survey boundaries, access, land-use or conversion status where applicable, layout approval, encumbrances, road reservations, acquisition issues, utilities and physical possession. Use an independent lawyer and surveyor rather than relying only on plotted-layout marketing material.',1090,TRUE),
  ('homeowner','property','Approved layout and unapproved layout: what is the difference?','An approved layout has been sanctioned by the competent planning authority subject to applicable conditions, while an unapproved subdivision may not have that authorization. Buyers should verify the approval number, plan and current status directly with the relevant authority.',1100,TRUE),
  ('homeowner','property','What is a possession letter?','A possession letter generally records the promoter or seller offering or handing over possession under the transaction documents. It should be read together with the sale deed/agreement, completion or occupancy documentation where applicable, dues statement and physical handover checklist.',1110,TRUE),
  ('homeowner','property','Can a builder change the floor plan after booking?','Material changes to plans, specifications or common areas can be regulated by the agreement, RERA framework and applicable approvals. Buyers should review the registered project disclosures, agreement terms and documented consent/approval requirements rather than relying on verbal explanations.',1120,TRUE),
  ('homeowner','property','What should I check about parking before buying an apartment?','Confirm whether parking is allotted, its type and location, dimensions/access, what the agreement and sanctioned plan state, and whether any separate charge or ownership claim is legally permissible. Parking treatment can vary by project and law, so check documents carefully.',1130,TRUE),
  ('homeowner','property','How should I compare maintenance charges between projects?','Compare what the charge actually includes: security, housekeeping, lifts, power backup, water systems, amenities, landscaping, sinking/reserve funds and taxes. A lower monthly figure can be misleading if major services are billed separately.',1140,TRUE),
  ('homeowner','property','What documents should I collect at apartment possession?','Depending on the project, collect registered conveyance documents, possession/handover records, payment and no-dues statements, warranties/manuals, parking/allotment documents, approved or as-built information where provided, and relevant completion/occupancy records. Keep digital and physical copies.',1150,TRUE),
  ('homeowner','property','What is a power of attorney in a property transaction?','A power of attorney authorizes another person to act for the principal within stated powers. Because validity, scope, revocation and registration requirements matter greatly in property deals, have the specific document reviewed by a qualified lawyer before relying on it.',1160,TRUE),
  ('homeowner','property','What should I check when buying land converted from agricultural use?','Verify whether the intended residential or commercial use is legally permitted, whether required conversion or land-use approvals exist, title and access are clear, and the plotted development itself has any necessary layout approvals. Requirements vary by state and local authority.',1170,TRUE),
  ('homeowner','property','How do I calculate rental yield on a property?','A simple gross rental yield compares annual rent with purchase price, but a more useful net view also considers vacancy, maintenance, property tax, brokerage, repairs and financing costs. Yield should be compared alongside location quality, liquidity and price risk.',1180,TRUE),
  ('homeowner','property','Villa or apartment: which is better to buy?','The choice depends on land component, privacy, maintenance responsibility, amenities, security, location, budget, future expansion needs and resale market. Compare total ownership cost and legal/project quality rather than assuming one property type is always better.',1190,TRUE),
  ('homeowner','property','Should I get an independent home inspection before buying a resale property?','An independent inspection can help identify visible defects in finishes, plumbing, electrical systems, moisture and maintenance condition. It does not replace structural investigation or legal due diligence, but it can improve negotiation and repair planning.',1200,TRUE),
  ('homeowner','property','What is the difference between booking amount and token advance?','Both terms are used commercially for early payments, but their legal effect depends on the receipt, application form or agreement. Before paying, get written terms covering the property, amount, adjustment against price, cancellation, refund and conditions.',1210,TRUE)
) AS seed(audience,category,question,answer,sort_order,is_active)
WHERE NOT EXISTS (
  SELECT 1
  FROM faq_entries existing
  WHERE existing.audience=seed.audience
    AND lower(trim(existing.question))=lower(trim(seed.question))
);
