import { useEffect, useState } from 'react';
import { getToken, clearSession } from '../../utils/auth';
import { useNavigate } from 'react-router-dom';
import './AdminMemberships.css';

const API = 'http://localhost:5000/api';

export default function AdminMemberships(){
 const navigate=useNavigate();
 const [plans,setPlans]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[show,setShow]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState({name:'',plan_type:'pro',price:'',duration_days:365,description:''});
 async function request(path,options={}){const token=getToken();if(!token){clearSession();navigate('/login',{replace:true});throw new Error('Admin session expired.');}const r=await fetch(`${API}${path}`,{...options,headers:{'Content-Type':'application/json',...(options.headers||{}),Authorization:`Bearer ${token}`}});const data=await r.json().catch(()=>({}));if(r.status===401){clearSession();navigate('/login',{replace:true});throw new Error('Admin session expired.');}if(!r.ok)throw new Error(data.error||'Request failed');return data;}
 async function load(){setLoading(true);setError('');try{setPlans(await request('/membership-plans'))}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 function openCreate(type){setEditing(null);setForm({name:type==='pro'?'Pro Yearly':'Non-Pro Yearly',plan_type:type,price:'',duration_days:365,description:''});setShow(true)}
 function openEdit(p){setEditing(p);setForm({name:p.name,plan_type:p.plan_type||'non_pro',price:p.price,duration_days:p.duration_days,description:p.description||''});setShow(true)}
 async function save(e){e.preventDefault();try{const body={name:form.name,planType:form.plan_type,price:Number(form.price),durationDays:Number(form.duration_days),description:form.description};await request(editing?`/membership-plans/${editing.id}`:'/membership-plans',{method:editing?'PUT':'POST',body:JSON.stringify(body)});setShow(false);load()}catch(e){setError(e.message)}}
 async function toggle(p){try{await request(`/membership-plans/${p.id}/status`,{method:'PATCH',body:JSON.stringify({isActive:!p.is_active})});load()}catch(e){setError(e.message)}}
 async function remove(p){if(!confirm(`Delete ${p.name}?`))return;try{await request(`/membership-plans/${p.id}`,{method:'DELETE'});load()}catch(e){setError(e.message)}}
 const pro=plans.filter(p=>(p.plan_type||'non_pro')==='pro'); const non=plans.filter(p=>(p.plan_type||'non_pro')!=='pro');
 const section=(title,items,type)=><div className="membership-section"><div className="membership-section-head"><div><span className="plan-kicker">{type==='pro'?'PRO ACCESS':'STANDARD ACCESS'}</span><h2>{title}</h2></div><button onClick={()=>openCreate(type)}>+ Add plan</button></div>{items.length===0?<div className="membership-empty">No {title.toLowerCase()} plans yet.</div>:<div className="plan-grid">{items.map(p=><article className={`plan-card ${type}`} key={p.id}><div className="plan-top"><span className="plan-badge">{type==='pro'?'PRO':'NON-PRO'}</span><span className={p.is_active?'active-dot':'inactive-dot'}>{p.is_active?'Active':'Inactive'}</span></div><h3>{p.name}</h3><div className="plan-price">₹{Number(p.price).toLocaleString('en-IN')}<small> / {p.duration_days} days</small></div><p>{p.description||'Yearly membership plan.'}</p><div className="plan-actions"><button onClick={()=>openEdit(p)}>Edit</button><button onClick={()=>toggle(p)}>{p.is_active?'Deactivate':'Activate'}</button><button className="danger" onClick={()=>remove(p)}>Delete</button></div></article>)}</div>}</div>;
 return <section className="admin-memberships-page"><div className="memberships-heading"><div><span className="eyebrow">MONETIZATION</span><h1>Membership plans</h1><p>Manage Pro and Non-Pro yearly access.</p></div></div>{error&&<div className="membership-error">{error}</div>}{loading?<div className="membership-loading">Loading plans...</div>:<>{section('Pro plans',pro,'pro')}{section('Non-Pro plans',non,'non_pro')}</>}{show&&<div className="membership-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setShow(false)}><form className="membership-modal" onSubmit={save}><div className="membership-modal-head"><div><span className="plan-kicker">PLAN SETUP</span><h2>{editing?'Edit plan':'Create plan'}</h2></div><button type="button" onClick={()=>setShow(false)}>×</button></div><div className="membership-form-grid"><label>Plan name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Type<select value={form.plan_type} onChange={e=>setForm({...form,plan_type:e.target.value})}><option value="pro">Pro</option><option value="non_pro">Non-Pro</option></select></label><label>Yearly price<input type="number" min="0" step="0.01" value={form.price} onChange={e=>setForm({...form,price:e.target.value})} required/></label><label>Duration<input type="number" min="1" value={form.duration_days} onChange={e=>setForm({...form,duration_days:e.target.value})} required/></label></div><label>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} rows="3" placeholder="Optional short description"/></label><button className="membership-save" type="submit">{editing?'Save changes':'Create plan'}</button></form></div>}</section>;
}
