import { useEffect, useMemo, useState } from 'react'
import { apiRequest } from '../../utils/api'
import { getToken, clearSession } from '../../utils/auth'
import { useNavigate } from 'react-router-dom'
import './AdminInvestments.css'

const money = value => `₹${Number(value || 0).toLocaleString('en-IN', { maximumFractionDigits: 2 })}`
const date = value => value ? new Date(value).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) : '—'
const fileToDataUrl = file => new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error('Unable to read transfer proof'));reader.readAsDataURL(file)})

export default function AdminInvestments(){
  const navigate=useNavigate()
  const [data,setData]=useState({stats:{},investors:[],items:[]})
  const [search,setSearch]=useState('');const [status,setStatus]=useState('all');const [industryId,setIndustryId]=useState('');const [industries,setIndustries]=useState([]);const [expanded,setExpanded]=useState({});const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(null);const [error,setError]=useState('')
  const [linked,setLinked]=useState(null);const [linkedLoading,setLinkedLoading]=useState(false);const [payoutModal,setPayoutModal]=useState(null);const [transferReference,setTransferReference]=useState('');const [proofFile,setProofFile]=useState(null);const [payoutBusy,setPayoutBusy]=useState(false)
  const request=async(path,options={})=>{if(!getToken()){clearSession();navigate('/login',{replace:true});throw new Error('Your admin session has expired. Please sign in again.')}return apiRequest(path,options)}
  const load=async(silent=false)=>{if(!silent)setLoading(true);setError('');try{const params=new URLSearchParams({search:search.trim(),status,industryId});const [dashboard,industryData]=await Promise.all([request(`/admin/commercial/investment-dashboard?${params}`),industries.length?Promise.resolve(industries):request('/industries')]);setData({stats:dashboard.stats||{},investors:dashboard.investors||[],items:dashboard.items||[]});if(!industries.length)setIndustries(Array.isArray(industryData)?industryData:industryData?.data||[])}catch(e){if(!silent)setError(e.message||'Unable to load investor analytics.')}finally{if(!silent)setLoading(false)}}
  useEffect(()=>{load()},[status,industryId])
  useEffect(()=>{const timer=window.setInterval(()=>load(true),30000);return()=>window.clearInterval(timer)},[status,industryId,search])
  const investorCycles=useMemo(()=>{const map=new Map();for(const row of data.items){if(!map.has(row.user_id))map.set(row.user_id,[]);map.get(row.user_id).push(row)}return map},[data.items])
  const toggle=userId=>setExpanded(value=>({...value,[userId]:!value[userId]}))
  const showLinked=async investor=>{setLinked({investor,items:[]});setLinkedLoading(true);try{const items=await request(`/investments/admin/investor/${investor.user_id}/linked-leads`);setLinked({investor,items:Array.isArray(items)?items:items?.data||[]})}catch(e){setError(e.message||'Unable to load linked leads.');setLinked(null)}finally{setLinkedLoading(false)}}
  const openPayout=cycle=>{setPayoutModal(cycle);setTransferReference('');setProofFile(null);setError('')}
  const submitPayout=async()=>{if(!payoutModal)return;setError('');if(!transferReference.trim())return setError('Enter the transfer reference / UTR.');if(!proofFile)return setError('Attach the transfer screenshot or proof.');if(proofFile.size>5*1024*1024)return setError('Transfer proof must be 5 MB or smaller.');setPayoutBusy(true);try{const proofUrl=await fileToDataUrl(proofFile);await request(`/investments/admin/${payoutModal.id}/payout`,{method:'POST',body:JSON.stringify({transferReference:transferReference.trim(),proofUrl})});setPayoutModal(null);setTransferReference('');setProofFile(null);await load()}catch(e){setError(e.message||'Unable to record investor transfer.')}finally{setPayoutBusy(false)}}
  const stats=data.stats||{}
  return <main className="admin-investments-page">
    <header className="admin-investments-head"><div><span className="admin-investments-kicker">INVESTOR OPERATIONS</span><h1>Investments</h1><p>Track investor capital, linked leads, lead sales, generated revenue, payouts and transfer proof.</p></div><button className="admin-investments-refresh" type="button" onClick={()=>load()}>↻ Refresh</button></header>
    {error&&<div className="admin-investments-error">{error}</div>}
    <section className="admin-investment-stats"><article><span>Investors</span><strong>{stats.investors??0}</strong></article><article><span>Total invested</span><strong>{money(stats.total_invested)}</strong></article><article><span>Active capital</span><strong>{money(stats.active_invested)}</strong></article><article className="payable"><span>Payable now</span><strong>{money(stats.payable_now)}</strong></article><article><span>Amount generated</span><strong>{money(stats.allocated_revenue)}</strong></article><article><span>Amount paid</span><strong>{money(stats.paid_to_investors)}</strong></article></section>
    <section className="admin-investment-note"><b>Investor accounting</b><span><strong>Invested</strong> excludes cancelled and pending cycles. <strong>Amount generated</strong> is allocated eligible paid lead-sale revenue. <strong>Current payable</strong> is due after maturity and remains payable until transferred.</span></section>
    <section className="admin-investment-panel"><div className="admin-investment-toolbar"><div className="admin-investment-search"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="Search investor, email, industry or location..."/></div><select value={industryId} onChange={e=>setIndustryId(e.target.value)}><option value="">All industries</option>{industries.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All cycles</option><option value="active">Active</option><option value="matured">Matured</option><option value="paid">Paid</option><option value="pending">Pending</option><option value="cancelled">Cancelled</option></select><button type="button" onClick={()=>load()}>Search</button></div>
      {loading?<div className="admin-investment-empty">Loading investor records…</div>:!data.investors.length?<div className="admin-investment-empty">No investor records match the selected filters.</div>:<div className="admin-investor-list">{data.investors.map(investor=>{const open=Boolean(expanded[investor.user_id]);const cycles=investorCycles.get(investor.user_id)||[];return <article className={`admin-investor-card ${open?'open':''}`} key={investor.user_id}>
        <button type="button" className="admin-investor-summary" onClick={()=>toggle(investor.user_id)}><div className="admin-investor-identity"><span className="admin-investor-avatar">{String(investor.user_name||'I').slice(0,1).toUpperCase()}</span><div><strong>{investor.user_name||'Investor'}</strong><small>{investor.user_email}</small></div></div><div><span>INVESTED</span><b>{money(investor.total_invested)}</b></div><div><span>LINKED LEADS</span><b>{investor.linked_leads}</b></div><div><span>LEADS SOLD</span><b>{investor.sold_linked_leads}</b></div><div><span>GENERATED</span><b>{money(investor.allocated_revenue)}</b></div><div><span>AMOUNT PAID</span><b>{money(investor.paid_to_investor)}</b></div><div><span>PAYABLE NOW</span><b className={investor.payable_now>0?'payable-text':''}>{money(investor.payable_now)}</b></div><i className="admin-investor-chevron">⌄</i></button>
        {open&&<div className="admin-investor-details"><div className="admin-investor-detail-stats"><div><span>Invested</span><b>{money(investor.total_invested)}</b></div><div><span>Total linked leads</span><b>{investor.linked_leads}</b></div><div><span>Leads sold</span><b>{investor.sold_linked_leads}</b></div><div><span>Amount generated by sales</span><b>{money(investor.linked_gross_sales)}</b></div><div><span>Investor amount paid</span><b>{money(investor.paid_to_investor)}</b></div><div><span>Current payable</span><b className={investor.payable_now>0?'payable-text':''}>{money(investor.payable_now)}</b></div></div>
          <div className="admin-investor-actions"><button type="button" className="admin-linked-leads-button" onClick={()=>showLinked(investor)}>View all linked leads →</button></div>
          <div className="admin-cycle-title"><h3>Investment cycles</h3><span>{cycles.length} cycle{cycles.length===1?'':'s'}</span></div><div className="admin-cycle-table-wrap"><table><thead><tr><th>Cycle</th><th>Industry / location</th><th>Invested</th><th>Lead sales</th><th>Revenue generated</th><th>Status</th><th>Maturity</th><th>Action</th></tr></thead><tbody>{cycles.map(cycle=><tr key={cycle.id}><td><b>#{cycle.id}</b></td><td><strong>{cycle.industry_name}</strong><small>{[cycle.city_name,cycle.state_name].filter(Boolean).join(', ')||'—'}</small></td><td>{money(cycle.amount)}</td><td><b>{cycle.sold_linked_leads}</b><small>{cycle.linked_leads} linked</small></td><td>{money(cycle.allocated_revenue)}</td><td><span className={`admin-investment-status ${cycle.status}`}>{cycle.status}</span></td><td>{date(cycle.matures_at)}</td><td>{cycle.payable_now>0?<button className="admin-payout-button" disabled={busy!==null} onClick={()=>openPayout(cycle)}>Transfer {money(cycle.payable_now)}</button>:<span className="admin-no-payout">{cycle.status==='paid'?'Paid':'Not due'}</span>}</td></tr>)}</tbody></table></div>
        </div>}
      </article>})}</div>}
    </section>

    {linked&&<div className="admin-investment-overlay"><section className="admin-investment-modal"><button className="admin-investment-modal-close" type="button" onClick={()=>setLinked(null)}>×</button><span className="admin-investments-kicker">LINKED LEADS</span><h2>{linked.investor.user_name}'s linked leads</h2><p>{linked.items.length} lead{linked.items.length===1?'':'s'} linked to this investor.</p>{linkedLoading?<div className="admin-investment-empty">Loading linked leads…</div>:!linked.items.length?<div className="admin-investment-empty">No linked leads found.</div>:<div className="admin-linked-lead-list">{linked.items.map(lead=><article className="admin-linked-lead-card" key={lead.id}><div><strong>{lead.name||'Lead'}</strong><span>{lead.industry_name}{lead.service_name?` · ${lead.service_name}`:''}</span><small>{[lead.city_name,lead.state_name].filter(Boolean).join(', ')||'Location not set'} · {date(lead.created_at)}</small></div><div><span>Budget</span><b>{lead.budget||'—'}</b></div><div><span>Sale amount</span><b>{money(lead.gross_sale_amount)}</b></div><div><span>Paid sales</span><b>{lead.paid_sale_count}</b></div></article>)}</div>}</section></div>}
    {payoutModal&&<div className="admin-investment-overlay"><section className="admin-investment-modal admin-payout-modal"><button className="admin-investment-modal-close" type="button" onClick={()=>!payoutBusy&&setPayoutModal(null)}>×</button><span className="admin-investments-kicker">INVESTOR TRANSFER</span><h2>Transfer {money(payoutModal.payable_now)}</h2><p>Record the external transfer to the investor. The transfer reference and screenshot will be saved so the investor can verify the payout.</p><div className="admin-payout-amount"><span>Amount to transfer</span><strong>{money(payoutModal.payable_now)}</strong></div><label>Transfer reference / UTR<input value={transferReference} onChange={e=>setTransferReference(e.target.value)} placeholder="Enter UTR or bank transfer reference"/></label><label>Transfer screenshot / proof<input type="file" accept="image/*,.pdf" onChange={e=>setProofFile(e.target.files?.[0]||null)}/></label>{proofFile&&<small className="admin-proof-name">Attached: {proofFile.name}</small>}<button className="admin-payout-confirm" type="button" disabled={payoutBusy} onClick={submitPayout}>{payoutBusy?'Saving transfer…':'Confirm transfer & save proof'}</button></section></div>}
  </main>
}
