import {useEffect,useState} from 'react';
import {getToken} from '../../utils/auth';
import './AdminLeadPricing.css';
const API='http://localhost:5000/api';
const emptyPricing=()=>({shares:[{shares:1,normal:0,pro:0},{shares:3,normal:0,pro:0},{shares:5,normal:0,pro:0}]});
const emptyForm=()=>({industryId:'',cityId:'',leadType:'basic',pricing:emptyPricing(),isActive:true});
const types=['basic','premium'];
const cap=v=>String(v||'').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
export default function AdminLeadPricing(){
 const [industries,setIndustries]=useState([]),[cities,setCities]=useState([]),[rules,setRules]=useState([]),[form,setForm]=useState(emptyForm()),[editId,setEditId]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[ok,setOk]=useState('');
 const req=async(p,o={})=>{const r=await fetch(API+p,{...o,headers:{Authorization:`Bearer ${getToken()}`,'Content-Type':'application/json',...(o.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Request failed');return d};
 const load=async()=>{try{setLoading(true);const [a,b,c]=await Promise.all([req('/industries'),req('/cities'),req('/leads/pricing/rules')]);setIndustries(Array.isArray(a)?a:[]);setCities(Array.isArray(b)?b:[]);setRules(Array.isArray(c)?c:[])}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const setTier=(i,k,v)=>setForm(f=>({...f,pricing:{...f.pricing,shares:f.pricing.shares.map((x,n)=>n===i?{...x,[k]:v}:x)}}));
 const reset=()=>{setEditId(null);setForm(emptyForm())};
 const edit=r=>{setEditId(r.id);setForm({industryId:r.industry_id??'',cityId:r.city_id??'',leadType:r.lead_type||'basic',pricing:{shares:Array.isArray(r.pricing?.shares)?r.pricing.shares:emptyPricing().shares},isActive:r.is_active});setOk('');window.scrollTo({top:0,behavior:'smooth'})};
 const save=async()=>{try{setSaving(true);setError('');setOk('');await req(editId?`/leads/pricing/rules/${editId}`:'/leads/pricing/rules',{method:editId?'PUT':'POST',body:JSON.stringify(form)});setOk(editId?'Pricing rule updated.':'Pricing rule created.');reset();await load()}catch(e){setError(e.message)}finally{setSaving(false)}};
 const del=async id=>{if(!confirm('Delete this pricing rule?'))return;try{await req(`/leads/pricing/rules/${id}`,{method:'DELETE'});await load()}catch(e){setError(e.message)}};
 const addTier=()=>setForm(f=>({...f,pricing:{...f.pricing,shares:[...f.pricing.shares,{shares:10,normal:0,pro:0}]}}));
 return <main className="pricing-page"><style>{`.pricing-hero>div:first-child{flex:1;text-align:center}.create-head,.rules-head{position:relative;justify-content:center;text-align:center;min-height:70px}.create-head>div,.rules-head>div{max-width:700px;margin:0 auto}.create-head .outline-btn,.rules-head .outline-btn{position:absolute;right:0;top:0}@media(max-width:700px){.create-head,.rules-head{min-height:0}.create-head .outline-btn,.rules-head .outline-btn{position:static;width:100%;margin-top:10px}}`}</style>
  <section className="pricing-hero"><div><span className="hero-kicker">REVENUE CONTROL</span><h1>Lead Pricing</h1><p>Set market-specific prices for Basic and Premium leads.</p></div><div className="hero-mark">₹</div></section>
  {error&&<div className="pricing-alert error">{error}</div>}{ok&&<div className="pricing-alert success">{ok}</div>}
  <section className="pricing-panel create-panel"><div className="panel-head create-head"><div><span className="kicker">{editId?'EDIT PRICING RULE':'CREATE PRICING RULE'}</span><h2>{editId?'Update pricing rule':'Create pricing rule'}</h2><p>Choose the market, then set Normal and Pro prices.</p></div>{editId&&<button className="outline-btn" onClick={reset}>Cancel</button>}</div>
   <div className="scope-grid"><label>Industry<select value={form.industryId} onChange={e=>setForm({...form,industryId:e.target.value})}><option value="">All industries</option>{industries.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>City<select value={form.cityId} onChange={e=>setForm({...form,cityId:e.target.value})}><option value="">All cities</option>{cities.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="active-box">Status<span><input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/> Active</span></label></div>
   <div className="lead-type-switch">{types.map(t=><button type="button" key={t} className={form.leadType===t?`selected ${t}`:''} onClick={()=>setForm({...form,leadType:t})}><strong>{cap(t)}</strong><small>{t==='basic'?'Standard leads':'High-value leads'}</small></button>)}</div>
   <div className="pricing-box"><div className="pricing-box-head"><div><h3>{cap(form.leadType)} sharing pricing</h3><p>Set Normal and Pro prices for each sharing tier.</p></div><button type="button" className="add-tier" onClick={addTier}>+ Add tier</button></div><div className="tier-head"><span>SHARES</span><span>NORMAL</span><span>PRO</span><span></span></div>{form.pricing.shares.map((x,i)=><div className="tier-row" key={i}><div className="field"><span>Shares</span><input type="number" min="1" value={x.shares} onChange={e=>setTier(i,'shares',e.target.value)}/></div><div className="field money"><span>Normal</span><div>₹<input type="number" min="0" value={x.normal} onChange={e=>setTier(i,'normal',e.target.value)}/></div></div><div className="field money"><span>Pro</span><div>₹<input type="number" min="0" value={x.pro} onChange={e=>setTier(i,'pro',e.target.value)}/></div></div><button type="button" className="remove-tier" disabled={form.pricing.shares.length===1} onClick={()=>setForm(f=>({...f,pricing:{...f.pricing,shares:f.pricing.shares.filter((_,n)=>n!==i)}}))}>×</button></div>)}</div>
   <div className="panel-foot"><span>Exclusive is configured per lead during upload, not in pricing.</span><button className="primary-btn" disabled={saving} onClick={save}>{saving?'Saving…':editId?'Update rule':'Save rule'}</button></div>
  </section>
  <section className="pricing-panel rules-panel"><div className="panel-head compact rules-head"><div><span className="kicker">PRICING MATRIX</span><h2>Configured rules</h2><p>Industry + City + Lead Type</p></div><button className="outline-btn" onClick={load}>Refresh</button></div>{loading?<div className="empty">Loading pricing rules…</div>:!rules.length?<div className="empty">No pricing rules configured yet.</div>:<div className="rule-cards">{rules.map(r=><article className="rule-card" key={r.id}><div className="rule-top"><div><span className={`type-pill ${r.lead_type}`}>{cap(r.lead_type)}</span><h3>{r.industry_name||'All industries'}</h3><p>{r.city_name||'All cities'}</p></div><span className={r.is_active?'status active':'status'}>{r.is_active?'ACTIVE':'OFF'}</span></div><div className="rule-prices">{(r.pricing?.shares||[]).map(x=><div key={x.shares}><b>{x.shares}</b><span>Normal <strong>₹{x.normal}</strong></span><span>Pro <strong>₹{x.pro}</strong></span></div>)}</div><div className="card-actions"><button onClick={()=>edit(r)}>Edit</button><button onClick={()=>del(r.id)}>Delete</button></div></article>)}</div>}</section>
 </main>;
}