import { useCallback, useEffect, useState } from 'react'
import { authRequest } from '../../utils/auth'
const STATUSES=[['pending','Pending'],['verified_fake','Verified fake'],['verified_genuine','Verified genuine'],['rejected','Rejected'],['all','All']]
const REASONS={fake:'Fake lead',wrong_number:'Wrong number',not_interested:'Customer not interested',duplicate:'Duplicate',other:'Other'}
export default function AdminLeadReports(){
 const [status,setStatus]=useState('pending'),[data,setData]=useState({data:[],pagination:{}}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(null),[message,setMessage]=useState('')
 const load=useCallback(async()=>{try{setLoading(true);setError('');setData(await authRequest(`/lead-reports/admin?status=${status}`))}catch(e){setError(e.message||'Failed to load reports')}finally{setLoading(false)}},[status])
 useEffect(()=>{let active=true;queueMicrotask(()=>{if(active)load()});return()=>{active=false}},[load])
 async function review(id,nextStatus){try{setBusy(id);setMessage('');setError('');await authRequest(`/lead-reports/admin/${id}`,{method:'PATCH',body:JSON.stringify({status:nextStatus})});setMessage(`Report #${id} marked ${nextStatus.replace('_',' ')}.`);await load()}catch(e){setError(e.message||'Failed to review report')}finally{setBusy(null)}}
 async function setControl(userId,canReportLeads){try{setBusy(`user-${userId}`);setMessage('');setError('');await authRequest(`/lead-reports/admin/user/${userId}/control`,{method:'PATCH',body:JSON.stringify({canReportLeads,reason:canReportLeads?null:'Lead reporting disabled by admin'})});setMessage(canReportLeads?'Reporting re-enabled for this user.':'Reporting disabled for this user.');await load()}catch(e){setError(e.message||'Failed to update reporting control')}finally{setBusy(null)}}
 return <section className="admin-page"><div className="admin-page-header"><div><span className="admin-eyebrow">LEAD QUALITY</span><h1>Lead Reports</h1><p>Review customer reports, verify lead quality, and control reporting access for repeat false reporters.</p></div></div><div style={{display:'flex',gap:8,flexWrap:'wrap',marginBottom:16}}>{STATUSES.map(([v,l])=><button key={v} onClick={()=>setStatus(v)} style={{padding:'9px 13px',borderRadius:8,border:'1px solid #d7e1ec',background:status===v?'#0b2d63':'#fff',color:status===v?'#fff':'#173f78',fontWeight:800,cursor:'pointer'}}>{l}</button>)}</div>{error&&<div className="admin-error">{error}</div>}{message&&<div className="admin-success">{message}</div>}{loading?<div className="admin-loading">Loading reports…</div>:!data.data?.length?<div className="admin-empty">No reports in this view.</div>:<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>ID</th><th>LEAD</th><th>REPORTER</th><th>REASON</th><th>DETAILS</th><th>STATUS</th><th>ACTION</th></tr></thead><tbody>{data.data.map(row=>{const enabled=row.can_report_leads!==false;const controlBusy=busy===`user-${row.reporter_user_id}`;return <tr key={row.id}><td>#{row.id}</td><td><b>#{row.lead_id} · {row.customer_name||'Customer'}</b><small>{row.industry_name||'—'} · {row.lead_status||'—'}</small></td><td><b>{row.reporter_name||'User'}</b><small>{row.reporter_email||'—'}</small><small>{enabled?'Reporting enabled':'Reporting disabled'} · False reports: {row.false_report_count||0}</small></td><td>{REASONS[row.reason]||row.reason}</td><td>{row.details||'—'}</td><td>{row.status}</td><td>{row.status==='pending'?<div style={{display:'flex',gap:6,flexWrap:'wrap'}}><button disabled={busy===row.id} onClick={()=>review(row.id,'verified_fake')}>Verify fake</button><button disabled={busy===row.id} onClick={()=>review(row.id,'verified_genuine')}>Genuine</button><button disabled={busy===row.id} onClick={()=>review(row.id,'rejected')}>Reject</button></div>:<button disabled={controlBusy} onClick={()=>setControl(row.reporter_user_id,!enabled)}>{enabled?'Disable reporting':'Enable reporting'}</button>}</td></tr>})}</tbody></table></div>}</section>
}
