import { useEffect, useMemo, useState } from 'react';
import { getToken, clearSession } from '../../utils/auth';
import { useNavigate } from 'react-router-dom';
import './AdminMembershipPlans.css';

const API='http://localhost:5000/api';
const empty={name:'',planType:'pro',billingPeriod:'monthly',monthlyBasePrice:'',discountPercent:0,description:''};
const months={monthly:1,quarterly:3,yearly:12};
const days={monthly:30,quarterly:90,yearly:365};
export default function AdminMembershipPlans(){
 const navigate=useNavigate(); const [plans,setPlans]=useState([]); const [form,setForm]=useState(empty); const [editing,setEditing]=useState(null); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
 async function request(path,options={}){const token=getToken();if(!token){clearSession();navigate('/login',{replace:true});throw Error('Session expired');}const r=await fetch(`${API}${path}`,{...options,headers:{'Content-Type':'application/json',...(options.headers||{}),Authorization:`Bearer ${token}`}});const d=await r.json().catch(()=>({}));if(r.status===401){clearSession();navigate('/login',{replace:true});throw Error('Session expired');}if(!r.ok)throw Error(d.error||'Request failed');return d}
 async function load(){setLoading(true);try{setPlans(await request('/membership-plans'))}catch(e){setError(e.message)}finally{setLoading(false)}} useEffect(()=>{load()},[]);
 function change(e){setForm({...form,[e.target.name]:e.target.value})}
 const calculated=useMemo(()=>{const base=Number(form.monthlyBasePrice)||0;const discount=Number(form.discountPercent)||0;return Number((base*(months[form.billingPeriod]||1)*(1-discount/100)).toFixed(2))},[form.monthlyBasePrice,form.discountPercent,form.billingPeriod]);
 async function save(e){e.preventDefault();setError('');try{const body={name:form.name,planType:form.planType,description:form.description,monthlyBasePrice:Number(form.monthlyBasePrice),discountPercent:Number(form.discountPercent),billingPeriod:form.billingPeriod,durationDays:days[form.billingPeriod]};if(editing)await request(`/membership-plans/${editing}`,{method:'PUT',body:JSON.stringify(body)});else await request('/membership-plans',{method:'POST',body:JSON.stringify(body)});setForm(empty);setEditing(null);load()}catch(e){setError(e.message)}}
 async function toggle(p){try{await request(`/membership-plans/${p.id}/status`,{method:'PATCH',body:JSON.stringify({isActive:!p.is_active})});load()}catch(e){setError(e.message)}}
 async function remove(p){if(!confirm(`Delete ${p.name}?`))return;try{await request(`/membership-plans/${p.id}`,{method:'DELETE'});load()}catch(e){setError(e.message)}}
 function edit(p){setEditing(p.id);setForm({name:p.name,planType:p.plan_type,billingPeriod:p.billing_period||'yearly',monthlyBasePrice:p.monthly_base_price??p.price,discountPercent:p.discount_percent??0,description:p.description||''})}
 const group=(type)=>plans.filter(p=>p.plan_type===type);
 const card=(p)=><div className={`plan-card ${p.is_active?'':'inactive'}`} key={p.id}><div className="plan-top"><span className={`tier ${p.plan_type}`}>{p.plan_type==='pro'?'PRO':'NON-PRO'}</span><span className={p.is_active?'active':'off'}>{p.is_active?'Active':'Inactive'}</span></div><h3>{p.name}</h3><div className="period-label">{(p.billing_period||'yearly').toUpperCase()}</div><div className="price">₹{Number(p.price).toLocaleString('en-IN')} <small>/ {p.billing_period==='monthly'?'month':p.billing_period==='quarterly'?'quarter':'year'}</small></div><p>Base ₹{Number(p.monthly_base_price||p.price).toLocaleString('en-IN')}/month · {Number(p.discount_percent||0)}% discount</p><div className="plan-actions"><button onClick={()=>edit(p)}>Edit</button><button onClick={()=>toggle(p)}>{p.is_active?'Deactivate':'Activate'}</button><button className="danger" onClick={()=>remove(p)}>Delete</button></div></div>;
 return <main className="membership-page"><header><div><span>MEMBERSHIPS</span><h1>Membership Plans</h1><p>Configure Pro and Non-Pro billing with automatic quarterly and yearly pricing.</p></div></header>{error&&<div className="membership-error">{error}</div>}<div className="membership-grid"><section className="plan-section"><div className="section-title"><h2>Pro</h2><span>Premium lead pricing & Investor unlock</span></div>{loading?<div className="empty">Loading...</div>:group('pro').length?group('pro').map(card):<div className="empty">No Pro plans yet.</div>}</section><section className="plan-section"><div className="section-title"><h2>Non-Pro</h2><span>Standard lead access</span></div>{loading?<div className="empty">Loading...</div>:group('non_pro').length?group('non_pro').map(card):<div className="empty">No Non-Pro plans yet.</div>}</section></div><section className="plan-form"><div><h2>{editing?'Edit plan':'Create plan'}</h2><p>Enter one monthly base price. The system calculates the selected billing period after discount.</p></div><form onSubmit={save}><label>Plan name<input name="name" value={form.name} onChange={change} required placeholder="e.g. Pro"/></label><label>Plan type<select name="planType" value={form.planType} onChange={change}><option value="pro">Pro</option><option value="non_pro">Non-Pro</option></select></label><label>Billing period<select name="billingPeriod" value={form.billingPeriod} onChange={change}><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option><option value="yearly">Yearly</option></select></label><label>Monthly base price<input name="monthlyBasePrice" type="number" min="0" step="0.01" value={form.monthlyBasePrice} onChange={change} required placeholder="999"/></label><label>Discount %<input name="discountPercent" type="number" min="0" max="100" step="0.01" value={form.discountPercent} onChange={change}/></label><label>Description<input name="description" value={form.description} onChange={change} placeholder="Plan benefits"/></label><div className="price-preview"><span>Calculated price</span><strong>₹{calculated.toLocaleString('en-IN')}</strong><small>{form.billingPeriod} · {days[form.billingPeriod]} days</small></div><div className="form-actions"><button type="submit">{editing?'Save changes':'Create plan'}</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm(empty)}}>Cancel</button>}</div></form></section></main>;
}
