import { useEffect, useState } from 'react';
import './AdminPayments.css';

export default function AdminPayments(){
 const [payments,setPayments]=useState([]),[status,setStatus]=useState('all'),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 async function load(){setLoading(true);setError('');try{const token=localStorage.getItem('token');const qs=new URLSearchParams({status,search});const r=await fetch(`http://localhost:5000/api/payments?${qs}`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error('Unable to load payments');setPayments(await r.json())}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[status]);
 async function update(id,next){const token=localStorage.getItem('token');const r=await fetch(`http://localhost:5000/api/payments/${id}/status`,{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({status:next})});if(r.ok)load();else setError('Payment update failed')}
 const money=(v)=>`₹${Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`;
 return <section className="admin-payments-page"><div className="payments-heading"><div><span className="eyebrow">FINANCE</span><h1>Payments</h1><p>Review gateway and manual payment activity.</p></div><button onClick={load}>↻ Refresh</button></div><div className="payment-cards"><div><span>Total</span><b>{payments.length}</b></div><div><span>Pending</span><b>{payments.filter(p=>p.status==='pending').length}</b></div><div><span>Paid</span><b>{payments.filter(p=>p.status==='paid').length}</b></div><div><span>Manual</span><b>{payments.filter(p=>p.payment_method==='manual').length}</b></div></div><div className="payment-panel"><div className="payment-toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="Search owner, email or reference..."/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="pending">Pending</option><option value="paid">Paid</option><option value="rejected">Rejected</option><option value="failed">Failed</option><option value="refunded">Refunded</option></select></div>{error&&<div className="payment-error">{error}</div>}<div className="payment-table-wrap"><table><thead><tr><th>ID</th><th>BUSINESS / USER</th><th>METHOD</th><th>AMOUNT</th><th>REFERENCE</th><th>STATUS</th><th>ACTION</th></tr></thead><tbody>{loading?<tr><td colSpan="7" className="payment-empty">Loading payments...</td></tr>:payments.length===0?<tr><td colSpan="7" className="payment-empty">No payments found.</td></tr>:payments.map(p=><tr key={p.id}><td>#{p.id}</td><td><b>{p.business_name||p.user_name||'—'}</b><small>{p.user_email}</small></td><td><span className="method">{p.payment_method}</span></td><td><strong>{money(p.amount)}</strong></td><td>{p.manual_reference||p.gateway_payment_id||'—'}</td><td><span className={`pay-status ${p.status}`}>{p.status}</span></td><td>{p.status==='pending'&&<div className="pay-actions"><button onClick={()=>update(p.id,'paid')}>Approve</button><button onClick={()=>update(p.id,'rejected')}>Reject</button></div>}</td></tr>)}</tbody></table></div></div></section>;
}
