import { useEffect, useMemo, useState } from 'react';
import { apiRequest } from '../../utils/api';
import { getToken, clearSession } from '../../utils/auth';
import { useNavigate } from 'react-router-dom';
import './AdminTable.css';
import './AdminWalletTopups.css';

export default function AdminWalletTopups(){
 const navigate=useNavigate();
 const [topups,setTopups]=useState([]),[status,setStatus]=useState('all'),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const request=async(path,options={})=>{if(!getToken()){clearSession();navigate('/login',{replace:true});throw new Error('Your admin session has expired. Please sign in again.')}return apiRequest(path,options)};
 const load=async()=>{setLoading(true);setError('');try{const q=new URLSearchParams({status,search});const data=await request(`/wallet/topups?${q}`);setTopups(Array.isArray(data)?data:data.items||[])}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[status]);
 const update=async(id,next)=>{try{await request(`/wallet/topups/${id}/status`,{method:'PATCH',body:JSON.stringify({status:next})});await load()}catch(e){setError(e.message)}};
 const money=v=>`₹${Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`;
 const counts=useMemo(()=>({total:topups.length,pending:topups.filter(x=>x.status==='pending').length,approved:topups.filter(x=>x.status==='approved').length}),[topups]);
 return <section className="admin-topups-page"><div className="topups-heading"><div><span className="eyebrow">WALLET</span><h1>Manual Top-ups</h1><p>Review proof-backed wallet funding requests.</p></div><button onClick={load}>↻ Refresh</button></div><div className="topup-cards"><div><span>Total</span><b>{counts.total}</b></div><div><span>Pending</span><b>{counts.pending}</b></div><div><span>Approved</span><b>{counts.approved}</b></div></div><div className="topup-panel"><div className="topup-toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="Search user, email or reference..."/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select></div>{error&&<div className="topup-error">{error}</div>}<div className="topup-table-wrap"><table><thead><tr><th>ID</th><th>USER</th><th>AMOUNT</th><th>REFERENCE</th><th>PROOF</th><th>STATUS</th><th>REVIEWED BY</th><th>ACTION</th></tr></thead><tbody>{loading?<tr><td colSpan="8" className="topup-empty">Loading top-ups...</td></tr>:topups.length===0?<tr><td colSpan="8" className="topup-empty">No top-ups found.</td></tr>:topups.map(t=><tr key={t.id}><td>#{t.id}</td><td><b>{t.business_name||t.user_name||'—'}</b><small>{t.user_email}</small></td><td><strong>{money(t.amount)}</strong></td><td>{t.reference||t.manual_reference||'—'}</td><td>{t.proof_url?<a className="proof-button" href={t.proof_url} target="_blank" rel="noreferrer">View proof</a>:<span>—</span>}</td><td><span className={`topup-status ${t.status}`}>{t.status}</span></td><td className="reviewed-by">{t.reviewed_by_name||'—'}</td><td>{t.status==='pending'&&<div className="topup-actions"><button onClick={()=>update(t.id,'approved')}>Approve</button><button onClick={()=>update(t.id,'rejected')}>Reject</button></div>}</td></tr>)}</tbody></table></div></div></section>;
}