import { useEffect, useMemo, useState } from 'react'
import { apiRequest } from '../../utils/api'
import { getToken, clearSession } from '../../utils/auth'
import { useNavigate } from 'react-router-dom'
import './AdminCoupons.css'

const initial={code:'',description:'',discount_type:'percent',discount_value:'',max_discount:'',min_order_amount:'',usage_limit:'',per_user_limit:'',starts_at:'',expires_at:'',purchase_types:['membership','lead','booster'],user_ids:[],industry_ids:[],membership_plan_ids:[],is_active:true}
const money=v=>`₹${Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`
export default function AdminCoupons(){
 const navigate=useNavigate();const [coupons,setCoupons]=useState([]),[users,setUsers]=useState([]),[industries,setIndustries]=useState([]),[form,setForm]=useState(initial),[editing,setEditing]=useState(null),[search,setSearch]=useState(''),[status,setStatus]=useState('all'),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('')
 async function request(path,options={}){if(!getToken()){clearSession();navigate('/login',{replace:true});throw new Error('Your admin session has expired. Please sign in again.')}return apiRequest(path,options)}
 async function load(){try{setLoading(true);setError('');const [c,u,i]=await Promise.all([request(`/coupons?search=${encodeURIComponent(search.trim())}&status=${status}`),request('/admin/users?role=business&status=active'),request('/industries')]);setCoupons(Array.isArray(c)?c:[]);setUsers(Array.isArray(u)?u:[]);setIndustries(Array.isArray(i)?i:[])}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[status]);
 const filteredUsers=useMemo(()=>users.filter(u=>`${u.name||''} ${u.email||''} ${u.business_name||''}`.toLowerCase().includes(search.toLowerCase())),[users,search])
 function toggle(field,id){setForm(f=>({...f,[field]:f[field].includes(id)?f[field].filter(x=>x!==id):[...f[field],id]}))}
 function reset(){setForm(initial);setEditing(null)}
 async function save(e){e.preventDefault();if(saving)return;try{setSaving(true);setError('');const body={...form,discount_value:Number(form.discount_value),max_discount:form.max_discount===''?null:Number(form.max_discount),min_order_amount:Number(form.min_order_amount||0),usage_limit:form.usage_limit===''?null:Number(form.usage_limit),per_user_limit:form.per_user_limit===''?null:Number(form.per_user_limit)};await request(editing?`/coupons/${editing}`:'/coupons',{method:editing?'PATCH':'POST',body:JSON.stringify(body)});setNotice(editing?'Coupon updated successfully.':'Coupon created successfully.');reset();await load()}catch(e){setError(e.message)}finally{setSaving(false)}}
 async function toggleActive(c){try{setError('');await request(`/coupons/${c.id}/status`,{method:'PATCH',body:JSON.stringify({isActive:!c.is_active})});await load()}catch(e){setError(e.message)}}
 async function edit(c){try{const d=await request(`/coupons/${c.id}`);setEditing(d.id);setForm({...initial,...d,user_ids:(d.users||[]).map(x=>x.id),industry_ids:(d.industries||[]).map(x=>x.id),purchase_types:Array.isArray(d.purchase_types)?d.purchase_types:JSON.parse(d.purchase_types||'[]'),membership_plan_ids:Array.isArray(d.membership_plan_ids)?d.membership_plan_ids:JSON.parse(d.membership_plan_ids||'[]')})}catch(e){setError(e.message)}}
 return <section className="admin-coupons"><div className="coupon-head"><div><span>PAYMENTS / COUPONS</span><h1>Coupons</h1><p>Create targeted discounts without changing the existing payment flow.</p></div><button onClick={reset}>{editing?'Cancel edit':'Create coupon'}</button></div>{error&&<div className="coupon-error">{error}</div>}{notice&&<div className="coupon-notice">{notice}</div>}
 <div className="coupon-grid"><form className="coupon-form" onSubmit={save}><div className="coupon-form-head"><h2>{editing?'Edit coupon':'Create coupon'}</h2><span>{editing?`#${editing}`:'New promotion'}</span></div><div className="coupon-fields"><label>Code<input required value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase()})} placeholder="WELCOME20"/></label><label>Description<input value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="New customer offer"/></label><label>Discount type<select value={form.discount_type} onChange={e=>setForm({...form,discount_type:e.target.value})}><option value="percent">Percentage</option><option value="fixed">Fixed amount</option></select></label><label>Discount value<input required type="number" min="0.01" step="0.01" value={form.discount_value} onChange={e=>setForm({...form,discount_value:e.target.value})}/></label><label>Maximum discount<input type="number" min="0" step="0.01" value={form.max_discount} onChange={e=>setForm({...form,max_discount:e.target.value})} placeholder="Optional"/></label><label>Minimum order<input type="number" min="0" step="0.01" value={form.min_order_amount} onChange={e=>setForm({...form,min_order_amount:e.target.value})}/></label><label>Total usage limit<input type="number" min="1" step="1" value={form.usage_limit} onChange={e=>setForm({...form,usage_limit:e.target.value})} placeholder="Unlimited"/></label><label>Per-user limit<input type="number" min="1" step="1" value={form.per_user_limit} onChange={e=>setForm({...form,per_user_limit:e.target.value})} placeholder="Unlimited"/></label><label>Starts at<input type="datetime-local" value={form.starts_at?String(form.starts_at).slice(0,16):''} onChange={e=>setForm({...form,starts_at:e.target.value})}/></label><label>Expires at<input type="datetime-local" value={form.expires_at?String(form.expires_at).slice(0,16):''} onChange={e=>setForm({...form,expires_at:e.target.value})}/></label></div>
 <div className="coupon-scope"><h3>Purchase types</h3>{['membership','lead','booster'].map(x=><label className="check" key={x}><input type="checkbox" checked={form.purchase_types.includes(x)} onChange={()=>toggle('purchase_types',x)}/>{x[0].toUpperCase()+x.slice(1)}</label>)}</div>
 <div className="coupon-scope"><h3>Industries <small>Leave empty for all industries</small></h3><div className="coupon-options">{industries.map(i=><label className="check" key={i.id}><input type="checkbox" checked={form.industry_ids.includes(i.id)} onChange={()=>toggle('industry_ids',i.id)}/>{i.name}</label>)}</div></div>
 <div className="coupon-scope"><h3>Specific users <small>Leave empty for all users</small></h3><div className="coupon-options">{filteredUsers.map(u=><label className="check" key={u.id}><input type="checkbox" checked={form.user_ids.includes(u.id)} onChange={()=>toggle('user_ids',u.id)}/><span>{u.business_name||u.name}<small>{u.email}</small></span></label>)}</div></div>
 <label className="coupon-active"><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/> Active immediately</label><button className="coupon-save" disabled={saving}>{saving?'Saving…':editing?'Save changes':'Create coupon'}</button></form>
 <div className="coupon-list"><div className="coupon-list-toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="Search coupon code or description..."/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All</option><option value="active">Active</option><option value="inactive">Inactive</option></select><button onClick={load}>Search</button></div>{loading?<div className="coupon-empty">Loading coupons…</div>:!coupons.length?<div className="coupon-empty">No coupons created yet.</div>:<div className="coupon-table"><table><thead><tr><th>CODE</th><th>DISCOUNT</th><th>SCOPE</th><th>USAGE</th><th>VALIDITY</th><th>STATUS</th><th>ACTION</th></tr></thead><tbody>{coupons.map(c=><tr key={c.id}><td><b>{c.code}</b><small>{c.description||'—'}</small></td><td><strong>{c.discount_type==='percent'?`${c.discount_value}%`:money(c.discount_value)}</strong>{c.max_discount&&<small>Max {money(c.max_discount)}</small>}</td><td><small>{Number(c.target_user_count)>0?`${c.target_user_count} users`:'All users'}</small><small>{Number(c.target_industry_count)>0?c.target_industries:'All industries'}</small></td><td>{c.redeemed_count}{c.usage_limit?` / ${c.usage_limit}`:' / ∞'}</td><td><small>{c.starts_at?new Date(c.starts_at).toLocaleString('en-IN'):'Now'}</small><small>{c.expires_at?`Until ${new Date(c.expires_at).toLocaleString('en-IN')}`:'No expiry'}</small></td><td><span className={c.is_active?'coupon-active-badge':'coupon-inactive-badge'}>{c.is_active?'ACTIVE':'INACTIVE'}</span></td><td><button onClick={()=>edit(c)}>Edit</button><button onClick={()=>toggleActive(c)}>{c.is_active?'Deactivate':'Activate'}</button></td></tr>)}</tbody></table></div>}</div></div></section>
}
