import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { apiRequest } from '../../utils/api'
import { clearSession, getToken } from '../../utils/auth'
import './AdminInvestmentAdAllocations.css'

const money=value=>`₹${Number(value||0).toLocaleString('en-IN',{maximumFractionDigits:2})`
const date=value=>value?new Date(value).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'}):'—'

export default function AdminInvestmentAdAllocations(){
 const navigate=useNavigate();const [items,setItems]=useState([]);const [drafts,setDrafts]=useState({});const [loading,setLoading]=useState(true);const [busy,setBusy]=useState({});const [error,setError]=useState('');const [message,setMessage]=useState('')
 const request=async(path,options={})=>{if(!getToken()){clearSession();navigate('/login',{replace:true});throw new Error('Admin session expired')}return apiRequest(path,options)}
 const load=async()=>{setLoading(true);setError('');try{const result=await request('/investments/admin/all');const rows=Array.isArray(result)?result:result?.data||[];setItems(rows);setDrafts(Object.fromEntries(rows.map(item=>[item.id,String(Number(item.amount_in_ads||0))])))}catch(e){setError(e.message||'Unable to load investment cycles')}finally{setLoading(false)}}
 useEffect(()=>{load()},[])
 const totals=useMemo(()=>items.reduce((out,item)=>{if(String(item.status).toLowerCase()==='cancelled')return out;out.invested+=Number(item.amount||0);out.ads+=Number(item.amount_in_ads||0);return out},{invested:0,ads:0}),[items])
 const save=async item=>{const value=Number(drafts[item.id]);if(!Number.isFinite(value)||value<0)return setError('Amount in ads must be zero or greater.');if(value>Number(item.amount))return setError(`Ad amount cannot exceed ${money(item.amount)} for cycle #${item.id}.`);setBusy(x=>({...x,[item.id]:true}));setError('');setMessage('');try{const result=await request(`/investments/admin/${item.id}/ad-amount`,{method:'PUT',body:JSON.stringify({amount:value})});setItems(rows=>rows.map(x=>x.id===item.id?{...x,amount_in_ads:Number(result.amount_in_ads||value)}:x));setMessage(`Cycle #${item.id}: amount in ads updated to ${money(value)}.`)}catch(e){setError(e.message||'Unable to update amount in ads')}finally{setBusy(x=>({...x,[item.id]:false}))}}
 return <main className="admin-ad-allocation-page"><header><div><span className="admin-ad-kicker">INVESTOR OPERATIONS</span><h1>Investment Ad Allocations</h1><p>Set how much of each investor cycle is currently deployed into advertising. The remaining investment capital is protected and cannot be transferred as generated funds.</p></div><button type="button" onClick={load}>↻ Refresh</button></header>{error&&<div className="admin-ad-error">{error}</div>}{message&&<div className="admin-ad-message">{message}</div>}
 <section className="admin-ad-summary"><article><span>TOTAL INVESTED</span><strong>{money(totals.invested)}</strong></article><article><span>AMOUNT IN ADS</span><strong>{money(totals.ads)}</strong></article><article><span>UNALLOCATED CAPITAL</span><strong>{money(Math.max(0,totals.invested-totals.ads))}</strong></article></section>
 <section className="admin-ad-panel">{loading?<div className="admin-ad-empty">Loading investment cycles…</div>:!items.length?<div className="admin-ad-empty">No investment cycles found.</div>:<div className="admin-ad-table-wrap"><table><thead><tr><th>Investor</th><th>Cycle</th><th>Investment</th><th>Amount in ads</th><th>Protected / unallocated</th><th>Status</th><th>Action</th></tr></thead><tbody>{items.map(item=>{const invested=Number(item.amount||0);const ads=Number(item.amount_in_ads||0);const remaining=Math.max(0,invested-ads);const cancelled=String(item.status).toLowerCase()==='cancelled';return <tr key={item.id}><td><strong>{item.user_name||item.investor_name||'Investor'}</strong><small>{item.user_email||''}</small></td><td><b>#{item.id}</b><small>{item.industry_name||'Investment'} · {item.city_name||item.state_name||'Location not set'}</small><small>{date(item.created_at)}</small></td><td><b>{money(invested)}</b></td><td><div className="admin-ad-input-wrap"><span>₹</span><input type="number" min="0" max={invested} step="0.01" value={drafts[item.id]??String(ads)} disabled={cancelled||busy[item.id]} onChange={e=>setDrafts(x=>({...x,[item.id]:e.target.value}))}/></div><small>Admin controlled</small></td><td><b>{money(remaining)}</b><small>Not transferable</small></td><td><span className={`admin-ad-status ${item.status}`}>{item.status}</span></td><td><button type="button" disabled={cancelled||busy[item.id]} onClick={()=>save(item)}>{busy[item.id]?'Saving…':'Save'}</button></td></tr>})}</tbody></table></div>}</section></main>
}
