import {useEffect,useMemo,useState} from 'react';
import{getToken,clearSession}from'../../utils/auth';
import{useNavigate}from'react-router-dom';
import'./AdminMembershipPlans.css';
import'./AdminMembershipPlansConfig.css';

const API='http://localhost:5000/api';
const defaultLeads=[{type:'shared',quantity:3,complimentary:true},{type:'premium',quantity:1,complimentary:true}];
const initialPeriods=[
 {key:'monthly',label:'Monthly',months:1,enabled:true,leadEntitlements:defaultLeads.map(x=>({...x}))},
 {key:'quarterly',label:'Quarterly',months:3,enabled:true,leadEntitlements:[{type:'shared',quantity:10,complimentary:true},{type:'premium',quantity:3,complimentary:true}]},
 {key:'yearly',label:'Yearly',months:12,enabled:true,leadEntitlements:[{type:'shared',quantity:40,complimentary:true},{type:'premium',quantity:12,complimentary:true}]}
];
const cloneForm=()=>({name:'',monthlyBasePrice:'',periods:initialPeriods.map(p=>({...p,leadEntitlements:p.leadEntitlements.map(e=>({...e}))})),pricing:{monthly:{discount:0,price:'',customPrice:false},quarterly:{discount:0,price:'',customPrice:false},yearly:{discount:0,price:'',customPrice:false}},benefits:['Pro lead pricing']});
const money=n=>`₹${Number(n||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`;
const makeKey=()=>`period_${Date.now()}_${Math.random().toString(36).slice(2,6)}`;

export default function AdminMembershipPlansConfig(){
 const nav=useNavigate();
 const[plans,setPlans]=useState([]),[form,setForm]=useState(cloneForm()),[editing,setEditing]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 async function req(path,opt={}){const t=getToken();if(!t){clearSession();nav('/login',{replace:true});throw Error('Session expired')}const r=await fetch(API+path,{...opt,headers:{'Content-Type':'application/json',Authorization:`Bearer ${t}`}}),d=await r.json().catch(()=>({}));if(r.status===401){clearSession();nav('/login',{replace:true});throw Error('Session expired')}if(!r.ok)throw Error(d.error||'Request failed');return d}
 async function load(){setLoading(true);try{const a=await req('/membership-plans');setPlans(a.filter(p=>p.plan_type==='pro'))}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const grouped=useMemo(()=>{const m={};plans.forEach(p=>{const k=p.plan_group||p.name.replace(/\s+(Monthly|Quarterly|Yearly)$/i,'');(m[k]??=[]).push(p)});return Object.values(m)},[plans]);
 const set=(k,v)=>setForm(x=>({...x,[k]:v}));
 const setPeriod=(key,k,v)=>setForm(x=>({...x,periods:x.periods.map(p=>p.key===key?{...p,[k]:v}:p)}));
 const setP=(key,k,v)=>setForm(x=>({...x,pricing:{...x.pricing,[key]:{...(x.pricing[key]||{discount:0,price:'',customPrice:false}),[k]:v}}}));
 const periodPrice=p=>{const cfg=form.pricing[p.key]||{discount:0,price:'',customPrice:false};const list=Number(form.monthlyBasePrice||0)*Number(p.months||1);const calculated=list*(1-(Number(cfg.discount)||0)/100);const final=cfg.customPrice&&cfg.price!==''?Number(cfg.price):calculated;return{list,final,saving:Math.max(0,list-final)}};
 const addPeriod=()=>{const key=makeKey();setForm(x=>({...x,periods:[...x.periods,{key,label:'Custom',months:1,enabled:true,leadEntitlements:defaultLeads.map(e=>({...e}))}],pricing:{...x.pricing,[key]:{discount:0,price:'',customPrice:false}}}))};
 const removePeriod=key=>setForm(x=>({...x,periods:x.periods.filter(p=>p.key!==key),pricing:Object.fromEntries(Object.entries(x.pricing).filter(([k])=>k!==key))}));
 const addEntitlement=key=>setForm(x=>({...x,periods:x.periods.map(p=>p.key===key?{...p,leadEntitlements:[...p.leadEntitlements,{type:'shared',quantity:1,complimentary:true}]}:p)}));
 const setEnt=(key,i,k,v)=>setForm(x=>({...x,periods:x.periods.map(p=>p.key===key?{...p,leadEntitlements:p.leadEntitlements.map((e,n)=>n===i?{...e,[k]:v}:e)}:p)}));
 const removeEnt=(key,i)=>setForm(x=>({...x,periods:x.periods.map(p=>p.key===key?{...p,leadEntitlements:p.leadEntitlements.filter((_,n)=>n!==i)}:p)}));
 async function create(e){e.preventDefault();setError('');const active=form.periods.filter(p=>p.enabled&&Number(p.months)>0);if(!active.length)return setError('Add at least one billing period.');try{await req('/membership-plans',{method:'POST',body:JSON.stringify({name:form.name,planType:'pro',bundle:true,monthlyBasePrice:Number(form.monthlyBasePrice||0),periods:active.map(p=>({...p,leadEntitlements:p.leadEntitlements.map(e=>({...e,quantity:Number(e.quantity)||0}))})),pricing:Object.fromEntries(active.map(p=>[p.key,{discount:Number(form.pricing[p.key]?.discount)||0,price:form.pricing[p.key]?.price||'',customPrice:Boolean(form.pricing[p.key]?.customPrice)}])),benefits:form.benefits})});setForm(cloneForm());await load()}catch(e){setError(e.message)}}
 function startEdit(p){setEditing(p.id);setForm({name:p.plan_group||p.name,monthlyBasePrice:p.monthly_base_price||'',periods:[{key:'edit',label:p.billing_period||'Period',months:Number(p.billing_months||1),enabled:true,leadEntitlements:(Array.isArray(p.lead_entitlements)?p.lead_entitlements:[]).map(e=>({...e}))}],pricing:{edit:{discount:Number(p.discount_percent)||0,price:p.price||'',customPrice:true}},benefits:Array.isArray(p.benefits)?p.benefits:['Pro lead pricing']});window.scrollTo({top:0,behavior:'smooth'})}
 async function saveEdit(e){e.preventDefault();setError('');const p=form.periods[0],cfg=form.pricing.edit||{};try{await req(`/membership-plans/${editing}`,{method:'PUT',body:JSON.stringify({name:`${form.name} ${p.label}`,planGroup:form.name,planType:'pro',billingPeriod:p.label,billingMonths:Number(p.months||1),monthlyBasePrice:Number(form.monthlyBasePrice||0),discountPercent:Number(cfg.discount)||0,priceOverride:cfg.customPrice&&cfg.price!==''?Number(cfg.price):'',benefits:form.benefits,leadEntitlements:p.leadEntitlements.map(e=>({...e,quantity:Number(e.quantity)||0}))})});setEditing(null);setForm(cloneForm());await load()}catch(e){setError(e.message)}}
 async function toggle(p){try{await req(`/membership-plans/${p.id}/status`,{method:'PATCH',body:JSON.stringify({isActive:!p.is_active})});load()}catch(e){setError(e.message)}}
 async function del(p){if(confirm(`Delete ${p.name}?`))try{await req(`/membership-plans/${p.id}`,{method:'DELETE'});load()}catch(e){setError(e.message)}}
 return <main className="commercial-page"><header className="commercial-head"><div><span>COMMERCIAL</span><h1>Membership Plans</h1><p>Configure billing periods, live pricing, discounts and complimentary leads.</p></div></header>{error&&<div className="error">{error}</div>}
 <section className="create-card hero-card"><div className="card-heading"><div><div className="eyebrow">{editing?'EDIT MEMBERSHIP':'PRO MEMBERSHIP'}</div><h2>{editing?'Update billing period':'Build a Pro plan'}</h2><p>Set a different lead allowance for every billing duration.</p></div><div className="pro-badge">PRO</div></div>
 <form onSubmit={editing?saveEdit:create}><div className="two"><label>Plan name<input value={form.name} onChange={e=>set('name',e.target.value)} placeholder="Pro" required/></label><label>Monthly base price ₹<input type="number" min="0" step="0.01" value={form.monthlyBasePrice} onChange={e=>set('monthlyBasePrice',e.target.value)} placeholder="999" required/></label></div>
 <div className="section-label"><div><b>Billing periods & lead allowance</b><small>Longer periods can include more leads.</small></div>{!editing&&<button type="button" className="mini-action" onClick={addPeriod}>＋ Add period</button>}</div>
 <div className="pricing-grid">{form.periods.map(p=>{const x=periodPrice(p),cfg=form.pricing[p.key]||{discount:0,price:'',customPrice:false};return <div className={`pricing-box ${p.enabled?'':'muted-box'}`} key={p.key}><div className="period-editor"><input className="period-name" value={p.label} onChange={e=>setPeriod(p.key,'label',e.target.value)}/><button type="button" className="icon-button" onClick={()=>setPeriod(p.key,'enabled',!p.enabled)}>{p.enabled?'On':'Off'}</button>{!editing&&form.periods.length>1&&<button type="button" className="remove-period" onClick={()=>removePeriod(p.key)}>×</button>}</div><label>Duration (months)<input type="number" min="1" step="1" value={p.months} onChange={e=>setPeriod(p.key,'months',e.target.value)}/></label><div className="price-preview"><small>List price</small><b>{money(x.list)}</b><span>{p.months} month{Number(p.months)===1?'':'s'} × base</span></div><label>Discount %<input type="number" min="0" max="100" step="0.01" value={cfg.discount} onChange={e=>setP(p.key,'discount',e.target.value)}/></label><label className="check-row"><input type="checkbox" checked={Boolean(cfg.customPrice)} onChange={e=>setP(p.key,'customPrice',e.target.checked)}/><span>Custom final price</span></label>{cfg.customPrice&&<label>Final price ₹<input type="number" min="0" step="0.01" value={cfg.price} onChange={e=>setP(p.key,'price',e.target.value)}/></label>}<div className="final-price"><div><small>Customer pays</small><strong>{money(x.final)}</strong></div>{x.saving>0&&<span>Save {money(x.saving)}</span>}</div>
 <div className="period-leads"><div className="period-leads-head"><div><b>Included leads</b><small>Set allowance for this period</small></div><button type="button" onClick={()=>addEntitlement(p.key)}>＋ Add</button></div>{p.leadEntitlements.length===0&&<div className="no-leads">No complimentary leads</div>}{p.leadEntitlements.map((e,i)=><div className="lead-row" key={i}><select value={e.type} onChange={ev=>setEnt(p.key,i,'type',ev.target.value)}><option value="shared">Shared</option><option value="premium">Premium</option><option value="standard">Standard</option></select><input aria-label="Lead quantity" type="number" min="0" value={e.quantity} onChange={ev=>setEnt(p.key,i,'quantity',ev.target.value)}/><label className="check-row"><input type="checkbox" checked={e.complimentary!==false} onChange={ev=>setEnt(p.key,i,'complimentary',ev.target.checked)}/><span>Free</span></label><button type="button" className="remove-lead" onClick={()=>removeEnt(p.key,i)}>×</button></div>)}</div>
 </div>})}</div>
 <div className="benefits"><div className="benefit-head"><div><b>Other benefits</b><small>Optional text benefits.</small></div><button type="button" onClick={()=>{const b=prompt('Add benefit');if(b?.trim())setForm(x=>({...x,benefits:[...x.benefits,b.trim()]}))}}>＋ Add</button></div><div className="chips">{form.benefits.map((b,i)=><span key={i}>{b}<button type="button" onClick={()=>setForm(x=>({...x,benefits:x.benefits.filter((_,n)=>n!==i)}))}>×</button></span>)}</div></div>
 <div className="form-footer"><button className="primary">{editing?'Save changes':'Create Pro plan'}</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm(cloneForm())}}>Cancel</button>}</div></form></section>
 <section className="plans-list">{loading?<div className="empty">Loading…</div>:grouped.length?grouped.map(g=><div className="plan-group" key={g[0].plan_group||g[0].id}><div className="group-head"><div><div className="eyebrow">PRO PLAN</div><h2>{g[0].plan_group||g[0].name}</h2></div><span className="live-count">{g.filter(x=>x.is_active).length}/{g.length} active</span></div>{g.sort((a,b)=>Number(a.billing_months||1)-Number(b.billing_months||1)).map(p=>{const list=Number(p.monthly_base_price||0)*Number(p.billing_months||1),final=Number(p.price||0),saving=Math.max(0,list-final),ents=Array.isArray(p.lead_entitlements)?p.lead_entitlements:[];return <div className="option" key={p.id}><div><b>{p.billing_period}</b><small>{Number(p.billing_months||1)} month{Number(p.billing_months||1)===1?'':'s'} · {p.discount_percent||0}% discount</small>{ents.length>0&&<div className="allocation-mini">{ents.map((e,i)=><span key={i}>{e.quantity} {e.type}{e.complimentary!==false?' complimentary':''}</span>)}</div>}</div><div className="price-stack">{saving>0&&<del>{money(list)}</del>}<strong>{money(final)}</strong>{saving>0&&<small>Save {money(saving)}</small>}</div><div className="actions"><button onClick={()=>startEdit(p)}>Edit</button><button onClick={()=>toggle(p)}>{p.is_active?'Disable':'Enable'}</button><button className="danger" onClick={()=>del(p)}>Delete</button></div></div>})}</div>):<div className="empty plan-empty"><strong>No Pro plan yet</strong><span>Create your first configurable membership above.</span></div>}</section></main>
}
