import { useEffect, useState } from 'react'
import { apiRequest } from '../../utils/api'
import { getToken } from '../../utils/auth'
import './AdminInvestorPayoutRequests.css'

const money=v=>`₹${Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`
const date=v=>v?new Date(v).toLocaleString('en-IN',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}):'—'
const fileToDataUrl=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(new Error('Unable to read proof'));r.readAsDataURL(file)})

export default function AdminInvestorPayoutRequests(){
 const [items,setItems]=useState([]),[status,setStatus]=useState('pending'),[search,setSearch]=useState(''),[selected,setSelected]=useState(null),[reference,setReference]=useState(''),[proof,setProof]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(true)
 const load=async()=>{setLoading(true);try{const q=new URLSearchParams({status,search});const data=await apiRequest(`/investments/admin/transfer-requests?${q}`,{headers:{Authorization:`Bearer ${getToken()}`}});setItems(Array.isArray(data)?data:[]);setError('')}catch(e){setError(e.message||'Unable to load transfer requests')}finally{setLoading(false)}}
 useEffect(()=>{load()},[status])
 const process=async action=>{if(!selected)return;setError('');if(action==='pay'){if(!reference.trim())return setError('Enter transfer reference / UTR.');if(!proof)return setError('Attach transfer proof.');if(proof.size>5*1024*1024)return setError('Proof must be 5 MB or smaller.')}setBusy(true);try{const proofUrl=action==='pay'?await fileToDataUrl(proof):null;await apiRequest(`/investments/admin/transfer-requests/${selected.id}/process`,{method:'POST',headers:{Authorization:`Bearer ${getToken()}`,'Content-Type':'application/json'},body:JSON.stringify({action,transferReference:reference,proofUrl})});setSelected(null);setReference('');setProof(null);await load()}catch(e){setError(e.message||'Unable to process request')}finally{setBusy(false)}}
 return <main className="admin-transfer-page"><header><div><span>INVESTOR OPERATIONS</span><h1>Generated funds transfers</h1><p>Review investor requests to transfer revenue generated from paid lead sales. Investment capital remains separate.</p></div><button onClick={load}>↻ Refresh</button></header>{error&&<div className="admin-transfer-error">{error}</div>}<section className="admin-transfer-toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="Search investor or email..."/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="pending">Pending</option><option value="paid">Paid</option><option value="rejected">Rejected</option><option value="all">All</option></select><button onClick={load}>Search</button></section>{loading?<div className="admin-transfer-empty">Loading requests…</div>:!items.length?<div className="admin-transfer-empty">No transfer requests found.</div>:<section className="admin-transfer-list">{items.map(item=><article key={item.id}><div><strong>#{item.id} · {item.user_name||'Investor'}</strong><small>{item.user_email} · {date(item.requested_at)}</small></div><b>{money(item.amount)}</b><span className={`admin-transfer-status ${item.status}`}>{item.status}</span>{item.status==='pending'&&<button onClick={()=>{setSelected(item);setReference('');setProof(null);setError('')}}>Review</button>}{item.transfer_reference&&<small>UTR: {item.transfer_reference}</small>}</article>)}</section>}{selected&&<div className="admin-transfer-overlay"><section className="admin-transfer-modal"><button className="close" onClick={()=>!busy&&setSelected(null)}>×</button><span>INVESTOR TRANSFER</span><h2>Request #{selected.id}</h2><p>{selected.user_name} · {selected.user_email}</p><div className="admin-transfer-amount"><span>Amount requested</span><strong>{money(selected.amount)}</strong></div><p>This amount is from generated lead-sale revenue, not the investor's deployed advertising capital.</p><label>Transfer reference / UTR<input value={reference} onChange={e=>setReference(e.target.value)} placeholder="Enter UTR"/></label><label>Transfer proof<input type="file" accept="image/*,.pdf" onChange={e=>setProof(e.target.files?.[0]||null)}/></label><div className="admin-transfer-actions"><button className="reject" disabled={busy} onClick={()=>process('reject')}>Reject</button><button className="pay" disabled={busy} onClick={()=>process('pay')}>{busy?'Processing…':'Confirm transfer'}</button></div></section></div>}</main>
}
