import { useEffect, useState } from 'react'
import { apiRequest } from '../../utils/api'
import { getToken, clearSession } from '../../utils/auth'
import { useNavigate } from 'react-router-dom'
import './AdminTable.css'
import './AdminPayments.css'

export default function AdminPayments(){
 const navigate=useNavigate();
 const [tab,setTab]=useState('approvals');
 const [payments,setPayments]=useState([]),[topups,setTopups]=useState([]);
 const [status,setStatus]=useState('all'),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(null),[error,setError]=useState(''),[page,setPage]=useState(1);
 const [paymentMeta,setPaymentMeta]=useState({total:0,pages:0,stats:{total:0,pending:0,paid:0,manual:0}});
 const [topupMeta,setTopupMeta]=useState({total:0,pages:0,stats:{total:0,pending:0,approved:0,rejected:0,approved_amount:0}});
 async function request(path,options={}){if(!getToken()){clearSession();navigate('/login',{replace:true});throw new Error('Your admin session has expired. Please sign in again.')}return apiRequest(path,options)}
 async function loadPayments(nextPage=1){
  const qs=new URLSearchParams({status,search:search.trim(),page:String(nextPage),limit:'50'});const data=await request(`/payments?${qs}`);
  setPayments(Array.isArray(data)?data:data.items||[]);setPaymentMeta({total:data.total??0,pages:data.pages??1,stats:data.stats||{total:data.total??0,pending:0,paid:0,manual:0}});setPage(nextPage)
 }
 async function loadTopups(nextPage=1){
  const qs=new URLSearchParams({status,search:search.trim(),page:String(nextPage),limit:'50'});const data=await request(`/wallet/topups?${qs}`);
  setTopups(Array.isArray(data)?data:data.items||[]);setTopupMeta({total:data.total??0,pages:data.pages??1,stats:data.stats||{total:data.total??0,pending:0,approved:0,rejected:0,approved_amount:0}});setPage(nextPage)
 }
 async function load(nextPage=1){setLoading(true);setError('');try{if(tab==='topups')await loadTopups(nextPage);else await loadPayments(nextPage)}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load(1)},[tab,status]);
 async function updatePayment(id,next){if(busy!==null)return;setBusy(`payment-${id}`);setError('');try{await request(`/payments/${id}/status`,{method:'PATCH',body:JSON.stringify({status:next})});await load(page)}catch(e){setError(e.message)}finally{setBusy(null)}}
 async function updateTopup(id,next){if(busy!==null)return;setBusy(`topup-${id}`);setError('');try{const endpoint=next==='approved'?`/wallet/topups/${id}/approve`:`/wallet/topups/${id}/reject`;await request(endpoint,{method:'PATCH'});await load(page)}catch(e){setError(e.message)}finally{setBusy(null)}}
 const money=v=>`₹${Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`;
 const openProof=proof=>{if(!proof)return;const win=window.open();if(win){const safe=String(proof).replaceAll('"','&quot;');win.document.write(`<title>Payment Proof</title><style>body{margin:0;background:#111;display:flex;align-items:center;justify-content:center;min-height:100vh}img{max-width:95vw;max-height:95vh;object-fit:contain}iframe{width:95vw;height:95vh;border:0;background:#fff}</style>${String(proof).startsWith('data:application/pdf')?`<iframe src="${safe}"></iframe>`:`<img src="${safe}" alt="Payment proof"/>`}`);win.document.close()}};
 const pstats=paymentMeta.stats||{};const tstats=topupMeta.stats||{};
 return <section className="admin-payments-page">
  <div className="payments-heading"><div><span className="eyebrow">FINANCE</span><h1>Payments</h1><p>Membership payment requests and wallet top-up approvals, history and balances.</p></div><button disabled={loading} onClick={()=>load(1)}>↻ Refresh</button></div>
  <div className="payment-tabs" role="tablist"><button className={tab==='approvals'?'active':''} onClick={()=>{setTab('approvals');setStatus('pending')}}>Payment Approvals</button><button className={tab==='membership'?'active':''} onClick={()=>{setTab('membership');setStatus('all')}}>Membership Payments</button><button className={tab==='topups'?'active':''} onClick={()=>{setTab('topups');setStatus('all')}}>Wallet Top-ups</button></div>
  {tab==='topups'?<div className="payment-cards"><div><span>Total top-ups</span><b>{tstats.total??topupMeta.total}</b></div><div><span>Pending approvals</span><b>{tstats.pending??0}</b></div><div><span>Approved</span><b>{tstats.approved??0}</b></div><div><span>Approved value</span><b>{money(tstats.approved_amount)}</b></div></div>:<div className="payment-cards"><div><span>Membership payments</span><b>{pstats.total??paymentMeta.total}</b></div><div><span>Pending approvals</span><b>{pstats.pending??0}</b></div><div><span>Paid</span><b>{pstats.paid??0}</b></div><div><span>Manual requests</span><b>{pstats.manual??0}</b></div></div>}
  <div className="payment-panel"><div className="payment-toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load(1)} placeholder={tab==='topups'?'Search user, email, business or UTR...':'Search owner, email, business, plan or reference...'}/><select value={status} onChange={e=>setStatus(e.target.value)}>{tab==='topups'?<><option value="all">All top-up statuses</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option></>:<><option value="all">All payment statuses</option><option value="pending">Pending</option><option value="paid">Paid</option><option value="rejected">Rejected</option><option value="failed">Failed</option><option value="refunded">Refunded</option></>}</select><button disabled={loading} onClick={()=>load(1)}>Search</button></div>
  {error&&<div className="payment-error">{error}</div>}
  <div className="payment-table-wrap"><table><thead>{tab==='topups'?<tr><th>ID</th><th>BUSINESS / USER</th><th>TOP-UP</th><th>WALLET BALANCE</th><th>METHOD</th><th>REFERENCE / UTR</th><th>PROOF</th><th>STATUS</th><th>REVIEWED BY</th><th>ACTION</th></tr>:<tr><th>ID</th><th>BUSINESS / USER</th><th>TYPE / PLAN</th><th>METHOD</th><th>AMOUNT</th><th>WALLET BALANCE</th><th>REFERENCE</th><th>PROOF</th><th>STATUS</th><th>ACTION</th></tr>}</thead><tbody>
   {loading?<tr><td colSpan="10" className="payment-empty">Loading...</td></tr>:tab==='topups'?(topups.length===0?<tr><td colSpan="10" className="payment-empty">No wallet top-ups found.</td></tr>:topups.map(t=><tr key={`topup-${t.id}`}><td>#{t.id}</td><td><b>{t.business_name||t.user_name||'—'}</b><small>{t.user_email}</small></td><td><strong>{money(t.amount)}</strong></td><td><strong>{money(t.wallet_balance)}</strong></td><td>{t.payment_method||'manual'}</td><td>{t.reference||'—'}</td><td>{t.proof_url?<button type="button" className="proof-button" onClick={()=>openProof(t.proof_url)}>View proof</button>:<span>—</span>}</td><td><span className={`pay-status ${t.status}`}>{t.status}</span></td><td>{t.reviewer_name||'—'}</td><td>{t.status==='pending'&&<div className="pay-actions"><button disabled={busy!==null} onClick={()=>updateTopup(t.id,'approved')}>{busy===`topup-${t.id}`?'Working…':'Approve'}</button><button disabled={busy!==null} onClick={()=>updateTopup(t.id,'rejected')}>Reject</button></div>}</td></tr>)):(payments.length===0?<tr><td colSpan="10" className="payment-empty">No membership payments found.</td></tr>:payments.map(p=><tr key={`payment-${p.id}`}><td>#{p.id}</td><td><b>{p.business_name||p.user_name||'—'}</b><small>{p.user_email}</small></td><td><span>{p.payment_type||'membership'}</span><small>{p.membership_plan_name||'—'}</small></td><td><span className="method">{p.payment_method}</span></td><td><strong>{money(p.amount)}</strong></td><td><strong>{money(p.wallet_balance)}</strong></td><td>{p.manual_reference||p.gateway_payment_id||'—'}</td><td>{p.proof_url?<button type="button" className="proof-button" onClick={()=>openProof(p.proof_url)}>View proof</button>:<span>—</span>}</td><td><span className={`pay-status ${p.status}`}>{p.status}</span></td><td>{p.status==='pending'&&<div className="pay-actions"><button disabled={busy!==null} onClick={()=>updatePayment(p.id,'paid')}>{busy===`payment-${p.id}`?'Working…':'Approve'}</button><button disabled={busy!==null} onClick={()=>updatePayment(p.id,'rejected')}>Reject</button></div>}</td></tr>))}
  </tbody></table></div>
  {(tab==='topups'?topupMeta.pages:paymentMeta.pages)>1&&<div className="payment-toolbar"><button disabled={page<=1||loading} onClick={()=>load(page-1)}>Previous</button><span>Page {page} of {tab==='topups'?topupMeta.pages:paymentMeta.pages}</span><button disabled={page>=(tab==='topups'?topupMeta.pages:paymentMeta.pages)||loading} onClick={()=>load(page+1)}>Next</button></div>}
  </div>
 </section>
}
