import { useEffect, useMemo, useState } from 'react';
import { getToken, clearSession } from '../../utils/auth';
import { useNavigate } from 'react-router-dom';
import './AdminWalletTopups.css';

const API='http://localhost:5000/api';

export default function AdminWalletTopups(){
 const navigate=useNavigate();
 const [items,setItems]=useState([]),[status,setStatus]=useState('pending'),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(null);
 async function request(path,options={}){const token=getToken();if(!token){clearSession();navigate('/login',{replace:true});throw new Error('Your admin session has expired. Please sign in again.')}const r=await fetch(`${API}${path}`,{...options,headers:{'Content-Type':'application/json',...(options.headers||{}),Authorization:`Bearer ${token}`}});const data=await r.json().catch(()=>({}));if(r.status===401){clearSession();navigate('/login',{replace:true});throw new Error('Your admin session has expired. Please sign in again.')}if(!r.ok)throw new Error(data.error||'Request failed');return data}
 async function load(){setLoading(true);setError('');try{const qs=new URLSearchParams({status,search});setItems(await request(`/wallet/topups?${qs}`))}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[status]);
 async function review(id,next){if(!window.confirm(next==='approve'?'Approve this wallet top-up and credit the customer balance?':'Reject this wallet top-up?'))return;setBusy(id);setError('');try{await request(`/wallet/topups/${id}/${next}`,{method:'PATCH'});await load()}catch(e){setError(e.message)}finally{setBusy(null)}}
 function openProof(proof){if(!proof)return;const win=window.open();if(!win)return;const isPdf=String(proof).startsWith('data:application/pdf')||String(proof).toLowerCase().endsWith('.pdf');win.document.write(`<title>Wallet Top-up Proof</title><style>body{margin:0;background:#111;display:flex;align-items:center;justify-content:center;min-height:100vh}img{max-width:95vw;max-height:95vh;object-fit:contain}iframe{width:95vw;height:95vh;border:0;background:#fff}</style>${isPdf?`<iframe src="${proof}"></iframe>`:`<img src="${proof}" alt="Wallet top-up proof"/>`}`);win.document.close()}
 const counts=useMemo(()=>({pending:items.filter(x=>x.status==='pending').length,approved:items.filter(x=>x.status==='approved').length,rejected:items.filter(x=>x.status==='rejected').length}),[items]);
 const money=v=>`₹${Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`;
 return <section className="admin-topups-page"><div className="topups-heading"><div><span className="eyebrow">WALLET</span><h1>Wallet Top-ups</h1><p>Review customer wallet funding requests before adding money.</p></div><button onClick={load}>↻ Refresh</button></div><div className="topup-cards"><div><span>Pending</span><b>{counts.pending}</b></div><div><span>Approved</span><b>{counts.approved}</b></div><div><span>Rejected</span><b>{counts.rejected}</b></div></div><div className="topup-panel"><div className="topup-toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="Search customer, business, email or UTR..."/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option><option value="all">All statuses</option></select></div>{error&&<div className="topup-error">{error}</div>}<div className="topup-table-wrap"><table><thead><tr><th>ID</th><th>CUSTOMER</th><th>AMOUNT</th><th>REFERENCE / UTR</th><th>PROOF</th><th>SUBMITTED</th><th>STATUS</th><th>ACTION</th></tr></thead><tbody>{loading?<tr><td colSpan="8" className="topup-empty">Loading wallet top-ups...</td></tr>:items.length===0?<tr><td colSpan="8" className="topup-empty">No wallet top-ups found.</td></tr>:items.map(x=><tr key={x.id}><td>#{x.id}</td><td><b>{x.business_name||x.user_name||'—'}</b><small>{x.user_email}</small></td><td><strong>{money(x.amount)}</strong></td><td>{x.reference||'—'}</td><td>{x.proof_url?<button type="button" className="proof-button" onClick={()=>openProof(x.proof_url)}>View proof</button>:<span>—</span>}</td><td>{x.created_at?new Date(x.created_at).toLocaleString('en-IN'): '—'}</td><td><span className={`topup-status ${x.status}`}>{x.status}</span></td><td>{x.status==='pending'?<div className="topup-actions"><button disabled={busy===x.id} onClick={()=>review(x.id,'approve')}>{busy===x.id?'...':'Approve'}</button><button disabled={busy===x.id} onClick={()=>review(x.id,'reject')}>Reject</button></div>:<span className="reviewed-by">{x.reviewer_name?`By ${x.reviewer_name}`:'Reviewed'}</span>}</td></tr>)}</tbody></table></div></div></section>;
}
