import {useEffect,useState} from 'react';
import {apiRequest} from '../../utils/api';
import './AdminLeadPricing.css';

const BUYER_TIERS=[1,2,3];
const emptyPricing=()=>({shares:BUYER_TIERS.map(shares=>({shares,normal:0,pro:0}))});
const emptyForm=()=>({industryId:'',cityId:'',leadType:'basic',pricing:emptyPricing(),isActive:true});
const defaultAccess=()=>({
  basic:{accessStrategy:'auto_release',buyerCapacity:3,releaseToTwoAfterHours:24,releaseToThreeAfterHours:48},
  premium:{accessStrategy:'auto_release',buyerCapacity:3,releaseToTwoAfterHours:48,releaseToThreeAfterHours:96},
});
const types=['basic','premium'];
const cap=v=>String(v||'').replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const ruleKey=r=>`${r.industry_id??0}:${r.city_id??0}:${String(r.lead_type||'basic').toLowerCase()}`;
const dedupeRules=rows=>{const seen=new Set();return(Array.isArray(rows)?rows:[]).filter(r=>{const key=ruleKey(r);if(seen.has(key))return false;seen.add(key);return true})};
const fixedTiers=shares=>{const source=Array.isArray(shares)?shares:[],by=new Map(source.filter(x=>BUYER_TIERS.includes(Number(x?.shares))).map(x=>[Number(x.shares),x]));return BUYER_TIERS.map(n=>{const row=by.get(n)||by.get(n===1?2:n===2?3:2)||by.get(1)||by.get(3)||{};return{shares:n,normal:Number(row.normal)||0,pro:Number(row.pro)||0}})};

export default function AdminLeadPricing(){
 const[industries,setIndustries]=useState([]),[cities,setCities]=useState([]),[rules,setRules]=useState([]),[form,setForm]=useState(emptyForm()),[editId,setEditId]=useState(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[partnerSaving,setPartnerSaving]=useState(false),[partnerSettings,setPartnerSettings]=useState({commissionPercent:5,normalPriceUplift:100}),[partnerDirty,setPartnerDirty]=useState(false),[accessSettings,setAccessSettings]=useState(defaultAccess()),[accessSaving,setAccessSaving]=useState(false),[accessDirty,setAccessDirty]=useState(false),[error,setError]=useState(''),[ok,setOk]=useState('');
 const req=(p,o={})=>apiRequest(p,o);

 const load=async()=>{try{setLoading(true);setError('');const[a,b,c,d,e]=await Promise.all([req('/industries'),req('/cities'),req('/leads/pricing/rules'),req('/leads/pricing/partner-settings'),req('/leads/access-settings')]);setIndustries(Array.isArray(a)?a:[]);setCities(Array.isArray(b)?b:[]);setRules(dedupeRules(c));setPartnerSettings({commissionPercent:Number(d?.commissionPercent??5),normalPriceUplift:Number(d?.normalPriceUplift??100)});setAccessSettings({basic:{...defaultAccess().basic,...(e?.basic||{})},premium:{...defaultAccess().premium,...(e?.premium||{})}});setPartnerDirty(false);setAccessDirty(false)}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{let active=true;queueMicrotask(()=>{if(active)load()});return()=>{active=false}},[]);

 const setTier=(i,k,v)=>setForm(f=>({...f,pricing:{...f.pricing,shares:f.pricing.shares.map((x,n)=>n===i?{...x,[k]:v}:x)}}));
 const reset=()=>{setEditId(null);setForm(emptyForm())};
 const edit=r=>{setEditId(r.id);setForm({industryId:r.industry_id??'',cityId:r.city_id??'',leadType:r.lead_type||'basic',pricing:{shares:fixedTiers(r.pricing?.shares)},isActive:r.is_active});setOk('');setError('');window.scrollTo({top:0,behavior:'smooth'})};

 const save=async()=>{try{setSaving(true);setError('');setOk('');const cleanForm={...form,pricing:{shares:fixedTiers(form.pricing.shares)}};await req(editId?`/leads/pricing/rules/${editId}`:'/leads/pricing/rules',{method:editId?'PUT':'POST',body:JSON.stringify(cleanForm)});setOk(editId?'Pricing rule updated.':'Pricing rule saved.');reset();await load()}catch(e){setError(e.message)}finally{setSaving(false)}};
 const savePartnerSettings=async()=>{try{setPartnerSaving(true);setError('');setOk('');const clean={commissionPercent:Number(partnerSettings.commissionPercent),normalPriceUplift:Number(partnerSettings.normalPriceUplift)};await req('/leads/pricing/partner-settings',{method:'PUT',body:JSON.stringify(clean)});setPartnerSettings(clean);setPartnerDirty(false);setOk('Lead Partner pricing settings updated.')}catch(e){setError(e.message)}finally{setPartnerSaving(false)}};
 const saveAccessSettings=async()=>{try{setAccessSaving(true);setError('');setOk('');const clean={};for(const type of types){const row=accessSettings[type];clean[type]={accessStrategy:row.accessStrategy,buyerCapacity:Number(row.buyerCapacity),releaseToTwoAfterHours:row.accessStrategy==='auto_release'?Number(row.releaseToTwoAfterHours):null,releaseToThreeAfterHours:row.accessStrategy==='auto_release'?Number(row.releaseToThreeAfterHours):null}}const result=await req('/leads/access-settings',{method:'PUT',body:JSON.stringify(clean)});setAccessSettings({basic:{...defaultAccess().basic,...result.basic},premium:{...defaultAccess().premium,...result.premium}});setAccessDirty(false);setOk('Buyer access defaults updated.')}catch(e){setError(e.message)}finally{setAccessSaving(false)}};
 const setAccess=(type,key,value)=>{setAccessSettings(s=>({...s,[type]:{...s[type],[key]:value,...(key==='accessStrategy'&&value==='permanent_single'?{buyerCapacity:1}: {})}}));setAccessDirty(true)};
 const del=async id=>{if(!confirm('Delete this pricing rule?'))return;try{setError('');await req(`/leads/pricing/rules/${id}`,{method:'DELETE'});await load()}catch(e){setError(e.message)}};

 return <main className="pricing-page"><style>{`.pricing-hero>div:first-child{flex:1;text-align:center}.create-head,.rules-head,.partner-settings-head{position:relative;justify-content:center;text-align:center;min-height:70px}.create-head>div,.rules-head>div,.partner-settings-head>div{max-width:760px;margin:0 auto}.create-head .outline-btn,.rules-head .outline-btn{position:absolute;right:0;top:0}.access-defaults-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.access-default-card{padding:16px;border:1px solid #e1e8f0;border-radius:14px;background:#fbfdff}.access-default-card h3{margin:0 0 4px;color:#173b65;font-size:15px}.access-default-card>p{margin:0 0 12px;color:#7c8da1;font-size:9px}.access-fields{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.access-fields label{display:grid;gap:5px;color:#708198;font-size:8px;font-weight:850}.access-fields select,.access-fields input{height:38px;border:1px solid #dce5ee;border-radius:9px;background:#fff;padding:0 10px;color:#244766;font-size:10px}.access-note{margin-top:10px;padding:9px 10px;border-radius:9px;background:#eef5fd;color:#55708e;font-size:8px;line-height:1.5}@media(max-width:850px){.access-defaults-grid{grid-template-columns:1fr}}@media(max-width:700px){.create-head,.rules-head,.partner-settings-head{min-height:0}.create-head .outline-btn,.rules-head .outline-btn{position:static;width:100%;margin-top:10px}.access-fields{grid-template-columns:1fr}}`}</style>
  <section className="pricing-hero"><div><span className="hero-kicker">REVENUE CONTROL</span><h1>Lead Pricing</h1><p>Set 1, 2 and 3-buyer prices plus the default buyer-access lifecycle for Basic and Premium leads.</p></div><div className="hero-mark">₹</div></section>
  {error&&<div className="pricing-alert error">{error}</div>}{ok&&<div className="pricing-alert success">{ok}</div>}

  <section className="pricing-panel partner-settings-panel"><div className="panel-head partner-settings-head"><div><span className="kicker">BUYER ACCESS DEFAULTS</span><h2>Freshness & sharing strategy</h2><p>New leads use these defaults unless the upload sheet or Lead Editor supplies an exact access strategy.</p></div></div>
   <div className="access-defaults-grid">{types.map(type=>{const row=accessSettings[type]||defaultAccess()[type];return <article className="access-default-card" key={type}><h3>{cap(type)} leads</h3><p>{type==='premium'?'Keep high-value leads exclusive longer before sharing.':'Move standard leads through the marketplace faster.'}</p><div className="access-fields">
    <label>Default strategy<select value={row.accessStrategy} onChange={e=>setAccess(type,'accessStrategy',e.target.value)}><option value="permanent_single">Single Only</option><option value="auto_release">Auto Release</option><option value="shared">Shared from Start</option></select></label>
    <label>Maximum buyers<select disabled={row.accessStrategy==='permanent_single'} value={row.accessStrategy==='permanent_single'?1:row.buyerCapacity} onChange={e=>setAccess(type,'buyerCapacity',Number(e.target.value))}><option value="1">1 buyer</option><option value="2">2 buyers</option><option value="3">3 buyers</option></select></label>
    <label>Release to 2 buyers (hours)<input type="number" min="0" disabled={row.accessStrategy!=='auto_release'||Number(row.buyerCapacity)<2} value={row.releaseToTwoAfterHours??''} onChange={e=>setAccess(type,'releaseToTwoAfterHours',e.target.value)}/></label>
    <label>Release to 3 buyers (hours)<input type="number" min="0" disabled={row.accessStrategy!=='auto_release'||Number(row.buyerCapacity)<3} value={row.releaseToThreeAfterHours??''} onChange={e=>setAccess(type,'releaseToThreeAfterHours',e.target.value)}/></label>
   </div><div className="access-note">{row.accessStrategy==='auto_release'?`Starts with 1 buyer. If still unsold, opens to 2 after ${row.releaseToTwoAfterHours||0}h and to 3 after ${row.releaseToThreeAfterHours||0}h. The first completed purchase locks the current stage.`:row.accessStrategy==='permanent_single'?'Single Only: one business can ever acquire the lead. No automatic release to 2 or 3 buyers.':'The lead is immediately available to the configured maximum number of buyers.'}</div></article>})}</div>
   <div className="panel-foot"><span>These rules apply to Propulse and Lead Partner leads. Sheet-level values override them when provided.</span><button className="primary-btn" disabled={accessSaving||!accessDirty} onClick={saveAccessSettings}>{accessSaving?'Saving…':'Save access defaults'}</button></div>
  </section>

  <section className="pricing-panel partner-settings-panel"><div className="panel-head partner-settings-head"><div><span className="kicker">LEAD PARTNER CONTROLS</span><h2>Partner pricing rules</h2><p>Partners set their Pro base price. The existing 1 / 2 / 3 buyer price curve and Admin uplift remain the source of marketplace pricing.</p></div></div>
   <div className="partner-settings-grid"><label>Partner commission (%)<input type="number" min="0" max="100" step="0.01" value={partnerSettings.commissionPercent} onChange={e=>{setPartnerSettings({...partnerSettings,commissionPercent:e.target.value});setPartnerDirty(true)}}/></label><label>Pro → Normal uplift (₹)<input type="number" min="0" step="0.01" value={partnerSettings.normalPriceUplift} onChange={e=>{setPartnerSettings({...partnerSettings,normalPriceUplift:e.target.value});setPartnerDirty(true)}}/></label><div className="partner-settings-preview"><span>Example</span><b>Partner Pro ₹500 + ₹{Number(partnerSettings.normalPriceUplift||0).toLocaleString('en-IN')} = Normal ₹{(500+Number(partnerSettings.normalPriceUplift||0)).toLocaleString('en-IN')}</b></div></div>
   <div className="panel-foot"><span>Lead Partner leads use the same buyer-access aging engine as Propulse leads.</span><button className="primary-btn" disabled={partnerSaving||!partnerDirty} onClick={savePartnerSettings}>{partnerSaving?'Saving…':'Save partner settings'}</button></div>
  </section>

  <section className="pricing-panel create-panel"><div className="panel-head create-head"><div><span className="kicker">{editId?'EDIT PRICING RULE':'CREATE PRICING RULE'}</span><h2>{editId?'Update pricing rule':'Create pricing rule'}</h2><p>Choose the market, then set the price for each buyer-capacity stage.</p></div>{editId&&<button className="outline-btn" onClick={reset}>Cancel</button>}</div>
   <div className="scope-grid"><label>Industry<select value={form.industryId} onChange={e=>setForm({...form,industryId:e.target.value})}><option value="">All industries</option>{industries.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>City<select value={form.cityId} onChange={e=>setForm({...form,cityId:e.target.value})}><option value="">All cities</option>{cities.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="active-box">Status<span><input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/> Active</span></label></div>
   <div className="lead-type-switch">{types.map(t=><button type="button" key={t} className={form.leadType===t?`selected ${t}`:''} onClick={()=>setForm({...form,leadType:t})}><strong>{cap(t)}</strong><small>{t==='basic'?'Standard leads':'High-value leads'}</small></button>)}</div>
   <div className="pricing-box"><div className="pricing-box-head"><div><h3>{cap(form.leadType)} buyer pricing</h3><p>1 buyer is the freshest/highest-price stage; 3 buyers is the broadest/lower-price stage.</p></div></div><div className="tier-head"><span>BUYER ACCESS</span><span>NORMAL</span><span>PRO</span><span></span></div>{fixedTiers(form.pricing.shares).map((x,i)=><div className="tier-row" key={x.shares}><div className="field"><span>Maximum buyers</span><input type="text" value={`${x.shares} buyer${x.shares===1?'':'s'}`} readOnly/></div><div className="field money"><span>Normal</span><div>₹<input type="number" min="0" value={x.normal} onChange={e=>setTier(i,'normal',e.target.value)}/></div></div><div className="field money"><span>Pro</span><div>₹<input type="number" min="0" value={x.pro} onChange={e=>setTier(i,'pro',e.target.value)}/></div></div><span></span></div>)}</div>
   <div className="panel-foot"><span>Pro Early Access is configured per lead and remains separate from buyer capacity.</span><button className="primary-btn" disabled={saving} onClick={save}>{saving?'Saving…':editId?'Update rule':'Save rule'}</button></div>
  </section>

  <section className="pricing-panel rules-panel"><div className="panel-head compact rules-head"><div><span className="kicker">PRICING MATRIX</span><h2>Configured rules</h2><p>Industry + City + Lead Type</p></div><button className="outline-btn" onClick={load}>Refresh</button></div>{loading?<div className="empty">Loading pricing rules…</div>:!rules.length?<div className="empty">No pricing rules configured yet.</div>:<div className="rule-cards">{dedupeRules(rules).map(r=><article className="rule-card" key={ruleKey(r)}><div className="rule-top"><div><span className={`type-pill ${r.lead_type}`}>{cap(r.lead_type)}</span><h3>{r.industry_name||'All industries'}</h3><p>{r.city_name||'All cities'}</p></div><span className={r.is_active?'status active':'status'}>{r.is_active?'ACTIVE':'OFF'}</span></div><div className="rule-prices">{fixedTiers(r.pricing?.shares).map(x=><div key={x.shares}><b>{x.shares}</b><span>Normal <strong>₹{x.normal}</strong></span><span>Pro <strong>₹{x.pro}</strong></span></div>)}</div><div className="card-actions"><button onClick={()=>edit(r)}>Edit</button><button onClick={()=>del(r.id)}>Delete</button></div></article>)}</div>}</section>
 </main>;
}
