import { useEffect, useMemo, useState } from 'react';
import { apiRequest } from '../../utils/api';
import { getToken, clearSession } from '../../utils/auth';
import { useNavigate } from 'react-router-dom';
import './AdminTable.css';
import './AdminWalletTopups.css';

export default function AdminWalletTopups(){
 const navigate=useNavigate(); const [topups,setTopups]=useState([]),[status,setStatus]=useState('all'),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(null),[error,setError]=useState(''),[page,setPage]=useState(1),[meta,setMeta]=useState({total:0,pages:0,stats:{total:0,pending:0,approved:0,rejected:0,approved_amount:0}});
 const request=async(path,options={})=>{if(!getToken()){clearSession();navigate('/login',{replace:true});throw new Error('Your admin session has expired. Please sign in again.')}return apiRequest(path,options)};
 const load=async(nextPage=1)=>{setLoading(true);setError('');try{const q=new URLSearchParams({status,search:search.trim(),page:String(nextPage),limit:'50'});const data=await request(`/wallet/topups?${q}`);setTopups(Array.isArray(data)?data:data.items||[]);setMeta({total:data.total??0,pages:data.pages??1,stats:data.stats||{total:data.total??0,pending:0,approved:0,rejected:0,approved_amount:0}});setPage(nextPage)}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load(1)},[status]);
 const update=async(id,next)=>{if(busy)return;setBusy(id);setError('');try{const endpoint=next==='approved'?`/wallet/topups/${id}/approve`:`/wallet/topups/${id}/reject`;await request(endpoint,{method:'PATCH'});await load(page)}catch(e){setError(e.message)}finally{setBusy(null)}};
 const money=v=>`₹${Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`;
 const counts=useMemo(()=>meta.stats||{total:meta.total,pending:0,approved:0,rejected:0,approved_amount:0},[meta]);
 return <section className="admin-topups-page"><div className="topups-heading"><div><span className="eyebrow">WALLET</span><h1>Manual Top-ups</h1><p>Review proof-backed wallet funding requests.</p></div><button disabled={loading} onClick={()=>load(1)}>↻ Refresh</button></div><div className="topup-cards"><div><span>Total</span><b>{counts.total??meta.total}</b></div><div><span>Pending</span><b>{counts.pending??0}</b></div><div><span>Approved</span><b>{counts.approved??0}</b></div><div><span>Approved value</span><b>{money(counts.approved_amount)}</b></div></div><div className="topup-panel"><div className="topup-toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load(1)} placeholder="Search user, email, business or reference..."/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select><button disabled={loading} onClick={()=>load(1)}>Search</button></div>{error&&<div className="topup-error">{error}</div>}<div className="topup-table-wrap"><table><thead><tr><th>ID</th><th>USER</th><th>AMOUNT</th><th>METHOD</th><th>REFERENCE</th><th>PROOF</th><th>STATUS</th><th>REVIEWED BY</th><th>ACTION</th></tr></thead><tbody>{loading?<tr><td colSpan="9" className="topup-empty">Loading top-ups...</td></tr>:topups.length===0?<tr><td colSpan="9" className="topup-empty">No top-ups found.</td></tr>:topups.map(t=><tr key={t.id}><td>#{t.id}</td><td><b>{t.business_name||t.user_name||'—'}</b><small>{t.user_email}</small></td><td><strong>{money(t.amount)}</strong></td><td>{t.payment_method||'manual'}</td><td>{t.reference||t.manual_reference||'—'}</td><td>{t.proof_url?<a className="proof-button" href={t.proof_url} target="_blank" rel="noreferrer">View proof</a>:<span>—</span>}</td><td><span className={`topup-status ${t.status}`}>{t.status}</span></td><td className="reviewed-by">{t.reviewer_name||t.reviewed_by_name||'—'}</td><td>{t.status==='pending'&&<div className="topup-actions"><button disabled={busy!==null} onClick={()=>update(t.id,'approved')}>{busy===t.id?'Working…':'Approve'}</button><button disabled={busy!==null} onClick={()=>update(t.id,'rejected')}>Reject</button></div>}</td></tr>)}</tbody></table></div>{meta.pages>1&&<div className="topup-toolbar"><button disabled={page<=1||loading} onClick={()=>load(page-1)}>Previous</button><span>Page {page} of {meta.pages}</span><button disabled={page>=meta.pages||loading} onClick={()=>load(page+1)}>Next</button></div>}</div></section>;
}