import { useEffect, useMemo, useState } from 'react';
import { getToken, clearSession } from '../../utils/auth';
import { useNavigate } from 'react-router-dom';
import './AdminMembershipPlans.css';

const API = 'http://localhost:5000/api';
const periods = [{ key: 'monthly', label: 'Monthly', months: 1 }, { key: 'quarterly', label: 'Quarterly', months: 3 }, { key: 'yearly', label: 'Yearly', months: 12 }];
const presets = {
  pro: { name: 'Pro', benefits: ['Pro lead pricing', 'Priority lead access'], leads: [{ type: 'shared', quantity: 3, complimentary: true }, { type: 'premium', quantity: 1, complimentary: true }], addOns: [] },
  investor: { name: 'Investor', benefits: ['Everything in Pro', 'Investor access', 'Investor opportunity discovery'], leads: [{ type: 'shared', quantity: 5, complimentary: true }, { type: 'premium', quantity: 2, complimentary: true }], addOns: [] },
  booster: { name: 'Booster', benefits: ['Everything in Pro', 'Website Builder', 'Website hosting & publishing', 'Growth tools'], leads: [{ type: 'shared', quantity: 8, complimentary: true }, { type: 'premium', quantity: 3, complimentary: true }], addOns: [{ name: 'Website Building & Maintenance', price: 4999 }, { name: 'Digital Marketing', price: 7999 }] },
};
const blank = { name: 'Pro', planType: 'pro', monthlyBasePrice: '', pricing: { monthly: { price: '', discount: 0 }, quarterly: { price: '', discount: 0 }, yearly: { price: '', discount: 0 } }, benefits: presets.pro.benefits, leads: presets.pro.leads, addOns: presets.pro.addOns };
const money = value => Number(value || 0).toLocaleString('en-IN', { maximumFractionDigits: 2 });
const clonePreset = type => { const p = presets[type]; return { name: p.name, planType: type, monthlyBasePrice: '', pricing: { monthly: { price: '', discount: 0 }, quarterly: { price: '', discount: 0 }, yearly: { price: '', discount: 0 } }, benefits: [...p.benefits], leads: p.leads.map(x => ({ ...x })), addOns: p.addOns.map(x => ({ ...x })) }; };

export default function AdminMembershipPlans() {
  const nav = useNavigate();
  const [tab, setTab] = useState('plans'), [plans, setPlans] = useState([]), [form, setForm] = useState(blank), [investor, setInvestor] = useState(null), [coupons, setCoupons] = useState([]), [coupon, setCoupon] = useState({ code: '', discountType: 'percent', discountValue: '', maxDiscount: '', minOrderAmount: '', usageLimit: '', startsAt: '', expiresAt: '' }), [editCoupon, setEditCoupon] = useState(null), [error, setError] = useState(''), [loading, setLoading] = useState(true);

  async function req(path, opt = {}) { const t = getToken(); if (!t) { clearSession(); nav('/login', { replace: true }); throw Error('Session expired'); } const r = await fetch(API + path, { ...opt, headers: { 'Content-Type': 'application/json', ...(opt.headers || {}), Authorization: `Bearer ${t}` } }); const d = await r.json().catch(() => ({})); if (r.status === 401) { clearSession(); nav('/login', { replace: true }); throw Error('Session expired'); } if (!r.ok) throw Error(d.error || 'Request failed'); return d; }
  async function load() { setLoading(true); try { const [a, b, c] = await Promise.all([req('/membership-plans'), req('/admin/commercial/investor-settings'), req('/admin/commercial/coupons')]); setPlans(a); setInvestor(b); setCoupons(c); } catch (e) { setError(e.message); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  const grouped = useMemo(() => { const map = {}; plans.forEach(p => { const key = p.plan_group || p.name.replace(/\s+(Monthly|Quarterly|Yearly)$/i, ''); (map[key] ??= []).push(p); }); return Object.values(map); }, [plans]);
  const set = (key, value) => setForm(x => ({ ...x, [key]: value }));
  const setP = (period, key, value) => setForm(x => ({ ...x, pricing: { ...x.pricing, [period]: { ...x.pricing[period], [key]: value } } }));
  const applyPreset = type => { setError(''); setForm(clonePreset(type)); };
  const addBenefit = () => { const value = prompt('Benefit name'); if (value?.trim()) setForm(x => ({ ...x, benefits: [...x.benefits, value.trim()] })); };
  const addLead = () => setForm(x => ({ ...x, leads: [...x.leads, { type: 'shared', quantity: 1, complimentary: true }] }));
  const updateLead = (index, key, value) => setForm(x => ({ ...x, leads: x.leads.map((lead, i) => i === index ? { ...lead, [key]: value } : lead) }));
  const addAddOn = () => setForm(x => ({ ...x, addOns: [...x.addOns, { name: '', price: 0 }] }));
  const updateAddOn = (index, key, value) => setForm(x => ({ ...x, addOns: x.addOns.map((item, i) => i === index ? { ...item, [key]: value } : item) }));

  async function create(e) { e.preventDefault(); setError(''); try { await req('/membership-plans', { method: 'POST', body: JSON.stringify({ name: form.name, planType: form.planType, planGroup: form.name, bundle: true, monthlyBasePrice: Number(form.monthlyBasePrice || 0), benefits: form.benefits, leadEntitlements: form.leads.map(x => ({ ...x, quantity: Number(x.quantity || 0) })), addOns: form.addOns.map(x => ({ ...x, price: Number(x.price || 0) })), periods: periods.map(p => ({ key: p.key, label: p.label, months: p.months, enabled: true, leadEntitlements: form.leads.map(x => ({ ...x, quantity: Number(x.quantity || 0) })) })), pricing: Object.fromEntries(periods.map(p => [p.key, { price: form.pricing[p.key].price === '' ? '' : Number(form.pricing[p.key].price), discount: Number(form.pricing[p.key].discount || 0), customPrice: form.pricing[p.key].price !== '' }])) }) }); setForm(clonePreset(form.planType)); await load(); } catch (e) { setError(e.message); } }
  async function toggle(p) { try { await req(`/membership-plans/${p.id}/status`, { method: 'PATCH', body: JSON.stringify({ isActive: !p.is_active }) }); load(); } catch (e) { setError(e.message); } }
  async function del(p) { if (!confirm(`Delete ${p.name}?`)) return; try { await req(`/membership-plans/${p.id}`, { method: 'DELETE' }); load(); } catch (e) { setError(e.message); } }
  async function saveInv(e) { e.preventDefault(); try { await req('/admin/commercial/investor-settings', { method: 'PUT', body: JSON.stringify({ ...investor, globalLimit: +investor.global_limit, defaultIndustryLimit: +investor.default_industry_limit, minInvestment: +investor.min_investment, maxInvestment: investor.max_investment }) }); load(); } catch (e) { setError(e.message); } }
  async function saveCoupon(e) { e.preventDefault(); try { await req(editCoupon ? `/admin/commercial/coupons/${editCoupon}` : '/admin/commercial/coupons', { method: editCoupon ? 'PUT' : 'POST', body: JSON.stringify({ ...coupon, discountValue: +coupon.discountValue }) }); setEditCoupon(null); load(); } catch (e) { setError(e.message); } }

  return <main className="commercial-page">
    <header className="commercial-head"><span>COMMERCIAL</span><h1>Membership Plans</h1></header>
    {error && <div className="error">{error}</div>}
    <nav className="tabs"><button className={tab === 'plans' ? 'selected' : ''} onClick={() => setTab('plans')}>Memberships</button><button className={tab === 'investor' ? 'selected' : ''} onClick={() => setTab('investor')}>Investor Settings</button><button className={tab === 'coupons' ? 'selected' : ''} onClick={() => setTab('coupons')}>Coupons</button></nav>

    {tab === 'plans' && <>
      <section className="create-card hero-card">
        <div className="card-heading"><div><div className="eyebrow">PLAN BUILDER</div><h2>Create membership</h2></div><div className="plan-presets">{Object.keys(presets).map(type => <button type="button" key={type} className={form.planType === type ? 'active' : ''} onClick={() => applyPreset(type)}>{presets[type].name}</button>)}</div></div>
        <form onSubmit={create}>
          <div className="two"><label>Plan name<input value={form.name} onChange={e => set('name', e.target.value)} required /></label><label>Plan type<select value={form.planType} onChange={e => applyPreset(e.target.value)}><option value="pro">Pro</option><option value="investor">Investor</option><option value="booster">Booster</option></select></label><label>Monthly base price ₹<input type="number" min="0" value={form.monthlyBasePrice} onChange={e => set('monthlyBasePrice', e.target.value)} placeholder="999" required /></label></div>
          <div className="section-label">Billing & live pricing</div>
          <div className="pricing-grid">{periods.map(p => { const base = Number(form.monthlyBasePrice || 0) * p.months; const discount = Number(form.pricing[p.key].discount || 0); const calculated = base * (1 - discount / 100); const override = form.pricing[p.key].price !== ''; return <div className="pricing-box" key={p.key}><div className="period-title"><b>{p.label}</b><span>{p.months} {p.months === 1 ? 'month' : 'months'}</span></div><label>Custom price ₹<input type="number" min="0" value={form.pricing[p.key].price} onChange={e => setP(p.key, 'price', e.target.value)} placeholder={base ? money(base) : 'Auto'} /></label><label>Discount %<input type="number" min="0" max="100" value={form.pricing[p.key].discount} onChange={e => setP(p.key, 'discount', e.target.value)} /></label><div className="live-price">Live price <strong>₹{money(override ? form.pricing[p.key].price : calculated)}</strong></div>{discount > 0 && <small className="saving">Save ₹{money(base - calculated)}</small>}</div>; })}</div>
          <div className="editor-section"><div className="benefit-head"><div><b>Included features</b><small>What this membership unlocks</small></div><button type="button" onClick={addBenefit}>＋ Add</button></div><div className="chips">{form.benefits.map((b, i) => <span key={i}>{b}<button type="button" onClick={() => setForm(x => ({ ...x, benefits: x.benefits.filter((_, n) => n !== i) }))}>×</button></span>)}</div></div>
          <div className="editor-section"><div className="benefit-head"><div><b>Complimentary leads</b><small>Configure shared, premium and exclusive quantities</small></div><button type="button" onClick={addLead}>＋ Add lead</button></div><div className="lead-editor">{form.leads.map((lead, i) => <div className="lead-row" key={i}><select value={lead.type} onChange={e => updateLead(i, 'type', e.target.value)}><option value="shared">Shared</option><option value="premium">Premium</option><option value="exclusive">Exclusive</option></select><input type="number" min="0" value={lead.quantity} onChange={e => updateLead(i, 'quantity', e.target.value)} /><label className="inline-check"><input type="checkbox" checked={lead.complimentary !== false} onChange={e => updateLead(i, 'complimentary', e.target.checked)} /> Complimentary</label><button type="button" className="remove" onClick={() => setForm(x => ({ ...x, leads: x.leads.filter((_, n) => n !== i) }))}>Remove</button></div>)}</div></div>
          <div className="editor-section"><div className="benefit-head"><div><b>Add-ons</b><small>Optional services customers can purchase with the plan</small></div><button type="button" onClick={addAddOn}>＋ Add add-on</button></div>{form.addOns.length === 0 ? <div className="muted-note">No add-ons configured.</div> : <div className="addon-editor">{form.addOns.map((item, i) => <div className="addon-row" key={i}><input value={item.name} onChange={e => updateAddOn(i, 'name', e.target.value)} placeholder="Add-on name" /><div className="addon-price"><span>₹</span><input type="number" min="0" value={item.price} onChange={e => updateAddOn(i, 'price', e.target.value)} /></div><button type="button" className="remove" onClick={() => setForm(x => ({ ...x, addOns: x.addOns.filter((_, n) => n !== i) }))}>Remove</button></div>)}</div>}</div>
          <button className="primary create-btn">Create {form.name || 'membership'} plan</button>
        </form>
      </section>
      <section className="plans-list">{loading ? <div className="empty">Loading…</div> : grouped.length ? grouped.map(g => { const type = g[0].plan_type || 'non_pro'; return <div className={`plan-group plan-${type}`} key={g[0].plan_group || g[0].id}><div className="group-head"><div><div className="eyebrow">{type.toUpperCase()}</div><h2>{g[0].plan_group || g[0].name}</h2></div><span className="live-count">{g.filter(x => x.is_active).length}/{g.length} active</span></div><div className="group-features">{(Array.isArray(g[0].benefits) ? g[0].benefits : []).slice(0, 6).map((b, i) => <span key={i}>✓ {b}</span>)}{(Array.isArray(g[0].add_ons) ? g[0].add_ons : []).map((a, i) => <span key={`a${i}`}>＋ {a.name} · ₹{money(a.price)}</span>)}</div>{g.sort((a, b) => Number(a.billing_months) - Number(b.billing_months)).map(p => <div className="option" key={p.id}><div><b>{p.billing_period}</b><small>{p.discount_percent || 0}% discount · {p.is_active ? 'Active' : 'Inactive'}</small></div><strong>₹{money(p.price)}</strong><div className="actions"><button onClick={() => toggle(p)}>{p.is_active ? 'Disable' : 'Enable'}</button><button className="danger" onClick={() => del(p)}>Delete</button></div></div>)}</div>; }) : <div className="empty plan-empty"><strong>No membership plans yet</strong><span>Create Pro, Investor or Booster above.</span></div>}</section>
    </>}

    {tab === 'investor' && investor && <section className="settings-card"><div className="card-title"><div><div className="eyebrow">INVESTOR ACCESS</div><h2>Investor controls</h2></div><span className={investor.enabled ? 'status on' : 'status'}>{investor.enabled ? 'Enabled' : 'Disabled'}</span></div><form onSubmit={saveInv}><div className="setting-grid"><label>Global investor limit<input type="number" min="0" value={investor.global_limit} onChange={e => setInvestor({ ...investor, global_limit: e.target.value })} /></label><label>Default industry limit<input type="number" min="0" value={investor.default_industry_limit} onChange={e => setInvestor({ ...investor, default_industry_limit: e.target.value })} /></label><label>Minimum investment ₹<input type="number" min="0" value={investor.min_investment} onChange={e => setInvestor({ ...investor, min_investment: e.target.value })} /></label><label>Maximum investment ₹<input type="number" min="0" value={investor.max_investment || ''} onChange={e => setInvestor({ ...investor, max_investment: e.target.value })} placeholder="No limit" /></label></div><button className="primary">Save settings</button></form></section>}

    {tab === 'coupons' && <section><div className="create-card"><div className="card-heading"><div><div className="eyebrow">PROMOTIONS</div><h2>{editCoupon ? 'Edit coupon' : 'Create coupon'}</h2></div></div><form onSubmit={saveCoupon}><div className="coupon-grid"><label>Coupon code<input value={coupon.code} onChange={e => setCoupon({ ...coupon, code: e.target.value.toUpperCase() })} placeholder="WELCOME20" required /></label><label>Discount type<select value={coupon.discountType} onChange={e => setCoupon({ ...coupon, discountType: e.target.value })}><option value="percent">Percentage</option><option value="fixed">Fixed amount</option></select></label><label>Value<input type="number" min="0" value={coupon.discountValue} onChange={e => setCoupon({ ...coupon, discountValue: e.target.value })} required /></label><label>Maximum discount ₹<input type="number" min="0" value={coupon.maxDiscount} onChange={e => setCoupon({ ...coupon, maxDiscount: e.target.value })} /></label><label>Minimum order ₹<input type="number" min="0" value={coupon.minOrderAmount} onChange={e => setCoupon({ ...coupon, minOrderAmount: e.target.value })} /></label><label>Usage limit<input type="number" min="0" value={coupon.usageLimit} onChange={e => setCoupon({ ...coupon, usageLimit: e.target.value })} placeholder="Unlimited" /></label><label>Starts<input type="datetime-local" value={coupon.startsAt} onChange={e => setCoupon({ ...coupon, startsAt: e.target.value })} /></label><label>Expires<input type="datetime-local" value={coupon.expiresAt} onChange={e => setCoupon({ ...coupon, expiresAt: e.target.value })} /></label></div><div className="form-footer"><button className="primary">{editCoupon ? 'Save coupon' : 'Create coupon'}</button></div></form></div><div className="coupon-list">{coupons.map(c => <div className="coupon-row" key={c.id}><div><b>{c.code}</b><small>{c.discount_type === 'percent' ? `${c.discount_value}% off` : `₹${c.discount_value} off`} · Used {c.used_count}{c.usage_limit != null ? `/${c.usage_limit}` : ''}</small></div><span className={c.is_active ? 'status on' : 'status'}>{c.is_active ? 'Active' : 'Inactive'}</span><div className="actions"><button onClick={async () => { await req(`/admin/commercial/coupons/${c.id}/status`, { method: 'PATCH', body: JSON.stringify({ isActive: !c.is_active }) }); load(); }}>{c.is_active ? 'Disable' : 'Enable'}</button><button className="danger" onClick={async () => { if (confirm(`Delete ${c.code}?`)) { await req(`/admin/commercial/coupons/${c.id}`, { method: 'DELETE' }); load(); } }}>Delete</button></div></div>)}</div></section>}
  </main>;
}
