import { useEffect, useState } from 'react';
import './AdminLeads.css';
import { getToken } from '../../utils/auth';

const API_BASE = 'http://localhost:5000';

export default function AdminLeads() {
  const [leads, setLeads] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  async function loadLeads() {
    try {
      setLoading(true);
      setError('');
      const token = getToken();
      const response = await fetch(`${API_BASE}/api/leads`, {
        headers: { Authorization: `Bearer ${token}` },
      });
      if (!response.ok) throw new Error('Failed to load leads');
      const data = await response.json();
      setLeads(Array.isArray(data) ? data : []);
    } catch (err) {
      console.error(err);
      setError(err.message || 'Failed to load leads');
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => { loadLeads(); }, []);

  return (
    <div className="admin-leads-page">
      <div className="admin-page-heading">
        <div>
          <span className="admin-eyebrow">MARKETPLACE</span>
          <h1>Leads</h1>
          <p>Manage and monitor leads generated by Propulse.</p>
        </div>
        <button className="admin-primary-btn">+ Create Lead</button>
      </div>

      <div className="admin-leads-stats">
        <div className="admin-lead-stat"><span>Total Leads</span><strong>{leads.length}</strong></div>
        <div className="admin-lead-stat"><span>Available</span><strong>{leads.filter(l => l.status === 'available').length}</strong></div>
        <div className="admin-lead-stat"><span>Sold</span><strong>{leads.filter(l => l.status === 'sold').length}</strong></div>
        <div className="admin-lead-stat"><span>Closed</span><strong>{leads.filter(l => l.status === 'closed').length}</strong></div>
      </div>

      <div className="admin-leads-card">
        <div className="admin-leads-card-header">
          <div><h2>All Leads</h2><p>Recently created marketplace leads</p></div>
          <button className="admin-refresh-btn" onClick={loadLeads} disabled={loading}>↻ Refresh</button>
        </div>

        {loading && <div className="admin-leads-state">Loading leads...</div>}
        {error && !loading && <div className="admin-leads-state admin-leads-error">{error}</div>}
        {!loading && !error && leads.length === 0 && <div className="admin-leads-state">No leads found.</div>}

        {!loading && !error && leads.length > 0 && (
          <div className="admin-leads-table-wrap">
            <table className="admin-leads-table">
              <thead><tr><th>ID</th><th>Customer</th><th>Industry</th><th>Service</th><th>Location</th><th>Budget</th><th>Status</th><th>Created</th></tr></thead>
              <tbody>
                {leads.map(lead => (
                  <tr key={lead.id}>
                    <td><strong>#{lead.id}</strong></td>
                    <td><div className="lead-customer"><strong>{lead.customer_name}</strong><span>{lead.customer_phone}</span></div></td>
                    <td>{lead.industry_name || '-'}</td>
                    <td>{lead.service_name || '-'}</td>
                    <td><div className="lead-location"><strong>{lead.city_name || '-'}</strong><span>{lead.state_name || '-'}</span></div></td>
                    <td>{lead.budget ? `₹${Number(lead.budget).toLocaleString('en-IN')}` : '-'}</td>
                    <td><span className={`lead-status lead-status-${lead.status}`}>{lead.status}</span></td>
                    <td>{lead.created_at ? new Date(lead.created_at).toLocaleDateString('en-IN') : '-'}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
