import {useEffect,useRef,useState} from 'react';
import './AdminLeadsV8.css';
import './AdminLeadsV8.overrides.css';
import {getToken} from '../../utils/auth';

const API='http://localhost:5000/api';
const TYPES=['basic','premium'];
const clean=v=>String(v??'').trim();
const norm=v=>clean(v).toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]/g,'');
const title=v=>clean(v).replace(/[_-]/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const emptyPricing={shares:[{shares:1,normal:null,pro:null},{shares:3,normal:null,pro:null},{shares:5,normal:null,pro:null}]};
const daysToHours=v=>{const n=Number(v);return Number.isFinite(n)&&n>0?Math.min(8760,Math.round(n*24)):0};
const csvRows=text=>{const out=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(clean))out.push(row);row=[];cell='';}else cell+=c;}row.push(cell);if(row.some(clean))out.push(row);if(!out.length)return[];const headers=out[0].map(clean);return out.slice(1).map(r=>Object.fromEntries(headers.map((h,i)=>[h,clean(r[i])] )))};
const get=(raw,names)=>{const key=Object.keys(raw).find(k=>names.some(n=>norm(k)===norm(n)));return key?clean(raw[key]):''};
const bool=v=>['true','yes','y','1','exclusive'].includes(norm(v));
const price=(raw,tier,n)=>{const v=get(raw,[`${tier} ${n} Share`,`${tier} ${n} Shares`,`${tier} ${n} Share Price`,`${tier.toLowerCase()}_${n}_share`,`${tier.toLowerCase()}_${n}_shares`]);return v===''?null:Number(v)};
const parsePricing=raw=>{const shares=[1,3,5].map(n=>({shares:n,normal:price(raw,'Normal',n),pro:price(raw,'Pro',n)}));return shares.some(x=>x.normal!==null||x.pro!==null)?{shares}:null};
function similarity(input,target){const a=norm(input),b=norm(target);if(!a||!b)return 0;if(a===b)return 100;if(b.startsWith(a)||a.startsWith(b))return 90;if(b.includes(a)||a.includes(b))return 80;return 0}
function best(items,value){if(!value)return null;let w=null,s=0;for(const x of items){const n=similarity(value,x.name);if(n>s){s=n;w=x}}return s>=80?w:null}
function sample(){const h=['Pricing Name','Lead Type','Exclusive','Exclusive Delay Days','Industry','Service','Subservice','State','City','Customer Name','Customer Phone','Customer Email','Requirement','Property Type','Budget','Source','Notes','Project Type','Area / Size','Preferred Date','Normal 1 Share','Normal 3 Shares','Normal 5 Shares','Pro 1 Share','Pro 3 Shares','Pro 5 Shares'];const r=['Construction Basic','premium','TRUE','1','Construction & Contractors','Building Construction','','Telangana','Hyderabad','Example Customer','9876500000','customer@example.com','Looking for a new house','Residential','2500000','Website','Example row','New Construction','2000 sq ft','2026-09-15','500','1200','1800','450','1050','1600'];const esc=v=>`"${String(v??'').replace(/"/g,'""')}"`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([h.map(esc).join(',')+'\n'+r.map(esc).join(',')],{type:'text/csv'}));a.download='propulse-leads-sample.csv';a.click();URL.revokeObjectURL(a.href)}
export default function AdminLeadsV8(){
 const [leads,setLeads]=useState([]),[cat,setCat]=useState({industries:[],services:[],subservices:[],states:[],cities:[]}),[rows,setRows]=useState([]),[selected,setSelected]=useState([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[upload,setUpload]=useState(false),[open,setOpen]=useState(null),[edit,setEdit]=useState(null),[googleOpen,setGoogleOpen]=useState(false);const file=useRef(null);
 const req=async(path,opt={})=>{const r=await fetch(API+path,{...opt,headers:{Authorization:`Bearer ${getToken()}`,'Content-Type':'application/json',...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok){const e=Error(d.error||'Request failed');e.status=r.status;e.data=d;throw e}return d};
 const load=async()=>{try{setLoading(true);const [l,i,s,ss,st,c]=await Promise.all([req('/leads?status=all'),req('/industries'),req('/services'),req('/subservices'),req('/states'),req('/cities')]);setLeads(Array.isArray(l)?l:[]);setCat({industries:i,services:s,subservices:ss,states:st,cities:c})}catch(e){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const services=i=>cat.services.filter(x=>String(x.industry_id)===String(i));const subservices=s=>cat.subservices.filter(x=>String(x.service_id)===String(s));const cities=s=>cat.cities.filter(x=>String(x.state_id)===String(s));
 const make=(raw,n)=>{let industry=best(cat.industries,get(raw,['Industry']));let service=industry?best(services(industry.id),get(raw,['Service'])):best(cat.services,get(raw,['Service']));if(!industry&&service)industry=cat.industries.find(x=>String(x.id)===String(service.industry_id))||null;let sub=service?best(subservices(service.id),get(raw,['Subservice'])):best(cat.subservices,get(raw,['Subservice']));if(!service&&sub){service=cat.services.find(x=>String(x.id)===String(sub.service_id))||null;industry=industry||cat.industries.find(x=>String(x.id)===String(service?.industry_id))||null}const state=best(cat.states,get(raw,['State']));const city=state?best(cities(state.id),get(raw,['City'])):best(cat.cities,get(raw,['City']));const pricing=parsePricing(raw);const known=new Set(['pricingname','leadtype','exclusive','isexclusive','exclusivedelaydays','exclusivedelayhours','industry','service','subservice','state','city','customername','customerphone','customeremail','requirement','propertytype','budget','source','notes','projecttype','areasize','preferreddate','normal1share','normal3share','normal5share','pro1share','pro3share','pro5share','normal1shares','normal3shares','normal5shares','pro1shares','pro3shares','pro5shares','normal1shareprice','normal3sharesprice','normal5sharesprice','pro1shareprice','pro3sharesprice','pro5sharesprice']);const customFields={};Object.entries(raw).forEach(([k,v])=>{if(!known.has(norm(k))&&clean(v))customFields[k]=v});return{tmp:`${Date.now()}-${n}-${Math.random()}`,rowNumber:n+2,pricingName:get(raw,['Pricing Name']),leadType:norm(get(raw,['Lead Type']))==='premium'?'premium':'basic',isExclusive:bool(get(raw,['Exclusive','Is Exclusive'])),exclusiveDelayHours:get(raw,['Exclusive Delay Hours'])!==''?Number(get(raw,['Exclusive Delay Hours'])):daysToHours(get(raw,['Exclusive Delay Days'])),industryId:industry?.id||'',serviceId:service?.id||'',subserviceId:sub?.id||'',stateId:state?.id||'',cityId:city?.id||'',customerName:get(raw,['Customer Name']),customerPhone:get(raw,['Customer Phone']),customerEmail:get(raw,['Customer Email']),requirement:get(raw,['Requirement']),propertyType:get(raw,['Property Type']),budget:get(raw,['Budget']),source:get(raw,['Source'])||'upload',notes:get(raw,['Notes']),customFields,pricingSource:pricing?'sheet':'rule',pricing:pricing||undefined};};
 const uploadFile=async e=>{const f=e.target.files?.[0];if(!f)return;try{const raw=csvRows(await f.text());if(!raw.length)throw Error('Sheet is empty');const r=raw.map(make);setRows(r);setSelected(r.map(x=>x.tmp));setUpload(true)}catch(e2){setError(e2.message)}finally{e.target.value=''}};
 const change=(id,k,v)=>setRows(a=>a.map(r=>r.tmp===id?{...r,[k:v],...(k==='industryId'?{serviceId:'',subserviceId:''}:{}),...(k==='serviceId'?{subserviceId:''}:{}),...(k==='stateId'?{cityId:''}:{}),...(k==='isExclusive'&&!v?{exclusiveDelayHours:0}:{})}:r));
 const bulk=(k,v)=>setRows(a=>a.map(r=>selected.includes(r.tmp)?{...r,[k:v],...(k==='industryId'?{serviceId:'',subserviceId:''}:{}),...(k==='serviceId'?{subserviceId:''}:{}),...(k==='stateId'?{cityId:''}:{}),...(k==='isExclusive'&&!v?{exclusiveDelayHours:0}:{})}:r));
 const duplicateKey=r=>{const phone=clean(r.customerPhone).replace(/\D/g,'');const email=clean(r.customerEmail).toLowerCase();const name=clean(r.customerName).toLowerCase();const reqv=clean(r.requirement).toLowerCase();return [r.industryId,phone,email,name&&reqv?`${name}|${reqv}`:''].join('|')};
 const validate=chosen=>{const errs=[];const seen=new Map();chosen.forEach(r=>{let reason='';if(!r.industryId)reason='Industry is required';else{const k=duplicateKey(r);if(k.split('|').some(Boolean)&&seen.has(k))reason=`Duplicate of row ${seen.get(k)}`;else{const phone=clean(r.customerPhone).replace(/\D/g,'');const email=clean(r.customerEmail).toLowerCase();const found=leads.find(x=>String(x.industry_id)===String(r.industryId)&&((phone&&phone.length>=7&&phone===clean(x.customer_phone).replace(/\D/g,''))||(email&&email===clean(x.customer_email).toLowerCase())||(nameReq(r,x))));if(found)reason=`Duplicate of lead #${found.id}`;seen.set(k,r.rowNumber)}}if(reason)errs.push({row:r.rowNumber,reason,lead:r})});return errs};
 const downloadErrors=errors=>{if(!errors?.length)return;const h=['Row','Error','Customer Name','Customer Phone','Customer Email','Industry','Service','Subservice','Lead Type','Exclusive'];const lines=errors.map(e=>[e.row,e.reason,e.lead.customerName,e.lead.customerPhone,e.lead.customerEmail,findName(cat.industries,e.lead.industryId),findName(cat.services,e.lead.serviceId),findName(cat.subservices,e.lead.subserviceId),e.lead.leadType,e.lead.isExclusive?'TRUE':'FALSE']);const esc=v=>`"${String(v??'').replace(/"/g,'""')}"`;const csv=[h,...lines].map(r=>r.map(esc).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='propulse-lead-errors.csv';a.click();URL.revokeObjectURL(a.href)};
 const proceed=async()=>{const chosen=rows.filter(x=>selected.includes(x.tmp));const errs=validate(chosen);if(errs.length){const ok=window.confirm(`${errs.length} selected row(s) have errors or duplicates.\n\nProceed with ${chosen.length-errs.length} valid row(s) and skip the errors?`);if(!ok)return;setError(`${errs.length} row(s) skipped. Download the error sheet before closing the preview.`)}const bad=new Set(errs.map(x=>x.lead.tmp));setBusy(true);try{for(const r of chosen.filter(x=>!bad.has(x.tmp))){const p={...r};delete p.tmp;delete p.rowNumber;delete p.raw;delete p.matchWarnings;delete p.pricingName;await req('/leads',{method:'POST',body:JSON.stringify(p)})}setRows(chosen.filter(x=>bad.has(x.tmp)));setSelected(chosen.filter(x=>bad.has(x.tmp)).map(x=>x.tmp));if(!errs.length){setUpload(false);setRows([]);setSelected([]);await load()}}catch(e){setError(e.message)}finally{setBusy(false)}};
 const remove=async id=>{if(!confirm('Delete this lead permanently?'))return;setBusy(true);try{await req(`/leads/${id}`,{method:'DELETE'});setOpen(null);await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
 const beginEdit=l=>setEdit({...l,leadType:l.lead_type||'basic',isExclusive:Boolean(l.is_exclusive),exclusiveDelayHours:l.exclusive_delay_hours??0,industryId:l.industry_id||'',serviceId:l.service_id||'',subserviceId:l.subservice_id||'',stateId:l.state_id||'',cityId:l.city_id||'',customerName:l.customer_name||'',customerPhone:l.customer_phone||'',customerEmail:l.customer_email||'',requirement:l.requirement||'',propertyType:l.property_type||'',budget:l.budget||'',source:l.source||'upload',status:l.status||'available',notes:l.notes||'',customFields:l.custom_fields||{},pricing:l.pricing||emptyPricing});
 const save=async()=>{setBusy(true);try{await req(`/leads/${edit.id}`,{method:'PUT',body:JSON.stringify(edit)});setEdit(null);await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
 return <div className="v8-leads"><header className="v8-head"><div><h1>Lead Inventory</h1></div><div className="v8-head-actions"><button className="v8-btn primary" onClick={sample}>↓ Sample Sheet</button><button className="v8-btn primary" onClick={()=>file.current?.click()}>↑ Upload Leads</button><button className="v8-btn secondary" onClick={()=>setGoogleOpen(true)}>Google Sheets</button><input ref={file} hidden type="file" accept=".csv" onChange={uploadFile}/></div></header><div className="v8-stats"><Stat label="Basic Leads" value={leads.filter(x=>x.lead_type==='basic').length}/><Stat label="Premium Leads" value={leads.filter(x=>x.lead_type==='premium').length}/><Stat label="Exclusive" value={leads.filter(x=>x.is_exclusive).length}/><Stat label="Total" value={leads.length}/></div>{error&&<div className="v8-error">{error}<button onClick={()=>setError('')}>×</button></div>}<section className="v8-panel"><div className="v8-panel-head"><div><h2>All Leads</h2></div><button className="v8-btn secondary" onClick={load}>↻ Refresh</button></div>{loading?<div className="v8-empty">Loading…</div>:!leads.length?<div className="v8-empty">No leads yet.</div>:<div className="v8-grid">{leads.map(l=><Card key={l.id} lead={l} open={open===l.id} toggle={()=>setOpen(open===l.id?null:l.id)} edit={()=>beginEdit(l)} remove={()=>remove(l.id)}/>)}</div>}</section>{upload&&<Upload rows={rows} selected={selected} setSelected={setSelected} cat={cat} services={services} subservices={subservices} cities={cities} change={change} bulk={bulk} save={proceed} busy={busy} close={()=>setUpload(false)} errors={validate(rows.filter(x=>selected.includes(x.tmp)))} downloadErrors={downloadErrors}/>} {edit&&<Editor data={edit} setData={setEdit} cat={cat} services={services} subservices={subservices} cities={cities} close={()=>setEdit(null)} save={save} busy={busy}/>} {googleOpen&&<GoogleSheetsModal close={()=>setGoogleOpen(false)}/>}</div>
}
function findName(items,id){return items.find(x=>String(x.id)===String(id))?.name||''}
function nameReq(r,x){const name=clean(r.customerName).toLowerCase(),req=clean(r.requirement).toLowerCase();return name&&req&&name===clean(x.customer_name).toLowerCase()&&req===clean(x.requirement).toLowerCase()}
function Stat({label,value}){return <div className="v8-stat"><span>{label}</span><strong>{value}</strong></div>}
function Card({lead,open,toggle,edit,remove}){return <article className={`v8-card ${lead.lead_type} ${lead.is_exclusive?'exclusive':''}`}><div className="v8-card-top"><b className="v8-badge">{lead.lead_type==='premium'?'Premium':'Basic'}</b>{lead.is_exclusive&&<b className="v8-exclusive">★ Exclusive</b>}<span>{lead.status}</span></div><button className="v8-main" onClick={toggle}><small>#{lead.id}</small><h3>{lead.customer_name||'Untitled Lead'}</h3><p>{lead.customer_phone||'No phone'}{lead.customer_email?` · ${lead.customer_email}`:''}</p><div className="v8-meta"><div><label>Market</label><strong>{lead.industry_name||'Unclassified'}</strong><em>{lead.service_name||'No service'}{lead.subservice_name?` · ${lead.subservice_name}`:''}</em></div><div><label>Location</label><strong>{lead.city_name||'—'}</strong><em>{lead.state_name||'—'}</em></div></div><footer><strong>{lead.budget?`₹ ${lead.budget}`:'Budget not set'}</strong><span>{open?'Hide details':'View details'} {open?'⌃':'⌄'}</span></footer></button><div className="v8-actions"><button onClick={edit}>Edit</button><button onClick={remove}>Delete</button></div>{open&&<div className="v8-details"><section><label>Requirement</label><p>{lead.requirement||'No requirement provided.'}</p></section><div className="v8-detail-grid"><Detail k="Lead Type" v={title(lead.lead_type)}/><Detail k="Exclusive" v={lead.is_exclusive?'Yes':'No'}/>{lead.is_exclusive&&<Detail k="Pro-first delay" v={`${Math.round((lead.exclusive_delay_hours||0)/24)} day(s)`}/>}<Detail k="Industry" v={lead.industry_name}/><Detail k="Service" v={lead.service_name}/><Detail k="Subservice" v={lead.subservice_name}/><Detail k="City" v={lead.city_name}/><Detail k="State" v={lead.state_name}/><Detail k="Property Type" v={lead.property_type}/><Detail k="Source" v={lead.source}/><Detail k="Phone" v={lead.customer_phone}/><Detail k="Email" v={lead.customer_email}/>{Object.entries(lead.custom_fields||{}).map(([k,v])=><Detail key={k} k={title(k)} v={String(v)}/>)}</div>{lead.notes&&<section><label>Notes</label><p>{lead.notes}</p></section>}<div className="v8-detail-actions"><button onClick={edit}>Edit Lead</button><button onClick={remove}>Delete Lead</button></div></div>}</article>}
function Detail({k,v}){return <div><label>{k}</label><strong>{v||'—'}</strong></div>}
function Field({label,children}){return <label className="v8-field"><span>{label}</span>{children}</label>}
function SelectField({label,value,options,onChange}){return <Field label={label}><select value={value||''} onChange={e=>onChange(e.target.value)}><option value="">Not set</option>{options.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field>}
function Bulk({label,options,onChange}){return <Field label={`Bulk ${label}`}><select defaultValue="" onChange={e=>{if(e.target.value)onChange(e.target.value);e.target.value=''}}><option value="">Choose</option>{options.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field>}
function Upload({rows,selected,setSelected,cat,services,subservices,change,bulk,save,busy,close,errors,downloadErrors}){const all=rows.length>0&&selected.length===rows.length;const first=rows.find(x=>selected.includes(x.tmp));return <div className="v8-overlay"><div className="v8-modal"><header><div><h2>Review Leads</h2></div><button onClick={close}>×</button></header><div className="v8-import-toolbar"><label><input type="checkbox" checked={all} onChange={e=>setSelected(e.target.checked?rows.map(r=>r.tmp):[])}/> Select all ({selected.length}/{rows.length})</label><Bulk label="Industry" options={cat.industries} onChange={v=>bulk('industryId',v)}/><Bulk label="Service" options={first?services(first.industryId):[]} onChange={v=>bulk('serviceId',v)}/><Bulk label="Subservice" options={first?subservices(first.serviceId):[]} onChange={v=>bulk('subserviceId',v)}/><Bulk label="Lead Type" options={TYPES.map(x=>({id:x,name:title(x)}))} onChange={v=>bulk('leadType',v)}/><label className="v8-bulk-check"><input type="checkbox" onChange={e=>bulk('isExclusive',e.target.checked)}/> Exclusive</label></div>{errors.length>0&&<div className="v8-import-errors"><strong>{errors.length} issue(s)</strong><button className="v8-btn secondary" onClick={()=>downloadErrors(errors)}>↓ Download Errors</button></div>}<div className="v8-preview">{rows.map(r=><div className="v8-row" key={r.tmp}><div className="v8-row-select"><input type="checkbox" checked={selected.includes(r.tmp)} onChange={()=>setSelected(a=>a.includes(r.tmp)?a.filter(x=>x!==r.tmp):[...a,r.tmp])}/><strong>#{r.rowNumber}</strong></div><SelectField label="Industry *" value={r.industryId} options={cat.industries} onChange={v=>change(r.tmp,'industryId',v)}/><SelectField label="Service" value={r.serviceId} options={services(r.industryId)} onChange={v=>change(r.tmp,'serviceId',v)}/><SelectField label="Subservice" value={r.subserviceId} options={subservices(r.serviceId)} onChange={v=>change(r.tmp,'subserviceId',v)}/><Field label="Type"><select value={r.leadType} onChange={e=>change(r.tmp,'leadType',e.target.value)}><option value="basic">Basic</option><option value="premium">Premium</option></select></Field><div className="v8-exclusive"><label><input type="checkbox" checked={r.isExclusive} onChange={e=>change(r.tmp,'isExclusive',e.target.checked)}/> Exclusive</label>{r.isExclusive&&<input type="number" min="1" max="365" value={Math.max(1,Math.round((r.exclusiveDelayHours||24)/24))} onChange={e=>change(r.tmp,'exclusiveDelayHours',daysToHours(e.target.value))}/>}</div><div className="v8-row-info"><strong>{r.customerName||'No name'}</strong><span>{r.customerPhone||'No phone'} · {r.industryId?'Matched':'Industry required'}</span></div></div>)}</div><footer><span>{selected.length} selected</span><div><button className="v8-btn secondary" onClick={close}>Cancel</button><button className="v8-btn primary" disabled={busy||!selected.length} onClick={save}>{busy?'Importing…':'Import selected'}</button></div></footer></div></div>}
function Editor({data,setData,cat,services,subservices,close,save,busy}){const f=(k,v)=>setData({...data,[k]:v});return <div className="v8-overlay"><div className="v8-editor"><header><div><h2>Lead #{data.id}</h2></div><button onClick={close}>×</button></header><div className="v8-editor-grid"><SelectField label="Industry *" value={data.industryId} options={cat.industries} onChange={v=>setData({...data,industryId:v,serviceId:'',subserviceId:''})}/><SelectField label="Service" value={data.serviceId} options={services(data.industryId)} onChange={v=>setData({...data,serviceId:v,subserviceId:''})}/><SelectField label="Subservice" value={data.subserviceId} options={subservices(data.serviceId)} onChange={v=>f('subserviceId',v)}/><Field label="Lead Type"><select value={data.leadType} onChange={e=>f('leadType',e.target.value)}><option value="basic">Basic</option><option value="premium">Premium</option></select></Field><Field label="Customer Name"><input value={data.customerName} onChange={e=>f('customerName',e.target.value)}/></Field><Field label="Phone"><input value={data.customerPhone} onChange={e=>f('customerPhone',e.target.value)}/></Field><Field label="Email"><input value={data.customerEmail} onChange={e=>f('customerEmail',e.target.value)}/></Field><Field label="Budget"><input value={data.budget} onChange={e=>f('budget',e.target.value)}/></Field><Field label="Property Type"><input value={data.propertyType} onChange={e=>f('propertyType',e.target.value)}/></Field><Field label="Status"><select value={data.status} onChange={e=>f('status',e.target.value)}>{['available','paused','sold','closed','invalid'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Requirement"><textarea value={data.requirement} onChange={e=>f('requirement',e.target.value)}/></Field><label className="v8-bulk-check"><input type="checkbox" checked={data.isExclusive} onChange={e=>f('isExclusive',e.target.checked)}/> Exclusive</label>{data.isExclusive&&<Field label="Exclusive delay days"><input type="number" min="1" max="365" value={Math.max(1,Math.round((data.exclusiveDelayHours||24)/24))} onChange={e=>f('exclusiveDelayHours',daysToHours(e.target.value))}/></Field>}<Field label="Notes"><textarea value={data.notes} onChange={e=>f('notes',e.target.value)}/></Field></div><footer><button className="v8-btn secondary" onClick={close}>Cancel</button><button className="v8-btn primary" disabled={busy||!data.industryId} onClick={save}>{busy?'Saving…':'Save changes'}</button></footer></div></div>}
function GoogleSheetsModal({close}){return <div className="v8-overlay"><div className="v8-google-modal"><header><div><h2>Google Sheets</h2><p>Connect a sheet for automated lead imports.</p></div><button onClick={close}>×</button></header><div className="v8-google-body"><div className="v8-google-icon">G</div><strong>Google Sheets automation</strong><p>Sheet automation is ready for the next integration step. This button is kept separate from CSV upload so manual imports continue to work normally.</p><button className="v8-btn secondary" onClick={close}>Close</button></div></div></div>}
