import {useEffect,useRef,useState} from 'react';
import {authRequest} from '../../utils/auth';

const STORAGE_KEY='propulse.admin.googleSheet.sources';
const legacyKey='propulse.admin.googleSheet.url';
const fingerprintKey=url=>`propulse.admin.googleSheet.fingerprint.${url}`;
const clean=v=>String(v??'').trim();
const norm=v=>clean(v).toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]/g,'');

function parseCsv(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(c===','&&!quoted){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(v=>clean(v)))rows.push(row);row=[];cell=''}else cell+=c}row.push(cell);if(row.some(v=>clean(v)))rows.push(row);return rows}
function csvEscape(v){const s=String(v??'');return /[",\r\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
function canonicalizeCsv(csv){
 const aliases={
  post_code:'Pincode',postal_code:'Pincode',pin_code:'Pincode',zip_code:'Pincode',zipcode:'Pincode',zip:'Pincode',
  full_name:'Customer Name',name:'Customer Name',customer:'Customer Name',customer_name:'Customer Name',customername:'Customer Name',
  phone_number:'Customer Phone',mob_no:'Customer Phone',mobile:'Customer Phone',phone:'Customer Phone',contact_number:'Customer Phone',customer_phone:'Customer Phone',
  email:'Customer Email',email_id:'Customer Email',customer_email:'Customer Email',
  share_more_details_and_requirement:'Requirement',requirements:'Requirement',requirement:'Requirement',requirement_details:'Requirement',
  plot_location:'Location',location:'Location',lead_status:'Lead Status',created_time:'Created At',
  conditional_question_1:'Question 1',conditional_question_2:'Question 2',conditional_question_3:'Question 3',
  industry_name:'Industry',service_name:'Service',subservice_name:'Subservice',lead_source:'Source'
 };
 const normalizedAliases=Object.fromEntries(Object.entries(aliases).map(([key,value])=>[norm(key),value]));
 const rows=parseCsv(csv);if(!rows.length)return'';
 const headers=rows[0].map(v=>normalizedAliases[norm(v)]||clean(v));
 const seen=new Set();const finalHeaders=headers.map((h,i)=>{let x=h||`Column ${i+1}`;if(seen.has(norm(x)))x=`${x} ${i+1}`;seen.add(norm(x));return x});
 const capacityIndex=finalHeaders.findIndex(h=>['buyercapacity','buyercapacitylimit','maxbuyers','capacity'].includes(norm(h)));
 if(capacityIndex<0)finalHeaders.push('Buyer Capacity');
 const industryIndex=finalHeaders.findIndex(h=>norm(h)==='industry');
 const data=rows.slice(1).map(source=>{const row=[...source];while(row.length<finalHeaders.length)row.push('');if(capacityIndex<0)row.push('3');else{const n=Number(row[capacityIndex]);row[capacityIndex]=String(Number.isFinite(n)&&n>=2?Math.floor(n):3)}if(industryIndex>=0){const value=norm(row[industryIndex]);if(value==='intrior design and home interiors')row[industryIndex]='Interior Design & Home Interiors';}return row.slice(0,finalHeaders.length)});
 return [finalHeaders,...data].map(row=>row.map(csvEscape).join(',')).join('\n');
}
async function fingerprint(text){if(window.crypto?.subtle){const data=new TextEncoder().encode(text);const hash=await window.crypto.subtle.digest('SHA-256',data);return Array.from(new Uint8Array(hash)).map(x=>x.toString(16).padStart(2,'0')).join('')}let h=2166136261;for(let i=0;i<text.length;i++)h=Math.imul(h^text.charCodeAt(i),16777619);return String(h>>>0)}
async function readSheetInBrowser(value){const url=new URL(String(value||'').trim());if(url.protocol!=='https:'||url.hostname!=='docs.google.com')throw new Error('Enter a valid Google Sheets URL');const match=url.pathname.match(/\/spreadsheets\/(?:u\/\d+\/)?d\/([a-zA-Z0-9_-]+)/);if(!match)throw new Error('Google Sheets URL is not in a supported format');const gid=url.searchParams.get('gid')||(url.hash.match(/(?:^#|&)gid=(\d+)/)||[])[1]||'0';const targets=[`https://docs.google.com/spreadsheets/d/${match[1]}/gviz/tq?tqx=out:csv&gid=${encodeURIComponent(gid)}`,`https://docs.google.com/spreadsheets/d/${match[1]}/export?format=csv&gid=${encodeURIComponent(gid)}`];let last='';for(const target of targets){try{const response=await fetch(target,{headers:{Accept:'text/csv,text/plain;q=0.9'}});if(!response.ok){last=`Google Sheet could not be read (HTTP ${response.status})`;continue}const text=await response.text();if(!text.trim()){last='Google Sheet is empty';continue}if(/<html|<title>/i.test(text.slice(0,500)))throw new Error('Google Sheet access is restricted. Set General access to Anyone with the link → Viewer');return{csv:text}}catch(error){last=error.message||last}}throw new Error(last||'Unable to read Google Sheet')}

export default function GoogleSheetAutoSync(){
 const initial=()=>{try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');if(Array.isArray(saved)&&saved.length)return saved.filter(Boolean);const old=localStorage.getItem(legacyKey);return old?[old]:[]}catch{return[]}};
 const[sources,setSources]=useState(initial),[input,setInput]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);const running=useRef(false),timer=useRef(null);
 const save=next=>{setSources(next);localStorage.setItem(STORAGE_KEY,JSON.stringify(next));};
 const triggerExistingImporter=async csv=>{const inputEl=document.querySelector('input[type="file"][accept=".csv"]');if(!inputEl)throw new Error('Lead CSV importer is not available on this page');const file=new File([csv],`google-sheet-${Date.now()}.csv`,{type:'text/csv'}),transfer=new DataTransfer();transfer.items.add(file);inputEl.files=transfer.files;inputEl.dispatchEvent(new Event('change',{bubbles:true}));const deadline=Date.now()+20000;while(Date.now()<deadline){await new Promise(r=>setTimeout(r,400));const button=[...document.querySelectorAll('button')].find(b=>b.textContent?.trim()==='Import Leads'&&!b.disabled);if(button){const modal=document.querySelector('.v9-modal'),overlay=modal?.closest('.v9-overlay');if(overlay)overlay.style.visibility='hidden';button.click();return true}}throw new Error('Lead import preview did not finish in time')};
 const syncOne=async(url,force=false)=>{const result=await readSheetInBrowser(url).catch(()=>authRequest('/leads/google-sheet/preview',{method:'POST',body:JSON.stringify({url})}));const csv=canonicalizeCsv(result.csv||'');const next=await fingerprint(csv),previous=localStorage.getItem(fingerprintKey(url));if(!force&&previous===next)return false;await triggerExistingImporter(csv);localStorage.setItem(fingerprintKey(url),next);return true};
 const syncAll=async(force=false)=>{if(running.current||!sources.length)return;running.current=true;setBusy(true);let changed=0;try{for(const url of sources){try{if(await syncOne(url,force))changed++}catch(e){setStatus(`${url}: ${e.message||'Unable to sync'}`)}}setStatus(changed?`${changed} sheet(s) checked · new data imported automatically`:'All connected sheets are up to date');window.dispatchEvent(new Event('propulse:leads-refresh'))}finally{running.current=false;setBusy(false)}};
 useEffect(()=>{if(!sources.length)return undefined;syncAll();timer.current=setInterval(()=>syncAll(),30000);return()=>{if(timer.current)clearInterval(timer.current)}},[sources.length]);
 const connect=async()=>{const value=input.trim();if(!value){setStatus('Paste a Google Sheets URL first');return}if(sources.includes(value)){setStatus('This Google Sheet is already connected');return}setBusy(true);setStatus('Connecting and importing automatically…');try{const result=await readSheetInBrowser(value).catch(()=>authRequest('/leads/google-sheet/preview',{method:'POST',body:JSON.stringify({url:value})}));const csv=canonicalizeCsv(result.csv||'');await triggerExistingImporter(csv);localStorage.setItem(fingerprintKey(value),await fingerprint(csv));const next=[...sources,value];save(next);setInput('');setStatus(`Connected · ${next.length} sheet(s) active · leads imported automatically`)}catch(e){setStatus(e.message||'Unable to connect Google Sheet')}finally{setBusy(false)}};
 const disconnect=url=>{localStorage.removeItem(fingerprintKey(url));const next=sources.filter(x=>x!==url);save(next);setStatus(next.length?`Disconnected · ${next.length} sheet(s) still connected`:'All Google Sheets disconnected')};
 return <section style={{marginBottom:18,border:'1px solid #e6eaf0',borderRadius:18,padding:18,background:'#fff',boxShadow:'0 8px 28px rgba(15,23,42,.06)'}}><div style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',flexWrap:'wrap'}}><div><div style={{fontSize:11,fontWeight:800,letterSpacing:'.12em',color:'#64748b'}}>AUTOMATIC LEAD SOURCES</div><h3 style={{margin:'5px 0 3px',fontSize:18}}>Google Sheets</h3><div style={{fontSize:13,color:'#64748b'}}>Attach multiple sheets. New rows are checked every 30 seconds and imported automatically.</div></div><span style={{fontSize:12,fontWeight:700,padding:'7px 10px',borderRadius:999,background:sources.length?'#ecfdf5':'#f1f5f9',color:sources.length?'#047857':'#64748b'}}>{sources.length?`● ${sources.length} Connected`:'○ No sheets connected'}</span></div><div style={{display:'flex',gap:10,marginTop:14,flexWrap:'wrap'}}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Paste another Google Sheets URL" style={{flex:'1 1 420px',minWidth:240,padding:'11px 13px',border:'1px solid #dbe1e8',borderRadius:10,outline:'none'}}/><button className="v9-btn primary" onClick={connect} disabled={busy}>{busy?'Connecting…':'Connect Sheet'}</button>{sources.length>0&&<button className="v9-btn secondary" onClick={()=>syncAll(true)} disabled={busy}>{busy?'Checking…':'Check All Now'}</button>}</div>{sources.length>0&&<div style={{display:'grid',gap:8,marginTop:14}}>{sources.map((url,i)=><div key={url} style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:12,padding:'10px 12px',border:'1px solid #edf0f4',borderRadius:10,background:'#fafbfc'}}><div style={{minWidth:0}}><div style={{fontSize:12,fontWeight:700}}>Sheet {i+1}</div><div style={{fontSize:11,color:'#64748b',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{url}</div></div><button className="v9-btn secondary" onClick={()=>disconnect(url)} disabled={busy}>Disconnect</button></div>)}</div>}{status&&<div style={{marginTop:10,fontSize:12,color:'#475569'}}>{status}</div>}</section>;
}
