import {useEffect,useRef,useState} from 'react';
import {authRequest} from '../../utils/auth';

const STORAGE_KEY='propulse.admin.googleSheet.sources';
const legacyKey='propulse.admin.googleSheet.url';
const fingerprintKey=url=>`propulse.admin.googleSheet.fingerprint.${url}`;
const clean=v=>String(v??'').trim();
const norm=v=>clean(v).toLowerCase().replace(/&/g,'and').replace(/[^a-z0-9]/g,'');
const phoneKey=v=>clean(v).replace(/\D/g,'');
const emailKey=v=>clean(v).toLowerCase();

function parseCsv(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(c===','&&!quoted){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(v=>clean(v)))rows.push(row);row=[];cell=''}else cell+=c}row.push(cell);if(row.some(v=>clean(v)))rows.push(row);return rows}
function csvEscape(v){const s=String(v??'');return /[",\r\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
function objectsToCsv(headers,items){return [headers,...items.map(item=>headers.map(h=>item[h]??''))].map(row=>row.map(csvEscape).join(',')).join('\n')}
function get(raw,names){const key=Object.keys(raw).find(k=>names.some(n=>norm(k)===norm(n)));return key?clean(raw[key]):''}
function sourceId(row){return get(row,['id','Lead Id','Lead ID','External Id','External ID'])}
function parseRows(csv){const rows=parseCsv(csv);if(!rows.length)return{headers:[],items:[]};const aliases={post_code:'Pincode',postal_code:'Pincode',pin_code:'Pincode',zip_code:'Pincode',zipcode:'Pincode',zip:'Pincode',full_name:'Customer Name',name:'Customer Name',customer:'Customer Name',customer_name:'Customer Name',customername:'Customer Name',phone_number:'Customer Phone',mob_no:'Customer Phone',mobile:'Customer Phone',phone:'Customer Phone',contact_number:'Customer Phone',customer_phone:'Customer Phone',email:'Customer Email',email_id:'Customer Email',customer_email:'Customer Email',share_more_details_and_requirement:'Requirement',requirements:'Requirement',requirement:'Requirement',requirement_details:'Requirement',plot_location:'Location',location:'Location',lead_status:'Lead Status',created_time:'Created At',conditional_question_1:'Question 1',conditional_question_2:'Question 2',conditional_question_3:'Question 3',industry_name:'Industry',service_name:'Service',subservice_name:'Subservice',lead_source:'Source'};const normalizedAliases=Object.fromEntries(Object.entries(aliases).map(([k,v])=>[norm(k),v]));const headers=rows[0].map(v=>normalizedAliases[norm(v)]||clean(v));const seen=new Set();const finalHeaders=headers.map((h,i)=>{let x=h||`Column ${i+1}`;if(seen.has(norm(x)))x=`${x} ${i+1}`;seen.add(norm(x));return x});const capacityIndex=finalHeaders.findIndex(h=>['buyercapacity','buyercapacitylimit','maxbuyers','capacity'].includes(norm(h)));if(capacityIndex<0)finalHeaders.push('Buyer Capacity');const industryIndex=finalHeaders.findIndex(h=>norm(h)==='industry');const data=rows.slice(1).map(source=>{const row=[...source];while(row.length<finalHeaders.length)row.push('');if(capacityIndex<0)row.push('3');else{const n=Number(row[capacityIndex]);row[capacityIndex]=String(Number.isFinite(n)&&n>=2?Math.floor(n):3)}if(industryIndex>=0&&norm(row[industryIndex])==='intrior design and home interiors')row[industryIndex]='Interior Design & Home Interiors';return row.slice(0,finalHeaders.length)});return{headers:finalHeaders,items:data.map(row=>Object.fromEntries(finalHeaders.map((h,i)=>[h,clean(row[i])])))};}
function canonicalizeCsv(csv){const parsed=parseRows(csv);return parsed.headers.length?objectsToCsv(parsed.headers,parsed.items):''}
function stableObject(value){if(!value||typeof value!=='object'||Array.isArray(value))return value;return Object.keys(value).sort().reduce((out,key)=>{out[key]=stableObject(value[key]);return out},{});}
function rowMatchesLead(row,lead){const id=sourceId(row);const custom=lead?.custom_fields&&typeof lead.custom_fields==='object'?lead.custom_fields:{};const storedId=get(custom,['id','leadId','lead_id','externalId','external_id']);if(id&&storedId&&id===storedId)return true;const phone=phoneKey(get(row,['Customer Phone']));const email=emailKey(get(row,['Customer Email']));return Boolean((phone&&phoneKey(lead?.customer_phone)===phone)||(email&&emailKey(lead?.customer_email)===email));}
function dynamicFields(row){const fixed=new Set(['id','createdat','pincode','industry','service','subservice','state','city','customername','customerphone','customeremail','requirement','propertytype','budget','source','notes','buyercapacity','buyercapacitylimit','maxbuyers','capacity','leadtype','exclusive','isexclusive','exclusivedelaydays','exclusivedelayhours','investor','investorname','investoremail']);const custom={};Object.entries(row).forEach(([key,value])=>{if(!fixed.has(norm(key))&&clean(value))custom[key]=value});return custom}
function catalogMatch(items,value){const wanted=norm(value);return wanted?items.find(x=>norm(x.name)===wanted)||null:null}
function resolveClassification(row,cat){let industry=catalogMatch(cat.industries,get(row,['Industry']));let service=catalogMatch(cat.services,get(row,['Service']));let subservice=catalogMatch(cat.subservices,get(row,['Subservice']));if(service&&industry&&String(service.industry_id)!==String(industry.id))service=null;if(subservice&&service&&String(subservice.service_id)!==String(service.id))subservice=null;if(subservice&&!service)service=cat.services.find(x=>String(x.id)===String(subservice.service_id))||null;if(service&&!industry)industry=cat.industries.find(x=>String(x.id)===String(service.industry_id))||null;return{industry,service,subservice}}
function resolveCatalogLocation(row,cat){const state=catalogMatch(cat.states,get(row,['State']));const cityName=get(row,['City']);const city=state?cat.cities.find(x=>String(x.state_id)===String(state.id)&&norm(x.name)===norm(cityName)):catalogMatch(cat.cities,cityName);return{state,city}}
async function lookupPincode(value){const p=clean(value).replace(/\D/g,'');if(!/^\d{6}$/.test(p))return null;const response=await fetch(`https://api.postalpincode.in/pincode/${p}`);if(!response.ok)return null;const data=await response.json();const office=data?.[0]?.Status==='Success'?data[0].PostOffice?.[0]:null;if(!office)return null;return{pincode:p,stateName:office.State||'',cityName:office.District||office.Block||office.Name||''}}
function locationFromCatalog(info,cat){if(!info)return{state:null,city:null,pincode:''};const state=catalogMatch(cat.states,info.stateName);const city=state?cat.cities.find(x=>String(x.state_id)===String(state.id)&&norm(x.name)===norm(info.cityName)):null;return{state,city,pincode:info.pincode}}
function hasColumn(row,names){return Object.keys(row).some(k=>names.some(n=>norm(k)===norm(n)))}
function buildPayload(row,lead,cat,locationInfo){const classification=resolveClassification(row,cat);const catalogLocation=resolveCatalogLocation(row,cat);const location=locationInfo?locationFromCatalog(locationInfo,cat):catalogLocation;const custom={...dynamicFields(row),buyerCapacity:Math.max(2,Number(get(row,['Buyer Capacity','Buyer Capacity Limit','Max Buyers']))||3)};const id=sourceId(row);if(id)custom.id=id;const exclusiveColumnPresent=hasColumn(row,['Exclusive','Is Exclusive']);const leadTypeValue=get(row,['Lead Type']);return{industryId:classification.industry?.id||lead?.industry_id||'',serviceId:classification.service?.id||lead?.service_id||'',subserviceId:classification.subservice?.id||lead?.subservice_id||'',stateId:location.state?.id||lead?.state_id||'',cityId:location.city?.id||lead?.city_id||'',customerName:get(row,['Customer Name'])||lead?.customer_name||'',customerPhone:get(row,['Customer Phone'])||lead?.customer_phone||'',customerEmail:get(row,['Customer Email'])||lead?.customer_email||'',requirement:get(row,['Requirement']),propertyType:get(row,['Property Type'])||lead?.property_type||'',budget:get(row,['Budget'])||lead?.budget||'',source:get(row,['Source'])||lead?.source||'google-sheet',notes:get(row,['Notes'])||lead?.notes||'',pincode:location.pincode||get(row,['Pincode'])||lead?.pincode||'',buyerCapacity:custom.buyerCapacity,leadType:norm(leadTypeValue)==='premium'?'premium':(lead?.lead_type||'basic'),isExclusive:exclusiveColumnPresent?['true','yes','y','1','exclusive'].includes(norm(get(row,['Exclusive','Is Exclusive']))):false,exclusiveDelayDays:Number(get(row,['Exclusive Delay Days']))||1,customFields:custom,pricing:lead?.pricing||{shares:[]},pricingSource:lead?'rule':undefined,status:lead?.status||'available',sheetSync:{exclusiveColumnPresent}}}
function needsUpdate(next,lead){return !stableEqual(next.customerName,lead.customer_name)||!stableEqual(next.customerPhone,lead.customer_phone)||!stableEqual(next.customerEmail,lead.customer_email)||!stableEqual(next.requirement,lead.requirement)||!stableEqual(next.propertyType,lead.property_type)||!stableEqual(next.budget,lead.budget)||!stableEqual(next.source,lead.source)||!stableEqual(next.notes,lead.notes)||!stableEqual(next.pincode,lead.pincode)||Number(next.buyerCapacity)!==Number(lead.buyer_capacity)||String(next.industryId||'')!==String(lead.industry_id||'')||String(next.serviceId||'')!==String(lead.service_id||'')||String(next.subserviceId||'')!==String(lead.subservice_id||'')||String(next.stateId||'')!==String(lead.state_id||'')||String(next.cityId||'')!==String(lead.city_id||'')||Boolean(next.isExclusive)!==Boolean(lead.is_exclusive)||stableObject(next.customFields)!==stableObject(lead.custom_fields||{});}
function stableEqual(a,b){return clean(a)===clean(b)}
async function fingerprint(text){if(window.crypto?.subtle){const data=new TextEncoder().encode(text);const hash=await window.crypto.subtle.digest('SHA-256',data);return Array.from(new Uint8Array(hash)).map(x=>x.toString(16).padStart(2,'0')).join('')}let h=2166136261;for(let i=0;i<text.length;i++)h=Math.imul(h^text.charCodeAt(i),16777619);return String(h>>>0)}
async function readSheetInBrowser(value){const url=new URL(String(value||'').trim());if(url.protocol!=='https:'||url.hostname!=='docs.google.com')throw new Error('Enter a valid Google Sheets URL');const match=url.pathname.match(/\/spreadsheets\/(?:u\/\d+\/)?d\/([a-zA-Z0-9_-]+)/);if(!match)throw new Error('Google Sheets URL is not in a supported format');const gid=url.searchParams.get('gid')||(url.hash.match(/(?:^#|&)gid=(\d+)/)||[])[1]||'0';const targets=[`https://docs.google.com/spreadsheets/d/${match[1]}/gviz/tq?tqx=out:csv&gid=${encodeURIComponent(gid)}`,`https://docs.google.com/spreadsheets/d/${match[1]}/export?format=csv&gid=${encodeURIComponent(gid)}`];let last='';for(const target of targets){try{const response=await fetch(target,{headers:{Accept:'text/csv,text/plain;q=0.9'}});if(!response.ok){last=`Google Sheet could not be read (HTTP ${response.status})`;continue}const text=await response.text();if(!text.trim()){last='Google Sheet is empty';continue}if(/<html|<title>/i.test(text.slice(0,500)))throw new Error('Google Sheet access is restricted. Set General access to Anyone with the link → Viewer');return{csv:text}}catch(error){last=error.message||last}}throw new Error(last||'Unable to read Google Sheet')}

export default function GoogleSheetAutoSync(){
 const initial=()=>{try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');if(Array.isArray(saved)&&saved.length)return saved.filter(Boolean);const old=localStorage.getItem(legacyKey);return old?[old]:[]}catch{return[]}};
 const[sources,setSources]=useState(initial),[input,setInput]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);const running=useRef(false),timer=useRef(null);
 const save=next=>{setSources(next);localStorage.setItem(STORAGE_KEY,JSON.stringify(next));};
 const loadCatalog=async()=>{const[i,s,ss,st,c]=await Promise.all([authRequest('/industries'),authRequest('/services'),authRequest('/subservices'),authRequest('/states'),authRequest('/cities')]);return{industries:i,services:s,subservices:ss,states:st,cities:c}};
 const syncRows=async(csv,leads,cat)=>{const parsed=parseRows(csv);const unique=[];const seen=new Set();for(const row of parsed.items){const key=sourceId(row)||phoneKey(get(row,['Customer Phone']))||emailKey(get(row,['Customer Email']))||JSON.stringify(row);if(seen.has(key))continue;seen.add(key);unique.push(row)}let updated=0,created=0,unchanged=0,failed=0;const failures=[];for(const row of unique){let lead=leads.find(x=>rowMatchesLead(row,x));let locationInfo=null;const rawPin=get(row,['Pincode']);if(rawPin)locationInfo=await lookupPincode(rawPin).catch(()=>null);try{if(lead){const next=buildPayload(row,lead,cat,locationInfo);if(needsUpdate(next,lead)){await authRequest(`/leads/${lead.id}`,{method:'PUT',body:JSON.stringify(next)});updated++}else unchanged++;}else{const next=buildPayload(row,null,cat,locationInfo);if(!next.industryId)throw new Error('Industry not found');await authRequest('/leads',{method:'POST',body:JSON.stringify({...next,source:next.source||'google-sheet'})});created++;}}catch(error){failed++;failures.push(`${sourceId(row)||get(row,['Customer Phone'])||'row'}: ${error.message||'sync failed'}`)}}return{total:unique.length,updated,created,unchanged,failed,failures};};
 const syncOne=async(url,force=false)=>{const result=await readSheetInBrowser(url).catch(()=>authRequest('/leads/google-sheet/preview',{method:'POST',body:JSON.stringify({url})}));const csv=canonicalizeCsv(result.csv||'');const next=await fingerprint(csv);const previous=localStorage.getItem(fingerprintKey(url));if(!force&&previous===next)return{skipped:true};const[leadsResult,cat]=await Promise.all([authRequest('/leads?status=all'),loadCatalog()]);const leads=Array.isArray(leadsResult)?leadsResult:[];const resultSet=await syncRows(csv,leads,cat);localStorage.setItem(fingerprintKey(url),next);return{skipped:false,...resultSet}};
 const syncAll=async(force=false)=>{if(running.current||!sources.length)return;running.current=true;setBusy(true);let checked=0,total=0,updated=0,created=0,unchanged=0,failed=0;const failures=[];try{for(const url of sources){try{const result=await syncOne(url,force);if(result.skipped)continue;checked++;total+=result.total||0;updated+=result.updated||0;created+=result.created||0;unchanged+=result.unchanged||0;failed+=result.failed||0;failures.push(...(result.failures||[]))}catch(e){failed++;failures.push(`${url}: ${e.message||'Unable to sync'}`)}}if(checked){setStatus(`${checked} sheet(s) checked · ${created} new · ${updated} updated · ${unchanged} unchanged · ${failed} failed${failures.length?` · ${failures.slice(0,3).join(' | ')}`:''}`)}else setStatus('All connected sheets are up to date');window.dispatchEvent(new Event('propulse:leads-refresh'))}finally{running.current=false;setBusy(false)}};
 useEffect(()=>{if(!sources.length)return undefined;syncAll();timer.current=setInterval(()=>syncAll(),30000);return()=>{if(timer.current)clearInterval(timer.current)}},[sources.length]);
 const connect=async()=>{const value=input.trim();if(!value){setStatus('Paste a Google Sheets URL first');return}if(sources.includes(value)){setStatus('This Google Sheet is already connected');return}setBusy(true);setStatus('Connecting and syncing…');try{const result=await readSheetInBrowser(value).catch(()=>authRequest('/leads/google-sheet/preview',{method:'POST',body:JSON.stringify({url:value})}));const csv=canonicalizeCsv(result.csv||'');const[leadsResult,cat]=await Promise.all([authRequest('/leads?status=all'),loadCatalog()]);const leads=Array.isArray(leadsResult)?leadsResult:[];const resultSet=await syncRows(csv,leads,cat);localStorage.setItem(fingerprintKey(value),await fingerprint(csv));const next=[...sources,value];save(next);setInput('');setStatus(`Connected · ${resultSet.created} new · ${resultSet.updated} updated · ${resultSet.unchanged} unchanged · ${resultSet.failed} failed`);window.dispatchEvent(new Event('propulse:leads-refresh'))}catch(e){setStatus(e.message||'Unable to connect Google Sheet')}finally{setBusy(false)}};
 const disconnect=url=>{localStorage.removeItem(fingerprintKey(url));const next=sources.filter(x=>x!==url);save(next);setStatus(next.length?`Disconnected · ${next.length} sheet(s) still connected`:'All Google Sheets disconnected')};
 return <section style={{marginBottom:18,border:'1px solid #e6eaf0',borderRadius:18,padding:18,background:'#fff',boxShadow:'0 8px 28px rgba(15,23,42,.06)'}}><div style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',flexWrap:'wrap'}}><div><div style={{fontSize:11,fontWeight:800,letterSpacing:'.12em',color:'#64748b'}}>AUTOMATIC LEAD SOURCES</div><h3 style={{margin:'5px 0 3px',fontSize:18}}>Google Sheets</h3><div style={{fontSize:13,color:'#64748b'}}>New rows and edits are checked every 30 seconds and synced automatically.</div></div><span style={{fontSize:12,fontWeight:700,padding:'7px 10px',borderRadius:999,background:sources.length?'#ecfdf5':'#f1f5f9',color:sources.length?'#047857':'#64748b'}}>{sources.length?`● ${sources.length} Connected`:'○ No sheets connected'}</span></div><div style={{display:'flex',gap:10,marginTop:14,flexWrap:'wrap'}}><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Paste another Google Sheets URL" style={{flex:'1 1 420px',minWidth:240,padding:'11px 13px',border:'1px solid #dbe1e8',borderRadius:10,outline:'none'}}/><button className="v9-btn primary" onClick={connect} disabled={busy}>{busy?'Syncing…':'Connect Sheet'}</button>{sources.length>0&&<button className="v9-btn secondary" onClick={()=>syncAll(true)} disabled={busy}>{busy?'Checking…':'Check All Now'}</button>}</div>{sources.length>0&&<div style={{display:'grid',gap:8,marginTop:14}}>{sources.map((url,i)=><div key={url} style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:12,padding:'10px 12px',border:'1px solid #edf0f4',borderRadius:10,background:'#fafbfc'}}><div style={{minWidth:0}}><div style={{fontSize:12,fontWeight:700}}>Sheet {i+1}</div><div style={{fontSize:11,color:'#64748b',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{url}</div></div><button className="v9-btn secondary" onClick={()=>disconnect(url)} disabled={busy}>Disconnect</button></div>)}</div>}{status&&<div style={{marginTop:10,fontSize:12,color:'#475569'}}>{status}</div>}</section>;
}
