const clean=v=>String(v??'').trim();
const fieldByLabel=(row,label)=>[...row.querySelectorAll('.v9-field')].find(x=>clean(x.querySelector('span')?.textContent).toLowerCase()===label.toLowerCase());
const controlIn=(row,label)=>fieldByLabel(row,label)?.querySelector('input,select,textarea');
const setControl=(el,value)=>{if(!el)return;const proto=Object.getPrototypeOf(el);const descriptor=Object.getOwnPropertyDescriptor(proto,'value');if(descriptor?.set)descriptor.set.call(el,String(value));else el.value=String(value);el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));};
function addOptionsFrom(source,target){if(!source)return;[...source.options].forEach(o=>target.append(new Option(o.text,o.value)));}
function enhance(modal){if(modal.querySelector('.v9-import-bulk-row'))return;const rows=()=>[...modal.querySelectorAll('.v9-preview .v9-row')];const first=rows()[0];const preview=modal.querySelector('.v9-preview');if(!first||!preview)return;const bulk=document.createElement('div');bulk.className='v9-import-bulk-row';bulk.innerHTML='<div class="v9-import-bulk-select"><label><input type="checkbox"> <span>Select all</span></label></div><div class="v9-import-bulk-controls"><strong>Bulk edit selected</strong></div>';
const controls=bulk.querySelector('.v9-import-bulk-controls');
const industry=document.createElement('select');industry.setAttribute('aria-label','Bulk industry');industry.append(new Option('Industry',''));addOptionsFrom(controlIn(first,'Industry'),industry);
const type=document.createElement('select');type.setAttribute('aria-label','Bulk lead type');type.innerHTML='<option value="">Lead Type</option><option value="basic">Basic</option><option value="premium">Premium</option>';
const exclusive=document.createElement('select');exclusive.setAttribute('aria-label','Bulk exclusive');exclusive.innerHTML='<option value="">Exclusive</option><option value="false">No</option><option value="true">Yes</option>';
const delay=document.createElement('input');delay.type='number';delay.min='1';delay.max='365';delay.placeholder='Delay days';
const capacity=document.createElement('input');capacity.type='number';capacity.min='2';capacity.placeholder='Capacity (min 2)';
const investor=document.createElement('select');investor.setAttribute('aria-label','Bulk investor');investor.append(new Option('Investor',''));addOptionsFrom(controlIn(first,'Investor'),investor);if(![...investor.options].some(o=>o.value==='__none__'))investor.append(new Option('None','__none__'));
const apply=document.createElement('button');apply.className='v9-btn secondary';apply.type='button';apply.textContent='Apply to Selected';
const clear=document.createElement('button');clear.className='v9-btn secondary';clear.type='button';clear.textContent='Clear';
[ industry,type,exclusive,delay,capacity,investor,apply,clear ].forEach(x=>controls.append(x));
const style=document.createElement('style');style.textContent='.v9-import-bulk-row{position:sticky;top:0;z-index:10;display:grid;grid-template-columns:55px 1fr;gap:8px;align-items:center;min-width:1780px;padding:9px 10px;margin:0 0 8px;border:1px solid #cfdbea;border-radius:10px;background:#f4f8fd;box-shadow:0 4px 12px rgba(13,38,73,.08)}.v9-import-bulk-select{height:34px;display:flex;align-items:center}.v9-import-bulk-select label{font-size:9px;font-weight:900;color:#29466c;white-space:nowrap}.v9-import-bulk-select input{margin:0}.v9-import-bulk-controls{display:flex;align-items:center;gap:7px;flex-wrap:wrap}.v9-import-bulk-controls strong{font-size:9px;color:#29466c;margin-right:3px;white-space:nowrap}.v9-import-bulk-controls select,.v9-import-bulk-controls input{height:34px;border:1px solid #d0dbe8;border-radius:7px;background:#fff;padding:7px 9px;font:inherit;font-size:10px;color:#263b5c;outline:none;box-sizing:border-box}.v9-import-bulk-controls input{width:110px}.v9-import-bulk-controls button{min-height:34px;padding:0 10px;font-size:10px}.v9-import-bulk-row .v9-import-bulk-select input:indeterminate{accent-color:#0b2d63}@media(max-width:700px){.v9-import-bulk-row{grid-template-columns:45px 1fr;min-width:760px;align-items:start}.v9-import-bulk-controls{align-items:stretch}.v9-import-bulk-controls strong{width:100%}}';modal.appendChild(style);
preview.insertBefore(bulk,preview.firstChild);
const all=bulk.querySelector('input');const label=bulk.querySelector('.v9-import-bulk-select span');
const sync=()=>{const rs=rows();const checked=rs.filter(r=>r.querySelector('.v9-row-select input')?.checked);all.checked=rs.length>0&&checked.length===rs.length;all.indeterminate=checked.length>0&&checked.length<rs.length;label.textContent=`Select all (${checked.length}/${rs.length})`};
all.addEventListener('change',()=>{rows().forEach(r=>{const box=r.querySelector('.v9-row-select input');if(box&&box.checked!==all.checked)box.click()});setTimeout(sync,0)});
preview.addEventListener('change',e=>{if(e.target.matches('.v9-row-select input[type="checkbox"]'))setTimeout(sync,0)});
apply.addEventListener('click',()=>{const selected=rows().filter(r=>r.querySelector('.v9-row-select input')?.checked);if(!selected.length)return;selected.forEach(row=>{if(industry.value)setControl(controlIn(row,'Industry'),industry.value);if(type.value)setControl(controlIn(row,'Type'),type.value);if(exclusive.value)setControl(controlIn(row,'Exclusive'),exclusive.value);if(capacity.value)setControl(controlIn(row,'Capacity'),Math.max(2,Number(capacity.value)||2));if(investor.value!=='')setControl(controlIn(row,'Investor'),investor.value==='__none__'?'':investor.value);if(exclusive.value==='false')setControl(controlIn(row,'Exclusive Delay (days)'),0);else if(delay.value&&exclusive.value!=='false')setControl(controlIn(row,'Exclusive Delay (days)'),Math.max(1,Math.min(365,Number(delay.value)||1)))});setTimeout(sync,30)});
clear.addEventListener('click',()=>{industry.value='';type.value='';exclusive.value='';delay.value='';capacity.value='';investor.value=''});sync()}
function scan(){document.querySelectorAll('.v9-modal').forEach(enhance)}
const observer=new MutationObserver(scan);observer.observe(document.body,{childList:true,subtree:true});scan();
