import { useEffect, useState } from 'react'
import UserHeader from '../components/UserHeader'
import { authRequest } from '../utils/auth'

export default function CustomerHistory(){
  const [payments,setPayments]=useState([]),[purchases,setPurchases]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
  useEffect(()=>{let active=true;Promise.all([authRequest('/payments'),authRequest('/leads/purchased')]).then(([p,l])=>{if(active){setPayments(Array.isArray(p)?p:[]);setPurchases(Array.isArray(l)?l:[])}}).catch(e=>active&&setError(e.message||'Failed to load history')).finally(()=>active&&setLoading(false));return()=>{active=false}},[])
  return <div style={{minHeight:'100vh',background:'#f7f8fa'}}><UserHeader/><main style={{maxWidth:1180,margin:'0 auto',padding:'42px 24px'}}><div style={{marginBottom:30}}><span style={{fontSize:12,fontWeight:800,letterSpacing:1.5,color:'#667085'}}>ACCOUNT HISTORY</span><h1 style={{margin:'8px 0',fontSize:36}}>Payment & purchase history</h1><p style={{color:'#667085'}}>Review membership payments and every lead you have purchased.</p></div>{error&&<div style={{padding:14,background:'#fff0f0',borderRadius:10,color:'#b42318',marginBottom:20}}>{error}</div>}{loading?<div>Loading history…</div>:<><section style={{background:'#fff',border:'1px solid #e5e7eb',borderRadius:16,padding:22,marginBottom:24}}><h2>Lead purchases</h2>{!purchases.length?<p style={{color:'#667085'}}>No lead purchases yet.</p>:<div style={{display:'grid',gap:12}}>{purchases.map(x=><div key={x.id} style={{display:'flex',justifyContent:'space-between',gap:20,padding:'14px 0',borderBottom:'1px solid #eee'}}><div><b>Lead #{x.lead_id}</b><div style={{color:'#667085'}}>{x.service_name||x.industry_name||'Lead'} · {x.city_name||'—'}</div></div><div style={{textAlign:'right'}}><b>₹{Number(x.amount||0).toLocaleString('en-IN')}</b><div style={{color:'#667085'}}>{new Date(x.created_at).toLocaleDateString('en-IN')}</div></div></div>)}</div>}</section><section style={{background:'#fff',border:'1px solid #e5e7eb',borderRadius:16,padding:22}}><h2>Payments</h2>{!payments.length?<p style={{color:'#667085'}}>No payment records yet.</p>:<div style={{display:'grid',gap:12}}>{payments.map(x=><div key={x.id} style={{display:'flex',justifyContent:'space-between',gap:20,padding:'14px 0',borderBottom:'1px solid #eee'}}><div><b>{x.membership_plan_name||'Payment'}</b><div style={{color:'#667085'}}>{x.payment_method||'—'} · {x.manual_reference||x.gateway_payment_id||'No reference'}</div></div><div style={{textAlign:'right'}}><b>₹{Number(x.amount||0).toLocaleString('en-IN')}</b><div style={{color:'#667085'}}>{x.status} · {new Date(x.created_at).toLocaleDateString('en-IN')}</div></div></div>)}</div>}</section></>}</main></div>
}
