import { useEffect, useMemo, useState } from 'react'
import './Investment.css'
import { authRequest, getToken } from '../utils/auth'
import { API_BASE_URL } from '../utils/api'

const money = v => `₹${Number(v || 0).toLocaleString('en-IN',{maximumFractionDigits:2})}`
const list = v => Array.isArray(v) ? v : Array.isArray(v?.data) ? v.data : Array.isArray(v?.rows) ? v.rows : []
const cycleDate = value => value ? new Date(value).toLocaleDateString('en-IN', { day:'2-digit', month:'short', year:'numeric' }) : '—'
const cycleStatus = item => { const status=String(item?.status||'').toLowerCase(); if(status==='paid') return 'Paid'; if(status==='matured') return 'Matured'; if(status==='pending') return 'Payment pending'; if(status==='cancelled') return 'Cancelled'; return 'Active' }

export default function Investment(){
  const [access,setAccess]=useState(null),[rules,setRules]=useState([]),[wallet,setWallet]=useState(null),[funds,setFunds]=useState(null),[investments,setInvestments]=useState([]),[cycleLeads,setCycleLeads]=useState([]),[selectedCycle,setSelectedCycle]=useState(null),[cycleLeadsLoading,setCycleLeadsLoading]=useState(false)
  const [amount,setAmount]=useState(''),[autoInvest,setAutoInvest]=useState(true),[showInvest,setShowInvest]=useState(false),[showWithdraw,setShowWithdraw]=useState(false),[withdrawAmount,setWithdrawAmount]=useState(''),[withdrawNotes,setWithdrawNotes]=useState('')
  const [message,setMessage]=useState(''),[error,setError]=useState(''),[withdrawError,setWithdrawError]=useState(''),[busy,setBusy]=useState(false),[withdrawBusy,setWithdrawBusy]=useState(false),[payment,setPayment]=useState(null),[receiving,setReceiving]=useState([]),[paymentError,setPaymentError]=useState(''),[directBusy,setDirectBusy]=useState(false),[loadError,setLoadError]=useState('')
  const request=async(path,options={})=>{const r=await fetch(`${API_BASE_URL}${path}`,{...options,headers:{Authorization:`Bearer ${getToken()}`,'Content-Type':'application/json',...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d.error||`Request failed (${r.status})`);e.code=d.code;throw e}return d}
  const load=async()=>{setLoadError('');try{const a=await request('/investments/access');setAccess(a);if(!a.canInvest)return;const [r,w,f,cycles]=await Promise.all([request('/investments/rules'),request('/wallet'),request('/investments/funds'),request('/investments')]);setRules(list(r));setWallet(w);setFunds(f);setInvestments(list(cycles))}catch(e){setLoadError(e.message||'Unable to load investor workspace');setAccess(null)}}
  useEffect(()=>{load()},[])
  const openCycleLeads=async cycle=>{setSelectedCycle(cycle);setCycleLeads([]);setCycleLeadsLoading(true);try{const result=await request(`/investments/assigned-leads?cycleId=${Number(cycle.id)}`);setCycleLeads(list(result))}catch(e){setCycleLeads([{__error:e.message||'Unable to load linked leads'}])}finally{setCycleLeadsLoading(false)}}
  const config=useMemo(()=>{const active=rules.filter(x=>x&&x.is_active!==false);if(!active.length)return null;const minimum=Math.min(...active.map(x=>Number(x.minimum_amount)).filter(Number.isFinite));const maximum=Math.max(...active.map(x=>Number(x.maximum_amount)).filter(Number.isFinite));return{minimum,maximum}},[rules])
  const walletBalance=Number(wallet?.balance||0),value=Number(amount||0),canPay=value>0&&walletBalance>=value
  const totalInvested=Number(funds?.total_invested||0),availableAds=Number(funds?.available_for_ads ?? funds?.amount_in_ads ?? 0),spentAds=Number(funds?.ad_spent ?? funds?.total_ad_spent ?? 0),generated=Number(funds?.generated||0),transferable=Number(funds?.withdrawable_earnings ?? funds?.transferable ?? 0),pendingWithdrawal=Number(funds?.pending_withdrawal ?? funds?.payout_reserved ?? funds?.reserved ?? 0)
  const payoutAccount=funds?.payout_account||null
  const investorShare=Number(access?.revenueSharePercent ?? 100),marketingFee=Math.max(0,100-investorShare)
  const withdrawalValue=Number(withdrawAmount||0)
  const reinvestmentEnabled=autoInvest
  const validate=()=>{if(!config)throw Error('Investment configuration is unavailable. Please contact Propulse support.');if(value<=0)throw Error('Enter an investment amount.');if(value<config.minimum||value>config.maximum)throw Error(`Investment must be between ${money(config.minimum)} and ${money(config.maximum)}.`)}
  const payload=useWallet=>({amount:value,useWallet,reinvestmentEnabled })
  const invest=async()=>{setBusy(true);setError('');setMessage('');try{validate();if(!canPay)throw Error('Your wallet balance is not enough. Use direct payment to continue.');await request('/investments/checkout',{method:'POST',body:JSON.stringify(payload(true))});setShowInvest(false);setAmount('');setMessage('Investment started successfully. Propulse will manage the advertising allocation.');await load()}catch(e){setError(e.message||'Unable to create investment')}finally{setBusy(false)}}
  const startDirect=async()=>{setBusy(true);setError('');try{validate();if(canPay)throw Error('Your wallet can cover this investment. Use wallet payment instead.');const details=list(await authRequest('/payment-receiving-details'));if(!details.length)throw Error('Direct payment is not configured yet.');setReceiving(details);const p=await request('/investments/checkout',{method:'POST',body:JSON.stringify(payload(false))});setPayment(p);setShowInvest(false);setAmount('')}catch(e){setError(e.message||'Unable to prepare payment')}finally{setBusy(false)}}
  const submitPayment=async()=>{setPaymentError('');const ref=document.getElementById('investment-payment-utr')?.value?.trim();const file=document.getElementById('investment-payment-proof')?.files?.[0];if(!ref)return setPaymentError('Enter the payment reference / UTR first.');if(!file)return setPaymentError('Upload the payment screenshot or PDF first.');if(file.size>5*1024*1024)return setPaymentError('Payment proof must be 5 MB or smaller.');if(!payment?.payment?.id)return setPaymentError('Payment session is unavailable.');try{setDirectBusy(true);const proof=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error('Unable to read payment proof'));reader.readAsDataURL(file)});await authRequest(`/payments/${payment.payment.id}/reference`,{method:'POST',body:JSON.stringify({manualReference:ref,proofUrl:proof,notes:'Propulse managed investment direct payment'})});setPayment(null);setMessage('Payment submitted for verification.');await load()}catch(e){setPaymentError(e.message||'Unable to submit payment')}finally{setDirectBusy(false)}}
  const openWithdraw=()=>{setWithdrawError('');setWithdrawAmount('');setWithdrawNotes('');setShowWithdraw(true)}
  const submitWithdrawal=async()=>{setWithdrawError('');if(!payoutAccount){setWithdrawError('Add your Bank Account or UPI before withdrawing.');return}if(!Number.isFinite(withdrawalValue)||withdrawalValue<=0){setWithdrawError('Enter a withdrawal amount.');return}if(withdrawalValue>transferable){setWithdrawError('Withdrawal amount exceeds your available earnings.');return}try{setWithdrawBusy(true);await request('/investments/funds/transfer-request',{method:'POST',body:JSON.stringify({amount:withdrawalValue,notes:withdrawNotes})});setShowWithdraw(false);setWithdrawAmount('');setWithdrawNotes('');setMessage(`Withdrawal request for ${money(withdrawalValue)} submitted for review.`);await load()}catch(e){setWithdrawError(e.message||'Unable to submit withdrawal request')}finally{setWithdrawBusy(false)}}
  if(!access)return <main className="investment-page"><div className="investment-shell"><div className="investment-card investment-loading">{loadError||'Loading investor workspace…'}</div></div></main>
  if(!access.canInvest)return <main className="investment-page"><div className="investment-shell"><section className="investment-access-card"><span className="investment-kicker">PROPULSE INVESTOR</span><h1>Investment access</h1><p>{access.requiresPro?'An active Pro membership is required before you can invest.':'Investment is currently unavailable.'}</p></section></div></main>
  return <main className="investment-page"><div className="investment-shell">
    <section className="investment-hero"><div className="investment-hero-copy"><span className="investment-kicker">PROPULSE INVESTOR</span><h1>Grow with Propulse.</h1><p>Invest in your business profile and let Propulse put that capital to work. We use your investment to run targeted advertising for your business, generate customer enquiries, and call and qualify those leads before they are delivered to the market.</p><p>When your leads are sold, the configured Propulse Marketing Fee is deducted and the remaining investor share is credited as earnings. You can keep eligible earnings working through Auto-Invest or withdraw them to your saved Bank Account or UPI.</p><div className="investment-fee-split"><span>Propulse Marketing Fee: <b>{marketingFee}%</b></span><span>Investor Share: <b>{investorShare}%</b></span></div></div><div className="investment-hero-action"><span>READY TO INVEST?</span><strong>{money(walletBalance)}</strong><small>Available in your wallet</small><button type="button" onClick={()=>{setShowInvest(true);setError('')}}>＋ Invest Now</button>{transferable>0&&<button type="button" className="investment-withdraw-trigger" onClick={openWithdraw}>Withdraw Earnings</button>}</div></section>
    {message&&<div className="investment-message">{message}</div>}
    <section className="investment-how"><div className="investment-how-heading"><span className="investment-kicker">HOW IT WORKS</span><h2>You invest. Propulse operates.</h2></div><div className="investment-steps investment-steps-eight"><article><b>01</b><strong>Your investment</strong><p>You invest in your business profile.</p></article><article><b>02</b><strong>Targeted advertising</strong><p>Propulse uses your available investment funds to run advertising.</p></article><article><b>03</b><strong>Customer enquiries</strong><p>Advertising generates enquiries for your business.</p></article><article><b>04</b><strong>Call &amp; qualify</strong><p>Propulse calls and qualifies the generated leads.</p></article><article><b>05</b><strong>Lead sold</strong><p>Eligible leads are sold through the Propulse lead marketplace/process.</p></article><article><b>06</b><strong>Marketing fee</strong><p>The configured Propulse commission is deducted from the lead sale.</p></article><article><b>07</b><strong>Your earnings</strong><p>Your configured investor share is credited.</p></article><article><b>08</b><strong>Reinvest or withdraw</strong><p>Auto-Invest can put eligible earnings back into advertising, or you can withdraw eligible earnings.</p></article></div></section>
    <section className="investment-summary investment-summary-five"><article className="investment-summary-card investment-summary-primary"><span>TOTAL INVESTMENT</span><strong>{money(totalInvested)}</strong><small>Your original investor-contributed capital</small></article><article className="investment-summary-card"><span>AVAILABLE FOR ADS</span><strong>{money(availableAds)}</strong><small>Capital and unconsumed Auto-Invest earnings available for advertising</small></article><article className="investment-summary-card"><span>AD SPENT</span><strong>{money(spentAds)}</strong><small>Total actual advertising spend recorded</small></article><article className="investment-summary-card investment-withdraw-card"><span>AVAILABLE TO WITHDRAW</span><strong>{money(transferable)}</strong><small>Eligible earnings available for Bank / UPI withdrawal</small>{transferable>0&&<button type="button" onClick={openWithdraw}>Withdraw Earnings</button>}</article><article className="investment-summary-card"><span>LEAD GENERATED EARNINGS</span><strong>{money(generated)}</strong><small>Total investor earnings generated from paid lead sales</small></article></section>
    <section className="investment-cycles-section">
      <div className="investment-cycles-head">
        <div><span className="investment-kicker">INVESTMENT CYCLES</span><h2>Your investment cycles</h2><p>Every investment is tracked as a separate cycle. The cycle period and maturity date come directly from your investment record.</p></div>
        <div className="investment-cycle-config"><span>CONFIGURED CYCLE</span><strong>{Number(access?.investmentCycleDays ?? 0) === 0 ? 'Immediate' : String(Number(access?.investmentCycleDays ?? 0)) + ' days'}</strong></div>
      </div>
      {investments.length ? <div className="investment-cycle-list">{investments.map((item,index) => <article className="investment-cycle-card" key={item.id}>
        <div className="investment-cycle-top"><div><span>CYCLE #{item.id || index + 1}</span><strong>{item.industry_name || 'Propulse investment'}</strong><small>{[item.city_name,item.state_name].filter(Boolean).join(', ') || 'Managed investment target'}</small></div><b className={`investment-cycle-status ${String(item.status||'').toLowerCase()}`}>{cycleStatus(item)}</b></div>
        <div className="investment-cycle-metrics"><div><span>INVESTED</span><strong>{money(item.amount)}</strong></div><div><span>CYCLE</span><strong>{Number(item.maturity_days ?? access?.investmentCycleDays ?? 0) === 0 ? 'Immediate' : String(Number(item.maturity_days ?? access?.investmentCycleDays ?? 0)) + ' days'}</strong></div><div><span>STARTED</span><strong>{cycleDate(item.starts_at || item.created_at)}</strong></div><div><span>MATURES</span><strong>{cycleDate(item.matures_at)}</strong></div></div>
        <div className="investment-cycle-bottom"><span>Auto-Invest <b>{item.reinvestment_enabled ? 'ON' : 'OFF'}</b></span><span>Generated <b>{money(item.realized_revenue)}</b></span><span>Withdrawn / paid <b>{money(item.payout_amount)}</b></span><span>{item.parent_investment_id ? `Reinvested from #${item.parent_investment_id}` : item.reinvested_to_id ? `Reinvested to #${item.reinvested_to_id}` : 'Original cycle'}</span><button type="button" onClick={()=>openCycleLeads(item)}>View linked leads →</button></div>
      </article>)}</div> : <div className="investment-cycle-empty">No investment cycles yet. Start your first investment to create a cycle.</div>}
    </section>
    {selectedCycle&&<div className="investment-cycle-leads-overlay" onMouseDown={e=>e.target===e.currentTarget&&!cycleLeadsLoading&&setSelectedCycle(null)}><section className="investment-cycle-leads-modal"><button type="button" className="investment-cycle-leads-close" onClick={()=>setSelectedCycle(null)}>×</button><span className="investment-kicker">CYCLE #{selectedCycle.id} · LINKED LEADS</span><h2>{selectedCycle.industry_name||'Investment cycle'}</h2><p>Only leads whose paid-sale revenue is allocated to this investment cycle are shown here.</p>{cycleLeadsLoading?<div className="investment-cycle-leads-empty">Loading linked leads…</div>:cycleLeads.some(x=>x.__error)?<div className="investment-cycle-leads-empty">{cycleLeads.find(x=>x.__error)?.__error}</div>:cycleLeads.length?<div className="investment-cycle-leads-list">{cycleLeads.map(lead=><article key={lead.id}><div><strong>Lead #{lead.id} · {lead.name||'Customer lead'}</strong><small>{[lead.industry_name,lead.service_name,lead.subservice_name].filter(Boolean).join(' · ')}</small></div><div><span>PAID SALES</span><b>{Number(lead.paid_sale_count||0)}</b></div><div><span>GROSS SALE</span><b>{money(lead.gross_sale_amount)}</b></div><div><span>YOUR REVENUE</span><b>{money(lead.investor_revenue)}</b></div><div><span>STATUS</span><b>{lead.status||'—'}</b></div></article>)}</div>:<div className="investment-cycle-leads-empty">No linked lead-sale records are attached to this cycle yet.</div>}</section></div>}
    </section>{pendingWithdrawal>0&&<div className="investment-pending-withdrawal"><div><b>Pending withdrawal</b><span>{money(pendingWithdrawal)} reserved for an active withdrawal request.</span></div>{payoutAccount&&<small>{payoutAccount.method==='upi'?`UPI · ${payoutAccount.upi_id}`:`${payoutAccount.bank_name} · ${payoutAccount.account_number_masked} · ${payoutAccount.ifsc_code}`}</small>}</div>}
    {showInvest&&<div className="investment-modal-overlay" onMouseDown={e=>e.target===e.currentTarget&&!busy&&setShowInvest(false)}><section className="investment-modal investment-managed-modal"><button className="investment-modal-close" type="button" disabled={busy} onClick={()=>setShowInvest(false)}>×</button><span className="investment-kicker">INVEST IN PROPULSE</span><h2>Put your capital to work</h2><p>You choose the amount. Propulse automatically manages industry, location, advertising, lead generation and calling.</p><div className="managed-investment-explainer"><span>PROPULSE MANAGED</span><b>Investment → Advertising → Calling → Qualified leads → Lead sales → Earnings</b></div><label>Investment amount<input type="number" min={config?.minimum||1} max={config?.maximum||undefined} step="0.01" value={amount} onChange={e=>{setAmount(e.target.value);setError('')}} placeholder="Enter amount"/></label>{config&&<div className="investment-range"><span>Minimum <b>{money(config.minimum)}</b></span><span>Maximum <b>{money(config.maximum)}</b></span></div>}<label className="investment-reinvest-choice"><input type="checkbox" checked={reinvestmentEnabled} onChange={e=>setAutoInvest(e.target.checked)}/><span><b>Auto-Invest {reinvestmentEnabled?'ON':'OFF'}</b><small>{reinvestmentEnabled?'Eligible generated earnings stay available for Propulse advertising automatically.':'Eligible generated earnings can become available for withdrawal instead.'}</small></span></label><div className="investment-wallet-action"><div><span>Available wallet balance</span><strong>{money(walletBalance)}</strong></div>{canPay?<span className="investment-wallet-ready">✓ Wallet payment available</span>:value>0?<span className="investment-wallet-short">Direct payment available</span>:null}</div>{error&&<div className="investment-action-error" role="alert">{error}</div>}<div className="investment-action-buttons">{canPay?<button type="button" className="investment-submit" disabled={busy} onClick={invest}>{busy?'Processing…':'Invest Now →'}</button>:<button type="button" className="investment-submit investment-submit-direct" disabled={busy||!value} onClick={startDirect}>{busy?'Preparing payment…':'Continue to Payment →'}</button>}</div><div className="investor-note"><b>Propulse-managed investment</b><span>Returns depend on actual eligible lead-sale revenue and are not a fixed guaranteed return.</span></div></section></div>}
    {showWithdraw&&<div className="investment-modal-overlay" onMouseDown={e=>e.target===e.currentTarget&&!withdrawBusy&&setShowWithdraw(false)}><section className="investment-modal investment-withdraw-modal"><button className="investment-modal-close" type="button" disabled={withdrawBusy} onClick={()=>setShowWithdraw(false)}>×</button><span className="investment-kicker">WITHDRAW EARNINGS</span><h2>Withdraw your eligible earnings</h2><p>Only realized investor earnings can be withdrawn. Your original invested capital is never included.</p><div className="withdraw-available"><span>AVAILABLE TO WITHDRAW</span><strong>{money(transferable)}</strong></div>{payoutAccount?<div className="withdraw-destination"><span>SAVED DESTINATION</span>{payoutAccount.method==='upi'?<><b>UPI</b><small>{payoutAccount.upi_id}</small></>:<><b>{payoutAccount.bank_name}</b><small>{payoutAccount.account_holder_name} · {payoutAccount.account_number_masked} · {payoutAccount.ifsc_code}</small></>}</div>:<div className="withdraw-no-account"><b>Add your Bank Account or UPI before withdrawing.</b><a href="/profile/payout-account">Add payout account →</a></div>}<label>Withdrawal amount<input type="number" min="0.01" max={transferable||undefined} step="0.01" value={withdrawAmount} onChange={e=>setWithdrawAmount(e.target.value)} placeholder="Enter amount" disabled={!payoutAccount||withdrawBusy}/></label><label>Note (optional)<textarea value={withdrawNotes} onChange={e=>setWithdrawNotes(e.target.value)} placeholder="Optional note for the transfer request" disabled={withdrawBusy}/></label>{withdrawError&&<div className="investment-action-error" role="alert">{withdrawError}</div>}<button type="button" className="investment-submit" disabled={withdrawBusy||!payoutAccount||transferable<=0} onClick={submitWithdrawal}>{withdrawBusy?'Submitting…':'Submit Withdrawal Request →'}</button><div className="investor-note"><b>Withdrawal processing</b><span>Your request is reserved immediately and will be reviewed by Propulse. Rejected requests release the reserved amount.</span><span>Direct owner transfer sends approved earnings to your saved Bank Account or UPI.</span></div></section></div>}
    {payment&&<div className="investment-payment-overlay" onMouseDown={e=>e.target===e.currentTarget&&!directBusy&&setPayment(null)}><section className="investment-payment-modal"><button className="investment-payment-close" type="button" disabled={directBusy} onClick={()=>setPayment(null)}>×</button><span className="investment-kicker">DIRECT PAYMENT</span><h2>Complete your investment</h2><p>Transfer the exact amount, then submit your UTR and payment proof.</p><div className="investment-payment-amount"><span>AMOUNT TO PAY</span><strong>{money(payment.externalAmount??payment.payment?.external_amount??payment.payment?.amount)}</strong></div>{receiving.map((item,i)=><article className="investment-receiving-card" key={item.id||i}><strong>{item.account_name||item.bank_name||item.upi_id||'Payment account'}</strong><span>{[item.bank_name,item.account_number,item.ifsc,item.upi_id].filter(Boolean).join(' · ')}</span>{item.qr_code_url&&<img src={item.qr_code_url} alt="Payment QR code"/>}</article>)}<label className="investment-payment-field">Payment reference / UTR<input id="investment-payment-utr" type="text" placeholder="Enter UTR / transaction reference"/></label><label className="investment-payment-field">Payment proof<input id="investment-payment-proof" type="file" accept="image/*,.pdf"/></label>{paymentError&&<div className="investment-payment-error">{paymentError}</div>}<button className="investment-payment-submit" type="button" disabled={directBusy} onClick={submitPayment}>{directBusy?'Submitting…':'Submit for verification'}</button></section></div>}
  </div></main>
}
