import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import './Investment.css'
import { authRequest, getToken } from '../utils/auth'
import { API_BASE_URL } from '../utils/api'
const money = v => `₹${Number(v || 0).toLocaleString('en-IN',{maximumFractionDigits:2})}`
const list = v => Array.isArray(v) ? v : Array.isArray(v?.data) ? v.data : Array.isArray(v?.rows) ? v.rows : []
export default function Investment(){
  const navigate=useNavigate(); const [access,setAccess]=useState(null),[rules,setRules]=useState([]),[wallet,setWallet]=useState(null),[funds,setFunds]=useState(null),[cycle,setCycle]=useState(null)
  const [amount,setAmount]=useState(''),[autoInvest,setAutoInvest]=useState(true),[showInvest,setShowInvest]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[payment,setPayment]=useState(null),[receiving,setReceiving]=useState([]),[paymentError,setPaymentError]=useState(''),[directBusy,setDirectBusy]=useState(false),[loadError,setLoadError]=useState('')
  const [showWithdraw,setShowWithdraw]=useState(false),[withdrawAmount,setWithdrawAmount]=useState(''),[withdrawBusy,setWithdrawBusy]=useState(false),[withdrawError,setWithdrawError]=useState(''),[exitBusy,setExitBusy]=useState(false)
  const request=async(path,options={})=>{const r=await fetch(`${API_BASE_URL}${path}`,{...options,headers:{Authorization:`Bearer ${getToken()}`,'Content-Type':'application/json',...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d.error||`Request failed (${r.status})`);e.code=d.code;throw e}return d}
  const load=async()=>{setLoadError('');try{const a=await request('/investments/access');setAccess(a);if(!a.canInvest)return;const [r,w,f,cy]=await Promise.all([request('/investments/rules'),request('/wallet'),request('/investments/funds'),request('/investments/cycle')]);setRules(list(r));setWallet(w);setFunds(f);setCycle(cy?.cycle||cy||null);if(cy?.cycle)setAutoInvest(Boolean(cy.cycle.auto_invest))}catch(e){setLoadError(e.message||'Unable to load investor workspace');setAccess(null)}}
  useEffect(()=>{load()},[])
  const config=useMemo(()=>{const active=rules.filter(x=>x&&x.is_active!==false);if(!active.length)return null;const minimum=Math.min(...active.map(x=>Number(x.minimum_amount)).filter(Number.isFinite));const maximum=Math.max(...active.map(x=>Number(x.maximum_amount)).filter(Number.isFinite));return{minimum,maximum}},[rules])
  const walletBalance=Number(wallet?.balance||0),value=Number(amount||0),canPay=value>0&&walletBalance>=value
  const totalInvested=Number(funds?.total_invested||0),availableAds=Number(funds?.available_for_ads||0),spentAds=Number(funds?.ad_spent ?? funds?.total_ad_spent ?? 0),generated=Number(funds?.generated||0),transferable=Number(funds?.withdrawable_earnings ?? funds?.transferable ?? 0),reserved=Number(funds?.payout_reserved ?? funds?.reserved ?? 0)
  const payoutAccount=funds?.payout_account||null,requests=Array.isArray(funds?.requests)?funds.requests:[],pendingRequests=requests.filter(x=>String(x.status).toLowerCase()==='pending')
  const commissionPercent=Math.max(0,Math.min(100,100-Number(access?.revenueSharePercent ?? 100))),investorSharePercent=Math.max(0,Math.min(100,Number(access?.revenueSharePercent ?? 100))),withdrawValue=Number(withdrawAmount||0)
  const cycleStatus=String(cycle?.status||'').toUpperCase(),cycleClosing=['EXIT_REQUESTED','WAITING_FOR_LEADS'].includes(cycleStatus)
  const validate=()=>{if(!config)throw Error('Investment configuration is unavailable. Please contact Propulse support.');if(value<=0)throw Error('Enter an investment amount.');if(value<config.minimum||value>config.maximum)throw Error(`Investment must be between ${money(config.minimum)} and ${money(config.maximum)}.`)}
  const payload=useWallet=>({amount:value,useWallet,reinvestmentEnabled:autoInvest})
  const invest=async()=>{setBusy(true);setError('');setMessage('');try{validate();if(cycleClosing)throw Error('Your current cycle is closing. Wait until it is closed before starting another cycle.');if(!canPay)throw Error('Your wallet balance is not enough. Use direct payment to continue.');await request('/investments/checkout',{method:'POST',body:JSON.stringify(payload(true))});setShowInvest(false);setAmount('');setMessage(cycle?'Additional investment added to your current cycle successfully.':'Investment cycle started successfully. Propulse will manage the advertising allocation.');await load()}catch(e){setError(e.message||'Unable to create investment')}finally{setBusy(false)}}
  const startDirect=async()=>{setBusy(true);setError('');try{validate();if(cycleClosing)throw Error('Your current cycle is closing. Wait until it is closed before starting another cycle.');if(canPay)throw Error('Your wallet can cover this investment. Use wallet payment instead.');const details=list(await authRequest('/payment-receiving-details'));if(!details.length)throw Error('Direct payment is not configured yet.');setReceiving(details);const p=await request('/investments/checkout',{method:'POST',body:JSON.stringify(payload(false))});setPayment(p);setShowInvest(false);setAmount('')}catch(e){setError(e.message||'Unable to prepare payment')}finally{setBusy(false)}}
  const submitPayment=async()=>{setPaymentError('');const ref=document.getElementById('investment-payment-utr')?.value?.trim(),file=document.getElementById('investment-payment-proof')?.files?.[0];if(!ref)return setPaymentError('Enter the payment reference / UTR first.');if(!file)return setPaymentError('Upload the payment screenshot or PDF first.');if(file.size>5*1024*1024)return setPaymentError('Payment proof must be 5 MB or smaller.');if(!payment?.payment?.id)return setPaymentError('Payment session is unavailable.');try{setDirectBusy(true);const proof=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error('Unable to read payment proof'));reader.readAsDataURL(file)});await authRequest(`/payments/${payment.payment.id}/reference`,{method:'POST',body:JSON.stringify({manualReference:ref,proofUrl:proof,notes:'Propulse managed investment direct payment'})});setPayment(null);setMessage('Payment submitted for verification.');await load()}catch(e){setPaymentError(e.message||'Unable to submit payment')}finally{setDirectBusy(false)}}
  const openWithdraw=()=>{setWithdrawAmount('');setWithdrawError('');setMessage('');setShowWithdraw(true)}
  const submitWithdraw=async()=>{setWithdrawError('');const requested=Number(withdrawAmount);if(!Number.isFinite(requested)||requested<=0)return setWithdrawError('Enter a withdrawal amount greater than zero.');if(requested>transferable+1e-6)return setWithdrawError('Withdrawal amount exceeds your available earnings.');if(!payoutAccount)return setWithdrawError('Add your Bank Account or UPI before withdrawing.');try{setWithdrawBusy(true);await request('/investments/funds/transfer-request',{method:'POST',body:JSON.stringify({amount:requested,withdrawalType:'PARTIAL'})});setShowWithdraw(false);setWithdrawAmount('');setMessage('Withdrawal request submitted. Your earnings are now reserved while the request is pending.');await load()}catch(e){setWithdrawError(e.message||'Unable to submit withdrawal request')}finally{setWithdrawBusy(false)}}
  const requestFinalExit=async()=>{setError('');setMessage('');try{setExitBusy(true);await request('/investments/cycle/final-exit',{method:'POST',body:JSON.stringify({cycleId:cycle?.id})});setMessage('Final exit requested. New leads will stop and the cycle will close after existing leads reach a final state.');await load()}catch(e){setError(e.message||'Unable to request final exit')}finally{setExitBusy(false)}}
  const payoutDestination=()=>{if(!payoutAccount)return null;if(payoutAccount.method==='upi')return <><b>UPI</b><span>{payoutAccount.upi_id}</span></>;return <><b>Bank Account</b><span>{payoutAccount.account_holder_name} · {payoutAccount.bank_name}</span><span>{payoutAccount.account_number_masked} · {payoutAccount.ifsc_code}</span></>}
  if(!access)return <main className="investment-page"><div className="investment-shell"><div className="investment-card investment-loading">{loadError||'Loading investor workspace…'}</div></div></main>
  if(!access.canInvest)return <main className="investment-page"><div className="investment-shell"><section className="investment-access-card"><span className="investment-kicker">PROPULSE INVESTOR</span><h1>Investment access</h1><p>{access.requiresPro?'An active Pro membership is required before you can invest.':'Investment is currently unavailable.'}</p></section></div></main>
  return <main className="investment-page"><div className="investment-shell">
    <section className="investment-hero"><div className="investment-hero-copy"><span className="investment-kicker">PROPULSE INVESTOR</span><h1>Grow with Propulse.</h1><p>Invest in your business profile and let Propulse put that capital to work. We use your investment to run targeted advertising for your business, generate customer enquiries, and call and qualify those leads before they are delivered to the market.</p><p className="investment-hero-secondary">When your leads are sold, the configured Propulse Marketing Fee is deducted and the remaining investor share is credited as earnings. You can keep eligible earnings working through Auto-Invest or withdraw them to your saved Bank Account or UPI.</p><div className="investment-share-badges"><span>Propulse Marketing Fee: <b>{commissionPercent}%</b></span><span>Investor Share: <b>{investorSharePercent}%</b></span></div></div><div className="investment-hero-action"><span>{cycle?'CURRENT CYCLE':'READY TO INVEST?'}</span><strong>{money(walletBalance)}</strong><small>Available in your wallet</small><button type="button" onClick={()=>{setShowInvest(true);setError('')}} disabled={cycleClosing}>＋ {cycle?'Add Investment':'Invest Now'}</button></div></section>
    {message&&<div className="investment-message">{message}</div>}{error&&<div className="investment-action-error" role="alert">{error}</div>}
    {cycle&&<section className="investment-pending-card"><div><span className="investment-kicker">CURRENT INVESTMENT CYCLE</span><strong>Cycle #{cycle.id} · {cycleStatus.replaceAll('_',' ')}</strong><p>{money(cycle.principal)} invested · {Number(cycle.final_leads||0)} of {Number(cycle.total_leads||0)} leads final · {cycle.auto_invest?'Auto-Invest ON':'Auto-Invest OFF'}</p>{cycle.maturity_at&&<small>Maturity: {new Date(cycle.maturity_at).toLocaleDateString('en-IN')}</small>}</div><div>{cycle.auto_invest&&!cycleClosing&&<button type="button" className="investment-submit investment-submit-direct" disabled={exitBusy} onClick={requestFinalExit}>{exitBusy?'Requesting…':'Request Final Exit'}</button>}{cycleClosing&&<span className="investment-pending-pill">{cycleStatus.replaceAll('_',' ')}</span>}</div></section>}
    <section className="investment-how"><div className="investment-how-heading"><span className="investment-kicker">HOW IT WORKS</span><h2>Your capital. Our operations. Your eligible earnings.</h2></div><div className="investment-steps investment-steps-eight"><article><b>01</b><strong>Your Investment</strong><p>You invest in your business profile.</p></article><article><b>02</b><strong>Targeted Advertising</strong><p>Propulse uses available investment funds to run advertising.</p></article><article><b>03</b><strong>Customer Enquiries</strong><p>Advertising generates enquiries for your business.</p></article><article><b>04</b><strong>Call &amp; Qualify</strong><p>Propulse calls and qualifies generated leads.</p></article><article><b>05</b><strong>Lead Sold</strong><p>Eligible leads are sold through the Propulse lead process.</p></article><article><b>06</b><strong>Marketing Fee</strong><p>The configured Propulse commission is deducted from the sale.</p></article><article><b>07</b><strong>Your Earnings</strong><p>Your configured investor share is credited as earnings.</p></article><article><b>08</b><strong>Reinvest or Withdraw</strong><p>Auto-Invest can return eligible earnings to advertising, or you can withdraw them.</p></article></div></section>
    <section className="investment-summary investment-summary-five"><article className="investment-summary-card investment-summary-primary"><span>TOTAL INVESTMENT</span><strong>{money(totalInvested)}</strong><small>Your total invested capital. Principal is not withdrawable.</small></article><article className="investment-summary-card"><span>AVAILABLE FOR ADS</span><strong>{money(availableAds)}</strong><small>Money currently available to Propulse for advertising.</small></article><article className="investment-summary-card"><span>AD SPENT</span><strong>{money(spentAds)}</strong><small>Total actual advertising spend recorded.</small></article><article className="investment-summary-card investment-withdraw-card"><span>AVAILABLE TO WITHDRAW</span><strong>{money(transferable)}</strong><small>Eligible earnings not consumed by advertising and not already pending or paid.</small>{transferable>0&&<button type="button" onClick={openWithdraw}>Withdraw Earnings</button>}</article><article className="investment-summary-card"><span>LEAD GENERATED EARNINGS</span><strong>{money(generated)}</strong><small>Revenue credited from eligible paid lead sales.</small></article></section>
    {pendingRequests.length>0&&<section className="investment-pending-card"><div><span className="investment-kicker">WITHDRAWAL STATUS</span><strong>{pendingRequests.length===1?'Withdrawal request pending':`${pendingRequests.length} withdrawal requests pending`}</strong><p>{money(pendingRequests.reduce((sum,row)=>sum+Number(row.amount||0),0))} is currently reserved for pending withdrawal.</p></div><span className="investment-pending-pill">PENDING</span></section>}
    {reserved>0&&pendingRequests.length===0&&<section className="investment-pending-card"><div><span className="investment-kicker">WITHDRAWAL STATUS</span><strong>Pending withdrawal reserve</strong><p>{money(reserved)} is reserved for withdrawal requests awaiting processing.</p></div></section>}
    {showWithdraw&&<div className="investment-modal-overlay" onMouseDown={e=>e.target===e.currentTarget&&!withdrawBusy&&setShowWithdraw(false)}><section className="investment-modal investment-withdraw-modal"><button className="investment-modal-close" type="button" disabled={withdrawBusy} onClick={()=>setShowWithdraw(false)}>×</button><span className="investment-kicker">WITHDRAW EARNINGS</span><h2>Withdraw eligible earnings</h2><p>Your invested principal is never included. Only realized earnings that remain eligible after advertising consumption, paid withdrawals and pending reservations can be withdrawn.</p><div className="investment-withdraw-available"><span>Available to Withdraw</span><strong>{money(transferable)}</strong></div><div className="investment-withdraw-destination"><span>Current payout destination</span>{payoutDestination()}<button type="button" onClick={()=>navigate('/profile/payout-account')}>{payoutAccount?'Change payout account':'Add Bank Account or UPI'}</button></div><label>Withdrawal amount<input type="number" min="0.01" max={transferable||undefined} step="0.01" value={withdrawAmount} onChange={e=>setWithdrawAmount(e.target.value)} placeholder="Enter amount"/></label>{withdrawError&&<div className="investment-action-error" role="alert">{withdrawError}</div>}<button type="button" className="investment-submit investment-submit-direct" disabled={withdrawBusy||!payoutAccount||withdrawValue<=0||withdrawValue>transferable+1e-6} onClick={submitWithdraw}>{withdrawBusy?'Submitting…':'Submit Withdrawal Request →'}</button><div className="investor-note"><b>What happens next?</b><span>Your requested amount is reserved immediately. If an admin rejects the request, the reservation is released. Once paid, the amount permanently leaves your withdrawable earnings.</span></div></section></div>}
    {showInvest&&<div className="investment-modal-overlay" onMouseDown={e=>e.target===e.currentTarget&&!busy&&setShowInvest(false)}><section className="investment-modal investment-managed-modal"><button className="investment-modal-close" type="button" disabled={busy} onClick={()=>setShowInvest(false)}>×</button><span className="investment-kicker">{cycle?'ADD TO CURRENT CYCLE':'INVEST IN PROPULSE'}</span><h2>{cycle?'Add investment funds':'Put your capital to work'}</h2><p>You choose only the amount. Propulse automatically manages advertising, lead generation, calling and allocation.</p><div className="managed-investment-explainer"><span>PROPULSE MANAGED</span><b>Investment → Advertising → Calling → Qualified leads → Lead sales → Earnings</b></div><label>Investment amount<input type="number" min={config?.minimum||1} max={config?.maximum||undefined} step="0.01" value={amount} onChange={e=>{setAmount(e.target.value);setError('')}} placeholder="Enter amount"/></label>{config&&<div className="investment-range"><span>Minimum <b>{money(config.minimum)}</b></span><span>Maximum <b>{money(config.maximum)}</b></span></div>}<label className="investment-reinvest-choice"><input type="checkbox" checked={autoInvest} disabled={Boolean(cycle)} onChange={e=>setAutoInvest(e.target.checked)}/><span><b>Auto-Invest {autoInvest?'ON':'OFF'}</b><small>{cycle?'The current cycle keeps its Auto-Invest setting for all additional investments.':autoInvest?'Eligible generated earnings can stay available for Propulse advertising automatically.':'Eligible generated earnings can become available for withdrawal instead of being directed to advertising.'}</small></span></label><div className="investment-wallet-action"><div><span>Available wallet balance</span><strong>{money(walletBalance)}</strong></div>{canPay?<span className="investment-wallet-ready">✓ Wallet payment available</span>:value>0?<span className="investment-wallet-short">Direct payment available</span>:null}</div>{error&&<div className="investment-action-error" role="alert">{error}</div>}<div className="investment-action-buttons">{canPay?<button type="button" className="investment-submit" disabled={busy||cycleClosing} onClick={invest}>{busy?'Processing…':cycle?'Add to Current Cycle →':'Invest Now →'}</button>:<button type="button" className="investment-submit investment-submit-direct" disabled={busy||!value||cycleClosing} onClick={startDirect}>{busy?'Preparing payment…':'Continue to Payment →'}</button>}</div><div className="investor-note"><b>Propulse-managed investment</b><span>Returns depend on actual eligible lead-sale revenue and are not a fixed guaranteed return.</span></div></section></div>}
    {payment&&<div className="investment-payment-overlay" onMouseDown={e=>e.target===e.currentTarget&&!directBusy&&setPayment(null)}><section className="investment-payment-modal"><button className="investment-payment-close" type="button" disabled={directBusy} onClick={()=>setPayment(null)}>×</button><span className="investment-kicker">DIRECT PAYMENT</span><h2>Complete your investment</h2><p>Transfer the exact amount, then submit your UTR and payment proof.</p><div className="investment-payment-amount"><span>AMOUNT TO PAY</span><strong>{money(payment.externalAmount??payment.payment?.external_amount??payment.payment?.amount)}</strong></div>{receiving.map((item,i)=><article className="investment-receiving-card" key={item.id||i}><strong>{item.account_name||item.bank_name||item.upi_id||'Payment account'}</strong><span>{[item.bank_name,item.account_number,item.ifsc,item.upi_id].filter(Boolean).join(' · ')}</span>{item.qr_code_url&&<img src={item.qr_code_url} alt="Payment QR code"/>}</article>)}<label className="investment-payment-field">Payment reference / UTR<input id="investment-payment-utr" type="text" placeholder="Enter UTR / transaction reference"/></label><label className="investment-payment-field">Payment proof<input id="investment-payment-proof" type="file" accept="image/*,.pdf"/></label>{paymentError&&<div className="investment-payment-error">{paymentError}</div>}<button className="investment-payment-submit" type="button" disabled={directBusy} onClick={submitPayment}>{directBusy?'Submitting…':'Submit for verification'}</button></section></div>}
  </div></main>
}
