import {useEffect,useMemo,useState} from 'react'
import {Link} from 'react-router-dom'
import {authRequest,getUser} from '../utils/auth'
import UserHeader from '../components/UserHeader'
import './LeadPartner.css'
const money=v=>`₹${Number(v||0).toLocaleString('en-IN',{maximumFractionDigits:2})}`
export default function LeadPartner(){
 const user=getUser(),[partner,setPartner]=useState(null),[leads,setLeads]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[search,setSearch]=useState(''),[status,setStatus]=useState('all'),[editing,setEditing]=useState(null),[saving,setSaving]=useState(false)
 const load=async()=>{setLoading(true);try{const p=await authRequest('/lead-partner/me');setPartner(p);if(p?.status==='active'){const d=await authRequest(`/lead-partner/leads?status=${encodeURIComponent(status)}`);setLeads(Array.isArray(d?.leads)?d.leads:[])}else setLeads([])}catch(e){setError(e.message||'Unable to load Lead Partner workspace')}finally{setLoading(false)}}
 useEffect(()=>{load()},[status])
 const filtered=useMemo(()=>leads.filter(x=>{const q=search.trim().toLowerCase();return !q||[x.customer_name,x.customerName,x.industry_name,x.industryName,x.service_name,x.serviceName,x.city_name,x.cityName,x.customer_phone].some(v=>String(v||'').toLowerCase().includes(q))}),[leads,search])
 const apply=async()=>{try{setError('');await authRequest('/lead-partner/apply',{method:'POST',body:'{}'});setNotice('Application submitted. Admin approval is required.');await load()}catch(e){setError(e.message)}}
 const edit=lead=>setEditing({id:lead.id,name:lead.customerName||lead.customer_name||`Lead #${lead.id}`,shares:(lead.pricing?.shares||[]).map(x=>({shares:Number(x.shares),pro:Number(x.pro)}))})
 const save=async()=>{setSaving(true);try{await authRequest(`/lead-partner/leads/${editing.id}/pricing`,{method:'PATCH',body:JSON.stringify({shares:editing.shares.map(x=>({...x,pro:Number(x.pro)}))})});setEditing(null);setNotice('Lead pricing updated successfully.');await load()}catch(e){setError(e.message)}finally{setSaving(false)}}
 return <div className="lp-shell"><UserHeader/><main className="lp-page">
  <section className="lp-hero"><div><span>PROPULSE LEAD PARTNER</span><h1>Lead Partner Portal</h1><p>Manage your uploaded leads, set prices, and track their performance.</p></div><div className="lp-stat"><small>PARTNER STATUS</small><b>{partner?.status||'not_applied'}</b></div></section>
  {notice&&<div className="lp-notice">{notice}</div>}{error&&<div className="lp-error">{error}</div>}
  {(!partner||partner.status==='not_applied')&&<section className="lp-apply"><div><small>BECOME A PARTNER</small><h2>Turn your leads into inventory.</h2><p>Apply to become a Lead Partner. Once approved, you can manage your lead inventory and pricing.</p></div><button onClick={apply}>Apply as Lead Partner →</button></section>}
  {partner&&partner.status!=='active'&&partner.status!=='not_applied'&&<section className="lp-status"><small>APPLICATION STATUS</small><h2>{partner.status}</h2><p>Your account must be active before lead inventory access is enabled.</p></section>}
  {partner?.status==='active'&&<><section className="lp-toolbar"><div><small>LEAD INVENTORY</small><h2>Your uploaded leads</h2></div><div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search leads..."/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="available">Available</option><option value="sold">Sold</option><option value="invalid">Invalid</option></select></div></section><section className="lp-table"><header><span>Lead</span><span>Industry / Service</span><span>Location</span><span>Status</span><span>Pricing</span><span></span></header>{loading?<div className="lp-empty">Loading inventory…</div>:!filtered.length?<div className="lp-empty">No leads in your inventory.</div>:filtered.map(l=><article key={l.id}><div><b>#{l.id}</b><strong>{l.customerName||l.customer_name||'Customer lead'}</strong><small>{l.customerPhone||l.customer_phone||''}</small></div><div><strong>{l.industryName||l.industry_name||'—'}</strong><small>{l.serviceName||l.service_name||'—'}</small></div><div>{l.cityName||l.city_name||'—'}</div><div><em>{l.status}</em></div><div><strong>{(l.pricing?.shares||[]).length} tiers</strong><small>{l.overridden?'Customized':'Base pricing'}</small></div><button onClick={()=>edit(l)}>Manage pricing</button></article>)}</section></>}
 </main>{editing&&<div className="lp-overlay"><section className="lp-modal"><button className="lp-close" onClick={()=>setEditing(null)}>×</button><small>LEAD PRICING</small><h2>{editing.name}</h2><p>Configure the Pro price for each share tier.</p>{editing.shares.map((x,i)=><label className="lp-price" key={x.shares}>{x.shares} share{x.shares===1?'':'s'}<input type="number" min="0" value={x.pro} onChange={e=>setEditing(v=>({...v,shares:v.shares.map((t,j)=>j===i?{...t,pro:e.target.value}:t)}))}/></label>)}<button className="lp-save" disabled={saving} onClick={save}>{saving?'Saving…':'Save pricing'}</button></section></div>}</div>
}