import {Link,useSearchParams} from 'react-router-dom';
import {useEffect,useState} from 'react';
import {getToken,getUser} from '../utils/auth';
import './LeadsV2.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:5000/api';
const money=v=>v===null||v===undefined||v===''?'—':`₹${Number(v).toLocaleString('en-IN')}`;
export default function LeadsV2(){
 const [params]=useSearchParams();const category=params.get('category');const user=getUser();const token=getToken();const logged=Boolean(token&&user);const [leads,setLeads]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[upgrade,setUpgrade]=useState(false);
 useEffect(()=>{if(!logged||user?.role==='admin')return;let live=true;(async()=>{setLoading(true);try{const q=new URLSearchParams({status:'available'});const r=await fetch(`${API}/leads?${q}`,{headers:{Authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok)throw Error(d.error||'Failed to load leads');if(live)setLeads(Array.isArray(d)?d:[])}catch(e){if(live)setError(e.message)}finally{if(live)setLoading(false)}})();return()=>{live=false}},[logged,token,user?.role]);
 if(!logged)return <main className="lv2-page"><section className="lv2-empty"><span>PROPULSE LEAD MARKETPLACE</span><h1>Sign in to access leads.</h1><p>Browse opportunities matched to your business profile.</p><Link to="/login">Login to continue →</Link></section></main>;
 if(user?.role==='admin')return <main className="lv2-page"><section className="lv2-empty"><span>ADMIN ACCOUNT</span><h1>Lead management is in the Admin Panel.</h1><Link to="/admin/leads">Open Admin Leads →</Link></section></main>;
 const filtered=category?leads.filter(l=>`${l.industry_name||''} ${l.service_name||''} ${l.subservice_name||''}`.toLowerCase().includes(category.replaceAll('-',' ').toLowerCase())):leads;const isPro=Boolean(leads.find(l=>l.is_pro_member)?.is_pro_member);
 const exclusiveAction=lead=>{if(!lead.has_exclusive_option)return; if(lead.exclusive_action==='upgrade_to_pro'){setUpgrade(true);return} window.alert('Exclusive purchase selected. Connect your checkout/payment flow to complete the purchase.');};
 return <main className="lv2-page"><header className="lv2-head"><div><span>LEAD MARKETPLACE</span><h1>{category?`${category.replaceAll('-',' ')} leads`:'Available leads'}</h1><p>Qualified opportunities matched to your business profile.</p></div><div className="lv2-head-right">{isPro&&<b className="pro-chip">PRO MEMBER</b>}<Link to="/dashboard">Dashboard →</Link></div></header>{error&&<div className="lv2-error">{error}</div>}{loading?<div className="lv2-empty">Loading available leads…</div>:!filtered.length?<div className="lv2-empty"><strong>No available leads yet</strong><span>Complete your business profile with the services and locations you serve.</span><Link to="/profile">Update business profile →</Link></div>:<div className="lv2-grid">{filtered.map(lead=><article className={`lv2-card ${lead.lead_type}`} key={lead.id}><div className="lv2-card-top"><span className={`lv2-tier ${lead.lead_type}`}>{lead.lead_type==='premium'?'PREMIUM':'BASIC'}</span><span className="lv2-status">AVAILABLE</span></div><div className="lv2-id">#{lead.id}</div><h2>{lead.service_name||'Lead opportunity'}</h2><p className="lv2-req">{lead.requirement||'Requirement details available after selection.'}</p><div className="lv2-location">⌖ {lead.city_name||'—'}, {lead.state_name||'—'}</div><div className="lv2-prices"><div><small>1 SHARE</small><b>{money(lead.pricing?.shares?.find(x=>Number(x.shares)===1)?.normal)}</b></div><div><small>3 SHARES</small><b>{money(lead.pricing?.shares?.find(x=>Number(x.shares)===3)?.normal)}</b></div><div><small>5 SHARES</small><b>{money(lead.pricing?.shares?.find(x=>Number(x.shares)===5)?.normal)}</b></div></div>{lead.has_exclusive_option&&<div className="lv2-exclusive"><div><b>EXCLUSIVE</b><span>{lead.exclusive_available?'Available now':`Pro-first for ${lead.exclusive_delay_hours??24}h`}</span></div><strong>{money(lead.is_pro_member?lead.pricing?.exclusive?.pro:lead.pricing?.exclusive?.normal)}</strong></div>}<div className="lv2-actions"><button onClick={()=>window.alert('Share purchase selected. Connect your checkout/payment flow to complete the purchase.')}>Buy Share</button>{lead.has_exclusive_option&&(lead.exclusive_action==='upgrade_to_pro'?<button className="upgrade" onClick={()=>exclusiveAction(lead)}>Get Pro to buy Exclusive</button>:lead.exclusive_action==='buy'?<button className="exclusive-btn" onClick={()=>exclusiveAction(lead)}>Buy Exclusive</button>:null)}</div></article>)}</div>}{upgrade&&<div className="lv2-overlay"><div className="lv2-upgrade"><button onClick={()=>setUpgrade(false)}>×</button><span>EXCLUSIVE ACCESS</span><h2>Go Pro to buy Exclusive leads first.</h2><p>Pro members can purchase the Exclusive option immediately during the Pro-first period.</p><div><Link to="/dashboard">View Pro options →</Link><button onClick={()=>setUpgrade(false)}>Not now</button></div></div></div>}</main>;
}
