import { Fragment, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { authRequest, clearSession, getUser } from '../utils/auth';
import './LeadPartnerHome.css';
import './LeadPartnerInventory.css';

const statusLabel = value => String(value || '').replace(/_/g, ' ').replace(/\b\w/g, x => x.toUpperCase());
const formatDate = value => value ? new Date(value).toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' }) : 'Never';
const detailLabel = key => String(key || '').replace(/[_-]+/g, ' ').replace(/\s+/g, ' ').replace(/\b\w/g, x => x.toUpperCase());

function downloadCsvSample() {
  const headers = ['Lead ID','Industry','Service','Subservice','Pincode','Customer Name','Customer Phone','Customer Email','Requirement','Property Type','Budget','Source','Notes','Buyer Capacity','Lead Type','Exclusive','WhatsApp Number','STATUS','Remarks','CONTACTED BY','NEXT FOLLOWUP','How soon do you want to buy?','Job title'];
  const row = ['LP-001','REPLACE WITH ACTIVE INDUSTRY','','','500001','Example Customer','9876500000','customer@example.com','Example lead requirement','Residential','2500000','Website','Example note','3','basic','FALSE','9876500000','FOLLOW UP','Call tomorrow','Ravi','Tomorrow','Right away','Owner'];
  const esc = value => `"${String(value ?? '').replace(/"/g, '""')}"`;
  const csv = [headers,row].map(values => values.map(esc).join(',')).join('\n');
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8' });
  const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'propulse-lead-partner-upload-sample.csv'; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url);
}

export default function LeadPartnerInventory() {
  const navigate = useNavigate(); const location = useLocation(); const user = getUser(); const fileRef = useRef(null);
  const [data,setData]=useState({data:[],stats:{}}); const [loading,setLoading]=useState(true); const [importing,setImporting]=useState(false); const [sheetBusy,setSheetBusy]=useState(false); const [syncingId,setSyncingId]=useState(null); const [sheetUrl,setSheetUrl]=useState(''); const [search,setSearch]=useState(''); const [status,setStatus]=useState('all'); const [industryId,setIndustryId]=useState('all'); const [cityId,setCityId]=useState('all'); const [connections,setConnections]=useState([]); const [message,setMessage]=useState(null); const [expanded,setExpanded]=useState({}); const [sourceOpen,setSourceOpen]=useState(false); const [view,setView]=useState('list');
  const initials=useMemo(()=>(user?.name||'Lead Partner').split(' ').filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'LP',[user?.name]);
  const load=useCallback(async()=>{try{setLoading(true);const params=new URLSearchParams({status,search,industryId,cityId});setData(await authRequest(`/lead-partner/inventory?${params}`));}catch(e){setMessage({type:'error',text:e.message});}finally{setLoading(false);}},[status,search,industryId,cityId]);
  const loadConnections=useCallback(async()=>{try{const result=await authRequest('/lead-partner/inventory/sheets');setConnections(result?.connections||[]);}catch(e){setMessage({type:'error',text:e.message});}},[]);
  useEffect(()=>{load();},[load]); useEffect(()=>{loadConnections();},[loadConnections]);
  async function connectGoogleSheet(e){e.preventDefault();if(!sheetUrl.trim())return setMessage({type:'error',text:'Enter a Google Sheets URL.'});try{setSheetBusy(true);setMessage(null);const r=await authRequest('/lead-partner/inventory/sheets',{method:'POST',body:JSON.stringify({url:sheetUrl.trim()})});setSheetUrl('');setMessage({type:r.failed?'error':'success',text:`Sheet connected. Imported ${r.created} leads. ${r.duplicate} duplicates, ${r.failed} failed.${r.failures?.length?` First failure: ${r.failures[0]}`:''}`});await Promise.all([load(),loadConnections()]);}catch(e){setMessage({type:'error',text:e.message});}finally{setSheetBusy(false);}}
  async function syncSheet(id){try{setSyncingId(id);setMessage(null);const r=await authRequest(`/lead-partner/inventory/sheets/${id}/sync`,{method:'POST'});setMessage({type:r.failed?'error':'success',text:`Sync complete. Imported ${r.created} leads. ${r.duplicate} duplicates, ${r.failed} failed.${r.failures?.length?` First failure: ${r.failures[0]}`:''}`});await Promise.all([load(),loadConnections()]);}catch(e){setMessage({type:'error',text:e.message});}finally{setSyncingId(null);}}
  async function disconnectSheet(id){if(!window.confirm('Disconnect this Google Sheet? Existing imported leads will remain in your inventory.'))return;try{setSheetBusy(true);await authRequest(`/lead-partner/inventory/sheets/${id}`,{method:'DELETE'});setMessage({type:'success',text:'Google Sheet disconnected. Existing leads were not deleted.'});await loadConnections();}catch(e){setMessage({type:'error',text:e.message});}finally{setSheetBusy(false);}}
  async function importCsv(file){if(!file)return;if(!/\.csv$/i.test(file.name))return setMessage({type:'error',text:'Please export the sheet as CSV before uploading.'});try{setImporting(true);setMessage(null);const csv=await file.text();const r=await authRequest('/lead-partner/inventory/import/csv',{method:'POST',body:JSON.stringify({csv})});setMessage({type:r.failed?'error':'success',text:`Imported ${r.created} leads. ${r.duplicate} duplicates, ${r.failed} failed.${r.failures?.length?` First failure: ${r.failures[0]}`:''}`});await load();}catch(e){setMessage({type:'error',text:e.message});}finally{setImporting(false);if(fileRef.current)fileRef.current.value='';}}
  const rows=data.data||[];

  function signOut(){clearSession();localStorage.removeItem('propulse_session_mode');navigate('/login',{replace:true});}
  const stats=data.stats||{}; const activeConnections=connections.filter(x=>x.status==='active'); const money=v=>Number(v||0)>0?`₹${Number(v).toLocaleString('en-IN',{maximumFractionDigits:2})}`:'—'; const getPrice=lead=>lead.partner_base_pricing?.shares?.[0]?.price??lead.pricing?.shares?.[0]?.price??lead.price; const getBuyerCount=lead=>lead.buyer_count??lead.buyers_count??0; function exportCsv(){const h=['ID','Name','Phone','Service','Location','Price','Buyers','Status','Added On'];const csv=[h,...rows.map(l=>[l.id,l.customer_name||'',l.customer_phone||'',l.service_name||l.industry_name||'',l.city_name||'',getPrice(l)||'',getBuyerCount(l),l.status||'',l.created_at||''])].map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='propulse-lead-inventory.csv';a.click();URL.revokeObjectURL(a.href);}
  return <div className="partner-shell">
    <aside className="partner-sidebar"><div className="partner-brand"><span className="partner-brand-mark">P</span><span><b>PRO<span>PULSE</span></b><small>LEAD PARTNER</small></span></div><div className="partner-nav-label">WORKSPACE</div><nav className="partner-nav"><Link className={location.pathname==='/lead-partner'?'active':''} to="/lead-partner"><i>⌂</i><span>Overview</span></Link><Link className={location.pathname.startsWith('/lead-partner/inventory')?'active':''} to="/lead-partner/inventory"><i>◈</i><span>Lead Inventory</span></Link><Link to="/lead-partner/pricing" className={location.pathname.startsWith('/lead-partner/pricing')?'active':''}><i>₹</i><span>Pricing & Revenue</span></Link><Link to="/lead-partner/withdrawals" className={location.pathname.startsWith('/lead-partner/withdrawals')?'active':''}><i>⇩</i><span>Earnings & Withdrawals</span></Link></nav><div className="partner-sidebar-bottom"><div className="partner-sidebar-user"><span>{initials}</span><div><b>{user?.name||'Lead Partner'}</b><small>{user?.email||'Partner account'}</small></div></div><button onClick={signOut}>↪ <span>Log out</span></button></div></aside>
    <main className="partner-main"><header className="partner-topbar"><div className="partner-breadcrumb"><span>Lead Partner</span><b>/</b><strong>Lead Inventory</strong></div><div className="partner-top-status"><i/> Partner account</div></header>
      <div className="partner-content">
        <section className="inventory-hero"><div><span className="inventory-eyebrow">LEAD PARTNER PORTAL</span><h1>Lead Inventory</h1><p>Manage your uploaded leads, set prices, and track their performance.</p></div><div className="inventory-actions"><button onClick={()=>fileRef.current?.click()}><span>↥</span> Import Leads</button><button onClick={()=>setSourceOpen(v=>!v)}><span>▣</span> Connect Google Sheet</button><button className="primary" onClick={()=>setSourceOpen(true)}><span>＋</span> Add Lead</button></div></section>
        {message&&<div className={`partner-alert ${message.type}`}><strong>{message.type==='success'?'Import complete':'Import needs attention'}</strong><span>{message.text}</span></div>}
        {sourceOpen&&<section className="inventory-source"><div><b>Lead sources</b><span>Import CSV or connect a shareable Google Sheet.</span></div><div className="inventory-source-actions"><input value={sheetUrl} onChange={e=>setSheetUrl(e.target.value)} placeholder="Google Sheets URL"/><button onClick={connectGoogleSheet} disabled={sheetBusy}>{sheetBusy?'Connecting…':'Connect Sheet'}</button><button onClick={()=>fileRef.current?.click()} disabled={importing}>{importing?'Importing…':'Choose CSV'}</button><button onClick={downloadCsvSample}>Sample CSV</button></div></section>}
        <input ref={fileRef} hidden type="file" accept=".csv,text/csv" onChange={e=>importCsv(e.target.files?.[0])}/>
        <section className="inventory-panel"><div className="inventory-toolbar"><div className="inventory-search"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by name, phone, service, location or lead ID..."/></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All Status</option><option value="available">Available</option><option value="paused">Paused</option><option value="sold">Sold</option><option value="refunded">Refunded</option><option value="fake">Verified Fake</option><option value="expired">Expired Access</option><option value="closed">Closed</option><option value="invalid">Invalid</option></select>
<select value={industryId} onChange={e=>setIndustryId(e.target.value)}><option value="all">All Industries</option>{(data.filters?.industries||[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>
<select value={cityId} onChange={e=>setCityId(e.target.value)}><option value="all">All Cities</option>{(data.filters?.cities||[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select>
<select><option>Date Range</option></select></div><div className="inventory-toolbar-bottom"><div><button onClick={exportCsv}>⇩ Export</button><button type="button" className={view==='list'?'selected':''} aria-label="List view" onClick={()=>setView('list')}>☷</button><button type="button" className={view==='grid'?'selected':''} aria-label="Grid view" onClick={()=>setView('grid')}>▦</button></div>v>
          <div className="partner-table-wrap">{loading?<div className="partner-empty">Loading inventory…</div>:!data.data?.length?<div className="partner-empty">No partner leads found.</div>:view==='grid'?<div className="inventory-grid-view">{data.data.map(lead=><article key={lead.id} className="inventory-grid-card"><div className="inventory-grid-top"><span>#{lead.id}</span><span className={`partner-status ${lead.outcome_status||lead.status}`}>{statusLabel(lead.outcome_status||lead.status)}</span></div><h3>{lead.customer_name||'—'}</h3><p>{lead.industry_name||'Industry'} · {lead.service_name||'Service'}</p><div className="inventory-grid-meta"><span><small>Location</small><b>{lead.city_name||'—'}</b></span><span><small>Buyers</small><b>{lead.buyer_count??getBuyerCount(lead)}/{lead.buyer_capacity||3}</b></span><span><small>Price</small><b>{money(getPrice(lead))}</b></span></div><button type="button" onClick={()=>setExpanded(x=>({...x,[lead.id]:!x[lead.id]}))}>{expanded[lead.id]?'Hide details':'View details'}</button>{expanded[lead.id]&&<div className="inventory-grid-details">{Object.entries(lead.custom_fields||{}).filter(([k,v])=>String(v??'').trim()&&k!=='buyerCapacity').map(([k,v])=><div key={k}><small>{detailLabel(k)}</small><span>{String(v)}</span></div>)}</div>}</article>)}</div>:<table className="partner-table"><thead><tr><th>ID</th><th>NAME</th><th>PHONE</th><th>SERVICE</th><th>LOCATION</th><th>PRICE</th><th>BUYERS</th><th>STATUS</th><th>ADDED ON</th><th>ACTIONS</th></tr></thead><tbody>{data.data.map(lead=>{const details=Object.entries(lead.custom_fields||{}).filter(([k,v])=>String(v??'').trim()&&k!=='buyerCapacity');const open=!!expanded[lead.id];return <Fragment key={lead.id}>
            <tr><td><button type="button" onClick={()=>setExpanded(x=>({...x,[lead.id]:!open}))} style={{border:'1px solid #dbe4f0',borderRadius:8,background:'#fff',cursor:'pointer',width:30,height:30}}>{open?'−':'+'}</button></td><td>#{lead.id}</td><td><b>{lead.customer_name||'—'}</b></td><td>{lead.customer_phone||'—'}</td><td>{lead.service_name||lead.industry_name||'—'}</td><td><span>⌖ {lead.city_name||'—'}</span><small>{lead.state_name||'—'}</small></td><td>{money(getPrice(lead))}</td><td>{lead.buyer_count??getBuyerCount(lead)}/{lead.buyer_capacity||3}</td><td><span className={`partner-status ${lead.outcome_status||lead.status}`}>{statusLabel(lead.outcome_status||lead.status)}</span></td><td>{new Date(lead.created_at).toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'})}</td><td><button className="inventory-more" onClick={()=>setExpanded(x=>({...x,[lead.id]:!open}))}>⋮</button></td></tr>
            {open&&<tr><td colSpan="11"><div style={{padding:'18px',background:'#f8fafc',border:'1px solid #e5ebf3',borderRadius:12}}><div style={{fontWeight:800,marginBottom:12,color:'#173b70'}}>Complete lead details</div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:10}}>
<div><b>Lead ID</b><div>#{lead.id}</div></div><div><b>Name</b><div>{lead.customer_name||'—'}</div></div><div><b>Phone</b><div>{lead.customer_phone||'—'}</div></div><div><b>Email</b><div>{lead.customer_email||'—'}</div></div>
<div><b>Industry</b><div>{lead.industry_name||'—'}</div></div><div><b>Service</b><div>{lead.service_name||'—'}</div></div><div><b>Subservice</b><div>{lead.subservice_name||'—'}</div></div><div><b>State</b><div>{lead.state_name||'—'}</div></div><div><b>City</b><div>{lead.city_name||'—'}</div></div><div><b>Pincode</b><div>{lead.pincode||'—'}</div></div>
<div><b>Requirement</b><div>{lead.requirement||'—'}</div></div><div><b>Budget</b><div>{lead.budget||'—'}</div></div><div><b>Property type</b><div>{lead.property_type||'—'}</div></div><div><b>Source</b><div>{lead.source||'—'}</div></div><div><b>Lead type</b><div>{lead.lead_type||'—'}</div></div><div><b>Exclusive</b><div>{lead.is_exclusive?'Yes':'No'}</div></div><div><b>Buyer capacity</b><div>{lead.buyer_capacity||3}</div></div><div><b>Status</b><div>{statusLabel(lead.outcome_status||lead.status)}</div></div><div><b>Added on</b><div>{formatDate(lead.created_at)}</div></div>
{details.map(([k,v])=><div key={k}><b>{detailLabel(k)}</b><div>{String(v)}</div></div>)}</div></div></td></tr>}
          </Fragment>})}</tbody></table>}</div>
        </section>
        <section className="partner-panel partner-sheets-panel"><div className="partner-panel-head"><div><span className="partner-kicker">CONNECTED SOURCES</span><h2>Google Sheets connections</h2><p>{activeConnections.length} active connection{activeConnections.length===1?'':'s'}. Syncing imports only new/non-duplicate leads.</p></div></div>{!connections.length?<div className="partner-empty partner-sheet-empty">No Google Sheets connected yet.</div>:<div className="partner-sheet-list">{connections.map(c=>{const failures=Array.isArray(c.last_sync_failures)?c.last_sync_failures:[];const busy=syncingId===c.id;return <article className={`partner-sheet-row ${c.status==='disabled'?'disabled':''}`} key={c.id}><div className="partner-sheet-info"><div className="partner-sheet-title"><strong>Google Sheet</strong><span className={`partner-connection-status ${c.status}`}>{statusLabel(c.status)}</span></div><a href={c.source_url} target="_blank" rel="noreferrer">{c.source_url}</a><small>Spreadsheet: {c.spreadsheet_id} · Tab: {c.gid}</small><small>Last sync: {formatDate(c.last_synced_at)} · Created {c.last_sync_created??0} · Duplicates {c.last_sync_duplicate??0} · Failed {c.last_sync_failed??0}</small>{failures.length>0&&<details className="partner-sheet-failures"><summary>View {failures.length} import failures</summary><ul>{failures.slice(0,30).map((x,i)=><li key={i}>{typeof x==='string'?x:x.message||JSON.stringify(x)}</li>)}</ul></details>}</div><div className="partner-sheet-actions">{c.status==='active'&&<button className="partner-action-btn primary" disabled={busy||sheetBusy} onClick={()=>syncSheet(c.id)}>{busy?'Syncing…':'Sync now'}</button>}{c.status==='active'&&<button className="partner-action-btn danger" disabled={busy||sheetBusy} onClick={()=>disconnectSheet(c.id)}>Disconnect</button>}</div></article>})}</div>}</section>
      </div>
    </main>
  </div>;
}
