import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import UserHeader from '../components/UserHeader'
import { authRequest } from '../utils/auth'
import './PurchasedLeads.css'

export default function PurchasedLeads() {
  const [leads,setLeads]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
  useEffect(()=>{let active=true;authRequest('/leads/purchased').then(d=>{if(active)setLeads(Array.isArray(d)?d:[])}).catch(e=>{if(active)setError(e.message||'Failed to load purchased leads')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[])
  return <div className="purchased-page"><UserHeader/><main className="purchased-main"><div className="purchased-head"><div><span>PURCHASED LEADS</span><h1>Your lead access</h1><p>Customer contact details for leads you have purchased.</p></div><Link to="/leads">Explore marketplace →</Link></div>{error&&<div className="purchased-error">{error}</div>}{loading?<div className="purchased-empty"><strong>Loading purchased leads…</strong></div>:!leads.length?<div className="purchased-empty"><strong>No purchased leads yet</strong><p>Browse the marketplace and purchase a lead that matches your business.</p><Link to="/leads">Browse available leads →</Link></div>:<div className="purchased-grid">{leads.map(lead=><article className="purchased-card" key={lead.id}><div className="purchased-card-top"><span>LEAD #{lead.lead_id}</span><b>{lead.pricing_tier==='pro'?'PRO':'NORMAL'}</b></div><h2>{lead.service_name||lead.industry_name||'Business opportunity'}</h2><p>{lead.requirement||'No requirement provided.'}</p><div className="purchased-meta"><span>{lead.city_name||'—'}, {lead.state_name||'—'}</span><span>{lead.shares} share{lead.shares===1?'':'s'}</span><span>₹{Number(lead.amount||0).toLocaleString('en-IN')}</span></div><div className="purchased-contact"><small>CUSTOMER CONTACT</small><strong>{lead.customer_name||'—'}</strong><a href={lead.customer_phone?`tel:${lead.customer_phone}`:undefined}>{lead.customer_phone||'—'}</a><a href={lead.customer_email?`mailto:${lead.customer_email}`:undefined}>{lead.customer_email||'—'}</a></div><div className="purchased-details">{lead.property_type&&<span>Property: {lead.property_type}</span>}{lead.budget&&<span>Budget: {lead.budget}</span>}<span>Purchased {new Date(lead.created_at).toLocaleDateString('en-IN')}</span></div></article>)}</div>}</main></div>
}
